### ISSUE TITLE
[New App Shortcut]: F1TV

### ISSUE THREAD

**Issue by prupp89** [PRProd/HA-Firemote#104]
### App Name

F1TV

### Device Platform

Amazon Fire

### Is this app downloadable through you device's "store" app?

- [X] Yes

### Optional Comments

If you can add this, this would be great!!

**Comment by PRProd** [comment]
Hello @prupp89!

The F1 TV App shortcut has been added to the latest release, [v2.2.1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.2.1) and is ready for you to download and use.  Enjoy!
