### ISSUE TITLE
Latest version - Firestick 4k Max card buttons no longer work

### ISSUE THREAD

**Issue by Scoff123** [PRProd/HA-Firemote#106]
### Describe the bug

Since updating to the latest version, my firemote card no longer controls my firestick 4k Max. Pressing nav buttons up, down, left, right produces no response from my firestick. 

If I go to the Android TV Integration, I can play and pause the Firestick from the entities 'play/pause' control in HA.

### To Reproduce

Use actual Firestick remote to turn firestick on, then try to control it from firemote card in HA dashboard.

### Expected Behavior

Card buttons control the firestick as they did in the previous version of this card.

### Which Type of Device Do You Own?

Firestick 4k Max

### Troubleshooting Steps Completed

Restarted firestick, restarted HA, redownloaded firemote card (latest version), enabled debug logging on Android TV integration

### Additional context

The Firestick state attributes shows:

adb_response: 'sendevent: /dev/input/event5: No such file or directory'

**Comment by PRProd** [comment]
Hello @Scoff123!

Let's try a few things.  We will start off with the most likely cause.

Please check out the [FAQ](https://github.com/PRProd/HA-Firemote#faq) section under the heading [Why don't any of the buttons on the Firemote work at all?](https://github.com/PRProd/HA-Firemote#why-dont-any-of-the-buttons-on-the-firemote-work-at-all).  I'm wondering if maybe you need to switch to event4.  (the FAQ describes how to do that).  Additionally, along with powering on your firestick with the physical remote, please also ensure that the physical remote's directional buttons function as expected before trying the virtual ones on your Firemote card.

While I don't think this next option is the root of the problem, I can't say for sure.  Firemote [v2.2.0](https://github.com/PRProd/HA-Firemote/releases/tag/v2.2.0) introduces support for the new integration called "[Android TV Remote](https://www.home-assistant.io/integrations/androidtv_remote)" which was just introduced in Home Assistant, version [2023.5](https://www.home-assistant.io/blog/2023/05/03/release-20235/).  To avoid confusion with the existing "Android TV" integration, "Android TV" was renamed to [Android Debug Bridge](https://www.home-assistant.io/integrations/androidtv).  I assume by the way you worded your issue that you haven't updated to the latest HA version yet.  While I don't think that's the issue, I can't rule it out.  All of the testing for Firemote v2.2.0 was done against HA 2023.5 and newer.
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/bd5f56ac-6f27-4836-be32-6c003904bd8d)

If neither of those things helps, you might find it useful to take a look at closed issue #89 to see what we did there.  After a little struggle to identify that the OP was in fact using a 4K Max Firestick, a data dump was requested and provided that showed the physical remote wasn't actually connected to the firestick.   ...or at least that's the conclusion I came to, and heard nothing back afterwords.  If you happen to look through all of that too and STILL can't make it work, then maybe something else has recently changed that I'm just not seeing on my end yet.  I'm on the latest HA version, and my Firestick 4K max is also at the latest update (new one downloaded this morning for me) and things still appear to be working properly.

Please let me know what happens on your end!  Thanks!

**Comment by Scoff123** [comment]
Hi @PRProd 

Thanks very much for the detailed reply. I'm happy tonsay that the Firemote card is now working again.

Unfortunately, I have no explanation as to why it stopped originally, or indeed, why it started working again. All I have done today is carry out a full host power down to run some memory diagnostics, which were fine, and so booted my host back up again and restarted my HA VM.
Upon HA loading, I tried the firemote card, and it instantly just worked. No adb_response message anymore in my firestick entity attributes. 

I am still on 2023.4.6 of HA OS, and I did see mention about the android TV Integration changing name in the newer version. I'm holding off though after reading about the Alexa exposed entity issue. 

Anyway, I wish I could report more in order to help anyone else that faces this issue, but I really don't know what caused it, or what cured it, other than my Proxmox host power off/on. I'll close this one done, but thanks once again, and thanks for the great card!

**Comment by PRProd** [comment]
@Scoff123 Thanks for the follow up message!  I normally don't suggest a Home Assistant restart as a troubleshooting step, but maybe I should.  The most frustrating issues are always the ones that start and stop working with no diagnosed reason, right? 
 Either way, I'm glad that it's working for you now!

Just as an FYI: the Android TV Remote integration in HA 2023.5 only benefits non Amazon Fire Android TV devices, so if you are using a Firestick, you're not missing anything.
