### ISSUE TITLE
androidTV integration don't work anymore

### ISSUE THREAD

**Issue by PRProd** [PRProd/HA-Firemote#107]
### Discussed in https://github.com/PRProd/HA-Firemote/discussions/105

<div type='discussions-op-text'>

<sup>Originally posted by **PrzemekSkw** May 14, 2023</sup>
Hello, I noticed that Android tv integration don't work anymore in HA. Is there any fix to make Fireremote cord works?</div>

**Comment by PrzemekSkw** [comment]
Hi, thanks for guide. I try first that Android tv remote but it don't work at all. Meybe it's not for firestick.
I use Android device bridge and it works great. 
Thank You.

**Comment by PRProd** [comment]
@PrzemekSkw you are correct.  Unfortunately the Android TV Remote integration doesn't work on Amazon Fire devices.  The author of the new Android TV Remote integration was asked about that in this issue https://github.com/home-assistant/core/issues/92656 confirming that it wasn't designed to work with them.  I haven't heard if it will work in the future or not.  Thankfully, Firemote doesn't need it!
