### ISSUE TITLE
[New App Shortcut]: GO play

### ISSUE THREAD

**Issue by jrspowers** [PRProd/HA-Firemote#109]
### App Name

GO play

### Device Platform

NVIDIA Shield

### Is this app downloadable through you device's "store" app?

- [X] Yes

### Optional Comments

hello can you also add this app and here's the logo for the app itself it's go play belgium app just like vrt max and vtmgo thanks
![goplay](https://github.com/PRProd/HA-Firemote/assets/60328474/5c7ee78d-096c-4070-8a0b-c3569d850f9b)

GO play : be.goplay.app.tv

**Comment by PRProd** [comment]
Hello @jrspowers!  Nice to see you again!

I'm having a little trouble locating an APK for be.goplay.app.tv - I did find be.goplay.app which seemed to open properly on my Shield, and it matched the logo that you posted but I'm not sure that's what you're looking for.

I'll keep searching, but in the meantime I might need you to do the [Details For App Requests](be.goplay.app.tv) procedure for me, and send your results.

**Comment by jrspowers** [comment]
> Hello @jrspowers! Nice to see you again!
> 
> I'm having a little trouble locating an APK for be.goplay.app.tv - I did find be.goplay.app which seemed to open properly on my Shield, and it matched the logo that you posted but I'm not sure that's what you're looking for.
> 
> I'll keep searching, but in the meantime I might need you to do the Details For App Requests procedure for me, and send your results.

hello yes that's what i'm looking for that app is it & what do you need the apk for? & the path is the one I mentioned above what else can I help with?

**Comment by PRProd** [comment]
I prefer to have the APK so I can sideload the same app that you are using to do proper testing before releasing something to you that doesn't work like it should.  You're right though, I could also use just the information that you provided which will likely work, but some apps are a little more stubborn and require an ADB start command.  Using that command will help bypass any "stubbornness" and it will cause your app launch button to react a lot faster.

I don't like guessing and checking, but if you're OK with the potential that I might need try a few times before getting it right, that's OK.  I don't want to bug or annoy you, I only want to help you.  :smile:

**Comment by PRProd** [comment]
@jrspowers - Update:
All good.  I found the proper APK to sideload here in the US.  I have everything I need now.

**Comment by jrspowers** [comment]
> @jrspowers - Update:
> All good. I found the proper APK to sideload here in the US. I have everything I need now.

I understand that you want to have everything in order before you release it, but indeed this is the correct code to open it, but you can view it now & then I will see the update appear so that I can also use it on this top remote 😊

**Comment by PRProd** [comment]
Firemote [v2.2.2](https://github.com/PRProd/HA-Firemote/releases/tag/v2.2.2) is now available for download.  The new version includes your requested app shortcut.

Enjoy!
