### ISSUE TITLE
Fire TV Stick 4k Max - Volume and Mute buttons

### ISSUE THREAD

**Issue by Scoff123** [PRProd/HA-Firemote#11]
**Describe the bug**
After installing the Android TV Integration and this HA-Firemote card, all other buttons work on my Firemote card, however the volume up, volume down and mute buttons do not perform any actions. I am using the  Fire TV Stick 4k Max and have selected this as the device type, and am using default compatability mode.

**To Reproduce**
1. Go to 'HA-Firemote card in dashboard'
2. Click on any of 'volume up', 'volume down' or 'mute' buttons on screen remote
3. Nothing happens

**Expected behavior**
Volume should increase, decrease or mute accordingly

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Samsung S21+]
 - OS: [Android 12]
 - Android HA Companion app
 - Version [2022.10.2-full]

**Additional context**
The same behaviour happens on iPhone companion app also.

**Comment by PRProd** [comment]
Is your Fire TV Stick 4K Max plugged into a [CEC port](https://en.wikipedia.org/wiki/Consumer_Electronics_Control) on your television / display?

**Comment by ghvader** [comment]
@Scoff123 I'm using event6 for compatibility mode on my 4k max. although my audio goes through my receiver, so i can't say for sure, but see if that helps

**Comment by Scoff123** [comment]
Thanks for the suggestion. I've tried all of the options under compatibility including event6 but none of them allow the volume or mute buttons to work. I get the haptic feedback from the press but no action. 

My setup is my CEC HDMI port on my Panasonic TV is connected to the CEC HDMI port on my Yamaha AV Receiver. The 4k Max stick is in one of the other non CEC HDMI ports onbtge Receiver. 

The physical 4k Max remote control works fine and adjusts the Receiver volume or mutes it accordingly, so I was hoping this card would allow the sane actions as the physical remote.

Also, when the TV and Receiver are both in standby, if I press the 'Netflix' button on my 4k Max remote control, it will turn the TV on, switch to AV imput, and make tge Fire Stick load Netflix.

Pressing the Netflix button, or any of the 4 programmable app launch buttons, on the Firemote card does nothing. Not sure if this is possible to do the same as the physical remote or not? The same with the power button.

**Comment by ghvader** [comment]
@Scoff123 I suspect you have the same situation i do. your remote is controlling the stereo via IR. to test cover the end off the remote with a pillow or something and try to adjust. if it doesn't then it's IR and which case if your Yamaha is already in HA you can go the route I am hoping to go, is control it via script and then the buttons can be mapped to a script. I believe @PRProd is working on this as a possibility.

**Comment by Scoff123** [comment]
@ghvader great thanks for the suggestion! I've tested and confirmed the physical fire remote is indeed using IR when pressing the volume buttons. 

I do have my yamaha receiver in HA as a media player entity using the yamaha platform, although I've not actually done anything with it yet. The script idea sounds good if this does get implemented for this card.

**Comment by ghvader** [comment]
@Scoff123 Yeah same situation as me. remote controls firetv via bluetooth and the Yamaha via IR. (I have lg tv's and yamaha receivers) what we are thinking is to create 3 or 4 scripts / services that when you press, power, vol up/down/mute will have HA send those commands directly to the receiver, he will need to create a over-ride function for each of the buttons to be remapped.

**Comment by PRProd** [comment]
Closing this issue since it now appears to be a duplicate of #6 

That issue (plus many other things) are currently in the works.  Thanks for the discussion!

**Comment by PRProd** [comment]
I've also added some notes to the [FAQ section of the readme file](../blob/main/README.md#faq) to help others who run into this same issue.  I sincerely appreciate everybody's help discussing and dissecting things like this!
