### ISSUE TITLE
[New App Shortcut]: StreamTV

### ISSUE THREAD

**Issue by Bojack84** [PRProd/HA-Firemote#110]
### App Name

StreamTV 

### Device Platform

Amazon Fire

### Is this app downloadable through you device's "store" app?

- [X] Yes

**Comment by PRProd** [comment]
Firemote [v2.2.2](https://github.com/PRProd/HA-Firemote/releases/tag/v2.2.2) is now available for download.  The new version includes your requested app shortcut.

Enjoy!
