### ISSUE TITLE
[New App Shortcut]: discovery plus

### ISSUE THREAD

**Issue by pailloM** [PRProd/HA-Firemote#111]
### App Name

Discovery Plus

### Device Platform

Amazon fire

### Is this app downloadable through you device's "store" app?

- [X] Yes

**Comment by PRProd** [comment]
Firemote [v2.2.2](https://github.com/PRProd/HA-Firemote/releases/tag/v2.2.2) is now available for download.  The new version includes your requested app shortcut.

Enjoy!
