### ISSUE TITLE
[New App Shortcut]: Steam Link

### ISSUE THREAD

**Issue by stinobook** [PRProd/HA-Firemote#114]
### App Name

Steam Link

### Device Platform

Nvidia Shield

### Is this app downloadable through you device's "store" app?

- [X] Yes

### Optional Comments

https://play.google.com/store/apps/details?id=com.valvesoftware.steamlink&hl=en&gl=US&pli=1

would love to see this added!
tyvm !

**Comment by PRProd** [comment]
Congrats!  Release [v2.3.0](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.0) has just been published, and it includes your requested app shortcut!

Enjoy!
