### ISSUE TITLE
[New App Shortcut]: GCN

### ISSUE THREAD

**Issue by johnnytaupo** [PRProd/HA-Firemote#119]
### App Name

GCN (Global Cycling Network)

### Device Platform

Amazon Fire

### Is this app downloadable through you device's "store" app?

- [X] Yes

**Comment by PRProd** [comment]
New version [v2.3.1 ](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.1)is now available for download.  This new version contains your app shortcut request!

Enjoy!
