### ISSUE TITLE
[New App Shortcut]: NLZiet

### ISSUE THREAD

**Issue by dennidoubles** [PRProd/HA-Firemote#120]
### App Name

NLZiet

### Device Platform

NVIDIA Shield 2015

### Is this app downloadable through you device's "store" app?

- [X] Yes

### Optional Comments

Would like to have the NLZiet app on my remote also (Shield and Google Chromecast).

Love your work!

**Comment by jrspowers** [comment]
hallo here logo nlziet

![NLZIET_logo](https://github.com/PRProd/HA-Firemote/assets/60328474/37e1cc7d-0cf7-4794-beb2-46d7a9acd7ec)

**Comment by PRProd** [comment]
Thank you!  I appreciate your kind words!  

New version [v2.3.1 ](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.1)is now available for download.  This new version contains your app shortcut request!

Enjoy!
