### ISSUE TITLE
[New App Shortcut]: Mediaset Infinity

### ISSUE THREAD

**Issue by malorezzanzo64** [PRProd/HA-Firemote#122]
### App Name

Mediaset Infinity

### Device Platform

Amazon Fire

### Google App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=it.mediaset.infinitytv

### Application Info

app_id: it.mediaset.infinitytv1
source: Mediaset Infinity
adb_response: mSurface=Surface(name=)/@0xd3930bb       mSurface=Surface(name=it.mediaset.infinitytv1/it.mediaset.mediasetplay.ctv.MainActivity)/@0x476f592   mCurrentFocus=Window{5d3afcf u0 it.mediaset.infinitytv1/it.mediaset.mediasetplay.ctv.MainActivity}   mFocusedApp=AppWindowToken{e9d2e6e token=Token{b97f1e9 ActivityRecord{9dbfa70 u0 it.mediaset.infinitytv1/it.mediaset.mediasetplay.ctv.MainActivity t6190}}}

**Comment by PRProd** [comment]
Hello @malorezzanzo64!  Thanks for your request!

There appears to be a disagreement between the app store link and the application info data that you included:

- **it.mediaset.infinitytv**  (Appstore link)
- **it.mediaset.infinitytv1** (App running on your device)

Can you let me know if the Google Play store link is correct, or if there is some other reason for the conflicting information?  Thank you!

**Comment by PRProd** [comment]
@malorezzanzo64 - WOW!  THANK YOU!  You're the best!

I've decided to add this two ways.  There will be an app choice named "Mediaset Infinity" and one named "Mediaset Infinity (alt)".  

The appstore version will be "Mediaset Infinity" and the harder to find version that you have will be the one named "Mediaset Infinity (alt)". 

This will be ready in the next release.

**Comment by PRProd** [comment]
Good news!  Version [2.3.2](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.2) has been released, and your request is inside!

Enjoy!
