### ISSUE TITLE
[New App Shortcut]: Home Assistant

### ISSUE THREAD

**Issue by malorezzanzo64** [PRProd/HA-Firemote#123]
### App Name

Home Assistant

### Device Platform

Amazon Fire

### Google App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=io.homeassistant.companion.android&pli=1

### Application Info

source_list: io.homeassistant.companion.android
app_id: io.homeassistant.companion.android
source: io.homeassistant.companion.android
adb_response: mSurface=Surface(name=)/@0xd3930bb
      mSurface=Surface(name=io.homeassistant.companion.android/io.homeassistant.companion.android.webview.WebViewActivity)/@0xb793ee
  mCurrentFocus=Window{fcead9a u0 io.homeassistant.companion.android/io.homeassistant.companion.android.webview.WebViewActivity}
  mFocusedApp=AppWindowToken{d469639 token=Token{2683e00 ActivityRecord{e821c83 u0 io.homeassistant.companion.android/.webview.WebViewActivity t6215}}}

**Comment by PRProd** [comment]
Good news!  Version [2.3.2](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.2) has been released, and your request is inside!

Enjoy!
