### ISSUE TITLE
Add option to disable button yellow highlighting?

### ISSUE THREAD

**Issue by jackyaz** [PRProd/HA-Firemote#126]
I find the yellow highlighting of the buttons, the Home button in particular, to detract from the visual appeal of the remote. Is it possible to add an option to the card config to disable the highlighting on relevant buttons please?

**Comment by PRProd** [comment]
Is it just the remote function buttons (power, home, play/pause) that you want that option for, or do you also dislike the app button highlights?

**Comment by PRProd** [comment]
Pre-release [v2.3.1-b1 ](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.3-b1)is available for you to download and test.

Adding the following line to your Firemote card's YAML config should produce the desired result.
```yaml
hide_button_highlights: true
```

Please let me know how it works, if this satisfies your request, and if you'd also like to have a highlight disable option for the active app as well.

**Comment by PRProd** [comment]
Official release [v2.3.3](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.3) is now available for download, and it includes the ability to hide the normal remote button highlights.  Feel free to open a different issue if you'd also like for the active application to have the same kind of option as well.  Enjoy!

**Comment by jackyaz** [comment]
Sorry, I was away on holiday. Looks great!
