### ISSUE TITLE
New Button

### ISSUE THREAD

**Issue by Jimgkok** [PRProd/HA-Firemote#128]
Hey I really like how the AL2 card looks like but im missing the keyboard from the shield TV remote,is there anyway to add it in the AL2 remote?

**Comment by alexdelprete** [comment]
I like the AL2 style too...I'm missing the hamburger button...the one that opens the side menu.

**Comment by PRProd** [comment]
@Jimgkok & @alexdelprete 

For the **keyboard** and the **menu** buttons, Do we like where the green arrows are pointing?  Do we hate it?
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/a3ec0f83-de96-464a-b542-178eb30554bf)


This approach will make those buttons optional, just like the **reboot** and **switch apps** buttons.

**Comment by PRProd** [comment]
@alexdelprete - On the topic of "dynamic scaling", the left image that you say is "too small", are you referring to the app launch buttons alone, or the entire thing?  I'm wondering if a second scale option for the app launcher buttons would solve your concern.

**Comment by alexdelprete** [comment]
> For the **keyboard** and the **menu** buttons, Do we like where the green arrows are pointing? Do we hate it?

The good Doug always comes to the rescue. :)

I would put those where the other buttons are: for example where the mute/volume buttons are, there's some space. 

> I'm wondering if a second scale option for the app launcher buttons would solve your concern.

Seems like a good idea...my goal is to have some order on the bottom...when I scale up those buttons go all over the place. If they could scale up keeping the same layout it would be good, but I don't know if that's doable.

**Comment by PRProd** [comment]
> If they could scale up keeping the same layout it would be good, but I don't know if that's doable.

I just did a quick test to see if making a separate scale slider for just the app launch grid could do what you were asking for, and it looks like it can
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/df085e80-85ab-4a86-b04a-c7cd31d651d1)

I just want to be sure... is this the kind of layout you are looking for?  You can even go crazy with this potential option
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/357d1a28-c593-4028-a501-6500a8794cc1)

**Comment by PRProd** [comment]
@Jimgkok & @alexdelprete ~ Do we like this better?  Do I win?

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/7e1d9e41-4a62-4ea8-8c4b-621da8eed3d8)

**Comment by PRProd** [comment]
Pre-release [v2.3.1-b1 ](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.3-b1)is available for you to download and test.  Please try it out and send me your thoughts.

**Comment by alexdelprete** [comment]
Much much better! You won! :)

In order to keep the ordered horizontal layout like in the image, buttons are a little bit small, but if I scale up further, the layout gets messed again. I was wondering if those spaces could be actually used when scaling up, I mean utilized, without reordering all items...so more compact but keeping same layout.

![image](https://github.com/PRProd/HA-Firemote/assets/7027842/edf88f50-6523-41fb-a74b-073bfbc2be63)

**Comment by alexdelprete** [comment]
oh...one last thing Doug, while we're beta testing things: can we add an option to show the Firemote version on the card, maybe blended with the background, so to be unobtrusive, almost invisible. (gray on gray, or tone on tone in general). A bit like the Device Name.

**Comment by PRProd** [comment]
How is this for spacing?  I pretty much collapsed all of the minimum gap sizes so that the three panels on the bottom could get very close before they start stacking on each other
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/54e588e8-e4b0-4a4e-9774-8ea316d5036c)

**Comment by PRProd** [comment]
Take a look at the newly released [v2.3.3-b2](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.3-b2) to see if it is the card of your dreams, or the card of your nightmares.  :smile:

To show the version number, add the following to your card's YAML config: (undocumented until release)
```yaml
show_version_number: true
```

**Comment by alexdelprete** [comment]
Wow...amazing job Doug...we're almost there. :)

Just two things:

- the version font size: I'd go with a smaller size, if it's 14 now, I'd go 10 or 11.
- the reboot app button: could we make it a remote button (with a reboot icon) instead of an app launch button? When pressed can it ask for a confirmation, to prevent accidental press?

![image](https://github.com/PRProd/HA-Firemote/assets/7027842/ea4a15d3-ab56-4216-921c-ac6788069a0d)

**Comment by alexdelprete** [comment]
My goodness...it's exactly like I imagined it...amazing job Doug.

I'm sorry if I asked for too many changes, didn't mean to stress you out, it's just that I love this project. :)

Thanks for everything.

**Comment by alexdelprete** [comment]
You could call this remote style: **ADP Launcher**. :D

**Comment by PRProd** [comment]
Official release [v2.3.3](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.3) is now available for download, and it now has all of the things!  :tada:  

Enjoy!
