### ISSUE TITLE
[New App Shortcut]: Curiosity Stream (TV)

### ISSUE THREAD

**Issue by scphyle** [PRProd/HA-Firemote#130]
### App Name

Curiosity Stream (TV)

### Device Platform

Nvidia Shield

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.curiosity.curiositystream.androidtv

### Application Info

A video streaming service for documentaries

**Comment by PRProd** [comment]
Hello there @scphyle!  

I'm in the midst of a few functional test releases before the next official Firemote release, but I wanted you to know that the Curiosity Stream TV App was added to the latest pre-release version, [v2.3.3-b2](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.3-b2) 

You're welcome to download the pre-release version now if you'd like to use it immediately, and you can expect to also see it in the next upcoming stable release.
