### ISSUE TITLE
[New App Shortcut]: Nebula

### ISSUE THREAD

**Issue by scphyle** [PRProd/HA-Firemote#131]
### App Name

Nebula

### Device Platform

NVIDIA Shield

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=tv.standard.nebula

### Application Info

An app to access Nebula its similar to YouTube.

**Comment by PRProd** [comment]
Hello again @scphyle!  

I'm in the midst of a few functional test releases before the next official Firemote release, but I wanted you to know that the Nebula App was added to the latest pre-release version, [v2.3.3-b2](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.3-b2) 

You're welcome to download the pre-release version now if you'd like to use it immediately, and you can expect to also see it in the next upcoming stable release.

**Comment by PRProd** [comment]
Official release [v2.3.3](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.3) is now available for download, and it includes the Nebula app as promised.  Enjoy!
