### ISSUE TITLE
Crunchyroll launch command has changed for FireTV

### ISSUE THREAD

**Issue by asucrews** [PRProd/HA-Firemote#133]
Hello,

It looks like chruchyroll made change to the path to launch the app.  I am not sure how to look this up but if there a way I will be more then happy to.  I am suing this through home assistant.

adb_response: >-
  Starting: Intent { act=android.intent.action.VIEW
  cmp=comadb_response.crunchyroll.crunchyroid/.MainActivity }

  Error type 3

  Error: Activity class
  {com.crunchyroll.crunchyroid/com.crunchyroll.crunchyroid.MainActivity} does
  not exist.
hdmi_input: null
device_class: tv
supported_features: 22961
source_list:
  - com.amazon.tv.launcher
app_id: com.amazon.tv.launcher
source: com.amazon.tv.launcher

**Comment by PRProd** [comment]
@asucrews - Thank you for letting me know!  I sincerely appreciate it!

Release [v2.3.3](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.3) is now available for download, and it includes the updated command to launch the Crunchyroll app.

Enjoy!
