### ISSUE TITLE
[New App Shortcut]: RedPlay

### ISSUE THREAD

**Issue by Pxex2008** [PRProd/HA-Firemote#134]
### App Name

RedpPlay

### Device Platform

Amazon Fire

### App Store Link or URL to .apk file if sideloaded

https://www.mediafire.com/file/ff4v4o02e5uh0u6/redplay_box.apk/file

### Application Info

adb_response: mSurface=Surface(name=com.mm.droid.livetv.redplaybox/com.mm.droid.livetv.live.LiveNewActivity)/@0x76ac3fa
  mCurrentFocus=Window{ce936b7 u0 com.mm.droid.livetv.redplaybox/com.mm.droid.livetv.live.LiveNewActivity}
  mFocusedApp=AppWindowToken{b7c6419 token=Token{87f1760 ActivityRecord{570ff63 u0 com.mm.droid.livetv.redplaybox/com.mm.droid.livetv.live.LiveNewActivity t5144}}}

**Comment by PRProd** [comment]
Hello @Pxex2008!  

Firemote version [v2.3.4](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.4) has just been released, and it includes the app shortcut for RedPlay as you requested.

Enjoy!
