### ISSUE TITLE
[New App Shortcut]: My Family Cinema

### ISSUE THREAD

**Issue by Pxex2008** [PRProd/HA-Firemote#135]
### App Name

My Family Cinema

### Device Platform

Amazon Fire

### App Store Link or URL to .apk file if sideloaded

https://rebrand.ly/mfcboxwebsite

### Application Info

adb_response: mSurface=Surface(name=com.valor.mfc.droid.tvapp.generic/com.cv.media.m.home.home.ui.HomeActivity)/@0x2a9fe90
  mCurrentFocus=Window{ec0f8c u0 com.valor.mfc.droid.tvapp.generic/com.cv.media.m.home.home.ui.HomeActivity}
  mFocusedApp=AppWindowToken{1c32071 token=Token{ce42e18 ActivityRecord{825ddfb u0 com.valor.mfc.droid.tvapp.generic/com.cv.media.m.home.home.ui.HomeActivity t5146}}}

**Comment by PRProd** [comment]
Hello @Pxex2008!  

Firemote version [v2.3.4](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.4) has just been released, and it includes the app shortcut for My Family Cinema as you requested.

Enjoy!

**Comment by Pxex2008** [comment]
thanks :)
