### ISSUE TITLE
[New App Shortcut]: Twire

### ISSUE THREAD

**Issue by Ginpachi98** [PRProd/HA-Firemote#137]
### App Name

Twire

### Device Platform

Xiaomi( custom chinese android box)

### App Store Link or URL to .apk file if sideloaded

https://f-droid.org/packages/com.perflyst.twire/

### Application Info

Its twitch, but (ad)least twice better

**Comment by PRProd** [comment]
Greetings @Ginpachi98!  

Firemote [v2.3.5](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.5) has just been released, and it includes an app shortcut button for Twire.  

Enjoy!

**Comment by Ginpachi98** [comment]
Thanks, very nice :D
