### ISSUE TITLE
[New App Shortcut]: TVExpress

### ISSUE THREAD

**Issue by arthuraltino** [PRProd/HA-Firemote#138]
### App Name

TVExpress

### Device Platform

Amazon Fire, Android TV, Xiaomi

### App Store Link or URL to .apk file if sideloaded

https://oss.mb99.tech/tve/TVExpress%20BR_3.1.3_20230322_stb.apk

### Application Info

adb_response: mSurface=Surface(name=)/@0xcc1f1b6
      mSurface=Surface(name=com.mm.droid.livetv.tve/com.mm.droid.livetv.live.LiveNewActivity)/@0x2ab3479
  mCurrentFocus=Window{c34dadd u0 com.mm.droid.livetv.tve/com.mm.droid.livetv.live.LiveNewActivity}
  mFocusedApp=AppWindowToken{cbc92c1 token=Token{90db7a8 ActivityRecord{ee053cb u0 com.mm.droid.livetv.tve/com.mm.droid.livetv.live.LiveNewActivity t2436}}}

**Comment by PRProd** [comment]
Hello @arthuraltino!  

Release [v2.3.6 ](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.6)is now available for download.  This new release includes a new app launch button for TVExpress, as you requested. 

Enjoy!
