### ISSUE TITLE
[New App Shortcut]: GO TV

### ISSUE THREAD

**Issue by colincachia** [PRProd/HA-Firemote#139]
### App Name

GO TV

### Device Platform

NVIDIA Shield

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=mt.com.go.iptv.android.devices

### Application Info

GO is a TV company operating in the island of Malta.

GO TV is their app for Android / Fire TVs - for streaming of their subscription-based content.

**Comment by PRProd** [comment]
Hello @colincachia 

Release [v2.3.6 ](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.6)is now available for download.  This new release includes a new app launch button for GO TV, as you requested. 

Enjoy!
