### ISSUE TITLE
[New App Shortcut]: ViaPlay

### ISSUE THREAD

**Issue by AzzMG** [PRProd/HA-Firemote#140]
### App Name

ViaPlay

### Device Platform

Amazon Fire TV Stick 4K Max

### App Store Link or URL to .apk file if sideloaded

https://www.amazon.com/Nordic-Entertainment-Group-Viaplay/dp/B09SZQHN9R/ref=sr_1_1?keywords=viaplay&qid=1686411839&s=mobile-apps&sr=1-1

### Application Info

adb_response: >-
  mSurface=Surface(name=com.viaplay.android/com.viaplay.android.features.home.HomeActivity)/@0x7066e45
    mCurrentFocus=Window{588fcdb u0 com.viaplay.android/com.viaplay.android.features.home.HomeActivity}
    mFocusedApp=AppWindowToken{b416883 token=Token{8e12332 ActivityRecord{3bb6f3d u0 com.viaplay.android/.features.home.HomeActivity t4183}}}

**Comment by PRProd** [comment]
Hello @AzzMG!  

Release [v2.3.6 ](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.6)is now available for download.  This new release includes a new app launch button for ViaPlay as you requested. 

Enjoy!

**Comment by AzzMG** [comment]
Great. Thank you :D
