### ISSUE TITLE
[New Device Support]: Gamepad

### ISSUE THREAD

**Issue by PrzemekSkw** [PRProd/HA-Firemote#142]
### Device Name

Firestick 4K Max

### Which compatability mode event number works BEST with your device?

event0

### Additional Comments (optional)

It is possible to add support to gamepad to use it when I stream games from laptop trough Moonlight?

**Comment by PrzemekSkw** [comment]
Hi, I mean virtual game controller like virtual pilot I have now in Fireremote card. Something like that on that video:
https://www.youtube.com/watch?v=MHgJmBSofKQ
Regards.

**Comment by PRProd** [comment]
Thank you for that video link.  

I'm not entirely sure if this is something that I will add, I need to think about it some more.

**Comment by PrzemekSkw** [comment]
OK, I understand. Thank You for answer.
Regards.
