### ISSUE TITLE
[New App Shortcut]:  MLB

### ISSUE THREAD

**Issue by jtonzi** [PRProd/HA-Firemote#143]
### App Name

MLB

### Device Platform

Chromecast

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.bamnetworks.mobile.android.gameday.atbat

### Application Info

Streaming MLB games

**Comment by PRProd** [comment]
Greetings @jtonzi!

Sorry about the delay, I was taking some time with my family.  Version [v2.3.8 ](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.8)is now available for download, and it includes the app shortcut that you requested.

Enjoy!

**Comment by jtonzi** [comment]
No worries at all. I hope you had a good break!
Thank you for taking care of this!
________________________________
