### ISSUE TITLE
[New App Shortcut]:  settings

### ISSUE THREAD

**Issue by jrspowers** [PRProd/HA-Firemote#149]
### App Name

settings 

### Device Platform

nvidia shield

### App Store Link or URL to .apk file if sideloaded

app_id : com.android.tv.settings  

### Application Info

hello could you set this as an app so that we arrive directly at the setting this would be useful thanks again

**Comment by PRProd** [comment]
Apologies for the delay.  I've had some work and some health issues that have kept me tied up lately.  Don't worry!  I haven't forgotten about you!  :smiley:

**Comment by PRProd** [comment]
Hello!

I just published a pre-release that includes your request.  You can download version [v2.3.9-b1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.9-b1) to try it out!

**Comment by jrspowers** [comment]
hello going to test this later today then give you feedback

**Comment by PRProd** [comment]
I'm impatient.  :smile:  Actually, I'm just trying to close some issues.  They've been piling up.

I pushed this to an official release [v2.3.9](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.9)

I'm going to close this for now, but feel free to let me know if something isn't quite right and I'll take another look.

**Comment by jrspowers** [comment]
> I'm impatient.  :smile:  Actually, I'm just trying to close some issues.  They've been piling up.
> 
> 
> 
> I pushed this to an official release [v2.3.9](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.9)
> 
> 
> 
> I'm going to close this for now, but feel free to let me know if something isn't quite right and I'll take another look.

Thanks this work perfect !
