### ISSUE TITLE
Can't use the up/down/right.. buttons on FireTV Stick 4K Max without using "Compatibility Mode"

### ISSUE THREAD

**Issue by Nikey** [PRProd/HA-Firemote#15]
**Describe the bug**
I cant use the up/down/left/right and okay buttons without using the "Compatibility Mode"

**To Reproduce**
Just click any of the buttons without "Compatibility Mode" when using a FireTV 4K Max

**Expected behavior**
The button should be virtually pressed

**Additional context**
Happened after one of the latest updates in the last 2 days.

**Comment by PRProd** [comment]
Which compatibility mode makes the dpad buttons work again?  Are the dpad buttons the only ones that fail to work?

**Comment by Nikey** [comment]
- the "Strong (Slower)" one
- I think so. Home, back and the app buttons are working fine, can't test the mute/volume ones as i don't use the CEC feature at all
- tested all compability modes and unfortunatly only "Strong (Slower)" is working after I updated to the newest version. Before it was working fine in "Default"-Mode

**Comment by Nikey** [comment]
Oh sorry nevermind, I didn't notice i had to do this.. so case closed
