### ISSUE TITLE
[New App Shortcut]: TVer

### ISSUE THREAD

**Issue by CountParadox** [PRProd/HA-Firemote#150]
### App Name

TVer

### Device Platform

Google Chromecast 4k

### App Store Link or URL to .apk file if sideloaded

https://apkcombo.com/downloader/#package=jp.co.tver.tvapp&device=tv

### Application Info

https://play.google.com/store/apps/datasafety?id=jp.co.tver.tvapp&hl=en_AU&gl=US

The app is "only available in Japan" but works through NordVPN and probably others. 
Used for watching Japanese dramas etc.

My wife uses this daily so would love to make it easier for her :) 

Then ill just have to figure out how to make NOrd connect automatically when TVER is launched.....

Edit: oh nice! Split tunnelling solves my problem for the VPN! Now I just need the TVer icon! ;) 

### Optional Comments

Here's the media player dump with the app running:
`
volume_level: 1
is_volume_muted: false
media_content_id: epxjuvnmuo
media_content_type: video
media_duration: 3962.959
media_position: 494.676
media_position_updated_at: '2023-07-02T11:09:34.999348+00:00'
media_title: さんま大先生と卒業生たちが27年ぶりに大集結！
app_id: AndroidNativeApp
app_name: TVer
entity_picture_local: >-
  /api/media_player_proxy/media_player.bedroom_tv?token=c176d659c250aeaddad194dac196b9b88940a32db3534111903c3f6bd888213d&cache=d85bea7063035ae3
entity_picture: >-
  https://statics.tver.jp/images/content/thumbnail/episode/xlarge/epxjuvnmuo.jpg?v=7
friendly_name: Bedroom TV
supported_features: 152451
`

This is the ADB device state from HA

`
adb_response: null
hdmi_input: null
device_class: tv
friendly_name: Android TV 172.16.0.101
supported_features: 23997
source_list:
  - com.android.systemui
  - com.droidlogic
  - com.google.android.ext.services
  - com.google.process.gservices
  - com.android.providers.media.module
  - Google Cast
  - com.google.android.tv.axel
  - com.google.android.tv.remotecontrol.logging
  - Google TV Launcher
  - com.google.android.apps.tv.launcherx:coreservices
  - com.google.android.katniss:interactor
  - com.google.android.tv.remote.service
  - com.google.android.inputmethod.latin
  - Play Store
  - com.google.android.gms.unstable
  - Netflix
  - com.google.android.katniss:search
  - com.google.process.gapps
  - com.google.android.gms
  - com.google.android.gms.persistent
  - com.android.providers.tv
  - YouTube
  - jp.co.tver.tvapp
  - com.google.android.apps.mediashell:privileged_process0
  - com.google.android.webview:webview_service
  - com.android.providers.calendar
  - com.nordvpn.android
  - com.android.vending:instant_app_installer
volume_level: 1
is_volume_muted: false
app_id: jp.co.tver.tvapp
app_name: jp.co.tver.tvapp
source: jp.co.tver.tvapp
`

**Comment by CountParadox** [comment]
Here is an SVG of the service logo:
https://upload.wikimedia.org/wikipedia/commons/6/6a/TVer_logo.svg

**Comment by CountParadox** [comment]
7027ef1ee7f669d69899088b78993249058b778b

**Comment by CountParadox** [comment]
I do not know how to locate the correct activity to call, but I believe I have made the balance of required changes.

**Comment by PRProd** [comment]
Greetings @CountParadox!

WOW!!  You really went above and beyond here!  Thanks!  

Looking at https://github.com/PRProd/HA-Firemote/commit/7027ef1ee7f669d69899088b78993249058b778b I can see that you configured the JSON data to show that it works for all supported Firemote platforms:
```json
  "deviceFamily": ["amazon-fire", "chromecast", "nvidia-shield", "xiaomi"]
```
Did you test this on all platforms, or only on your Chromecast 4K?

**Comment by CountParadox** [comment]
I didn't test it but I don't see a reason it won't work 😇

**Comment by PRProd** [comment]
If you've seen the things that I've seen....

**Comment by PRProd** [comment]
I was able to make this work across all of the device families, so it's good to go.

I just published a pre-release that includes this new app launch request.  You can download version [v2.3.9-b1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.9-b1) to try it out!

**Comment by PRProd** [comment]
@CountParadox 

The beta version has now become official with the release of  [v2.3.9](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.9), so I will close this now.  Feel free to contribute more ideas, or join the discussions as well.  If you are a fan of this project, don't forget to hit the star button.  Fun fact: Whenever this project gets a new star, a home assistant automation plays a happy song to keep me motivated.  :smile: 

Enjoy!

-Doug

**Comment by CountParadox** [comment]
![Screenshot_20230710_061427_Home Assistant.png](https://github.com/PRProd/HA-Firemote/assets/6279380/aae67812-c346-4ab8-b6a0-6fc9d318a48a)

Yay
