### ISSUE TITLE
[New App Shortcut]: IPTV Extreme

### ISSUE THREAD

**Issue by CountParadox** [PRProd/HA-Firemote#151]
### App Name

IPTV Extreme

### Device Platform

Chromecast

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.pecana.iptvextremepro

**Comment by PRProd** [comment]
Apologies for the delay.  I've had some work and some health issues that have kept me tied up lately.  Don't worry!  I haven't forgotten about you!  :smiley:

**Comment by CountParadox** [comment]
All good! I spoke to the developer and they don't have an SVG of the icon... I'll see if I can make one

**Comment by CountParadox** [comment]
All good! I spoke to the developer and they don't have an SVG of the icon... I'll see if I can make one

**Comment by PRProd** [comment]
Great!

In the meantime, could I ask you to follow the steps [here](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F) under the [Details For App Requests](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests) heading, and reply in this thread with the results?  I want to be sure that I get it right without actually paying for the app.

**Comment by PRProd** [comment]
I made my own.  :smile: 
![IPTVExtremeButtonLogo](https://github.com/PRProd/HA-Firemote/assets/25486599/8e107ba0-6740-4a03-9d5d-008c7e1b0671)

**Comment by PRProd** [comment]
Hello @CountParadox!

I made my own SVG, and paid for the app because it really didn't cost too much, and I'm impatient.  :smile: 

Release [v2.3.11](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.11) has just been published, and it includes the app shortcut for the IPTV Extreme Pro app.

Enjoy!

**Comment by CountParadox** [comment]
Thank you so much!!!❤️

**Comment by CountParadox** [comment]
Update: 

![image](https://github.com/PRProd/HA-Firemote/assets/6279380/af2aa916-0b0f-432b-9c90-6e0717b865dc)


Looks like this
