### ISSUE TITLE
[New App Shortcut]: NBA on Fire TV

### ISSUE THREAD

**Issue by Goobiegoobers** [PRProd/HA-Firemote#153]
### App Name

NBA on Fire TV

### Device Platform

Amazon Fire

### Application Info

Hi Mate,

Firstly, love this!!!

What would be amazing for me if possible is a shortcut to the NBA app. Comes straight up if you search it in the App store. 

Thank you in advance!

**Comment by PRProd** [comment]
Apologies for the delay.  I've had some work and some health issues that have kept me tied up lately.  Don't worry!  I haven't forgotten about you!  :smiley:

**Comment by PRProd** [comment]
I just published a pre-release that includes this new app launch request.  You can download version [v2.3.9-b1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.9-b1) to try it out, or else you can wait for the next official release.

**Comment by Goobiegoobers** [comment]
That’s amazing,

Thank you Doug!

Regards

David Gobourn

On 9 Jul 2023, at 03:46, Doug Nelson ***@***.***> wrote:

﻿

I just published a pre-release that includes this new app launch request. You can download version v2.3.9-b1<https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.9-b1> to try it out, or else you can wait for the next official release.

**Comment by PRProd** [comment]
@Goobiegoobers

The beta version has now become official with the release of  [v2.3.9](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.9), so I will close this now.  Feel free to contribute more ideas, or join the discussions as well.

Enjoy!

-Doug
