### ISSUE TITLE
[New App Shortcut]: Bgtime.tv

### ISSUE THREAD

**Issue by ilianhris** [PRProd/HA-Firemote#155]
### App Name

Bgtime.tv

### Device Platform

Nvidia Shield

### App Store Link or URL to .apk file if sideloaded

~https://apps.apple.com/us/app/bgtime-tv/id1093760355~

### Application Info

app_name: bg.mytv.android

### Optional Comments

Thanks

**Comment by PRProd** [comment]
I just published a pre-release that includes this new app launch request.  You can download version [v2.3.9-b1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.9-b1) to try it out, or else you can wait for the next official release.

**Comment by PRProd** [comment]
@ilianhris

The beta version has now become official with the release of  [v2.3.9](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.9).  

Enjoy!

-Doug

**Comment by ilianhris** [comment]
Thanks
