### ISSUE TITLE
[New App Shortcut]: 

### ISSUE THREAD

**Issue by michael7oliver** [PRProd/HA-Firemote#156]
### App Name

Kayo

### Device Platform

NVIDIA Shield

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=au.com.kayosports&hl=en&gl=US

### Application Info

app_name: au.com.kayosports.tv
source: au.com.kayosports.tv
adb_response: >-
  mSurface=Surface(name=au.com.kayosports.tv/au.com.foxsports.martian.tv.main.MainActivity)/@0xfe37b35
        mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xd2b42fc
    mInputMethodTarget in display# 0 Window{71d050a u0 au.com.kayosports.tv/au.com.foxsports.martian.tv.main.MainActivity}
hdmi_input: null
device_class: tv
entity_picture: >-
  /api/media_player_proxy/media_player.android_tv_192_168_0_19?token=428d49f687c402ffc191bfefc39a452d0829525dde3a048db61d64a1144f6a06&cache=1688902867.09202
friendly_name: Android TV 192.168.0.19
supported_features: 23997
source_list:
  - com.android.systemui
  - com.google.android.ext.services
  - com.google.android.tv.remote.service
  - com.nvidia.shield.remote.server
  - com.nvidia.blakepairing
  - com.nvidia.shieldtech.accessoryui
  - com.nvidia.osc
  - com.nvidia.app.messaging
  - com.nvidia.shield.ask
  - com.android.providers.media.module
  - com.android.providers.tv
  - Android TV Launcher
  - com.google.android.tvrecommendations
  - Google Cast
  - com.google.android.leanback.ime
  - com.google.android.katniss:interactor
  - com.nvidia.tegrazone3
  - au.com.ninenow.ctv
  - com.google.process.gservices
  - com.google.process.gapps
  - Netflix
  - com.google.android.gms
  - com.google.android.gms.persistent
  - com.nvidia.tegrazone3:PersonalGridService
  - com.nvidia.tegrazone3:telemetry
  - com.sbs.ondemand.tv
  - com.plexapp.mediaserver.smb
  - Disney+
  - com.google.android.youtube.tv.recommendations
  - au.com.kayosports.tv
  - com.google.android.katniss:search
  - com.google.android.apps.mediashell:privileged_process3
  - Live Channels
volume_level: 1
is_volume_muted: false
app_id: au.com.kayosports.tv

### Optional Comments

Hey I hope I’ve done this correctly. Cheers.

**Comment by PRProd** [comment]
@michael7oliver - Yup!  You filled out the request correctly!  Thank you!

The Kayo app was requested in issue #86 and was added to the Firemote card with version [v2.1.0](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.10) on May 4th, 2023.

Please ensure that you are using the latest version of the Firemote card.  Once you are updated, you will find the Kayo app in the list:
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/d4e84ebe-7e05-40df-ab57-697179b5a3c3)
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/621dd04e-b60f-4d08-91fc-5cf2b8841781)

Please let me know if you need any additional assistance.  I'm here to help!

-Doug

**Comment by michael7oliver** [comment]
Brilliant! I hadn’t checked it following the updates… thanks.
