### ISSUE TITLE
[New App Shortcut]: Binge

### ISSUE THREAD

**Issue by michael7oliver** [PRProd/HA-Firemote#157]
### App Name

Binge

### Device Platform

NVIDIA Shield

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=au.com.streamotion.ares&hl=en&gl=US

### Application Info

app_name: au.com.streamotion.ares.tv
source: au.com.streamotion.ares.tv
adb_response: >-
  mSurface=Surface(name=au.com.streamotion.ares.tv/au.com.streamotion.ares.tv.main.MainActivity)/@0xfe16c48
        mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xd2b42fc
    mInputMethodTarget in display# 0 Window{1695241 u0 au.com.streamotion.ares.tv/au.com.streamotion.ares.tv.main.MainActivity}
hdmi_input: null
device_class: tv
entity_picture: >-
  /api/media_player_proxy/media_player.android_tv_192_168_0_19?token=428d49f687c402ffc191bfefc39a452d0829525dde3a048db61d64a1144f6a06&cache=1688903285.365881
friendly_name: Android TV 192.168.0.19
supported_features: 23997
source_list:
  - com.android.systemui
  - com.google.android.ext.services
  - com.google.android.tv.remote.service
  - com.nvidia.shield.remote.server
  - com.nvidia.blakepairing
  - com.nvidia.shieldtech.accessoryui
  - com.nvidia.osc
  - com.nvidia.app.messaging
  - com.nvidia.shield.ask
  - com.android.providers.media.module
  - com.android.providers.tv
  - Android TV Launcher
  - com.google.android.tvrecommendations
  - Google Cast
  - com.google.android.leanback.ime
  - com.google.android.katniss:interactor
  - com.nvidia.tegrazone3
  - au.com.ninenow.ctv
  - com.google.process.gservices
  - com.google.process.gapps
  - Netflix
  - com.google.android.gms
  - com.google.android.gms.persistent
  - com.nvidia.tegrazone3:PersonalGridService
  - com.nvidia.tegrazone3:telemetry
  - com.plexapp.mediaserver.smb
  - com.google.android.youtube.tv.recommendations
  - au.com.kayosports.tv
  - com.google.android.katniss:search
  - com.google.android.apps.mediashell:privileged_process3
  - Prime Video
  - com.nvidia.ota
  - Play Movies & TV
  - Play Store
  - com.android.vending:background
  - au.com.streamotion.ares.tv
  - com.google.android.webview:webview_service
  - Live Channels
volume_level: 1
is_volume_muted: false
app_id: au.com.streamotion.ares.tv

### Optional Comments

Another one, thanks.

**Comment by PRProd** [comment]
@michael7oliver 

The newest version [v2.3.9](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.9) of Firemote has just been released, which includes the Binge app shortcut.

Enjoy!

-Doug

**Comment by michael7oliver** [comment]
Great, updating now!
