### ISSUE TITLE
[New App Shortcut]: КиноПоиск

### ISSUE THREAD

**Issue by Sergey-SRG** [PRProd/HA-Firemote#161]
### App Name

КиноПоиск 

### Device Platform

Xiaomi 

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=ru.kinopoisk

**Comment by PRProd** [comment]
![Kinopoisk_colored_logo_(2021-present)](https://github.com/PRProd/HA-Firemote/assets/25486599/0f0c7faf-2416-475b-8853-f84a41e9be24)

**Comment by Sergey-SRG** [comment]
![image](https://github.com/PRProd/HA-Firemote/assets/3891900/2f25f7bd-6582-47a0-b796-0f5d6feb1c6c)

**Comment by PRProd** [comment]
Greetings @Sergey-SRG!  

I just published version [v2.3.10](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.10) which includes the app launch shortcut that you requested.

Enjoy!
