### ISSUE TITLE
[New App Shortcut]: SmartTV Client for Twitch

### ISSUE THREAD

**Issue by WozTen** [PRProd/HA-Firemote#162]
### App Name

SmartTV Client for Twitch

### Device Platform

Chromecast

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.fgl27.twitch&hl=en_US&gl=US

### Application Info

adb_response: mSurface=Surface(name=com.fgl27.twitch/com.fgl27.twitch.PlayerActivity)/@0xd2de354
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xfefda6d
  mInputMethodTarget in display# 0 Window{f064245 u0 com.fgl27.twitch/com.fgl27.twitch.PlayerActivity}

**Comment by PRProd** [comment]
![joystick-32039](https://github.com/PRProd/HA-Firemote/assets/25486599/e04defe7-9e72-4f64-8ae4-3eade4a970a0)

**Comment by PRProd** [comment]
Greetings @WozTen!

I just published version [v2.3.10](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.10) which includes the app launch shortcut that you requested.

Enjoy!
