### ISSUE TITLE
[New App Shortcut]: LAZYMEDIA DELUXE

### ISSUE THREAD

**Issue by dengi76** [PRProd/HA-Firemote#163]
### App Name

LAZYMEDIA DELUXE

### Device Platform

mi-box-s

### App Store Link or URL to .apk file if sideloaded

https://lazymediadeluxe.ru/

### Application Info

LazyMedia Deluxe is a convenient online catalog of movies, various video shows, music, and the most popular Android games. The program is compatible with Android OS (both mobile version and adapted for TV boxes, Android set-top boxes). In fact, it is an online cinema with free content.

**Comment by PRProd** [comment]
Hello @dengi76!

Release [v2.3.11](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.11) has just been published, and it includes the app shortcut for the LAZYMEDIA DELUXE app.

Enjoy!

**Comment by dengi76** [comment]
Thank you very much !!! 👍👍👍
