### ISSUE TITLE
[New App Shortcut]: Internet (Silk Browser)

### ISSUE THREAD

**Issue by andynash** [PRProd/HA-Firemote#164]
### App Name

Internet

### Device Platform

Amazon Fire

### App Store Link or URL to .apk file if sideloaded

https://www.amazon.co.uk/Amazon-com-Amazon-Silk-Web-Browser/dp/B01M35MQV4/ref=cm_cr_arp_mb_bdcrb_top?ie=UTF8

### Application Info

mSurface=Surface(name=com.amazon.cloud9/com.amazon.slate.fire_tv.FireTvSlateActivity)/@0x410ff62
    mCurrentFocus=Window{fc18d67 u0 com.amazon.cloud9/com.amazon.slate.fire_tv.FireTvSlateActivity}
    mFocusedApp=AppWindowToken{600524a token=Token{99c0bb5 ActivityRecord{1946bec u0 com.amazon.cloud9/com.amazon.slate.fire_tv.FireTvSlateActivity t207}}}

### Optional Comments

I'd prefer to see this listed simply as Internet as that is how it appears when using a Fire TV, though I appreciate this might clash with browsers that can be launched via non-Amazon platforms.

Perhaps the display name (what appears on the button) could be Internet, whilst in the backend drop down it appears as Internet (Silk Browser)?

**Comment by PRProd** [comment]
![image2vector - 2023-07-18T163631 317](https://github.com/PRProd/HA-Firemote/assets/25486599/e7dee5e2-58f9-4800-a116-30d7207c2c67)

**Comment by PRProd** [comment]
Hello @andynash!

Release [v2.3.11](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.11) has just been published, and it includes the app shortcut for the internet Silk Browser app for FireTV devices.

Enjoy!
