### ISSUE TITLE
[New App Shortcut]: Channels dvr

### ISSUE THREAD

**Issue by ovsims** [PRProd/HA-Firemote#165]
### App Name

Channels dvr 

### Device Platform

Amazon Fire, Nvidia Shield, Nvidia Shield Pro

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/search?q=channels+dvr&c=apps

### Application Info

app_id: com.getchannels.dvr.app
app_name: com.getchannels.dvr.app
source: com.getchannels.dvr.app
~adb_response: /system/bin/sh: no closing quote~
hdmi_input: null
device_class: tv
entity_picture: /api/media_player_proxy/media_player.android_tv_10_25_4_148?token=859a48b9d5d3e9d40573ad91d2cbcb609772ebbe454f05c539a7e93ab7993439&cache=1689451636.235954
friendly_name: Nvidia Shield Hole
supported_features: 23997

**Comment by PRProd** [comment]
![untitled-drawing (6) (1)](https://github.com/PRProd/HA-Firemote/assets/25486599/7988a6b4-87b1-4d8d-b354-1f6b320d1e30)

**Comment by PRProd** [comment]
Greetings @ovsims!

Release [v2.3.11](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.11) has just been published, and it includes the app shortcut for the Channels: whole home DVR app.

Enjoy!

**Comment by ovsims** [comment]
Thank you.

**Comment by ovsims** [comment]
Will you help me figure out how to run the commands to use a script to press these buttons on the firemote. I can’t figure out the remote commands to launch the particular apps for my Shield 2019. Pressing the button on the below works all the apps but I can find any trace in the logs of how it does it so I can run a script to automate it.
