### ISSUE TITLE
[New App Shortcut]: Purple Cheetah

### ISSUE THREAD

**Issue by themodfatherinc** [PRProd/HA-Firemote#168]
### App Name

Cheetah Purple

### Device Platform

Chromecast

### App Store Link or URL to .apk file if sideloaded

tiny.cc/cheepurp

### Application Info

adb_response: mSurface=Surface(name=)/@0xc110478
      mSurface=Surface(name=com.purple.cheetah.player/com.purpleplayer.iptv.android.activities.DashBoardActivity)/@0x6513d42
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xdad1fbc

### Optional Comments

Not sure how popular this app is but I use it for my IPTV service, so its addition would be much appreciated. Thank you!

**Comment by PRProd** [comment]
Greetings @themodfatherinc!

I have just published Version [v2.3.12](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.12) which contains the app shortcut that you requested.

Enjoy!
