### ISSUE TITLE
[New App Shortcut]: BBC iPlayer for NVIDIA Shield

### ISSUE THREAD

**Issue by billthe4th** [PRProd/HA-Firemote#169]
### App Name

BBC iPlayer

### Device Platform

NVIDIA Shield

### Application Info

mSurface=Surface(name=com.nvidia.bbciplayer/com.nvidia.bbciplayer.BaseWebViewActivity)/@0x5cab83e
mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xecc6a4a
mInputMethodTarget in display# 0 Window{9d671e6 u0 com.nvidia.bbciplayer/com.nvidia.bbciplayer.BaseWebViewActivity}

### Optional Comments

Not sure if this should be a new application or just the nvidia-shield version of the existing iPlayer app. I added the following to the bbc-iplayer section of the fastappchoices object in my local ha-firemote.js and it works exactly as I would want it to:

```
"nvidia-shield": {
        "appName": "com.nvidia.bbciplayer",
        "androidName": "com.nvidia.bbciplayer",
        "adbLaunchCommand": "adb shell am start -n com.nvidia.bbciplayer/.BaseWebViewActivity",
      }
```
Thanks for making this card, it looks and works great.

**Comment by PRProd** [comment]
@billthe4th,

This was the best request ever!  You did all of the work for me!  :smile:  I just tested and released [v2.3.12](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.12) which contains the NVIDIA Shield shortcut for the BBC iPlayer app as requested.

Enjoy!
