### ISSUE TITLE
[New App Shortcut]: Tving

### ISSUE THREAD

**Issue by codinghb** [PRProd/HA-Firemote#171]
### App Name

Tving

### Device Platform

chromecast

### App Store Link or URL to .apk file if sideloaded

net.cj.em.tving

### Application Info

app_name: net.cj.em.tving
source: net.cj.em.tving
adb_response: '/system/bin/sh: no closing quote'
hdmi_input: null
device_class: tv
app_id: net.cj.em.tving

### Optional Comments

Please add this app for app shortcut of fireremote. 
Please let me know if you need more data.

**Comment by PRProd** [comment]
Hello @codinghb!

Before making this release official, I want to check with you to be sure that I've done it correctly.  Could you please download the most recent pre-release [v2.3.13-b1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.13-b1) and verify that the tving app is launching as expected?  Thanks.

-Doug

**Comment by codinghb** [comment]
Hello,
Thanks for your feedback 

I updated beta version, 2.3.13-bi, and added Tving shortcut. 
But the device hasn't reacted with Tving button. (reacted other shortcut like youtube, plex, etc.)

Could you please test again?

In addtion, the color code of CI might be R255 G20 B60.
White background and colored letter might be official CI, but white letter and colored backgroud doens't matter if you want.

**Comment by PRProd** [comment]
@codinghb,

Sorry about that.  When I tried to download the app here in the United States, I ran into region restrictions stating that it is not available in my country.  I searched for an APK to sideload, found one with the package name of net.cj.em.tving (as indicated in your request) and used the artwork, color scheme, and I wrote a working launch command for that app.  It sounds like I picked the wrong app to download and test.

I searched again today for the proper APK and so far I have not been able to find a different one with that name that I can download.  Do you have a link to an .apk file that I can download/sideload?  It's OK if you don't.

In your original request, under the "Application Info" section, you posted the following:
```
adb_response: '/system/bin/sh: no closing quote'
```
Unfortunately, that's an error message, and not what I was looking for.  Please retry the steps found in the [Details For App Requests](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests) section, making sure that you've copied the entire command listed, and then post the results here.

On the topic of the logos, which one of the two you replied with is the actual artwork found in this app?  Are they both in the app, or is just one of them in the app?

**Comment by codinghb** [comment]
hello,
Sorry for lack of data.

https://play.google.com/store/apps/details?id=net.cj.em.tving

And below pictures are CI in the app.

![image](https://github.com/PRProd/HA-Firemote/assets/90979173/5a39f90a-1e3c-4243-bc4b-b62ae74aa4f5)
![image](https://github.com/PRProd/HA-Firemote/assets/90979173/6231a5e8-f116-40ce-80f5-48bf94777556)

And below picture is official CI released by press by company. 
https://cjnews.cj.net/medialibrary/cj-enm-%EC%97%94%ED%84%B0%ED%85%8C%EC%9D%B8%EB%A8%BC%ED%8A%B8%EB%B6%80%EB%AC%B8/cj-enm-%EC%97%94%ED%84%B0-tving-ci/

**Comment by PRProd** [comment]
Unfortunately, the app store link is what gives me the region restriction problem.

It looks like I used the correct logo, just not the official color scheme, so I've updated that.  I also changed the launch command, so it will hopefully work for you.

Please download the latest pre-release [v2.3.13-b2](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.13-b2) and test it.

Thanks.

**Comment by codinghb** [comment]
I did.
It works well.
and the logo is better.

Thanks.

**Comment by PRProd** [comment]
Great!

I'm waiting to hear back from someone on one more unrelated issue before I make the pre-release version into an official release.  You are welcome to use the pre-release that you just downloaded, or wait until the official one comes out.  Either way is perfectly OK.

**Comment by PRProd** [comment]
Your app request has now been pushed into the latest official release [v2.3.13](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.13).

Enjoy!
