### ISSUE TITLE
[New App Shortcut]: PODA.tv

### ISSUE THREAD

**Issue by PetrolejCZ** [PRProd/HA-Firemote#172]
### App Name

PODA.tv

### Device Platform

Chromecast

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=tv.poda.tv

### Application Info

mSurface=Surface(name=tv.poda.tv/cz.sledovanitv.androidtv.main.MainActivity)/@0x16dc9af
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x433449a
hdmi_input: null
device_class: tv
entity_picture: /api/media_player_proxy/media_player.android_tv_192_168_31_177?token=06ce95017a7469e117bc957b3132a39ffbfc176c4ebce1f566d06fc3d9432cc3&cache=73563fe1bf91bb34
supported_features: 23997

### Optional Comments

It's a clone of SledovaniTV - online televize. [https://play.google.com/store/apps/details?id=cz.sledovanitv.android](url)

mSurface=Surface(name=cz.sledovanitv.android/cz.sledovanitv.androidtv.wizard.wizardv2.LoginWizardActivity)/@0x687cc33
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xa87971c
hdmi_input: null
device_class: tv
entity_picture: /api/media_player_proxy/media_player.android_tv_192_168_31_177?token=06ce95017a7469e117bc957b3132a39ffbfc176c4ebce1f566d06fc3d9432cc3&cache=77f3b0d500f7488d
supported_features: 23997

**Comment by PRProd** [comment]
@PetrolejCZ - Have you had the opportunity to try this out yet?

**Comment by PetrolejCZ** [comment]
Hopefully I'll be home in two hours to try it out.

**Comment by PetrolejCZ** [comment]
It works. Thank you very much.

**Comment by PRProd** [comment]
Your app request has now been pushed into the latest official release [v2.3.13](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.13).

Enjoy!
