### ISSUE TITLE
[New App Shortcut]: JustWatch - Streaming Guide

### ISSUE THREAD

**Issue by dennisholtkamp** [PRProd/HA-Firemote#174]
### App Name

JustWatch - Streaming Guide

### Device Platform

NVIDEA Shield

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.justwatch.justwatch

### Application Info

mSurface=Surface(name=com.justwatch.justwatch/com.justwatch.justwatch.MainActivity)/@0xc6873a4
        mSurface=Surface(name=com.google.android.tvlauncher/com.google.android.tvlauncher.MainActivity)/@0x98dc62a
        mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x911cb59
    mInputMethodTarget in display# 0 Window{d371bdb u0 com.justwatch.justwatch/com.justwatch.justwatch.MainActivity}

**Comment by PRProd** [comment]
Version [v2.3.14](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.14) has just been released, and it contains your app shortcut request.

Enjoy!
