### ISSUE TITLE
[New App Shortcut]: Emby

### ISSUE THREAD

**Issue by michaelhenningersrb** [PRProd/HA-Firemote#18]
### App Name

Emby

### Can this app be freely downloaded through official means?

- [X] Yes

**Comment by PRProd** [comment]
Pre-release [v1.8.8](https://github.com/PRProd/HA-Firemote/releases/tag/v1.8.8) is now available for testing.  Please download the new version and let me know if the emby app shortcut is working as expected.  Thanks.

**Comment by michaelhenningersrb** [comment]
@PRProd Works ;) Thanks a lot

**Comment by PRProd** [comment]
Thanks!

This is now available in the Firemote official release v1.9.0

**Comment by ChristophCaina** [comment]
Hi,
I've just tested this card with my Android TV Remote (basic remote control.
So far, it is working pretty much perfect...

I've added the following Apps:

--> jellyfin (working)
--> prime video (working)
--> netflix (working)
--> youtube (working)
--> emby (not working)

unfortunately, the Shortcut for Emby seems not working...
The remote is from Nokia (Streaming Box 8000) - but as far as I could see, all controls are working so far... so the only difference seems to be calling the EMBY App...

![image](https://user-images.githubusercontent.com/26391061/227981648-4b5da24d-984a-4596-ad75-f5f8e3a799e1.png)

**Comment by PRProd** [comment]
@ChristophCaina - Let's diagnose the problem!  Could you open the emby app on your Nokia Streaming Box 8000, follow [the steps listed here](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests), and post your results?

**Comment by PRProd** [comment]
Hmmm... puzzling.  I'm not quite sure why it's not working based off of what you sent me.  Could you try that process again, but this time send me all of the data in the Attributes field?  (not just the adb_response)

**Comment by ChristophCaina** [comment]
sure :)
Here it is:

```
source_list:
  - Android TV Launcher
  - Spotify
  - Google Cast
  - Magenta TV
  - Emby
  - Jellyfin
  - Play Store
volume_level: 0.13333333333333333
is_volume_muted: false
adb_response: >-
  mSurface=Surface(name=tv.emby.embyatv/tv.emby.embyatv.browsing.MainActivity)/@0x9e7b81c
        mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x242014e
hdmi_input: null
device_class: tv
entity_picture: >-
  /api/media_player_proxy/media_player.android_tv_192_168_52_73?token=a1a1dac6014c8cb9c0b5bf54651689dddfd1396ddd6d2843bad3b9d9d7e357f3&cache=1679945229.963202
friendly_name: Android TV
supported_features: 23997
```

compared with another app which is working (Jellyfin)
```
source_list:
  - Android TV Launcher
  - Spotify
  - Google Cast
  - Magenta TV
  - Emby
  - Jellyfin
  - Play Store
volume_level: 0.13333333333333333
is_volume_muted: false
adb_response: >-
  mSurface=Surface(name=org.jellyfin.androidtv/org.jellyfin.androidtv.ui.startup.StartupActivity)/@0x19f0db3
        mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x242014e
hdmi_input: null
device_class: tv
entity_picture: >-
  /api/media_player_proxy/media_player.android_tv_192_168_52_73?token=a1a1dac6014c8cb9c0b5bf54651689dddfd1396ddd6d2843bad3b9d9d7e357f3&cache=1679945319.967976
friendly_name: Android TV
supported_features: 23997
```

**Comment by PRProd** [comment]
Wow!  That's certainly different!  For some reason, there are missing entries in that dump that all other devices I've encountered seem to have, specifically app_id, source, and the 2nd half of the ADB response:

![image](https://user-images.githubusercontent.com/25486599/228057012-2ade8fec-a2a6-411c-833d-b400e3177703.png)

I might have a solution to that problem, but I'll need some time to work on it.  I'll let you know when I have something available for you to test if you are willing to help.  I don't yet own a Nokia Streaming Box 8000 to test with.

**Comment by ChristophCaina** [comment]
what I don't understand in that case:
Why are the other buttons working then?

I know, there are other issues with this device, since the media player / android tv integration is also not working as expected... 
In case that it help: The device is based on Android10 ...

I'm looking forward to support and test on that device :)
Beta is already enabled ;)

**Comment by PRProd** [comment]
Other things aren't working with the integration?  Hmmm... I wonder if your Android device needs to be removed and re-added into Home Assistant.  Do you remember what you chose when you first added it?  **auto** or **androidtv** - I wonder if you'll have different results if you try one, then remove it, and then try the other.
![image](https://user-images.githubusercontent.com/25486599/228077034-274122d0-c40d-498e-bc6a-56f3f9d79568.png)

![image](https://user-images.githubusercontent.com/25486599/228076701-1062903c-734b-4e11-ae48-98ba074e0e1b.png)

**Comment by ChristophCaina** [comment]
good point :)
I think, I've used "auto"...

I'll try to remove it and add it again.

**Comment by PRProd** [comment]
Unfortunately, that's a .png file and I actually need a .svg, of the smallest possible file size.  I looked for a little while yesterday, but gave up and moved on since I had others to find.  Feel free to post one if you find it!  (as long as it has a small file size!)

I had a [very similar conversation](https://github.com/PRProd/HA-Firemote/discussions/52#discussioncomment-5445151) with @jrspowers today already.

**Comment by ChristophCaina** [comment]
something like this?
https://www.svgrepo.com/svg/330370/emby

**Comment by PRProd** [comment]
Yes, but with the word emby next to it

**Comment by ChristophCaina** [comment]
ah okey ... can you please have a look if this would be ok?
It might not be 100% accurate.... 

![OmLzxEm_adobe_express](https://user-images.githubusercontent.com/26391061/228091377-70750388-5fa9-4a71-b43b-70bd7795f821.svg)

**Comment by PRProd** [comment]
That'll work!  I got the 14.3kB file down to 2.9kB too!

**Comment by PRProd** [comment]
@ChristophCaina [Version 2.1.0-beta2](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.0-beta2) is ready for you to download and test!  It has the shiny new logo on it too!

**Comment by ChristophCaina** [comment]
thanks :)
Button looks great - unfortunately, it seems that it still doesn't start the emby app... :-(

I will do some more tests tomorrow... here it is already 3:00 am - so I should go to bed :D

**Comment by PRProd** [comment]
Thanks for staying up so late with me yesterday!  Let's try a slightly different approach today.  Please run the following command in the Developer Tools console, and let me know if this command will launch emby properly:

`adb shell am start -a android.intent.category.LEANBACK_LAUNCHER -d -n tv.emby.embyatv/.startup.StartupActivity`

Developer Tools -> Services -> Android TV: ADB command
![image](https://user-images.githubusercontent.com/25486599/228285631-b3305d2e-2891-44d4-be2d-2c1c92fcbd7b.png)

**Comment by ChristophCaina** [comment]
hm... not sure if this needs to be implemented for the existing devices (I don't know, if it is failing with shield or so)
Maybe... release it as an beta with an alternate device - just to be sure not breaking something for working shield devices?

**Comment by PRProd** [comment]
I have a high confidence that this will work properly on all other devices.  In fact, adb launch commands like this one will typically generate a MUCH faster response from your device, so this will be an improvement for emby app launch users.

 I always try to use a command like this to launch applications, but my first attempt at it for emby resulted in a permissions error.  I defaulted back to one that I know "_always works_", and everything was OK... until it met your Nokia device.  :smile:

**Comment by PRProd** [comment]
[v2.1.0-beta3](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.0-beta3) is ready for you to download and confirm that it's working now.  Please let me know.

**Comment by ChristophCaina** [comment]
thanks for the effort.
I am not sure - but at the moment, it still seems not working as expected :-(

I've updated to beta3 - removed the card and re-added it to the dashboard, but the emby button still does not work :-(
I will try to remove the card completely and reinstall it again - it might still be an issue with my "not yet" supported hardware...?

**Comment by PRProd** [comment]
SWEET!!!!!

Home Assistant has a very very sticky cache, so sometimes when you've done everything you can think of to try to clear it, TWICE, it still wants to use the cache that shouldn't even exist anymore.  I have a rhythm of keystrokes that I just do now without thinking about them since development takes a lot of writing / testing / rewriting / retesting... without my cache purge routines, I wouldn't get anywhere with a cache that doesn't want to forget my mistakes.  Sometimes destruction (like deleting your card and adding it again) can do the trick.  Glad it worked for you in this case!

I'm going to re-close this issue now since we're confident that it works.  Thanks for your help!
