### ISSUE TITLE
no physical looking remote, just buttons

### ISSUE THREAD

**Issue by Vansmak** [PRProd/HA-Firemote#181]
I searched but couldn't find info on this. I would like to layout the commands/buttons without a physical looking remote. Like maybe just direction buttons, menu and text input. 
![Screenshot_20230904_172323_Home Assistant](https://github.com/PRProd/HA-Firemote/assets/16037573/4a271c97-27ef-4f1e-bf10-c9bb3d91858d)
This works well but has limitations and lacks text. If I need to all merge the 2. Hope I've made sense.

**Comment by PRProd** [comment]
Hello @Vansmak!

Have you tried the "App Launcher 2" layout option?  You can select that layout in one of two ways:

Through the Visual Editor
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/db31f789-50bc-456b-ad19-2381b39bd05e)

Through a YAML config
```YAML
defaultRemoteStyle_override: AL2
```

**Comment by Vansmak** [comment]
yes, i looked at that too, its not apps im looking for. really just dpad home menu and text

**Comment by PRProd** [comment]
I could make one!  

Just to be clear, when you say "text", are you referring to the keyboard button, the Device Name text option, or some other button?

Keyboard Button:
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/3052f1f4-617b-4e26-b48b-5d0f13975a1e)

Device Name Text
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/2c49271f-1122-4f0b-8da7-292f216645cc)

**Comment by Vansmak** [comment]
yes, thats what brought me here. you made a comment about text input via adb on some forum i was.

**Comment by PRProd** [comment]
Like this?
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/38405863-2ac2-4b10-8127-c1bc6c78be57)

...or do you want ONLY the D-pad, home, and keyboard buttons?

**Comment by Vansmak** [comment]
wow, first let me ty for being so responsive.  i do not want to nit pick as you are being so gracious. just the buttons in me screenshot plus the keyboard, plain buttons

**Comment by PRProd** [comment]
No need to worry about that!  I just want to make it the way you want it!

Is this the correct layout?
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/371af2d4-2c26-40ad-805b-786b5e568f30)

If this is correct, my next step will be to try to make the colors follow the theme that you've chosen.  After confirmation/instruction from you, and after I complete the color step, I'll get a beta version published for you to test.

**Comment by Vansmak** [comment]
That works!

**Comment by PRProd** [comment]
I've published pre-release version [v2.4.1-b1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.4.1-b1) for you to download and test.

After downloading the pre-release, you can choose the "Controls Only" style remote through the Visual Editor
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/7e217a0e-e81e-42ec-85fe-7de894da5f19)

or via YAML
```YAML
defaultRemoteStyle_override: CO1
```

**Comment by Vansmak** [comment]
got it and it works great overall.  the challenge is in scaling it since its not a layout of the indiv buttons, its a large image so scaling to get the right width in turn makes it too tall for instance.  feels more like a picture element card where the remote is a jpg and the elements are over it with xy coordinates.

**Comment by Vansmak** [comment]
Ok so I appreciate all your efforts. I went ahead an incorporated the text inputbfrom you firemote to the shield-card that was forked from tv-card. I am not going to share it. Just my personal use. Thanks again. 
![Screenshot_20230907_195429_Home Assistant](https://github.com/PRProd/HA-Firemote/assets/16037573/b8bb78fe-7d46-45de-9a09-167042ad6290)
![Screenshot_20230907_195421_Home Assistant](https://github.com/PRProd/HA-Firemote/assets/16037573/96dfef7c-9a6e-49dd-8a3b-61702713ba55)

**Comment by PRProd** [comment]
Is it OK for me to revert the changes I made for your requests, or would you like the Firemote project to keep them and/or continue modifying them?

**Comment by Vansmak** [comment]
you can revert, unless you want to have a minimal option like that for others.  I hope i didnt waste your time too much.
