### ISSUE TITLE
[New App Shortcut]: Volleyball TV

### ISSUE THREAD

**Issue by zhdenny** [PRProd/HA-Firemote#182]
### App Name

Volleyball TV

### Device Platform

NVIDIA Shield

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=dce.fivb.volleyballtv&hl=en_US&gl=US

### Application Info

adb_response: >-
  mSurface=Surface(name=dce.fivb.volleyballtv/com.dicetv.MainActivity)/@0x8932694
        mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x94e4359
    mInputMethodTarget in display# 0 Window{85b85a5 u0 dce.fivb.volleyballtv/com.dicetv.MainActivity}

**Comment by PRProd** [comment]
I have just published pre-release version [v2.3.15-b1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.15-b1) which contains your app request.  Feel free to download it, test it out, and let me know if you experience any issues.  If not, this will be included in the official release soon.

Enjoy!

**Comment by PRProd** [comment]
Firemote version [v2.3.15](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.15) has been officially released.
