### ISSUE TITLE
[New App Shortcut]: ARD Mediathek

### ISSUE THREAD

**Issue by tandama** [PRProd/HA-Firemote#183]
### App Name

ard Mediathek

### Device Platform

Amazon Fire

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=de.swr.avp.ard

### Application Info

adb_response: mSurface=Surface(name=de.swr.ard.avp.mobile.android.amazon/de.swr.ard.avp.mobile.android.amazon.TvActivity)
  mCurrentFocus=Window{fc6c587 u0 de.swr.ard.avp.mobile.android.amazon/de.swr.ard.avp.mobile.android.amazon.TvActivity}
  mFocusedApp=AppWindowToken{f3b0ffd token=Token{4c67a7 ActivityRecord{771d866 u0 de.swr.ard.avp.mobile.android.amazon/.TvActivity t212}}}
hdmi_input: null
device_class: tv
friendly_name: Fire TV 192.168.178.24
supported_features: 22961
source_list: com.amazon.client.metrics, com.amazon.imp, android.ext.services, com.amazon.device.messaging, com.android.proxyhandler, com.amazon.tv.ime, com.amazon.vizzini, com.amazon.tcomm, com.amazon.tv.devicecontrol, com.amazon.whad, com.amazon.tv.launcher, com.amazon.kso.blackbird, logcat, com.amazon.tv.alexaalerts, FireTV Store, Amazon Video, com.amazon.whisperjoin.middleware.np, com.amazon.whisperjoin.wss.wifiprovisioner, com.amazon.connectivitycontroller, com.amazon.device.rdmapplication, de.swr.ard.avp.mobile.android.amazon, com.amazon.webview.chromium:AWVArcusServiceProcess, com.amazon.alexamediaplayer.runtime.ftv, com.amazon.webview.chromium:AWVMetricsProcess, com.amazon.discoveryservice.core.android, com.amazon.ftv.xpicker, com.amazon.whisperlink.core.android, com.amazon.uxcontrollerservice, com.amazon.ceviche, com.amazon.bueller.photos, Prime Video (FireTV), com.amazon.prism.android.service:remote, com.amazon.ods.kindleconnect, tv.arte.plus7, com.amazon.alexa.externalmediaplayer.fireos, com.amazon.tv.settings.v2, com.amazon.cardinal, com.amazon.identity.auth.device.authorization, com.android.providers.downloads, com.amazon.device.bluetoothkeymaplib, com.amazon.aca, com.amazon.tv.devicecontrolsettings, com.android.providers.calendar, com.zdf.android.mediathek, com.amazon.device.blepa, com.amazon.avsyncslider
app_id: de.swr.ard.avp.mobile.android.amazon
source: de.swr.ard.avp.mobile.android.amazon
entity_picture: /api/media_player_proxy/media_player.fire_tv_192_168_178_24?token=58b91e1085e90d5fccc93ef17a2ffc264730c8d9a72509b0f690952f5af1c748&cache=5f2296a481bf799c

**Comment by PRProd** [comment]
I have just published pre-release version [v2.3.15-b1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.15-b1) which contains your app request.  

I request that you would download it, test it out, and let me know if you experience any issues, or if it works as expected.  Thanks.

**Comment by tandama** [comment]
Hi, works fine, thank you very much!

**Comment by PRProd** [comment]
Thank you for your feedback!  Firemote version [v2.3.15](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.15) has now been officially released.
