### ISSUE TITLE
[New App Shortcut]: ZDF Mediathek

### ISSUE THREAD

**Issue by tandama** [PRProd/HA-Firemote#184]
### App Name

ZDF Mediathek

### Device Platform

Amazon Fire

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.zdf.android.mediathek

### Application Info

adb_response: mSurface=Surface(name=com.zdf.android.mediathek/com.zdf.android.mediathek.ui.common.MainActivity)
  mCurrentFocus=Window{ed2a20f u0 com.zdf.android.mediathek/com.zdf.android.mediathek.ui.common.MainActivity}
  mFocusedApp=AppWindowToken{feef96 token=Token{e60deb1 ActivityRecord{104fd58 u0 com.zdf.android.mediathek/.ui.common.MainActivity t213}}}
hdmi_input: null
device_class: tv
friendly_name: Fire TV 192.168.178.24
supported_features: 22961
source: com.zdf.android.mediathek
entity_picture: /api/media_player_proxy/media_player.fire_tv_192_168_178_24?token=58b91e1085e90d5fccc93ef17a2ffc264730c8d9a72509b0f690952f5af1c748&cache=36bb8256deca0ad7
source_list: com.amazon.client.metrics, com.amazon.imp, android.ext.services, com.amazon.device.messaging, com.android.proxyhandler, com.amazon.tv.ime, com.amazon.vizzini, com.amazon.tcomm, com.amazon.tv.devicecontrol, com.amazon.whad, com.amazon.tv.launcher, com.amazon.kso.blackbird, logcat, com.amazon.tv.alexaalerts, FireTV Store, Amazon Video, com.amazon.whisperjoin.middleware.np, com.amazon.whisperjoin.wss.wifiprovisioner, com.amazon.connectivitycontroller, com.amazon.device.rdmapplication, de.swr.ard.avp.mobile.android.amazon, com.amazon.webview.chromium:AWVArcusServiceProcess, com.amazon.alexamediaplayer.runtime.ftv, com.amazon.webview.chromium:AWVMetricsProcess, com.amazon.discoveryservice.core.android, com.amazon.ftv.xpicker, com.amazon.whisperlink.core.android, com.amazon.uxcontrollerservice, com.amazon.bueller.photos, com.amazon.prism.android.service:remote, com.amazon.alexa.externalmediaplayer.fireos, com.amazon.cardinal, com.zdf.android.mediathek, com.amazon.device.blepa, com.android.providers.tv, com.amazon.tv.livetv, com.amazon.ceviche, com.amazon.assetsync.service, com.amazon.ftv.screensaver, com.amazon.aca, com.amazon.tv.notificationcenter, Prime Video (FireTV)
app_id: com.zdf.android.mediathek

**Comment by PRProd** [comment]
I have just published pre-release version [v2.3.15-b1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.15-b1) which contains your app request.  

I request that you would download it, test it out, and let me know if you experience any issues, or if it works as expected.  Thanks.

**Comment by tandama** [comment]
Hi, works fine! Thank you very much!

**Comment by PRProd** [comment]
Thank you for your feedback!  Firemote version [v2.3.15](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.15) has now been officially released.
