### ISSUE TITLE
[New App Shortcut]: Pluto TV

### ISSUE THREAD

**Issue by d-nx** [PRProd/HA-Firemote#185]
### App Name

Pluto TV

### Device Platform

Chromecast Google TV

### Application Info

app_name: tv.pluto.android
source: tv.pluto.android
adb_response: mSurface=Surface(name=tv.pluto.android/tv.pluto.android.ui.main.LeanbackMainActivity)/@0x1c1ae7e
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x816a718
supported_features: 23997
source_list: com.google.android.apps.tv.launcherx:coreservices, com.android.systemui, com.droidlogic, com.google.android.ext.services, com.google.android.permissioncontroller, com.android.providers.media.module, com.google.android.tv.axel, com.google.android.tv.remotecontrol.logging, com.google.android.tv.remote.service, com.google.android.inputmethod.latin, tv.pluto.android, com.android.providers.tv, com.google.android.syncadapters.calendar, Play Store, com.google.process.gservices, com.google.android.apps.mediashell:privileged_process0, com.android.providers.calendar, com.android.vending:background, com.android.vending:quick_launch, Netflix, com.hulu.livingroomplus, com.google.android.gms.persistent, com.teamsmart.videomanager.tv, com.google.android.tts, Google Cast, com.google.android.gms, Google TV Launcher, com.google.android.katniss:search, com.google.android.katniss:interactor, flar2.homebutton
volume_level: 1
is_volume_muted: false
app_id: tv.pluto.android

**Comment by PRProd** [comment]
I have just published pre-release version [v2.3.15-b1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.15-b1) which contains your app request.  Feel free to download it, test it out, and let me know if you experience any issues.  If not, this will be included in the official release soon.

Enjoy!

**Comment by PRProd** [comment]
Firemote version [v2.3.15](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.15) has been officially released.
