### ISSUE TITLE
[New App Shortcut]: Syncler

### ISSUE THREAD

**Issue by Odan1988** [PRProd/HA-Firemote#186]
### App Name

Syncler

### Device Platform

Amazon Fire

### App Store Link or URL to .apk file if sideloaded

https://syncler.net/d

### Application Info

Tv/movie streaming app

**Comment by PRProd** [comment]
I have just published pre-release version [v2.3.15-b1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.15-b1) which contains your app request.  Feel free to download it, test it out, and let me know if you experience any issues.  If not, this will be included in the official release soon.

Enjoy!

**Comment by Odan1988** [comment]
Thank you so much.

**Comment by PRProd** [comment]
Firemote version [v2.3.15](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.15) has been officially released.
