### ISSUE TITLE
[New App Shortcut]: PBS

### ISSUE THREAD

**Issue by lk229** [PRProd/HA-Firemote#187]
### App Name

PBS

### Device Platform

Amazon Fire

### Application Info

adb_response: >-
  mSurface=Surface(name=com.pbs.video/com.pbs.video.tv.ui.home.TvMainActivity)/@0x8edda1
    mCurrentFocus=Window{b7fd3bc u0 com.pbs.video/com.pbs.video.tv.ui.home.TvMainActivity}
    mFocusedApp=AppWindowToken{9087906 token=Token{d3de7e1 ActivityRecord{958ad48 u0 com.pbs.video/.tv.ui.home.TvMainActivity t1521}}}

**Comment by PRProd** [comment]
I have just published pre-release version [v2.3.15-b1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.15-b1) which contains your app request.  Feel free to download it, test it out, and let me know if you experience any issues.  If not, this will be included in the official release soon.

Enjoy!

**Comment by lk229** [comment]
The new PBS link works correctly. Thank you.


*______________Lee Kupersmith*

**Comment by PRProd** [comment]
Thank you for your feedback.  Firemote version [v2.3.15](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.15) has now been officially released.
