### ISSUE TITLE
[New App Shortcut]: WOW

### ISSUE THREAD

**Issue by htmen79** [PRProd/HA-Firemote#188]
### App Name

WOW

### Device Platform

Amazon Fire

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/search?q=wow&c=apps&gl=DE

https://www.apkmirror.com/apk/sky-deutschland-fernsehen-gmbh/wow-android-tv/wow-android-tv-5-8-1-androidtv-de-release/wow-android-tv-5-8-1-androidtv-de-android-apk-download/

**Comment by htmen79** [comment]
Thank you very much, I forgot to include the name, sorry.

**Comment by PRProd** [comment]
I have just published pre-release version [v2.3.15-b1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.15-b1) which contains your app request.  Feel free to download it, test it out, and let me know if you experience any issues.  If not, this will be included in the official release soon.

Enjoy!

**Comment by PRProd** [comment]
Firemote version [v2.3.15](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.15) has now been officially released.
