### ISSUE TITLE
[New App Shortcut]: Watched

### ISSUE THREAD

**Issue by htmen79** [PRProd/HA-Firemote#189]
### App Name

Watched

### Device Platform

Amazon Fire

### App Store Link or URL to .apk file if sideloaded

https://www.watched.com/download/get?package=com.watched.play&platform=android&arch=universal

**Comment by PRProd** [comment]
I have just published pre-release version [v2.3.15-b1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.15-b1) which contains your app request.  Feel free to download it, test it out, and let me know if you experience any issues.  If not, this will be included in the official release soon.

Enjoy!

**Comment by PRProd** [comment]
Firemote version [v2.3.15](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.15) has now been officially released.
