### ISSUE TITLE
[New App Shortcut]: CyberGhost

### ISSUE THREAD

**Issue by jamhotld** [PRProd/HA-Firemote#19]
### App Name

Cyber Ghost

### Can this app be freely downloaded through official means?

- [X] Yes

### Optional Comments

I use this app all the time to be able to watch TV.

**Comment by PRProd** [comment]
Pre-release [v1.8.8](https://github.com/PRProd/HA-Firemote/releases/tag/v1.8.8) is now available for testing.  Please download the new version and let me know if the CyberGhost VPN app shortcut is working as expected.  Thanks.

**Comment by jamhotld** [comment]
Works like a charme! Thank you for the fast response!

**Comment by PRProd** [comment]
This is now available in the Firemote official release v1.9.0
