### ISSUE TITLE
[New App Shortcut]: iQIYI

### ISSUE THREAD

**Issue by samchuchu** [PRProd/HA-Firemote#191]
### App Name

iQIYI

### Device Platform

Amazon fire

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.iqiyi.i18n

### Application Info

adb_response: mSurface=Surface(name=)/@0x580edaf
      mSurface=Surface(name=com.iqiyi.i18n.tv/com.iqiyi.i18n.tv.home.activity.HomeActivity)/@0x9ac0b9
       mAnimationIsEntrance=true      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x3b11639
  mCurrentFocus=Window{7645c76 u0 com.iqiyi.i18n.tv/com.iqiyi.i18n.tv.home.activity.HomeActivity}
  mFocusedApp=AppWindowToken{32afd58 token=Token{795623b ActivityRecord{23690ca u0 com.iqiyi.i18n.tv/.home.activity.HomeActivity t1129}}}

### Optional Comments

Thank you so much guys. Not necessarily need this, but it's fun if it worked out. That's why I'm a fan of github and HA now.

**Comment by PRProd** [comment]
Firemote version [v2.3.15](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.15) has now been officially released.
