### ISSUE TITLE
[New App Shortcut]: France.tv

### ISSUE THREAD

**Issue by Philpagan** [PRProd/HA-Firemote#193]
### App Name

france.tv

### Device Platform

Amazon Fire

### App Store Link or URL to .apk file if sideloaded

https://www.amazon.fr/France-T%C3%A9l%C3%A9visions-francetv-pluzz/dp/B009FXK6D4

**Comment by PRProd** [comment]
I've just released version [v2.3.16](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.16) containing your app launch request!

Enjoy!
