### ISSUE TITLE
[New App Shortcut]: ARTE

### ISSUE THREAD

**Issue by Philpagan** [PRProd/HA-Firemote#194]
### App Name

ARTE

### Device Platform

Amazon Fire

### App Store Link or URL to .apk file if sideloaded

https://www.amazon.fr/ARTE-G-E-I-E/dp/B00AML8D24/ref=sr_1_1?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=WQFZ2QFR6KUM&keywords=arte&qid=1695547576&s=mobile-apps&sprefix=arte%2Cmobile-apps%2C117&sr=1-1

**Comment by PRProd** [comment]
I've just released version [v2.3.16](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.16) containing your app launch request!

Enjoy!

**Comment by Philpagan** [comment]
Thanks a lot Doug. Impressed by your fast response.

Le lun. 25 sept. 2023 à 23:05, Doug Nelson ***@***.***> a
écrit :
