### ISSUE TITLE
[New App Shortcut]: hdhomerun

### ISSUE THREAD

**Issue by brianhenson** [PRProd/HA-Firemote#195]
### App Name

hdhomerun

### Device Platform

Amazon Fire

### App Store Link or URL to .apk file if sideloaded

https://www.amazon.com/SiliconDust-USA-Inc-HDHomeRun/dp/B01MSBCRDY/

### Application Info

Used to provide live TV channels via the network to the FireTV

adb_response: mSurface=Surface(name=com.silicondust.view/com.silicondust.view.App)
      mSurface=Surface(name=com.silicondust.view/com.silicondust.view.App)
  mCurrentFocus=Window{90b9194 u0 com.silicondust.view/com.silicondust.view.App}
  mFocusedApp=AppWindowToken{d190a46 token=Token{6ee0c88 ActivityRecord{c2b702b u0 com.silicondust.view/.App t3155}}}

**Comment by PRProd** [comment]
I've just released version [v2.3.16](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.16) containing your app launch request!

Enjoy!
