### ISSUE TITLE
Close Settings app if button is pressed while app is open.

### ISSUE THREAD

**Issue by Gtasian** [PRProd/HA-Firemote#198]
**Is your feature request related to a problem? Please describe.**
Small issue for the Nvidia Shield- On the native remote, when you press settings, the settings overlay pops out. When you press settings again while the overlay is out, the overlay closes. With the firemote remote, pressing settings while the overlay is already out results in the settings overlay opening again.

**Describe the solution you'd like**
Have it work like the native remote where the settings button closes the settings app if open.

**Describe alternatives you've considered**
Thought about having it read the state of media player to see if settings app was open but updates happen too slow for this to be a meaningful difference.

**Comment by PRProd** [comment]
@Gtasian - Thanks for bringing that up.  If I'm remembering correctly, you can press the back button to dismiss that menu, but as you pointed out, it's not the same behavior as with the physical remote.  I actually forgot about that shortfall until you reminded me just now, so I'll take another look at it to see what I might be able to accomplish.

**Comment by PRProd** [comment]
I managed to find a [reddit thread](https://www.reddit.com/r/ShieldAndroidTV/comments/ih81m1/adb_and_keyevent_for_menu_button/jcibw0q/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) where I reached out asking for help with this exact issue 6 months ago.  Unfortunately, nobody has replied since my post.

I'm going to keep poking around, but if I can't find an answer on my own, I'll tag you, add this to #115 and hope that someone can offer their wisdom.

**Comment by Gtasian** [comment]
I tried looking into it further but I couldn't find too much about it either. I tried "learn_sendevent" commands but they didn't seem to do anything. Both "on" and "off" commands were identical but didn't seem to do anything when sending the commands. 

I then tried the "GET_PROPERTIES" and saw that the "current_app" changed instantly (needed to call the service each time before updates applied tho). I tried making a script to "GET_PROPERTIES", check the "current_app" and then send the appropriate commands, but I was unable to grab the "current_app" attribute since it was in a string format. I'm out of ideas at this point:/

**Comment by PRProd** [comment]
@Gtasian - I'm at a loss too.  I moved it [over here](https://github.com/PRProd/HA-Firemote/discussions/115#discussioncomment-7203959) into #115, so hopefully one day a wise sage might come along and bless us with the answer.  For now, I'll close this issue.
