### ISSUE TITLE
Add support for Fire TV 4k MAX

### ISSUE THREAD

**Issue by ghvader** [PRProd/HA-Firemote#2]
Request support for 4k Max remote.
It works with Android tv integration.
happy to help with testing.
https://www.amazon.com/dp/B08MQZXN1X
Edit: it works if I set compatibility to Event1

2nd: my remote controls my receiver for audio. is it possible to change what device the volume/mute buttons control? (my receivers are also in HA)

**Comment by PRProd** [comment]
Thanks for the link, and thanks in advance for the help!  Could you do me a favor?  Can you make sure you've downloaded the latest version of HA-Firemote through HACS, then follow these steps:
- Open a new Ha-Firemote card on your dashboard and point it to your 4K Max
- In the configuration menu for the card under compatibility mode, select "event0"
- Test several buttons
- Move down to "event1" and repeat your button testing
- Continue this process until you've made it all the way to event7
- Let me know which "event" mode (there may be more than one) was the most successful.

Thanks!

**Comment by PRProd** [comment]
Ha!  You answered my questions before I posted them!

About the other control, I might need to do some digging first.  Does your current physical fire remote do that magic already through ARC?

**Comment by ghvader** [comment]
No, it's IR.. fire tv through blue tooth (or whatever protocol they use, i assume BT) and the receiver is IR, you set it up in fire tv settings, but you pick the mfg. in my case, yamaha. so they have you press a few buttons and then ask you if it works. if it does they assign the IR codes to the remote, if not, on to the next...  since the receivers already work in HA, i don't know how much trouble it would be to instead of sending ADB command for volume up, to just call the existing services instead. "media_player.volume_down", "media_player.volume_up", mute.. etc.

**Comment by PRProd** [comment]
Gotcha!  I'll see what I can do.

**Comment by PRProd** [comment]
Just released 1.4.0 with support for Fire TV 4K Max.  Please let me know if it works as expected.

**Comment by ghvader** [comment]
> Just released 1.4.0 with support for Fire TV 4K Max. Please let me know if it works as expected.

Thank you for the fast turn around. I tested all and it works, except  Hulu and Prime video button. they do nothing. the netflix and disney + do launch.  I did leave compatibility at default instead of event 1. so I don't know if I need to try another event compatible options? but other than those 2 buttons all worked as expected.

**Comment by PRProd** [comment]
Does the hulu button work under "strong" mode?

**Comment by ghvader** [comment]
> Does the hulu button work under "strong" mode?

wife is watching tv lol I will test tomorrow and follow up.
thanks!!

**Comment by ghvader** [comment]
> > Does the hulu button work under "strong" mode?
> 
> wife is watching tv lol I will test tomorrow and follow up. thanks!!

Tested with "strong" mode, that made the hulu button work, but the prime video button still did nothing.

**Comment by PRProd** [comment]
[Version 1.5.0](https://github.com/PRProd/HA-Firemote/releases/tag/v1.5.0) is now available which should address the hulu button issue without the need for "strong" mode.

I'm still having some "special moments" with that silly Prime Video button.  I can only get that to launch using an ADB command that mimics a remote control button press.  I have a 100% success rate while testing, but you are at 0% so I'd imagine that my remote commands are different from yours.  Do you know how to use the "Android TV: Learn sendevent" service to capture a remote control button press?  If so, I'd love to have you evaluate your 'prime video' button press and let me know the results.

**Comment by ghvader** [comment]
> [Version 1.5.0](https://github.com/PRProd/HA-Firemote/releases/tag/v1.5.0) is now available which should address the hulu button issue without the need for "strong" mode.
> 
> I'm still having some "special moments" with that silly Prime Video button. I can only get that to launch using an ADB command that mimics a remote control button press. I have a 100% success rate while testing, but you are at 0% so I'd imagine that my remote commands are different from yours. Do you know how to use the "Android TV: Learn sendevent" service to capture a remote control button press? If so, I'd love to have you evaluate your 'prime video' button press and let me know the results.

I confirm the above. hulu worked. prime didn't. really nice feature with the custom app buttons. looks like there is room for 2 more, is 4 the max? I will look into the learn send event service and report back

**Comment by PRProd** [comment]
> I confirm the above. hulu worked. prime didn't

I'm glad that hulu is working!  I haven't given up on the prime button yet.  I'm persistant, so it WILL work... hopefully soon.


>  looks like there is room for 2 more, is 4 the max?

Nope!  Sky is the limit. Screen space is free.  :-)  Initially, I wanted to say no because of how much I wanted the UI to look like the real physical object, but that's just pride on my part.  Also, while I was actually using it last night, I thought to myself "It sure would be nice to have just one more button for..."  so, yes.  I'll work on making some sort of smooth easy to use solution for adding/removing buttons in the near future.  Thanks for the suggestion!

**Comment by ghvader** [comment]
Ok I ran it 3 times, not sure why the 1st was different than 2 or 3. but here is what i got.
`1
Output from service 'learn_sendevent' from media_player.basement_fire_tv: 'sendevent /dev/input/event6 20 0 0 && sendevent /dev/input/event6 20 1 0 && sendevent /dev/input/event6 1 745 1 && sendevent /dev/input/event6 0 0 0 && sendevent /dev/input/event6 1 745 0 && sendevent /dev/input/event6 0 0 0'

2
Output from service 'learn_sendevent' from media_player.basement_fire_tv: 'sendevent /dev/input/event6 1 745 1 && sendevent /dev/input/event6 0 0 0 && sendevent /dev/input/event6 1 745 0 && sendevent /dev/input/event6 0 0 0'

3
Output from service 'learn_sendevent' from media_player.basement_fire_tv: 'sendevent /dev/input/event6 1 745 1 && sendevent /dev/input/event6 0 0 0 && sendevent /dev/input/event6 1 745 0 && sendevent /dev/input/event6 0 0 0'`

**Comment by ghvader** [comment]
> > I confirm the above. hulu worked. prime didn't
> 
> I'm glad that hulu is working! I haven't given up on the prime button yet. I'm persistant, so it WILL work... hopefully soon.
> 
> > looks like there is room for 2 more, is 4 the max?
> 
> Nope! Sky is the limit. Screen space is free. :-) Initially, I wanted to say no because of how much I wanted the UI to look like the real physical object, but that's just pride on my part. Also, while I was actually using it last night, I thought to myself "It sure would be nice to have just one more button for..." so, yes. I'll work on making some sort of smooth easy to use solution for adding/removing buttons in the near future. Thanks for the suggestion!

Yeah I agree with the look part, but just like you i have 1 or 2 more would be nice to have on there. great job with that. also see post above for code i didn't tag u. thx

**Comment by PRProd** [comment]
Hmmm... interesting!  Based on what you posted, I bet that your prime button would work if you switched to compatibility mode 'event6'  The fun part is that a few days ago, it would have worked for you under event1, but maybe not today.  The 'revolving door' of random changes aren't unique to my custom card.  I've been reading about others who have tried to do this have experienced similar issues.

I have this (misguided?) confidence that if I just keep at it, eventually the defaults will be the most stable choices for any device, and that dealing with minor/random changes, such as your device wanting to listen more to event6 now, not event1 for some reason, will be made easier in the future.  I'm not giving up on anything yet!

**Comment by ghvader** [comment]
confirmed. event 6 setting did allow all the buttons to launch.
thanks for all the work on this. it's awesome since our remotes go missing so often, phones and tablets to the rescue. I will close this and open a new feature request for the volume buttons
