### ISSUE TITLE
[New App Shortcut]: TV4 Play

### ISSUE THREAD

**Issue by Skranta2** [PRProd/HA-Firemote#202]
### App Name

TV4 play

### Device Platform

Chromecast

### Optional Comments

Startpage:     https://www.tv4play.se/

Direct to TV channels:       https://www.tv4play.se/kanaler

**Comment by PRProd** [comment]
Hello @Skranta2!

I am currently in the process of adding Apple TV devices to the Firemote project (#200).  In this process, several beta versions of Firemote are published as "pre-release" versions.  I have added your app to the latest pre-release version [v2.4.0-b4](https://github.com/PRProd/HA-Firemote/releases/tag/v2.4.0-b4) which you can download and use right away, or you can choose to wait until the next official release.

Enjoy!

**Comment by PRProd** [comment]
@Skranta2 - The official release of Firemote version [v3.0.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.0) is now available!
