### ISSUE TITLE
[New App Shortcut]: NOSTV

### ISSUE THREAD

**Issue by horamarques** [PRProd/HA-Firemote#204]
### App Name

NOSTV

### Device Platform

Nvidia Shield

### App Store Link or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=pt.nos.iris.online&hl=pt_PT&gl=US

### Application Info

mSurface=Surface(name=pt.nostv.tv/pt.nos.iris.online.tv.MainTvActivity)/@0x8a1307
mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x105dcf2
mInputMethodTarget in display# 0 Window{a60a461 u0 pt.nostv.tv/pt.nos.iris.online.tv.MainTvActivity}

### Optional Comments

thanks for your support

**Comment by PRProd** [comment]
Hello @horamarques!

I am currently in the process of adding Apple TV devices to the Firemote project (#200).  In this process, several beta versions of Firemote are published as "pre-release" versions.  I have added your app to the latest pre-release version [v2.4.0-b4](https://github.com/PRProd/HA-Firemote/releases/tag/v2.4.0-b4) which you can download and use right away, or you can choose to wait until the next official release.

Enjoy!

**Comment by horamarques** [comment]
Hi @PRProd , Many thanks. Tested on v.2.4.0-b4 and its working fine.

**Comment by horamarques** [comment]
I Have an Apple TV, and im testing it with Fireremote also. Can you please add NOS TV to Apple TV? do you need any extra info?

Thanks again

**Comment by PRProd** [comment]
Absolutely!  I'm unable to download NOSTV on my Apple TV here in the US, so I will need some info from you.

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/8fee375d-08c9-4fd3-8d74-2e608c33c8a3)
1. Click on **Developer Tools**
2. Open the **STATES** tab
3. (optional) Type the name of your Apple TV Entity to help you sort through the list
4. Under **Filter attributes**, copy and paste the contents of the source_list into this thread.

For instance, my reply would look like this:
```
source_list: AMC+, App Store, Arcade, ARD Mediathek, ARTE, bgtime.tv, Channels, CNN, Computers, Crunchyroll, Curiosity Stream, Daily Wire, DAZN, DIRECTV, discovery+, Disney+, DS video, Emby, ESPN, F1 TV, FaceTime, Fitness, FOX Sports, Freevee, gcn, HDHomeRun, Hulu, IPTVX, IPVanish, iQIYI, JustWatchTV, Magenta TV, Max, Mediaset Infinity, MLB, Movies, Music, NBC Sports, Nebula, Netflix, NFL, NLZIET, NPO, OQEE by Free, Pandora, Paramount+, PBS, Peacock, Photos, Plex, Pluto TV, Podcasts, Prime Video, Proximus Pickx, Qmusic-BE, RaiPlay, Search, Settings, ShopHQ, Showtime, SiriusXM Radio for TV, Sky News, Speedtest, Spotify, STARZ, Steam Link, Stream, SVT Play, TBS, Tennis Channel, TestFlight, TIDAL, TNT, Tubi, TV, TV Shows, TV4 Play, TVNZ+, Twitch, VBTV, Viaplay, Videoland, VLC, VRT MAX, XCIPTV, YouTube, YouTube Kids, YouTube TV, ZDFmediathek
```

**Comment by horamarques** [comment]
> Absolutely! I'm unable to download NOSTV on my Apple TV here in the US, so I will need some info from you.
> 
> ![image](https://user-images.githubusercontent.com/25486599/274957912-8fee375d-08c9-4fd3-8d74-2e608c33c8a3.png)
> 
> 1. Click on **Developer Tools**
> 2. Open the **STATES** tab
> 3. (optional) Type the name of your Apple TV Entity to help you sort through the list
> 4. Under **Filter attributes**, copy and paste the contents of the source_list into this thread.
> 
> For instance, my reply would look like this:
> 
> ```
> source_list: AMC+, App Store, Arcade, ARD Mediathek, ARTE, bgtime.tv, Channels, CNN, Computers, Crunchyroll, Curiosity Stream, Daily Wire, DAZN, DIRECTV, discovery+, Disney+, DS video, Emby, ESPN, F1 TV, FaceTime, Fitness, FOX Sports, Freevee, gcn, HDHomeRun, Hulu, IPTVX, IPVanish, iQIYI, JustWatchTV, Magenta TV, Max, Mediaset Infinity, MLB, Movies, Music, NBC Sports, Nebula, Netflix, NFL, NLZIET, NPO, OQEE by Free, Pandora, Paramount+, PBS, Peacock, Photos, Plex, Pluto TV, Podcasts, Prime Video, Proximus Pickx, Qmusic-BE, RaiPlay, Search, Settings, ShopHQ, Showtime, SiriusXM Radio for TV, Sky News, Speedtest, Spotify, STARZ, Steam Link, Stream, SVT Play, TBS, Tennis Channel, TestFlight, TIDAL, TNT, Tubi, TV, TV Shows, TV4 Play, TVNZ+, Twitch, VBTV, Viaplay, Videoland, VLC, VRT MAX, XCIPTV, YouTube, YouTube Kids, YouTube TV, ZDFmediathek
> ```

Info from my AppleTV:
source_list:
  - Amazon Music
  - Apple TV Sample
  - "App\_Store"
  - Arcade
  - Bluetooth Inspector
  - Computers
  - Developer
  - Disney+
  - Fitness
  - Montessori Preschool
  - MotoGP
  - Movies
  - Music
  - Netflix
  - NOS TV
  - NOS TV (BETA)
  - Photos
  - Podcasts
  - Prime Video
  - RTP Play
  - Search
  - Settings
  - Sonic 1
  - Speedtest
  - testeApp
  - TestFlight
  - TV
  - Udemy
  - YouTube

Thanks once again

**Comment by PRProd** [comment]
No problem!  This will be available in the next release.

I have a quick question for you: Do you speak a non-English language?  If so, I'm wondering if you would be willing to help me out.  I'd simply send you a list of English words/phrases that are used in the Firemote setup page, and what I hope are the best translations for those words.  You can reply by offering corrections.  Are you interested?

**Comment by horamarques** [comment]
I speak Portuguese, feel free to send me the list of words and I will help you.

Best regards

**Comment by PRProd** [comment]
Here is the list of en -> pt translations:
```json
  "pt": {
      "App Launch Button": "Botão de Inicialização Do Aplicativo",
      "Associated": "Associada",
      "bottom": "fundo",
      "Compatibility Mode": "Modo de compatibilidade",
      "Device Family": "Família de Dispositivos",
      "Device Model": "Modelo do Dispositivo",
      "Device Name Text Color": "Cor do Texto do Nome do dispositivo",
      "Function: Control Center": "Função: Centro de Controle",
      "Function: Find My Remote": "Função: Encontre Meu Controle Remoto",
      "Function: Mute": "Função: Mudo",
      "Function: Next": "Função: Próximo",
      "Function: Previous": "Função: Anterior",
      "Function: Reboot": "Função: Reiniciar",
      "Function: Search": "Função: Pesquisa",
      "Function: Settings": "Função: Configurações",
      "Function: Skip Backward": "Função: Pular Para trás",
      "Function: Skip Forward": "Função: Pular Adiante",
      "Function: Switch Apps": "Função: Alternar Aplicativos",
      "hidden": "escondido",
      "Name Position": "Posição do Nome",
      "Remote Style": "Estilo Remoto",
      "Scale": "Escala",
      "top": "topo",
      "Visible Device Name": "Nome do Dispositivo Visível",
  },
```

This is how some of those words will be used:

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/5ac3c780-9a1a-4577-9c0d-f938738f8a36)

**Comment by horamarques** [comment]
Please find below. Translations to Portuguese from Portugal (PT-PT). For Portuguese-Brasilian (PT-BR) your text is OK. 

"pt": {
      "App Launch Button": "Botão de Inicialização Da Aplicação",
      "Associated": "Associada",
      "bottom": "fundo",
      "Compatibility Mode": "Modo de compatibilidade",
      "Device Family": "Família de Dispositivos",
      "Device Model": "Modelo do Dispositivo",
      "Device Name Text Color": "Cor do Texto do Nome do dispositivo",
      "Function: Control Center": "Função: Centro de Controlo",
      "Function: Find My Remote": "Função: Encontrar Controlo Remoto",
      "Function: Mute": "Função: Mudo",
      "Function: Next": "Função: Próximo",
      "Function: Previous": "Função: Anterior",
      "Function: Reboot": "Função: Reiniciar",
      "Function: Search": "Função: Pesquisa",
      "Function: Settings": "Função: Configurações",
      "Function: Skip Backward": "Função: Saltar Para trás",
      "Function: Skip Forward": "Função: Saltar par aa Frente",
      "Function: Switch Apps": "Função: Alternar Aplicativos",
      "hidden": "escondido",
      "Name Position": "Posição do Nome",
      "Remote Style": "Estilo Controlo Remoto",
      "Scale": "Escala",
      "top": "topo",
      "Visible Device Name": "Nome do Dispositivo Visível",
  },

**Comment by PRProd** [comment]
THANK YOU @horamarques!

**Comment by PRProd** [comment]
@horamarques - The official release of Firemote version [v3.0.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.0) is now available!  NOSTV is included, as well as both pt and pt-BR language translations!

Enjoy!
