### ISSUE TITLE
[New App Shortcut]: U-NEXT

### ISSUE THREAD

**Issue by JGKarlin** [PRProd/HA-Firemote#206]
### App Name

U-NEXT

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/jp/app/u-next-%E6%98%A0%E7%94%BB%E3%82%84%E3%83%89%E3%83%A9%E3%83%9E-%E3%82%A2%E3%83%8B%E3%83%A1%E3%81%AA%E3%81%A9%E3%81%AE%E5%8B%95%E7%94%BB%E3%81%8C%E8%A6%8B%E6%94%BE%E9%A1%8C/id882477693

### Application Info

U-NEXT is a premium streaming service provided by Sony in Japan.

**Comment by JGKarlin** [comment]
source_list: ABC News Live, App Store, Arcade, CBS News, Computers, Disney+, FaceTime, Fitness, HueParty, Hulu, Infuse, Moonlight, Movies, Music, NBC News, Netflix, Photos, Podcasts, Prime Video, Search, Settings, Steam Link, TV, TV Shows, Twitch, U-NEXT, VLC, YouTube

**Comment by PRProd** [comment]
Thanks @JGKarlin for that additional info!

I have just published Firemote version [v3.0.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3-0-2) which contains your app shortcut request.

Enjoy!
