### ISSUE TITLE
[New App Shortcut]: Infuse

### ISSUE THREAD

**Issue by nikolaj7072** [PRProd/HA-Firemote#207]
### App Name

Infuse

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/infuse-video-player/id1136220934?mt=8

### Application Info

source_list:
  - "App\_Store"
  - Arcade
  - Computere
  - discovery+
  - Disney+
  - DRTV
  - Film
  - Fotos
  - Indstillinger
  - Infuse
  - Musik
  - Podcasts
  - Speedtest
  - Spotify
  - Steam Link
  - Søg
  - TV
  - TV 2 Play
  - Viaplay
  - VLC
  - YouSee Play
  - YouTube

**Comment by PRProd** [comment]
Greetings @nikolaj7072!

I'm working on this request right now!  :smile:

Based on your app list, it looks like your native language is not English, is that correct?  If so, would you be willing to help out by helping me with some translations?  If you tell me the language you are using in Home Assistant and Apple TV, I will send back a small list of translations for your review.  Without proper translations, it looks like a few of the apps on your list will not open through Firemote.

**Comment by nikolaj7072** [comment]
Hi Doug.

Yes, Danish is my native language, and yes, I will happily translate into
Danish. I also have some Danish TV apps I would like to be added to the
remote, but let's take one step at a time 😉

Best regards

Nikolaj Christoffersen
+45 41 26 37 16

ons. 18. okt. 2023 17.56 skrev Doug Nelson ***@***.***>:

**Comment by PRProd** [comment]
Please review this list and let me know if any changes should be made, or if anything is missing.  The included picture displays how most of these translations are being used.
```json
  "da": {
      "App Launch Button": "Knap til start af app",
      "Apple Computers": "Apple Computeres",
      "Apple Music": "Apple Musik",
      "Apple Photos": "Apple Fotos",
      "Associated": "Tilhørende",
      "bottom": "bund",
      "Compatibility Mode": "Kompatibilitetstilstand",
      "Computers": "Computere",
      "Device Family": "Enhedsfamilie",
      "Device Model": "Enhed Model",
      "Device Name Text Color": "Tekstfarve på enhedsnavn",
      "Function: Control Center": "Funktion: Kontrolcenter",
      "Function: Find My Remote": "Funktion: Find min fjernbetjening",
      "Function: Mute": "Funktion: Slå lyden fra",
      "Function: Next": "Funktion: Næste",
      "Function: Previous": "Funktion: Tidligere",
      "Function: Reboot": "Funktion: Genstart",
      "Function: Search": "Funktion: Søg",
      "Function: Settings": "Funktion: Indstillinger",
      "Function: Skip Backward": "Funktion: Spring tilbage",
      "Function: Skip Forward": "Funktion: Spring fremad",
      "Function: Switch Apps": "Funktion: Skift apps",
      "hidden": "skjult",
      "Music": "Musik",
      "Name Position": "Navn Stilling",
      "Photos": "Fotos",
      "Remote Style": "Fjernbetjening stil",
      "Scale": "Størrelse",
      "Settings": "Indstillinger",
      "Search": "Søg",
      "Visible Device Name": "Synligt enhedsnavn",
  },
```
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/63b29718-3ef6-4110-b2a9-12eecafba482)

**Comment by nikolaj7072** [comment]
Here are the ones that need to be changed:
      "App Launch Button": "App-knap",
      "Apple Computers": "Apple Computere",
      "Device Model": "Enhedsmodel",
      "Name Position": "Position på navn",
      "Remote Style": "Fjernbetjeningsstil",

**Comment by PRProd** [comment]
Thank you so much for that @nikolaj7072!

**Comment by PRProd** [comment]
Release version [v3.0.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.1) which contains your app request and your translation has just been published.  

Thanks again, and Enjoy!
