### ISSUE TITLE
[New App Shortcut]: StartUp Show

### ISSUE THREAD

**Issue by erugaman** [PRProd/HA-Firemote#209]
### App Name

StartUp Show

### Device Platform

"Amazon Fire", "AppleTV"

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/ca/app/startup-show/id1483487566

### Application Info

With Startup Show you can add all of your favorite m3u playlists using our sleek-designed powerful built-in player.

**Comment by PRProd** [comment]
Greetings @erugaman!

I've been able to download and test the Startup Show app on Apple TV, Chromecast, NVIDIA-Shield, and Xiaomi Mi, but I'm unable to find a version of "Startup Show" that actually works properly on my Fire TV. 

I'm unable to download "Startup Show" through the Fire TV store, so I've been hunting for the proper APK.  I did notice that "Startup Show TV" (same logo, different name) does work properly on my Fire TV.  Is that the one I should use for the Fire TV?

Options for both "Startup Show" and "Startup Show TV" are available through the Google Play store for the Chromecast, Shield, and Xiaomi, so I can choose either one.  Only "Startup Show" exists for the Apple TV.  It's a little confusing.

**Comment by erugaman** [comment]
I only use the app for AndroidTV and AppleTV, I think that the app for
FireTV has to be downloaded from a custom repository.

In the HOME menu (top left tab) of downloader app, press select to open the
popup keyboard.

<https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/48192819202/original/NUA_T2YYt0sbAbHHHa4ZlZRA-08OEOLN_g.jpeg?1645504514>

Enter the code *13936 in to the HOME menu and then select the GO button.
Alternatively you can type in **67239*
If the above codes are not working for you enter link: rebrand.ly/apollotv
<http://apg.ooo/sstv.apk>and then Click the GO button

If that link doesn't work please use
<https://get.filelinked.com/>*apg.ooo/aptv.apk
<http://apg.ooo/aptv.apk>*

That’s all.



Enviado desde mi iPhone

**Comment by PRProd** [comment]
Thanks @erugaman!  It looks like the ones I found for each device were correct.

**Comment by erugaman** [comment]
Thanks for your help!


Enviado desde mi iPhone

**Comment by PRProd** [comment]
Release version [v3.0.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.1) which contains your app request has just been published.  

Enjoy!

**Comment by erugaman** [comment]
Great!!!

Thanks again.


Enviado desde mi iPhone
