### ISSUE TITLE
[New App Shortcut]: Syncnext

### ISSUE THREAD

**Issue by binghun9806** [PRProd/HA-Firemote#210]
App Name
Syncnext

Device Platform
 "AppleTV"

App Store Link and/or URL to .apk file if sideloaded
https://apps.apple.com/us/app/syncnext/id1591770603

Application Info
Syncnext is a media player that provides a beautiful interface and supports VOD protocols. It offers metadata matching, playback progress management, VOD content search, and VOD playback source subscription functionality.

Optional Comments
No response

**Comment by PRProd** [comment]
Closing as duplicate to #212
