### ISSUE TITLE
[New App Shortcut]: Cheers - Danmu Player

### ISSUE THREAD

**Issue by binghun9806** [PRProd/HA-Firemote#211]
### App Name

Cheers - Danmu Player

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/cheers-danmu-player/id1643375332

### Application Info

A new danmu player, support connect SMB services or play video directly through the link.

### Optional Comments

No response

**Comment by PRProd** [comment]
Greetings @binghun9806!

It appears that this app download will cost me $5.99.  I'd like to avoid buying an app that I probably won't use, so I would like your help. Please follow the linked instructions here: [Details for App Requests -> For Apple TV Devices](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#for-apple-tv-devices), and reply below with your results.  The list you provide will allow me to add your app request without having to buy the app for myself.

Based on your app requests, it looks like your native language is not English, is that correct? If so, would you be willing to help out by helping me with some translations? If you tell me the language you are using in Home Assistant and Apple TV, I will send back a small list of translations for your review.  Your small contribution could really help a lot of people!  Please let me know.

Thanks.

**Comment by PRProd** [comment]
@binghun9806 - Have you had an opportunity to check this out yet?

**Comment by PRProd** [comment]
@binghun9806 - Have you had a chance to go through the steps listed at this link: [Details for App Requests -> For Apple TV Devices](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#for-apple-tv-devices)?

I'd love to add this for you, but I still need your help with this step.

**Comment by PRProd** [comment]
@binghun9806 - I haven't heard from you in a month, and I'm unable to continue processing this request until you provide the results of the [steps listed here](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-apple-tv-devices).

I will leave this open for a few more days, and if I haven't heard back from you yet, I will close this issue as stale.
