### ISSUE TITLE
[New App Shortcut]: Kayo Sports

### ISSUE THREAD

**Issue by bacco007** [PRProd/HA-Firemote#213]
### App Name

Kayo Sports (AU)

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://itunes.apple.com/au/app/kayo-sports/id1434518367?mt=8

### Application Info

source_list: 10 play, 7plus, 9Now, ABC iview, App Store, Arcade, beIN Sports Connect, BINGE, Bluetooth Inspector, Channels, Computers, FaceTime, Fitness, Flash, Infuse, iPlayTV, IPTVX, Kayo, LiSTNR, Movies, Music, myTuner Radio Free, Netflix, Optus Sport, Photos, Plex, Podcasts, Prime Video, Red Bull TV, SBS On Demand, Search, Settings, Spotify, Stan, TV, TV Shows, TvhClient, YouTube

**Comment by PRProd** [comment]
@bacco007 ~ This source list is awesome!  I'm using it to confirm some AU only Apple TV apps that haven't been requested yet.

**Comment by PRProd** [comment]
Release version [v3.0.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.1) which contains your app request and six other apps I found on your list has just been published.  

Enjoy!
