### ISSUE TITLE
[New App Shortcut]: Flash (AU)

### ISSUE THREAD

**Issue by bacco007** [PRProd/HA-Firemote#214]
### App Name

Flash (AU)

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/au/app/flash-news/id1541762831

### Application Info

See my Kayo request :)

**Comment by PRProd** [comment]
Release version [v3.0.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.1) which contains your app request has just been published.  

Enjoy!
