### ISSUE TITLE
[New App Shortcut]: Binge (AU)

### ISSUE THREAD

**Issue by bacco007** [PRProd/HA-Firemote#215]
### App Name

Binge (AU)

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/au/app/binge-entertainment/id1486598248

**Comment by PRProd** [comment]
Release version [v3.0.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.1) which contains your app request has just been published.  

Enjoy!
