### ISSUE TITLE
[New App Shortcut]: iVysílání ČT

### ISSUE THREAD

**Issue by PetrolejCZ** [PRProd/HA-Firemote#216]
### App Name

iVysílání České televize

### Device Platform

Chromecast

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=cz.ceskatelevize.ivysilani.tvapp&hl=cs&gl=US

### Application Info

adb_response: >-
  mSurface=Surface(name=cz.ceskatelevize.ivysilani.tvapp/cz.ceskatelevize.ivysilani.tvapp.MainActivity)/@0x18e6bb0
        mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xcbb8b4f

**Comment by PRProd** [comment]
Greetings @PetrolejCZ!

I have just published Firemote version [v3.0.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3-0-2) which contains your app shortcut request.

Enjoy!
