### ISSUE TITLE
[New App Shortcut]: Bookmarker 1

### ISSUE THREAD

**Issue by berg4996** [PRProd/HA-Firemote#218]
### App Name

Bookmarker 1

### Device Platform

Amazon Fire

### Optional Comments

It is an app available to Amazon FireTV devices.  I use this to call a URL in Silk to view my surveillance cameras.  

Thank you!

**Comment by PRProd** [comment]
Greetings @berg4996!

I have just published Firemote version [v3.0.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3-0-2) which contains your app shortcut request.

Enjoy!

**Comment by berg4996** [comment]
I appreciate it more than you know.   Im going to submit one more app request later today.   I will send you more coffee too.  Thank you,Robert Berg714-809-8051Sent from my iPhoneOn Oct 23, 2023, at 12:57 PM, Doug Nelson ***@***.***> wrote:﻿
Greetings @berg4996!
I have just published Firemote version v3.0.2 which contains your app shortcut request.
Enjoy!

**Comment by PRProd** [comment]
Always happy to help!
