### ISSUE TITLE
[New App Shortcut]: Sling

### ISSUE THREAD

**Issue by berg4996** [PRProd/HA-Firemote#219]
### App Name

Sling

### Device Platform

Amazon Fire

### Optional Comments

Sling TV.  Available on Amazon Fire TV's and Devices.

Thank you!  I am really impressed with what you have done.  I will send a gift card as a thank you!

**Comment by PRProd** [comment]
WOW @berg4996!  You are very generous!  THANK YOU!!

I have just published Firemote version [v3.0.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3-0-2) which contains your app shortcut request.

Enjoy!
