### ISSUE TITLE
[New App Shortcut]: Fubo

### ISSUE THREAD

**Issue by berg4996** [PRProd/HA-Firemote#220]
### App Name

Fubo

### Device Platform

Amazon Fire

### Optional Comments

Fubo is available for download on all Amazon Fire Devices.  It is sometimes referenced as Fubo TV.

I am now using Firemote on several Fire TV's and Amazon Fire devices.   The flexibility you provided along with the instructions have been truly amazing.  It has simplified my automation tremendously.  I will buy you more Coffee!!

Thank you,

Robert Berg

**Comment by PRProd** [comment]
@berg4996 - WOW!  You are beyond generous!  I sincerely appreciate your kindness!

This should hopefully be released soon.  I'm waiting to hear back about something in issue #148 first.  If it takes too long to hear back from them, I'll work around it so you can have this right away.

**Comment by berg4996** [comment]
Much appreciated!!Have a great day.  Thank you,Robert Berg714-809-8051Sent from my iPhoneOn Oct 24, 2023, at 4:46 PM, Doug Nelson ***@***.***> wrote:﻿
@berg4996 - WOW!  You are beyond generous!  I sincerely appreciate your kindness!
This should hopefully be released soon.  I'm waiting to hear back about something in issue #148 first.  If it takes too long to hear back from them, I'll work around it so you can have this right away.

**Comment by PRProd** [comment]
Version [v3.0.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.3) has just been released with your app request included!

Enjoy!

**Comment by berg4996** [comment]
Awesome, thank you so much!

**Comment by PRProd** [comment]
You're welcome!  I'm happy to help!
