### ISSUE TITLE
[New App Shortcut]: Swiftfin

### ISSUE THREAD

**Issue by Paradox8** [PRProd/HA-Firemote#221]
### App Name

Swiftfin

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/swiftfin/id1604098728

### Application Info

Official Jellyfin client for tvOS.
Even though app name is swiftfin, the name in sources_list for the Apple TV integration is Jellyfin

source_list: 10 play, 7plus, 9Now, ABC iview, App Store, Arcade, Computers, FaceTime, Fitness, Hill Climb, Infuse, iPlayTV, Jellyfin, Minion Rush, Movies, Music, Photos, Plex, Podcasts, Prime Video, Red Bull TV, SBS On Demand, Search, Settings, Sonic 2, Spotify, Steam Link, Tailscale, TV, TV Shows, YouTube

**Comment by PRProd** [comment]
Version [v3.0.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.3) has just been released with your app request included!

Enjoy!
