### ISSUE TITLE
[New App Shortcut]: Tailscale

### ISSUE THREAD

**Issue by Paradox8** [PRProd/HA-Firemote#222]
### App Name

Tailscale

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/tailscale/id1470499037

### Application Info

source_list: Tailscale

**Comment by PRProd** [comment]
Version [v3.0.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.3) has just been released with your app request included!

Enjoy!
