### ISSUE TITLE
[New App Shortcut]: iPlayTV

### ISSUE THREAD

**Issue by Paradox8** [PRProd/HA-Firemote#223]
### App Name

iPlayTV

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/sa/app/iplaytv-iptv-m3u-player/id1072226801

### Application Info

source_list: iPlayTV

**Comment by PRProd** [comment]
Version [v3.0.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.3) has just been released with your app request included!

Enjoy!
