### ISSUE TITLE
Add ability to "Hide" app buttons.

### ISSUE THREAD

**Issue by GWLlosa** [PRProd/HA-Firemote#224]
**Is your feature request related to a problem? Please describe.**
When I'm setting up my FireMote card, it defaults to having 4 app buttons.  In my setup, I don't want/need app buttons, so I'd like to hide them. 

**Describe the solution you'd like**
If the app buttons were hideable, that would achieve the goal.

**Describe alternatives you've considered**
I tried overriding the app button selected app to "none", and that made the button blank, but not hidden.

**Comment by PRProd** [comment]
For clarity sake, this request is only for the **App Launcher 2** (AL2) style remote, correct?

**Comment by PRProd** [comment]
@GWLlosa 

I just published Firemote version [v3.0.4](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.4) which allows the **App Launcher 2** (AL2) style remote to no longer have a minimum number of 4 apps.

I've closed this issue for now, but feel free to reply here if something isn't quite right for you yet.

Enjoy!
