### ISSUE TITLE
[New App Shortcut]: TV 2 Play

### ISSUE THREAD

**Issue by nikolaj7072** [PRProd/HA-Firemote#226]
### App Name

TV 2 Play

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/dk/app/tv-2-play/id515236434?l=da

### Application Info

source_list:

"App_Store"
Arcade
Computere
discovery+
Disney+
DRTV
Film
Fotos
Indstillinger
Infuse
Musik
Podcasts
Speedtest
Spotify
Steam Link
Søg
TV
TV 2 Play
Viaplay
VLC
YouSee Play
YouTube

**Comment by PRProd** [comment]
Greetings @nikolaj7072!

I just published Firemote version [v3.0.4](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.4) which contains your app request.

Enjoy!
