### ISSUE TITLE
[New App Shortcut]: MEO Go

### ISSUE THREAD

**Issue by jpleite** [PRProd/HA-Firemote#231]
### App Name

MEO Go

### Device Platform

Apple TV, Android TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/pt/app/meo-go/id394637480?platform=appleTV

**Comment by PRProd** [comment]
Hello @jpleite!

This app is unavailable in my country through the Apple TV store, so I need some more information from you to continue.  Please follow the  [Details for App Requests](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests) steps found in the section [For Apple TV Devices](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#for-apple-tv-devices) and reply back here with the results.

Thanks!

**Comment by jpleite** [comment]
Thanks. Here it goes
Apple TV:

`source_list: Air Wings, Alba, AngryBirdsReloaded, App Store, Arcade, Beach Buggy Racing, Computers, Cut the Rope, DayView, Disney+, Epic Orchestra, FaceTime, Fitness, Frogger TT, Hangman, HBO Max, Hit Tennis 3, Infuse, iPlayTV, JustWatchTV, Leo's Fortune, MEO, Movies, Music, Netflix, Offroad Legends 2, Photos, Plex, Podcasts, Prime Video, Rayman, Rayman Adventures, RTP Play, Search, Settings, SketchParty TV, SkyShowtime, Snappy IPTV, SongPop Party, Sonic CD, Sonic Racing, Speedtest, Spire Blast, Super Mega Mini Party, TED, TestFlight, Trailers, TV, Vevo, VLC, wurdweb, YouTube`

Android

```
      mSurface=Surface(name=Taskbar$_3276)/@0x1e5e90e
      mSurface=Surface(name=NavigationBar0$_2720)/@0x6cd0f4b
      mSurface=Surface(name=com.samsung.android.app.cocktailbarservice/com.samsung.android.app.cocktailbarservice.CocktailBarService$_8168)/@0x4da0be6
      mSurface=Surface(name=StatusBar$_2720)/@0xdbbc21f
      mSurface=Surface(name=pt.ptinovacao.rma.meomobile/pt.ptinovacao.rma.meomobile.activities.ActivityDashboardFragment$_11140)/@0x717c652
      mSurface=Surface(name=com.android.systemui.ImageWallpaper$_2720)/@0xaafe59c
```

**Comment by PRProd** [comment]
Excellent!  Thank you!

**Comment by PRProd** [comment]
@jpleite - I'm not confident that I have the Android TV commands quite right yet, so I would like your help once more.

Please run the following command and let me know if your Android TV switches to the MEO Go App:
```
adb shell am start -n pt.ptinovacao.rma.meomobile/com.alticelabs.meogo.android.features.splash.ui.SplashActivity
```

Developer Tools -> Services -> select "Android Debug Bridge: ADB command" and the appropriate entity

**Comment by PRProd** [comment]
@jpleite ~ I just published Version [v3.0.5](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.5) which does include my untested command for launching the MEO Go app. 

Please download the new version and let me know if it works as expected.

Thanks.

**Comment by jpleite** [comment]
hi @PRProd I confirm it does work on Apple TV. Later I'll have access to an android box and will confirm if it works, Otherwise I'll double check your procedure. Thanks again

**Comment by jpleite** [comment]
Android activity was wrong

`mSurface=Surface(name=Splash Screen com.alticelabs.meo.androidtv)/@0x80e5fe9
      mSurface=Surface(name=AtchDlg:com.alticelabs.meo.androidtv/com.alticelabs.meo.androidtv.features.splash.ui.SplashActivity)/@0xae5970f
      mSurface=Surface(name=com.alticelabs.meo.androidtv/com.alticelabs.meo.androidtv.features.splash.ui.SplashActivity)/@0xe6411a5
       mAnimationIsEntrance=true      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xe4acd88
  mInputMethodTarget in display# 0 Window{80ea799 u0 Splash Screen com.alticelabs.meo.androidtv}`

The activity that launches the app is `com.alticelabs.meo.androidtv/com.alticelabs.meo.androidtv.features.splash.ui.SplashActivity`

**Comment by PRProd** [comment]
@jpleite ~ **Thank you** for providing the working activity!

Firemote version [v3.0.6](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.6) has just been published, and it includes the working Android launch command that you gave me.

Enjoy!
