### ISSUE TITLE
HBO MAX button not opening app on nVidia Shield

### ISSUE THREAD

**Issue by futomara** [PRProd/HA-Firemote#232]
### Describe the bug

MAX is not launching when the button is pressed

### To Reproduce

Add the hbo-max button and press MAX

### Expected Behavior

Pressing the button should launch the MAX app

### Which Type of Device Do You Own?

Shield Pro (2015)

### Troubleshooting Steps Completed

By overriding a button and assigning the following adb command the app opens properly when pressing the overridden button: am start -n com.wbd.stream/com.wbd.beam.BeamActivity

example:

button_overrides:
  hamburger-button:
    service: androidtv.adb_command
    target:
      entity_id: media_player.android_tv_192_168_36_234
      command: am start -n com.wbd.stream/com.wbd.beam.BeamActivity

### Additional context

I believe the code needs to be updated to reflect the change

**Comment by PRProd** [comment]
Thanks @futomara!

When HBO max changed to MAX a while ago, they kept the app name the same behind the scenes... until now.  Thanks for letting me know about this!  I just published Firemote version [v3.0.4](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.4) which now has separate hbo-max and max app launchers.  In a future release, the hbo-max launcher will be removed.  After updating your Firemote version, you may also need to update your Firemote config to pick up the change.

Enjoy!

**Comment by dennisholtkamp** [comment]
In at least the Netherlands the max option doesn't work since the app provided over here  is still the hbo-max version (com.wbd.stream available on the play store https://play.google.com/store/apps/details?id=com.wbd.stream&hl=en)

**Comment by PRProd** [comment]
@dennisholtkamp - Thanks for letting me know.  I removed it because it was no longer available in my region after getting the latest updates, but I will put it back into the next official release.  Please watch issue #274 for updates.
