### ISSUE TITLE
[New App Shortcut]: NBC News

### ISSUE THREAD

**Issue by futomara** [PRProd/HA-Firemote#237]
### App Name

NBC News

### Device Platform

nVidia Shield

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.zumobi.msnbc&hl=en_US&gl=US

### Application Info

I was able to get the NBC News app to launch from the adb shell with: 
`am start -n com.zumobi.msnbc/com.nbc.androidottweb.main.MainActivity`

**Comment by PRProd** [comment]
@futomara 

Version [v3.0.5](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.5) has just been published, and this new version contains a shortcut button for the NBC News app.

Enjoy!
