### ISSUE TITLE
[New App Shortcut]: Fotoo

### ISSUE THREAD

**Issue by dannymertens** [PRProd/HA-Firemote#238]
### App Name

Fotoo

### Device Platform

AndroidTV, Shield, Google Chromecast

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.bo.fotoo

### Application Info

Fotoo screenviewer

**Comment by PRProd** [comment]
Greetings @dannymertens!

Firemote version [v3.0.6](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.6) has just been published, and it includes the fotoo app shortcut that you requested.

Enjoy!

**Comment by dannymertens** [comment]
Thanks!
