### ISSUE TITLE
[New App Shortcut]: Allente

### ISSUE THREAD

**Issue by johanudden** [PRProd/HA-Firemote#239]
### App Name

Allente

### Device Platform

Apple TV 

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/se/app/allente/id914487438

**Comment by PRProd** [comment]
Greetings @johanudden!

Firemote version [v3.0.6](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.6) has just been published, and it includes the Allente app shortcut that you requested.

Enjoy!
