### ISSUE TITLE
[New App Shortcut]: Moonlight Game Streaming

### ISSUE THREAD

**Issue by Jaythe2nd** [PRProd/HA-Firemote#243]
### App Name

Moonlight Game Streaming

### Device Platform

NVIDIA Shield

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.limelight&hl=en_GB

### Application Info

adb_response: mSurface=Surface(name=com.limelight/com.limelight.PcView)/@0xb43b6be
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xd9ef8c4

**Comment by PRProd** [comment]
Greetings @Jaythe2nd!

Firemote version [v3.0.7](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.7) has just been published and it contains the app shortcut for Moonlight Game Streaming as you requested.

Enjoy!

**Comment by Jaythe2nd** [comment]
Woo that was insanely fast, really impressive. Much appreciated.
