### ISSUE TITLE
[New App Shortcut]: Snappier IPTV

### ISSUE THREAD

**Issue by jbeck22** [PRProd/HA-Firemote#245]
### App Name

Snappier IPTV

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/snappier-iptv/id1579702567?platform=appleTV

**Comment by PRProd** [comment]
Greetings @jbeck22!

Firemote version [v3.0.7](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.7) has just been published and it includes the AppleTV shortcut for the Snappier IPTV app.

Enjoy!

**Comment by jbeck22** [comment]
Awesome!  Thanks so much!
