### ISSUE TITLE
Shortcut to switch between ATV Devices

### ISSUE THREAD

**Issue by jbeck22** [PRProd/HA-Firemote#246]
I have multiple ATV devices in my home.  All of them are the same model / year (ATV 4k Gen2).

Would it be possible to add a button or dropdown menu that would allow me to switch between different ATV entities without having to go in and edit the card properties?

**Comment by PRProd** [comment]
@jbeck22 - Besides having more than one Firemote card on your dashboard, or using a popup card like I suggested above, I can't really think of a clean easy way to do what you are asking.  Have you been able to come up with a solution on your own?

**Comment by PRProd** [comment]
@jbeck22 - Any input here?

**Comment by jbeck22** [comment]
@PRProd  -- I haven't gotten back to try the pop-up card.

I guess you can close this out until I can work on it again.  I can always open a net new issue if needed.
