### ISSUE TITLE
[New App Shortcut]: IPTV Smarters Pro

### ISSUE THREAD

**Issue by Jaykurb** [PRProd/HA-Firemote#249]
### App Name

IPTV Smarters Pro

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

firesticktricks.com/smarter

### Application Info

source_list:
  - IPTV Smarters Pro
app_id: com.nst.iptvsmarterstvbox
source: IPTV Smarters Pro
adb_response: "mSurface=Surface(name=com.nst.iptvsmarterstvbox/com.nst.iptvsmarterstvbox.view.activity.HoneyPlayer)\r\n      mSurface=Surface(name=SurfaceView)\r\n  mCurrentFocus=Window{3bb35dd5 u0 com.nst.iptvsmarterstvbox/com.nst.iptvsmarterstvbox.view.activity.HoneyPlayer}\r\n  mFocusedApp=AppWindowToken{145545b8 token=Token{3b14101b ActivityRecord{33adca2a u0 com.nst.iptvsmarterstvbox/.view.activity.HoneyPlayer t919}}}"
hdmi_input: null
device_class: tv
entity_picture: >-
  /api/media_player_proxy/media_player.fire_tv_192_168_1_114?token=9a0d3aa322461a25553c8545a7252009da2ce6f1d02c22bf3bfb9f21626a8d4a&cache=7b6239318002592f
friendly_name: Fire TV 192.168.1.114
supported_features: 22961

**Comment by PRProd** [comment]
Greetings @Jaykurb!

I have just published Firemote beta release version [v3.1.0.b1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.0b1) which contains the app shortcut for IPTV Smarters Pro.  Feel free to download this beta version and use it if you'd like, or you can wait until the next official Firemote release.

**Comment by PRProd** [comment]
I have just published Firemote version [v3.1.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.0) which puts moves this app request into the official release.

Enjoy!
