### ISSUE TITLE
[New App Shortcut]: CNN

### ISSUE THREAD

**Issue by listlesslife** [PRProd/HA-Firemote#25]
### App Name

CNN

### Can this app be freely downloaded through official means?

- [X] Yes

**Comment by PRProd** [comment]
App shortcut has been added to the latest release, [V1.9.1](https://github.com/PRProd/HA-Firemote/releases/tag/v1.9.1)

**Comment by skavan** [comment]
This one doesn't seem to work on Android/Google TV...

**Comment by PRProd** [comment]
@skavan ~

Do you have the latest version of Firemote?  The newest release [v4.1.0](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.0) includes a change to the CNN launcher code.

[See the changes here](https://github.com/PRProd/HA-Firemote/blame/main/dist/launcher-buttons.js#L1347-L1389)

As I went through the app launchers while building [support for Homatics](https://youtu.be/AggYjQ4vI-U) I noticed that the CNN app launcher was unique from the others, so I went through all of the devices I own to see if any of them also changed, and updated them accordingly.  

Can you confirm for me that you have the latest version of the CNN app, AND at least Firemote [v4.1.0](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.0) or greater?  If so, try un-installing CNN, and re-installing it.  If that doesn't work, please let me know your device type, and I'll take another look.  It's possible that it just changed again

-Doug

**Comment by skavan** [comment]
My utter stupudity. The App wasn't installed as I watch it through YouTube TV. So sorry to waste your time!

**Comment by PRProd** [comment]
ha ha!  No worries, man!  It's not a waste!  These things happen quite often, actually.  I'm grateful that people message me about them.  It's nearly impossible to keep [over 290 launchers](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers) across eight different platforms all up to date all of the time!

Have a great day!
