### ISSUE TITLE
[New App Shortcut]: ITVX

### ISSUE THREAD

**Issue by Jaykurb** [PRProd/HA-Firemote#250]
### App Name

ITVX

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/gb/app/itvx/id446079916

### Application Info

source_list:
  - Amazon Music
  - "App\_Store"
  - Arcade
  - Barbie Magical
  - BBC iPlayer
  - Channel 4
  - Computers
  - Fitness
  - IPTVX
  - ITVX
  - Movies
  - Music
  - My5
  - Netflix
  - NOW
  - Photos
  - Plex
  - Podcasts
  - Prime Video
  - Qmedia by QNAP
  - Search
  - Settings
  - TestFlight
  - TV
  - TV Shows
  - YouTube
  - YouTube Kids

**Comment by PRProd** [comment]
Greetings @Jaykurb!

I have just published Firemote beta release version [v3.1.0.b1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.0b1) which contains your app shortcut request for ITVX.  Feel free to download this beta version and use it if you'd like, or you can wait until the next official Firemote release.

**Comment by Jaykurb** [comment]
Thank you for adding the app shortcuts. A great integration! The documentation is excellent, too.

**Comment by PRProd** [comment]
Thank you for your kind words, @Jaykurb!  I've spent a lot of time on the documentation, and I try to build on it whenever I can.  I'm happy to hear that it's useful!

**Comment by PRProd** [comment]
I have just published Firemote version [v3.1.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.0) which moves this app request into the official release.

Enjoy!
