### ISSUE TITLE
[New App Shortcut]: BBC iPlayer

### ISSUE THREAD

**Issue by Jaykurb** [PRProd/HA-Firemote#251]
### App Name

BBC iPlayer

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/gb/app/bbc-iplayer/id416580485?l=da

### Application Info

source_list:
  - Amazon Music
  - "App\_Store"
  - Arcade
  - Barbie Magical
  - BBC iPlayer
  - Channel 4
  - Computers
  - Fitness
  - IPTVX
  - ITVX
  - Movies
  - Music
  - My5
  - Netflix
  - NOW
  - Photos
  - Plex
  - Podcasts
  - Prime Video
  - Qmedia by QNAP
  - Search
  - Settings
  - TestFlight
  - TV
  - TV Shows
  - YouTube
  - YouTube Kids

**Comment by PRProd** [comment]
Greetings @Jaykurb!

I have just published Firemote beta release version [v3.1.0.b1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.0b1) which contains the Apple TV App Shortcut for the BBC iPlayer app.  Feel free to download this beta version and use it if you'd like, or you can wait until the next official Firemote release.

Enjoy!

**Comment by PRProd** [comment]
I have just published Firemote version [v3.1.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.0) which moves this app request into the official release.

Enjoy!
