### ISSUE TITLE
[New App Shortcut]: Channel 4

### ISSUE THREAD

**Issue by Jaykurb** [PRProd/HA-Firemote#252]
### App Name

Channel 4

### Device Platform

Aple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/gb/app/channel-4/id432494037

### Application Info

source_list:
  - Amazon Music
  - "App\_Store"
  - Arcade
  - Barbie Magical
  - BBC iPlayer
  - Channel 4
  - Computers
  - Fitness
  - IPTVX
  - ITVX
  - Movies
  - Music
  - My5
  - Netflix
  - NOW
  - Photos
  - Plex
  - Podcasts
  - Prime Video
  - Qmedia by QNAP
  - Search
  - Settings
  - TestFlight
  - TV
  - TV Shows
  - YouTube
  - YouTube Kids

**Comment by PRProd** [comment]
Greetings @Jaykurb!

I have just published Firemote beta release version [v3.1.0.b1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.0b1) which contains your requested app shortcut for Channel 4.  Feel free to download this beta version and use it if you'd like, or you can wait until the next official Firemote release.

**Comment by PRProd** [comment]
I have just published Firemote version [v3.1.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.0) which moves this app request into the official release.

Enjoy!
