### ISSUE TITLE
[New App Shortcut]: Salt TV

### ISSUE THREAD

**Issue by andreasbuff** [PRProd/HA-Firemote#255]
### App Name

Salt TV

### Device Platform

Apple TV

### Application Info

source_list: 8fit, App Store, Arcade, ChessGame, Computer, DS photo, DS video, Einstellungen, FaceTime, FileBrowserTV, Filme, Fitness, Fotos, Hill Climb, IP Cam Soft Lite, Kitchen Stories, Musik, Netflix, NRJ, Plex, Podcasts, ProSieben, Real Racing 3, RTL+, Salt TV, Salt Video, Sonic 1, Speedtest, Spotify, Suchen, swissRADIO TV, SwissRadioLive, TV, VLC, Web Video Caster Receiver, wetter.com live, Wilmaa TV, YouTube, Zattoo
media_position_updated_at: 2023-11-15T17:00:46.631142+00:00

### Optional Comments

Hello, I am looking for the Application, called "Salt TV". "Salt Video" is optional, because I do not use it :-) 

Sorry, I can not provide you with the Store Link, as I only have a AppleTV and no IPhones.. 

But thank you very much for your support! 

PS: please explain, what to do next? Regards

**Comment by PRProd** [comment]
Greetings @andreasbuff!

I've been working on some other Firemote changes which involve beta releases for the community to test.  I have just published Firemote beta release version [v3.1.0.b2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.0b2) which also includes your app shortcut request for Salt TV.  Feel free to download this beta version and use it if you'd like, or you can wait until the next official Firemote release.

**Comment by andreasbuff** [comment]
Hello
Great, thank you. I downloaded the new version  v3.1.0.b2<https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.0b2> and I can see the “Salt.tv” (with the correct log), but I am away until Monday and therefore can not test it right now, sorry…

I will send you new informations, when I will be back home on Monday.

Thank you very, very much! Regards. Andreas

Von: Doug Nelson ***@***.***>
Gesendet: Donnerstag, 16. November 2023 01:32
An: PRProd/HA-Firemote ***@***.***>
Cc: andreasbuff ***@***.***>; Mention ***@***.***>
Betreff: Re: [PRProd/HA-Firemote] [New App Shortcut]: Salt TV (Issue #255)


Greetings @andreasbuff<https://github.com/andreasbuff>!

I've been working on some other Firemote changes which involve beta releases for the community to test. I have just published Firemote beta release version v3.1.0.b2<https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.0b2> which also includes your app shortcut request for Salt TV. Feel free to download this beta version and use it if you'd like, or you can wait until the next official Firemote release.

**Comment by PRProd** [comment]
I have just published Firemote version [v3.1.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.0) which moves this app request into the official release.

Enjoy!
