### ISSUE TITLE
[New App Shortcut]: Dropout

### ISSUE THREAD

**Issue by aroronchynn** [PRProd/HA-Firemote#256]
### App Name

Dropout

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/dropout-by-collegehumor/id1380833056

### Optional Comments

Best streaming comedy platform in years!

**Comment by PRProd** [comment]
Greetings @aroronchynn!

I've been working on some other Firemote changes which involve beta releases for the community to test.  I have just published Firemote beta release version [v3.1.0.b2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.0b2) which also includes your app shortcut request for Dropout.  Feel free to download this beta version and use it if you'd like, or you can wait until the next official Firemote release.

**Comment by PRProd** [comment]
I have just published Firemote version [v3.1.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.0) which moves this app request into the official release.

Enjoy!
