### ISSUE TITLE
[New App Shortcut]: Voyo.cz

### ISSUE THREAD

**Issue by Zeollus** [PRProd/HA-Firemote#257]
### App Name

Voyo.cz

### Device Platform

Chromecast 

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=net.cme.voyo.cz

**Comment by PRProd** [comment]
Greetings @Zeollus!

Firemote version [v3.1.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.1) has just been published, and it contains your app shortcut request.

Enjoy!

**Comment by Zeollus** [comment]
Thank you very much.
