### ISSUE TITLE
[New App Shortcut]: Strim (Norwegian streaming service)

### ISSUE THREAD

**Issue by aherbjornsen** [PRProd/HA-Firemote#259]
### App Name

Strim

### Device Platform

NVIDIA Shield

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=no.strim.atv

### Application Details

      mSurface=Surface(name=no.strim.atv/no.rikstv.atv.MainActivity)/@0x1bcb804
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xc6ca551
     mCurrentFocus=Window{94c454b u0 no.strim.atv/no.rikstv.atv.MainActivity}
     mFocusedApp=AppWindowToken{b529057 token=Token{f6975d6 ActivityRecord{be495f1 u0 no.strim.atv/no.rikstv.atv.MainActivity t5010}}}

**Comment by PRProd** [comment]
Greetings @aherbjornsen!

Firemote version [v3.1.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.1) has just been published, and it contains your app shortcut request.

Enjoy!
