### ISSUE TITLE
[New App Shortcut]: NordVPN

### ISSUE THREAD

**Issue by dgpmaluco** [PRProd/HA-Firemote#26]
### App Name

NordVPN

### Can this app be freely downloaded through official means?

- [X] Yes

### Optional Comments

Just a widely used vpn provider as I’m sure there are many others.
Any way to be able to add apps ourselves?

**Comment by PRProd** [comment]
App shortcut has been added to the latest release, [V1.9.1](https://github.com/PRProd/HA-Firemote/releases/tag/v1.9.1)
