### ISSUE TITLE
[New App Shortcut]: Youtube ReVanced

### ISSUE THREAD

**Issue by Socialblurr** [PRProd/HA-Firemote#262]
### App Name

Youtube ReVanced

### Device Platform

Amazon Fire, Chromecast, NVIDIA Shield, Xiaomi

### App Store Link and/or URL to .apk file if sideloaded

https://www.reddit.com/r/revancedapp/comments/159zbb6/guide_youtube_revanced/

### Application Details

Modded youtube client

### Optional Comments

app.revanced.android.youtube

**Comment by Socialblurr** [comment]
"adb shell am start app.revanced.android.youtube" can launch it through ADB bridge on HA natively

**Comment by PRProd** [comment]
Is there a unique logo that should go with this mod, or is the normal YouTube logo ok?

**Comment by PRProd** [comment]
@Socialblurr ~

I just published beta release version [v3.1.2b1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.2b1) which contains an untested app launch button for YouTube ReVanced.  Please download and test this beta version to make sure that it works properly before I put it into the official release.

Thanks.

**Comment by PRProd** [comment]
Greetings @Socialblurr!

I wanted to push through some other pending changes, so I ended up publishing this change into the production release [v3.1.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.2).  Feel free to comment here if you find an issue with this app launcher button.  If not, enjoy!

-Doug

**Comment by Socialblurr** [comment]
It worked perfectly on my Nvidia shield and it using the normal YouTube action is great because it actually highlights if it's the running app
