### ISSUE TITLE
[New Language Support]: German DE

### ISSUE THREAD

**Issue by panteLx** [PRProd/HA-Firemote#264]
### Language Code

de

### Translation Chart

```text
01. App Launch Button => Anwendungsstartknopf
02. App Launcher Relative Scale => Relativer Maßstab des Anwendungslaunchers
03. Apple Computers => Apple Computer
04. Apple Music => Apple Musik
05. Apple Photos => Apple Bilder
06. Associated => Assoziiert 
07. bottom => unten
08. Compatibility Mode => Kompatibilitätsmodus
09. Computers => Computer
10. Device Family => Gerätegruppe
11. Device Model => Gerätemodell
12. Device Name Text Color =>  Textfarbe des Gerätenamens
13. Function: Control Center => Funktion: Kontrollzentrum
14. Function: Find My Remote => Funktion: Finde meine Fernbedienung
15. Function: Mute => Funktion: Stummschalten
16. Function: Next => Funktion: Weiter
17. Function: Previous => Funktion: Zurück
18. Function: Reboot => Funktion: Neustarten
19. Function: Search => Funktion: Suchen
20. Function: Settings => Funktion: Einstellungen
21. Function: Skip Backward => Funktion: Zurückspulen
22. Function: Skip Forward => Funktion: Vorspulen
23. Function: Switch Apps => Funktion: Apps wechseln
24. hidden => versteckt
25. Music => Musik
26. Name Position => Position des Namens
27. Optional => Optional
28. Photos => Fotos
29. Remote Style => Aussehen der Fernbedienung
30. Scale => Größe
31. Settings => Einstellungen
32. Search => Suche
33. top => oben
34. Visible Device Name => Sichtbarer Gerätename
```

### Additional Comments (optional)

I only translated „Apps“ in some places to „Anwendungen“ because we typically also call it „Apps“. However in some places it makes more sense to call it „Anwendungen“.

**Comment by panteLx** [comment]
Got no Apple TV so no translation for the device_list.

**Comment by PRProd** [comment]
Thank you so much for this list @panteLx!

These translations have been added to the latest beta release version [v3.1.2b2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.2b2).

While working on this, I realized that I forgot to put one item in the list I had you fill out, so I'd like to know if I've translated it properly:
> Default for => Vorgabe für

As requested in #234, I'd like for you to download this beta version and try it out.  The translations you provided are used on the Firemote Card Configuration Visual Editor menus.  I'm more than happy to change anything that isn't quite right, you're the expert!  Here is a quick example of what some of those translations look like:

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/2e16979a-1419-439e-b6dd-44674e4387d8)

This image does not show all of the translations, so I encourage you to look around and let me know what you think.

Thank you!

**Comment by panteLx** [comment]
Great to hear that! 
I would translate default for to „Standard für“ instead of your translation. In my opinion it makes more sense. 
Everything else looks great. 

I’ll try the new beta asap.

**Comment by panteLx** [comment]
Tested it so far. There is a missing translation for
`Android Debug Bridge Entity => Android Debug Bridge Entität`

The Name „Android debug bridge“ itself isn’t translated so I would call it by the English name in the translation as well. 

Everything else (including the issue #234 is working fine !

**Comment by PRProd** [comment]
Thank you @panteLx!  You're my favorite person today!

**Comment by PRProd** [comment]
Updated screenshot:
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/9e7b3d10-795a-4252-9daa-c15692a9bbbb)

**Comment by PRProd** [comment]
@panteLx ~

Since you are my favorite today, I decided to publish your changes right now.  Version [v3.1.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.2) is available for everyone now!

Enjoy!  Thank you once more for all of your help!
