### ISSUE TITLE
[New App Shortcut]:  CCTV Viewer

### ISSUE THREAD

**Issue by woody1961** [PRProd/HA-Firemote#269]
### App Name

CCTV Viewer

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/cctv-viewer/id1450658761?platform=appleTV

### Application Details

source_list: Air Wings, App Store, Arcade, Asphalt 8, Breakneck, CCTV Viewer, CNN, Computers, Does not Commute, FaceTime, Fitness, Infuse, Max, Movies, Music, Netflix, Pandora, Paramount Network, Paramount+, PBS, Peacock, Photos, Podcasts, Prime Video, Protect, Search, Settings, Showtime Anytime, Speedtest, STARZ, Steam Link, The Weather Channel, TV, TV Shows, Twitch, Webcam HQ, YouTube

### Optional Comments

Thank you!

**Comment by PRProd** [comment]
Greetings @woody1961!

I just published Firemote version [v3.1.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.3) which contains a new app launcher for CCTV Viewer on Apple TV.  Enjoy!

-Doug
