### ISSUE TITLE
[New App Shortcut]: globo TV

### ISSUE THREAD

**Issue by PRProd** [PRProd/HA-Firemote#273]
### App Name

globo TV

### Device Platform

Amazon Fire

### Application Details

adb shell am start -a android.intent.action.MAIN -n com.globo.globotv/.maintv. MainActivity

### Optional Comments

Posted by @ronaldorj in #272

![globoTV-sent](https://github.com/PRProd/HA-Firemote/assets/25486599/6cfb16a1-82e0-4fb5-bdb6-375f50ca7839)

"globo-tv": {
"button": ' ',
"friendlyName": "globo TV",
"className": "globoPlayButton",
"appName": "com.globo.globotv",
"androidName": "com.globo.globotv",
"adbLaunchCommand": "adb shell am start -a android.intent.action.MAIN -n com.globo.globotv/.maintv. MainActivity",
"deviceFamily": ["amazon-fire"], },

globoPlayButton {
background: #000;
}

**Comment by PRProd** [comment]
@ronaldorj ~

Firemote version [v3.1.5](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.5) has just been published which contains the app shortcut that you requested.

Enjoy!

**Comment by ronaldorj** [comment]
thanks
