### ISSUE TITLE
[New App Shortcut]: HBO Max

### ISSUE THREAD

**Issue by Kipjr** [PRProd/HA-Firemote#274]
### App Name

HBO Max

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.hbo.hbonow

### Application Details

source_list:
  - HBO Max
  - ES File Explorer
  - Spotify
app_id: com.hbo.hbonow
source: HBO Max
hdmi_input: null
device_class: tv
friendly_name: Fire TV amazon

**Comment by Kipjr** [comment]
Nevermind, it is called Max instead of HBO Max

**Comment by PRProd** [comment]
@Kipjr & @dennisholtkamp ~

Firemote version [v3.1.5](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.5) has just been published, which replaces the previously removed HBO Max app launcher.  **PLEASE** let me know if/when this can be removed again.  Thanks!

-Doug

**Comment by dennisholtkamp** [comment]
Hi Doug fast service again 👍

will let you know when the app intent will change in the Netherlands. This is of course no guarentee this will also be the case in other regions

Dennis

**Comment by PRProd** [comment]
@dennisholtkamp ~

Checking in to see if the special Netherlands launcher is still valid or not.  I hope you are doing well!

**Comment by PRProd** [comment]
Interesting!  Thanks!

I think I will change the name in the dropdown menu from "HBO Max - will be removed soon" to "HBO Max - Netherlands" for the next Firemote release.

When the change is made, nothing will be required on your end.  It will just seamlessly adjust in the background.
