### ISSUE TITLE
Apple TV Media Player Entity not showing up in firemote card setup

### ISSUE THREAD

**Issue by hackintoshlover** [PRProd/HA-Firemote#276]
### Describe the bug

![WhatsApp Image 2023-12-17 at 13 42 40 (2)](https://github.com/PRProd/HA-Firemote/assets/40655406/cc209b4b-f7ac-42eb-89a0-def1e912ce62)
As per above image mentioned on the github page,
The firemote card should show up a media player entity in Aplle TV remote setup.
But in my case it does not and instead it shows up android debug bridge entity.
Is it normal or did i messed up?

Attached are my setup images below for your refrence.
![WhatsApp Image 2023-12-17 at 13 42 40](https://github.com/PRProd/HA-Firemote/assets/40655406/52a0c7c9-1aea-48be-a8b4-b766c218b134)
![WhatsApp Image 2023-12-17 at 13 42 40 (1)](https://github.com/PRProd/HA-Firemote/assets/40655406/bcfa388e-fdbb-4301-81fc-b35646764a9a)

### To Reproduce

Install Apple TV integration from Home Assistant and setup Firemote from HACS by following official guide.

### Expected Behavior

The Media Player Entity should show up

### Which Type of Device Do You Own?

Apple TV Gen 4

**Comment by PRProd** [comment]
THANK YOU @hackintoshlover!

This has been fixed in Firemote version [v3.1.6](https://github.com/PRProd/HA-Firemote/releases/tag/v3.1.6)
