### ISSUE TITLE
[Existing App Shortcut]: 

### ISSUE THREAD

**Issue by github-sunny** [PRProd/HA-Firemote#28]
### App Name

Paramount+

### Can this app be freely downloaded through official means?

- [X] Yes

### Optional Comments

Hello Doug,

I found a difference here in Germany, Paramount+ has other configuration, I think.

source_list: com.cbs.ca
app_id: com.cbs.ca
source: com.cbs.ca
adb_response: Starting: Intent { cmp=com.cbs.ott/com.cbs.app.tv.ui.activity.DeepLinkActivity }
Error type 3
Error: Activity class {com.cbs.ott/com.cbs.app.tv.ui.activity.DeepLinkActivity} does not exist.
hdmi_input: null
device_class: tv
entity_picture: /api/media_player_proxy/media_player.fire_tv_192_168_178_37?token=d9c3c4005becac86c11eb3176c7e123b88c5bcfaa609dc73e10911c885baa42d&cache=1672839752.918439
friendly_name: Fire TV 192.168.178.37
supported_features: 22961

**Comment by PRProd** [comment]
@github-sunny - Interesting.  I wondered if that was ever going to happen. 

I don't know how much time you might have to help out with this project, but would you be willing to go through the list of available app shortcuts to see if any more of them don't work against their German counterparts?  It's OK if you don't, just let me know either way.  Thanks.

**Comment by github-sunny** [comment]
Hello Doug,

Ok, I try several apps, but I can't promise that I can check all apps.
Tomorrow...
What infos do you want? From the apps, which don't run, the attributes, I
think. And from the apps, which runs? The attributes too? Or only the info,
that this app works?

Am Mi., 4. Jan. 2023 um 18:09 Uhr schrieb Doug Nelson <
***@***.***>:

**Comment by PRProd** [comment]
Thanks!

From the ones you are able to test, if you find one that doesn't work in Germany, just send me the app name and the attributes.  You don't need to include anything else.

**Comment by github-sunny** [comment]
Hi Doug,

I tested several apps,
-Apple TV
-Disney+
-Netflix
-Prime video
-Spotify
-Youtube
all works except the paramount app.

Some Apps aren*t available in Germany:
- Youtube TV
- News by Fire TV
but the App Launch Button will work.

Hope that will help you a little bit.

Am Mi., 4. Jan. 2023 um 19:16 Uhr schrieb Doug Nelson <
***@***.***>:
