### ISSUE TITLE
[Feature Request]: enable long press for menu, home, siri, and play buttons (Apple TV 4k gen 1 remote)

### ISSUE THREAD

**Issue by depunkar** [PRProd/HA-Firemote#282]
### Feature Request

Request: Add long press functionality for home, menu, siri/search, and play buttons for apple 4k TV remote gen 1.

Details: Apple TV 4k remote gen 1 supports long pressing of different buttons to perform various actions. For ex. Long pressing home button pulls up pop up screen where user can take various actions such as switching profile, turning off the apple tv. Requesting similar long press capabilities for home, menu, siri/search, and play buttons for apple 4k TV remote gen 1 card.

**Comment by PRProd** [comment]
Greetings @depunkar!

Unfortunately at this time, Firemote does not currently support the ability to detect a long press button event.  In the meantime, there are ways to simulate a long press event that you could try.

I suggest taking a look at this discussion thread: [Long press? #270](https://github.com/PRProd/HA-Firemote/discussions/270)

Please let me know if you find this helpful, or if you'd like some more assistance.

**Comment by PRProd** [comment]
@depunkar - Have you had a chance to review my response from Jan 2?

**Comment by depunkar** [comment]
Yes. Thanks for the details. The ticket can be closed/ cancelled.

**Comment by PRProd** [comment]
@depunkar ~

Good news!  I just published a [new beta version](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.0b1) today that gives Firemote the ability to handle long press events!  Please give it a try, then join us over at [Discussion #477](https://github.com/PRProd/HA-Firemote/discussions/477) to let me know about your expierience!

-Doug
