### ISSUE TITLE
[New App Shortcut]: Synology Photos

### ISSUE THREAD

**Issue by Kevin-Kusters** [PRProd/HA-Firemote#288]
### App Name

Synology Photos

### Device Platform

Apple TV

**Comment by PRProd** [comment]
@Kevin-Kusters ~

I've just published a new Firemote Beta version [v3.2.0b4](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.0b4) which contains your app shortcut request.  You are welcome to download and use that beta version, or to wait until the official release is available for download.  Both options should work perfectly for you.

**Comment by PRProd** [comment]
@Kevin-Kusters ~

This has been pushed to the official Firemote release version [v3.2.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.0).  Enjoy!
