### ISSUE TITLE
[New App Shortcut]: SkyShowtime

### ISSUE THREAD

**Issue by Kevin-Kusters** [PRProd/HA-Firemote#289]
### App Name

SkyShowtime

### Device Platform

Apple TV

**Comment by PRProd** [comment]
Greetings @Kevin-Kusters!

I do not see an application named **SkyShowtime** available to download on Apple TV in my region.  Could you please follow the [instructions listed here](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-apple-tv-devices) and reply with your results?  Thanks in advance.

-Doug

**Comment by Kevin-Kusters** [comment]
Hi @PRProd,

source_list: App Store, Arcade, Computers, discovery+, Disney+, DS video, F1 TV, Films, Fireplace, Foto's, Instellingen, Muziek, Netflix, NPO, Odido TV, Pathé Thuis, Plex, Podcasts, Pokémon TV, Prime Video, Protect, SkyShowtime, Speedtest, Spotify, Synology Photos, TV, Videoland, YouTube, YouTube Kids, Zoek

Logo: 
https://www.hollandfilmnieuws.nl/files/logo-skyshowtime.jpg

**Comment by PRProd** [comment]
@Kevin-Kusters ~

I've just published a new Firemote Beta version [v3.2.0b4](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.0b4) which contains your app shortcut request.  You are welcome to download and use that beta version, or to wait until the official release is available for download.  Both options should work perfectly for you.

**Comment by PRProd** [comment]
@Kevin-Kusters ~

This has been pushed to the official Firemote release version [v3.2.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.0).  Enjoy!
