### ISSUE TITLE
[New Device Support]: Fire TV Cube Gen 1

### ISSUE THREAD

**Issue by raymatos** [PRProd/HA-Firemote#29]
### Device Name

Fire TV Cube Gen 1

### Which compatability mode event number works BEST with your device?

None

### Interrogation ADB Response (optional but EXTREMELY helpful)

adb_response: INPUT MANAGER (dumpsys input)

Input Manager State:
  Interactive: true
  System UI Visibility: 0x0
  Pointer Speed: 0
  Pointer Gestures Enabled: true
  Show Touches: false

Event Hub State:
  BuiltInKeyboardId: -2
  Devices:
    -1: Virtual
      Classes: 0x40000023
      Path: <virtual>
      Descriptor: a718a782d34bc767f4689c232d64d527998ea7fd:00000000
      Location: 
      ControllerNumber: 0
      UniqueId: <virtual>
      Identifier: bus=0x0000, vendor=0x0000, product=0x0000, version=0x0000
      KeyLayoutFile: /system/usr/keylayout/Generic.kl
      KeyCharacterMapFile: /system/usr/keychars/Virtual.kcm
      ConfigurationFile: 
      HaveKeyboardLayoutOverlay: false
    1: cec_input
      Classes: 0x00000001
      Path: /dev/input/event2
      Descriptor: 02b1ce58713e0e531eab61b0742baac6893ff49f:1b8e0cec
      Location: 
      ControllerNumber: 0
      UniqueId: 
      Identifier: bus=0x0010, vendor=0x1b8e, product=0x0cec, version=0x0001
      KeyLayoutFile: /system/usr/keylayout/Generic.kl
      KeyCharacterMapFile: /system/usr/keychars/Generic.kcm
      ConfigurationFile: 
      HaveKeyboardLayoutOverlay: false
    2: aml_keypad
      Classes: 0x00000800
      Path: /dev/input/event0
      Descriptor: 485d69228e24f5e46da1598745890b214130dbc4:00010001
      Location: keypad/input0
      ControllerNumber: 0
      UniqueId: 
      Identifier: bus=0x0010, vendor=0x0001, product=0x0001, version=0x0100
      KeyLayoutFile: 
      KeyCharacterMapFile: 
      ConfigurationFile: 
      HaveKeyboardLayoutOverlay: false
    3: gpio_keypad
      Classes: 0x00000001
      Path: /dev/input/event1
      Descriptor: d2c52ff0f656fac4cd7b7a118d575e0109a9fe1c:00010001
      Location: gpio_keypad/input0
      ControllerNumber: 0
      UniqueId: 
      Identifier: bus=0x0010, vendor=0x0001, product=0x0001, version=0x0100
      KeyLayoutFile: /system/usr/keylayout/Vendor_0001_Product_0001.kl
      KeyCharacterMapFile: /system/usr/keychars/Generic.kcm
      ConfigurationFile: 
      HaveKeyboardLayoutOverlay: false
    4: amazon_touch
      Classes: 0x00000014
      Path: /dev/input/event3
      Descriptor: 185733e0df071e21edd860dd6224a1f9f378c689:00000000
      Location: 
      ControllerNumber: 0
      UniqueId: 
      Identifier: bus=0x0005, vendor=0x0000, product=0x0000, version=0x0008
      KeyLayoutFile: 
      KeyCharacterMapFile: 
      ConfigurationFile: /system/usr/idc/amazon_touch.idc
      HaveKeyboardLayoutOverlay: false
    5: kcmouse
      Classes: 0x80000008
      Path: /dev/input/event4
      Descriptor: 3b975ed12e4cb4357a995906d1f9c74d8457fd71:00000000
      Location: 
      ControllerNumber: 0
      UniqueId: 
      Identifier: bus=0x0005, vendor=0x0000, product=0x0000, version=0x0008
      KeyLayoutFile: 
      KeyCharacterMapFile: 
      ConfigurationFile: 
      HaveKeyboardLayoutOverlay: false

Input Reader State:
  Device -1: Virtual
    Generation: 2
    IsExternal: false
    HasMic:     false
    Sources: 0x00000301
    KeyboardType: 2
    Keyboard Input Mapper:
      Parameters:
        HasAssociatedDisplay: false
        OrientationAware: false
        HandlesKeyRepeat: false
      KeyboardType: 2
      Orientation: 0
      KeyDowns: 0 keys currently down
      MetaState: 0x0
      DownTime: 0
  Device 1: cec_input
    Generation: 8
    IsExternal: false
    HasMic:     false
    Sources: 0x00000101
    KeyboardType: 1
    Keyboard Input Mapper:
      Parameters:
        HasAssociatedDisplay: false
        OrientationAware: false
        HandlesKeyRepeat: false
      KeyboardType: 1
      Orientation: 0
      KeyDowns: 0 keys currently down
      MetaState: 0x0
      DownTime: 0
  Device 2: aml_keypad
    Generation: 6
    IsExternal: false
    HasMic:     false
    Sources: 0x00004002
    KeyboardType: 0
    Motion Ranges:
      PRESSURE: source=0x00004002, min=0.000, max=1.000, flat=0.000, fuzz=0.000, resolution=0.000
    External Stylus Input Mapper:
      Raw Stylus Axes:
        Pressure: unknown range
      Stylus State:
        When: 177980064606978048
        Pressure: 0.000000
        Button State: 0x00000000
        Tool Type: 229864781
  Device 3: gpio_keypad
    Generation: 4
    IsExternal: false
    HasMic:     false
    Sources: 0x00000101
    KeyboardType: 1
    Keyboard Input Mapper:
      Parameters:
        HasAssociatedDisplay: false
        OrientationAware: false
        HandlesKeyRepeat: false
      KeyboardType: 1
      Orientation: 0
      KeyDowns: 0 keys currently down
      MetaState: 0x0
      DownTime: 0
  Device 4: amazon_touch
    Generation: 38
    IsExternal: false
    HasMic:     false
    Sources: 0x0000d002
    KeyboardType: 0
    Motion Ranges:
      X: source=0x0000d002, min=0.000, max=1919.000, flat=0.000, fuzz=0.000, resolution=0.000
      Y: source=0x0000d002, min=0.000, max=1079.000, flat=0.000, fuzz=0.000, resolution=0.000
      PRESSURE: source=0x0000d002, min=0.000, max=1.000, flat=0.000, fuzz=0.000, resolution=0.000
    Touch Input Mapper:
      Parameters:
        GestureMode: multi-touch
        DeviceType: touchScreen
        AssociatedDisplay: hasAssociatedDisplay=true, isExternal=false
        OrientationAware: true
      Raw Touch Axes:
        X: min=0, max=1919, flat=0, fuzz=0, resolution=0
        Y: min=0, max=1079, flat=0, fuzz=0, resolution=0
        Pressure: unknown range
        TouchMajor: unknown range
        TouchMinor: unknown range
        ToolMajor: unknown range
        ToolMinor: unknown range
        Orientation: unknown range
        Distance: unknown range
        TiltX: unknown range
        TiltY: unknown range
        TrackingId: unknown range
        Slot: unknown range
      Calibration:
        touch.size.calibration: none
        touch.size.scale: 40.000
        touch.size.bias: 0.000
        touch.size.isSummed: false
        touch.pressure.calibration: none
        touch.pressure.scale: 0.013
        touch.orientation.calibration: none
        touch.distance.calibration: none
        touch.coverage.calibration: none
      Affine Transformation:
        X scale: 1.000
        X ymix: 0.000
        X offset: 0.000
        Y xmix: 0.000
        Y scale: 1.000
        Y offset: 0.000
      Viewport: displayId=0, orientation=0, logicalFrame=[0, 0, 1920, 1080], physicalFrame=[0, 0, 3840, 2160], deviceSize=[3840, 2160]
      SurfaceWidth: 1920px
      SurfaceHeight: 1080px
      SurfaceLeft: 0
      SurfaceTop: 0
      SurfaceOrientation: 0
      Translation and Scaling Factors:
        XTranslate: 0.000
        YTranslate: 0.000
        XScale: 1.000
        YScale: 1.000
        XPrecision: 1.000
        YPrecision: 1.000
        GeometricScale: 1.000
        PressureScale: 0.000
        SizeScale: 0.000
        OrientationScale: 0.000
        DistanceScale: 0.000
        HaveTilt: false
        TiltXCenter: 0.000
        TiltXScale: 0.000
        TiltYCenter: 0.000
        TiltYScale: 0.000
      Last Raw Button State: 0x00000000
      Last Raw Touch: pointerCount=0
      Last Cooked Button State: 0x00000000
      Last Cooked Touch: pointerCount=0
      Stylus Fusion:
        ExternalStylusConnected: true
        External Stylus ID: -1
        External Stylus Data Timeout: 9223372036854775807
      External Stylus State:
        When: 9223372036854775807
        Pressure: 0.000000
        Button State: 0x00000000
        Tool Type: 0
  Device 5: kcmouse
    Generation: 39
    IsExternal: true
    HasMic:     false
    Sources: 0x00002002
    KeyboardType: 0
    Motion Ranges:
      X: source=0x00002002, min=0.000, max=1919.000, flat=0.000, fuzz=0.000, resolution=0.000
      Y: source=0x00002002, min=0.000, max=1079.000, flat=0.000, fuzz=0.000, resolution=0.000
      PRESSURE: source=0x00002002, min=0.000, max=1.000, flat=0.000, fuzz=0.000, resolution=0.000
      VSCROLL: source=0x00002002, min=-1.000, max=1.000, flat=0.000, fuzz=0.000, resolution=0.000
    Cursor Input Mapper:
      Parameters:
        HasAssociatedDisplay: true
        Mode: pointer
        OrientationAware: false
      XScale: 1.000
      YScale: 1.000
      XPrecision: 1.000
      YPrecision: 1.000
      HaveVWheel: true
      HaveHWheel: false
      VWheelScale: 1.000
      HWheelScale: 1.000
      Orientation: 0
      ButtonState: 0x00000000
      Down: false
      DownTime: 0
  Configuration:
    ExcludedDeviceNames: []
    VirtualKeyQuietTime: 0.0ms
    PointerVelocityControlParameters: scale=1.000, lowThreshold=500.000, highThreshold=3000.000, acceleration=3.000
    WheelVelocityControlParameters: scale=1.000, lowThreshold=15.000, highThreshold=50.000, acceleration=4.000
    PointerGesture:
      Enabled: true
      QuietInterval: 100.0ms
      DragMinSwitchSpeed: 50.0px/s
      TapInterval: 150.0ms
      TapDragInterval: 300.0ms
      TapSlop: 20.0px
      MultitouchSettleInterval: 100.0ms
      MultitouchMinDistance: 15.0px
      SwipeTransitionAngleCosine: 0.3
      SwipeMaxWidthRatio: 0.2
      MovementSpeedRatio: 0.8
      ZoomSpeedRatio: 0.3

Input Dispatcher State:
  DispatchEnabled: 1
  DispatchFrozen: 0
  FocusedApplication: name='AppWindowToken{17c92db token=Token{8a78bd5 ActivityRecord{6db588c u0 com.amazon.tv.settings.v2/.tv.device.DeviceActivity t12}}}', dispatchingTimeout=5000.000ms
  FocusedWindow: name='Window{17d0bd8 u0 com.amazon.tv.settings.v2/com.amazon.tv.settings.v2.tv.device.DeviceActivity}'
  TouchStates: <no displays touched>
  Windows:
    0: name='Window{4017a89 u0 com.amazon.vizzini}', displayId=0, paused=false, hasFocus=false, hasWallpaper=false, visible=false, canReceiveKeys=false, flags=0x01000108, type=0x000007da, layer=241005, frame=[0,0][1920,1080], scale=1.000000, touchableRegion=[0,0][1920,1080], inputFeatures=0x00000000, ownerPid=4195, ownerUid=10158, dispatchingTimeout=5000.000ms
    1: name='Window{8e4eac7 u0 com.amazon.vizzini}', displayId=0, paused=false, hasFocus=false, hasWallpaper=false, visible=false, canReceiveKeys=false, flags=0x01000100, type=0x000007da, layer=241000, frame=[0,0][1920,1080], scale=1.000000, touchableRegion=[0,0][1920,1080], inputFeatures=0x00000000, ownerPid=4195, ownerUid=10158, dispatchingTimeout=5000.000ms
    2: name='Window{341d1de u0 KeyguardScrim}', displayId=0, paused=false, hasFocus=false, hasWallpaper=false, visible=false, canReceiveKeys=false, flags=0x01110900, type=0x000007ed, layer=141000, frame=[0,0][1920,1080], scale=1.000000, touchableRegion=[0,0][1920,1080], inputFeatures=0x00000000, ownerPid=3628, ownerUid=1000, dispatchingTimeout=5000.000ms
    3: name='Window{17d0bd8 u0 com.amazon.tv.settings.v2/com.amazon.tv.settings.v2.tv.device.DeviceActivity}', displayId=0, paused=false, hasFocus=true, hasWallpaper=false, visible=true, canReceiveKeys=true, flags=0x83810120, type=0x00000001, layer=21010, frame=[0,0][1920,1080], scale=1.000000, touchableRegion=[0,0][1920,1080], inputFeatures=0x00000000, ownerPid=22626, ownerUid=10154, dispatchingTimeout=5000.000ms
    4: name='Window{2a66fb u0 com.nst.iptvsmarterstvbox/com.nst.iptvsmarterstvbox.view.activity.NewDashboardActivity}', displayId=0, paused=false, hasFocus=false, hasWallpaper=false, visible=false, canReceiveKeys=false, flags=0x81810520, type=0x00000001, layer=21005, frame=[0,0][1920,1080], scale=1.000000, touchableRegion=[0,0][1920,1080], inputFeatures=0x00000000, ownerPid=6409, ownerUid=10200, dispatchingTimeout=5000.000ms
    5: name='Window{5090e81 u0 com.amazon.tv.launcher/com.amazon.tv.launcher.ui.HomeActivity_vNext}', displayId=0, paused=false, hasFocus=false, hasWallpaper=false, visible=false, canReceiveKeys=false, flags=0x83810120, type=0x00000001, layer=21000, frame=[0,0][1920,1080], scale=1.000000, touchableRegion=[0,0][1920,1080], inputFeatures=0x00000000, ownerPid=16861, ownerUid=10144, dispatchingTimeout=5000.000ms
  MonitoringChannels:
    0: 'WindowManager (server)'
  RecentQueue: length=10
    KeyEvent, age=119447.5ms
    KeyEvent, age=119447.5ms
    KeyEvent, age=117358.5ms
    KeyEvent, age=117358.5ms
    KeyEvent, age=115226.5ms
    KeyEvent, age=115226.5ms
    KeyEvent, age=113145.5ms
    KeyEvent, age=113145.5ms
    KeyEvent, age=107355.5ms
    KeyEvent, age=107355.5ms
  PendingEvent: <none>
  InboundQueue: <empty>
  ReplacedKeys: <empty>
  Connections:
    0: channelName='WindowManager (server)', windowName='monitor', status=NORMAL, monitor=true, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
    1: channelName='341d1de KeyguardScrim (server)', windowName='Window{341d1de u0 KeyguardScrim}', status=NORMAL, monitor=false, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
    2: channelName='17d0bd8 com.amazon.tv.settings.v2/com.amazon.tv.settings.v2.tv.device.DeviceActivity (server)', windowName='Window{17d0bd8 u0 com.amazon.tv.settings.v2/com.amazon.tv.settings.v2.tv.device.DeviceActivity}', status=NORMAL, monitor=false, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
    3: channelName='8e4eac7 com.amazon.vizzini (server)', windowName='Window{8e4eac7 u0 com.amazon.vizzini}', status=NORMAL, monitor=false, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
    4: channelName='4017a89 com.amazon.vizzini (server)', windowName='Window{4017a89 u0 com.amazon.vizzini}', status=NORMAL, monitor=false, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
    5: channelName='2a66fb com.nst.iptvsmarterstvbox/com.nst.iptvsmarterstvbox.view.activity.NewDashboardActivity (server)', windowName='Window{2a66fb u0 com.nst.iptvsmarterstvbox/com.nst.iptvsmarterstvbox.view.activity.NewDashboardActivity}', status=NORMAL, monitor=false, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
    6: channelName='5090e81 com.amazon.tv.launcher/com.amazon.tv.launcher.ui.HomeActivity_vNext (server)', windowName='Window{5090e81 u0 com.amazon.tv.launcher/com.amazon.tv.launcher.ui.HomeActivity_vNext}', status=NORMAL, monitor=false, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
  AppSwitch: not pending
  Configuration:
    KeyRepeatDelay: 50.0ms
    KeyRepeatTimeout: 500.0ms

  Keyboard Layouts:
    "English (UK) - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_en_GB
    "French - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_fr_FR
    "Italian - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_it_IT
    "English (US) - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_en_US
    "Spanish (Latin) - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_es_ES
    "German - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_de_DE
    "Turkish - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_tr_TR
    "Danish - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_da_DK
    "Finnish - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_fi_FI
    "Swiss French - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_fr_CH
    "Slovak - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_sk_SK
    "Russian - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_ru_RU
    "Slovenian - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_sv_SE
    "Croatian - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_hr_HR
    "Norwegian - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_nb_NO
    "Swiss German - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_de_CH
    "Czech - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_cs_CZ
    "French (Canada) - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_fr_CA
    "Ukrainian - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_uk_UA
    "Bulgarian - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_bg_BG
    "Portuguese - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_pt_PT
    "Hungarian - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_hu_HU
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_05ac_pt_PT
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_04f2_fr_FR
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_05ac_fr_FR
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_045e_fr_FR
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_046d_fr_FR
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_04f2_de_DE
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_05ac_de_DE
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_045e_de_DE
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_046d_de_DE
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_05ac_it_IT
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_045e_it_IT
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_046d_it_IT
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_04f2_es_ES
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_05ac_es_ES
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_045e_es_ES
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_046d_es_ES
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_04f2_en_GB
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_05ac_en_GB
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_045e_en_GB
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_046d_en_GB
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_04f2_en_US
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_045e_ja_JP
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_05ac_ja_JP
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_1949_en_GB
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_0171_en_GB

  PersistentDataStore
    mLoaded=true
    mDirty=false
    InputDeviceStates:
hdmi_input: null
device_class: tv
friendly_name: Fire TV 192.168.20.185
supported_features: 22961
source_list: com.amazon.ceviche, com.amazon.diode, com.amazon.client.metrics, com.amazon.imp, android.ext.services, com.android.proxyhandler, com.amazon.vizzini, com.amazon.tcomm, com.amazon.tv.devicecontrol, com.amazon.whad, com.amazon.tv.ime, com.amazon.tv.alexaalerts, amazon.speech.davs.davcservice, logcat, com.amazon.kso.blackbird, com.amazon.connectivitycontroller, com.amazon.device.rdmapplication, Amazon Video, com.amazon.whisperjoin.middleware.np, IPTV Smarters Pro, com.amazon.alexamediaplayer.runtime.ftv, com.amazon.avl.stark, com.amazon.comms.knightcontacts, com.amazon.discoveryservice.core.android, com.amazon.whisperlink.core.android, com.amazon.uxcontrollerservice, Disney+, Plex, com.amazon.alexa.externalmediaplayer.fireos, com.amazon.cardinal, com.amazon.webview.chromium:AWVArcusServiceProcess, com.amazon.webview.chromium:AWVMetricsProcess, com.amazon.tv.launcher, com.amazon.wirelessmetrics.service, com.amazon.prism.android.service:remote, com.amazon.tv.livetv, com.amazon.tv.settings.v2, com.amazon.ftv.profilepicker, com.amazon.bueller.photos, com.amazon.tahoe, com.amazon.tv.notificationcenter, com.amazon.logan, FireTV Store, com.android.providers.downloads, Prime Video (FireTV), com.amazon.aca, com.amazon.device.software.ota
app_id: com.amazon.tv.settings.v2
source: com.amazon.tv.settings.v2
entity_picture: /api/media_player_proxy/media_player.fire_tv_192_168_20_185?token=c9558ecdaadea0499b91c14bdd7cefae98bf198e63bfc11debd3eb0ab3807188&cache=1672887779.119589

**Comment by PRProd** [comment]
Quick question for you - If you press a button on your physical remote control and it successfully interacts with your V1 Cube, are you able to control your cube immediately after that if you choose compatibility mode event5?

**Comment by PRProd** [comment]
Project wiki was updated to include the provided information for the [Fire TV Cube 1st Gen (2018)](https://github.com/PRProd/HA-Firemote/wiki/Fire-TV-Cube---1st-Gen-(2018)) but it remains incomplete until hearing back from @raymatos

**Comment by PRProd** [comment]
@raymatos   - Version [1.11.1](https://github.com/PRProd/HA-Firemote/releases/tag/v1.11.1) has been released and it contains a beta (untested) version of support for the Fire Cube 1st Gen.  I based some assumptions on previously observed behavior with FireTV devices, so I hope that this works in your case.  I do not own this device, so I was unable to test it for myself.

When you do your testing and confirmation, please FIRST press a few buttons on your cube's official remote control before you attempt to test this latest release of the Home Assistant Firemote card.  I'm anxious to hear your results.

I'll leave this issue open for a little while longer to give you a chance to weigh in with any further discussion.  Thanks.

**Comment by PRProd** [comment]
After providing a hopeful solution and not receiving any answers to my questions and/or testing results, I will be closing this issue now.  Please reply back to this issue thread if needed.  Thanks.

**Comment by raymatos** [comment]
Sorry for lack of reply.  I will test it this week. Sent from my iPhoneOn Feb 20, 2023, at 6:22 PM, Doug Nelson ***@***.***> wrote:﻿
Closed #29 as completed.
