### ISSUE TITLE
[Feature Request]: button override for volume on roku

### ISSUE THREAD

**Issue by manonstreet** [PRProd/HA-Firemote#296]
### Feature Request

Roku currently implements volume buttons similar to custom launchers on the dropdown menu.  However the button cannot be overridden (volume-up-button and volume-down-button) overrides are not honored.  I can alternatively create a similar style volume button as a custom launcher; however these buttons mandatorily receive shadow overlays for button highlighting, which is not ideal for volume buttons.

**Comment by manonstreet** [comment]
Looks like this does in fact work via an undocumented button override: function-volume-up-button, function-volume-down-button

**Comment by PRProd** [comment]
oh wow!  Yes, that'll do it!  You're clever!  :smile:

Since Roku support is not official yet, could I ask that further Roku issues/requests be posted in #275?

I REALLY REALLY REALLY appreciate all of your scrutiny here!  I mean it!  THANK YOU!
