### ISSUE TITLE
[New App Shortcut]: CBS Sports

### ISSUE THREAD

**Issue by jwmierzwa** [PRProd/HA-Firemote#298]
### App Name

CBS Sports

### Device Platform

Apple TV

**Comment by PRProd** [comment]
Greetings @jwmierzwa!

This request has been completed and has been published in the latest release, beta version [3.2.0b6](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.0b6).  You are welcome to download the beta version, or wait until the next official Firemote release.

Enjoy!

**Comment by PRProd** [comment]
@jwmierzwa ~

This has been pushed to the official Firemote release version [v3.2.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.0).  Enjoy!
