### ISSUE TITLE
[New App Shortcut]: Optimum TV

### ISSUE THREAD

**Issue by frank-perrone** [PRProd/HA-Firemote#299]
### App Name

Optimum TV

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/optimum-tv/id1296704509

### Application Details

source_list:
  - ABC
  - "App\_Store"
  - Arcade
  - Computers
  - discovery+
  - Disney+
  - DisneyNOW
  - ESPN
  - FaceTime
  - Fitness
  - Fox News
  - HBO Max
  - HISTORY
  - HISTORY Vault
  - Hulu
  - Max
  - MLB
  - Movies
  - Music
  - Netflix
  - News 12
  - Nick Jr
  - Optimum TV
  - Paramount+
  - Peacock
  - Photos
  - Podcasts
  - Prime Video
  - Protect
  - Search
  - Settings
  - The CW
  - The Emmys
  - TV
  - TV Shows
  - Veeps
  - YouTube
  - YouTube Kids

**Comment by PRProd** [comment]
Greetings @frank-perrone!

This request has been completed and has been published in the latest beta release, version [3.2.0b6](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.0b6).  You are welcome to download the beta version, or wait until the next official Firemote release.

Enjoy!

**Comment by PRProd** [comment]
@frank-perrone ~

This has been pushed to the official Firemote release version [v3.2.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.0).  Enjoy!
