### ISSUE TITLE
[New App Shortcut]: WireGuard

### ISSUE THREAD

**Issue by Anashost** [PRProd/HA-Firemote#300]
### App Name

WireGuard

### Device Platform

Chromecast, Xiaomi

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.wireguard.android

### Application Details

adb_response:
mSurface=Surface(name=)/@0x96d257e

mSurface=Surface(name=com.wireguard.android/com.wireguard.android.activity.TvMainActivity)/@0xc40e50f
  mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xd75f5fb

**Comment by PRProd** [comment]
Greetings @Anashost!

Firemote version [v3.2.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.1) has been published, and it contains your requested app launch shortcut.  Enjoy!
