### ISSUE TITLE
[New App Shortcut]: Radio Paradise

### ISSUE THREAD

**Issue by digoben** [PRProd/HA-Firemote#301]
### App Name

Radio Paradise

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/ca/app/radio-paradise/id517818306?platform=appleTV

### Application Details

source_list: ABC News Live, AccuWeather, Airbnb, Apple Events, App Store, Arcade, Asphalt 8, CANAL+, CanalCocina, CBS, CNN: Breaking US & World News, Computers, Crossy Road, Developer, DRTV, Euronews, FaceTime, Flickr, HBO Max, Infuse, Kitchen Stories, Livestream, Movies, Music, myTuner Radio Free, NASA, NBC, NBC News, Netflix, NHK WORLD, NordVPN, PBS, Photos, player, Plex, Podcasts, Prime Video, Radio Paradise Mk2, Rayman Adventures, Real Racing 3, Reuters TV, RTVE Play, Search, Settings, Sky News, SkyShowtime, Speedtest, Spotify, TED, Televio, TestFlight, The Weather Channel, Trailers, TV, Vevo, Vimeo, VLC, YouTube

### Optional Comments

Thank you in advance!

**Comment by PRProd** [comment]
Greetings @digoben!

Firemote version [v3.2.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.1) has been published, and it contains your requested app launch shortcut.

Enjoy!

**Comment by digoben** [comment]
Thank you!
