### ISSUE TITLE
[Feature Request]: Remove button borders

### ISSUE THREAD

**Issue by Frusciantism** [PRProd/HA-Firemote#309]
### Feature Request

First, thank you for your work. 

Would it be possible to remove button borders and have the possibility of a more clean dpad control

![Screenshot 2024-01-30 at 12-23-26 Overview – Home Assistant](https://github.com/PRProd/HA-Firemote/assets/20820046/771411d5-5d6c-4ba2-aeb4-9365a16dfd6d)
![Screenshot 2024-01-30 at 12-23-05 Dzydz1hXgAMc-eC jpg large (imagem JPEG 1431 × 2048 pixeis) - Redimensionado (59%)](https://github.com/PRProd/HA-Firemote/assets/20820046/e68157d8-a45a-471e-8e09-6625fab9d414)

**Comment by PRProd** [comment]
@Frusciantism ~

The border part of this request has also been requested in #290, so that is something that I will be looking into as time permits.

As far as your DPad question is concerned, I could work on a few options for different styles, including the example you provided.  I also see that you've built a different layout just below that which you didn't write about in your request, is this something you also want?

**Comment by PRProd** [comment]
I have just published Firemote beta version [v3.2.3b1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.3b1) for you to download and test.

This version contains the ability to turn off the frames around the button groups in the AL2 remote as you had requested.  It also has an additional feature that allows you to set a custom background color for your remote. (requested in #290)

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/5d4ee22c-2f2f-4b51-966e-7df28e5a2f32)

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/5f1aac6d-62c5-428f-a5f5-599d0950ef75)

Please download this beta version and let me know if it works as expected.  If so, I will continue on with designing some dpad options to choose from.

**Comment by PRProd** [comment]
The previously mentioned beta features have just been released in the latest Firemote version [v3.2.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.3).

**Comment by PRProd** [comment]
@Frusciantism ~

I've just published Firemote version [v3.2.4](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.4) which has a new dpad style selector when you are using App Launcher 2:
![Screenshot from 2024-02-17 11-34-38](https://github.com/PRProd/HA-Firemote/assets/25486599/7558df50-0e29-43e6-af29-615009a72af9)

I'm still working on one that looks like the picture you sent me.  It's mostly done, I just have a few things left to work out.  This is what that option (named Minimal) will look like:
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/d092cdbd-5ed7-408e-8462-f8ca8a532d4a)

**Comment by PRProd** [comment]
@Frusciantism ~

Firemote version [v3.2.5](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.5) has just been released, and it contains the "minimal" dpad option.

I haven't heard back from you, but I believe that I have accomplished everything that you asked for.  If there's anything else I can help with, just let me know!

-Doug
