### ISSUE TITLE
[New App Shortcut]: Three Now (NZ)

### ISSUE THREAD

**Issue by moh-Brent** [PRProd/HA-Firemote#31]
### App Name

Three Now (NZ)

### Can this app be freely downloaded through official means?

- [X] Yes

### Optional Comments

```
    "threenow": {
      "button": "Three Now",
      "friendlyName": "Three Now (NZ)",
      "appName": "com.mediaworks.android.tv",
      "className": "threenowButton",
      "androidName": "com.mediaworks.android.tv",
      "adbLaunchCommand": "adb shell am start -n com.mediaworks.android.tv/nz.co.mediaworks.vod.ui.splash.TVSplashActivity" },

```

```
          .threenowButton {
            font-size: calc(var(--sz) * 1rem);
            color: #fff;
            font-weight: bold;
            background: #ff004f;
          }
          .threenowButton:active, .threenowButton.appActive {
            color: #fff;
            box-shadow: 0 0 calc(var(--sz) * 0.857rem) calc(var(--sz) * 0.142rem) rgb(255 255 255 / 20%);
            text-shadow: 0 0 calc(var(--sz) * 0.2857rem) black;
          }

```

**Comment by PRProd** [comment]
@moh-Brent - Please download and test [Pre-Release Version 1.10.4](https://github.com/PRProd/HA-Firemote/releases/tag/v1.10.4) to see if this app shortcut works for you.  That app is not available in my region, so I am unable to confirm.

**Comment by PRProd** [comment]
From @moh-Brent  in #30 `also can't get the "Three Now" to work on the Mi Box either`

@moh-Brent - Sometimes, the security settings on Android apps don't allow for the direct ADB Launch Command to work properly.  I'm hoping that is the reason you experienced an issue with the new shortcut.  I've made a change and created a pre-release for you to test.  Please download pre-release [v1,10.4.2](https://github.com/PRProd/HA-Firemote/releases/tag/v1.10.4.2) and re-test the Three Now app shortcut and let me know if it works as expected.

Thanks.

**Comment by moh-Brent** [comment]
@PRProd magic mate, this worked perfectly :)

**Comment by PRProd** [comment]
@moh-Brent  - Version [1.11.1](https://github.com/PRProd/HA-Firemote/releases/tag/v1.11.1) has been released and it contains your requested app shortcut addition.  Thank you for your testing efforts earlier, and for your patience with the timing of this release.

Thanks for your contribution!
