### ISSUE TITLE
[New App Shortcut]: TiviMax

### ISSUE THREAD

**Issue by dangerouslaser** [PRProd/HA-Firemote#311]
### App Name

Tivimax IPTV Player (Premium)

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/tivimax-iptv-player-premium/id1632953327

### Application Details

source_list: App Store, Arcade, Computers, Creaks, ESPN, FaceTime, Fitness, Hue Match, iSTB-TV, Movies, Music, NCAA March Madness, Netflix, NFL, NHL, Photos, Plex, Podcasts, Prime Video, Search, Settings, Speedtest, TiviMax, TV, TV Shows, YouTube
app_id: 
friendly_name: Apple TV
supported_features: 450487

**Comment by PRProd** [comment]
Greetings @dangerouslaser!

Firemote version [v3.2.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.2) has just been published, and it contains the app shortcut that you requested.  Enjoy!

-Doug
