### ISSUE TITLE
[New App Shortcut]: Sparkle TV

### ISSUE THREAD

**Issue by stevemsefton** [PRProd/HA-Firemote#313]
### App Name

Sparkle TV

### Device Platform

Chromecast, NVIDIA Shield

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=se.hedekonsult.sparkle

### Application Details

adb_response: >-
  mSurface=Surface(name=se.hedekonsult.sparkle/se.hedekonsult.sparkle.MainActivity)/@0x30cc3bf
        mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x4f4fe05
    mInputMethodTarget in display# 0 Window{a35f90a u0 se.hedekonsult.sparkle/se.hedekonsult.sparkle.MainActivity}

**Comment by PRProd** [comment]
Greetings @stevemsefton!

Firemote version [v3.2.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.2) has just been published, and it contains the app shortcut that you requested.  Enjoy!

-Doug

**Comment by thearchitectuk** [comment]
Hi Doug, I've just upgraded to 3.2.2, rebooted and I would expect it to be here, but can't see SparkleTV. Am I missing something?

![image](https://github.com/PRProd/HA-Firemote/assets/35996506/add8916c-6d8e-41b9-a765-be536ca7eb08)

**Comment by PRProd** [comment]
You've probably run into the infamous "sticky cache" issue.  Take a look at this Firemote Wiki article [Force a Refresh](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for an in depth look at the best way to solve this.
<br>
<br>

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/69a1f722-589b-4496-affa-a53789197692)

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/b13787c7-5f86-4333-912f-72ded3416af8)

**Comment by thearchitectuk** [comment]
You're right. My apologies - all sorted :-) Thank you.

**Comment by PRProd** [comment]
Awesome!  Glad to hear it!
