### ISSUE TITLE
[New App Shortcut]: DogTV

### ISSUE THREAD

**Issue by lfarah** [PRProd/HA-Firemote#317]
### App Name

DogTV

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://www.amazon.com/PTV-Media-DOGTV-Online/dp/B06XB2NG71

_No response_

### Application Details

adb_response: >-
  mSurface=Surface(name=com.ptvmedia.dogtv/tv.accedo.one.app.bootstrap.BootstrapActivity)/@0x6aab604
    mCurrentFocus=Window{a2f8de5 u0 com.ptvmedia.dogtv/tv.accedo.one.app.bootstrap.BootstrapActivity}
    mFocusedApp=AppWindowToken{3be4d2c token=Token{42f7cdf ActivityRecord{9fb9f7e u0 com.ptvmedia.dogtv/tv.accedo.one.app.bootstrap.BootstrapActivity t329}}}
hdmi_input: null

### Optional Comments

Thank you so much for this app! Has been really really helpful. Have an amazing week!

**Comment by PRProd** [comment]
Greetings @lfarah!

Your app launcher request has been added in the latest Firemote version [v3.2.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.3)

Enjoy!
