### ISSUE TITLE
[New App Shortcut]: Formuler MYTVOnline3

### ISSUE THREAD

**Issue by giantorth** [PRProd/HA-Firemote#318]
### App Name

MYTVOnline3

### Device Platform

Amazon Fire, Chromecast, NVIDIA Shield

### Application Details

MYTVOnline3 is an IPTV app that only is available with the Z11 series of Formuler boxes.  They otherwise run Android TV.

App data when viewing Live TV:

> adb_response: mSurface=Surface(name=)/@0x9455a89
>       mSurface=Surface(name=tv.formuler.mol3.real/tv.formuler.mol3.live.view.LiveActivity)/@0x54a9817
>       mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xaa81054
>   mInputMethodTarget in display# 0 Window{1d31ddb u0 tv.formuler.mol3.real/tv.formuler.mol3.live.view.LiveActivity}
> 

App data when viewing VOD:

> adb_response: mSurface=Surface(name=)/@0x9455a89
>       mSurface=Surface(name=tv.formuler.mol3.real/tv.formuler.mol3.vod.ui.StreamActivity)/@0x60ab268
>       mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xaa81054
>   mInputMethodTarget in display# 0 Window{d3df3a1 u0 tv.formuler.mol3.real/tv.formuler.mol3.vod.ui.StreamActivity}

**Comment by PRProd** [comment]
Greetings @giantorth!

As you stated:
>MYTVOnline3 is an IPTV app that only is available with the Z11 series of Formuler boxes

Unfortunately, the [Formuler device family](https://www.formuler.tv/) is **not** supported by Firemote at this time. The [list of officially supported devices](https://github.com/PRProd/HA-Firemote/wiki#devices-officially-supported-by-firemote) can be found [here](https://github.com/PRProd/HA-Firemote/wiki#devices-officially-supported-by-firemote) in the [Firemote Wiki](https://github.com/PRProd/HA-Firemote/wiki).

Luckily, there is a process for the Firemote community to [vote on which device family they would like to see added next](https://github.com/PRProd/HA-Firemote/discussions/41).  That poll can be found at [discussion #41](https://github.com/PRProd/HA-Firemote/discussions/41).  Simply vote for **Other** and write **Formuler** in the [proper thread](https://github.com/PRProd/HA-Firemote/discussions/41#discussioncomment-5293057).

At this time, I will have to decline this request.  Thank you for your understanding.

-Doug

**Comment by giantorth** [comment]
I am currently using your firemote with both of my formuler boxes without issue. They support developer mode and adb mode the same as any android tv box.

**Comment by PRProd** [comment]
That's great to hear!  Unfortunately, that doesn't change the decision.

You're not out of options, though.  You can always [create your own app launch button](https://github.com/PRProd/HA-Firemote/wiki#create-a-custom-button-for-yourself) which can function just as well as if it was a native part of the Firemote project.
