### ISSUE TITLE
[New App Shortcut]: Formuler MYTVOnline2

### ISSUE THREAD

**Issue by giantorth** [PRProd/HA-Firemote#319]
### App Name

MYTVOnline2

### Device Platform

Amazon Fire, Chromecast, NVIDIA Shield

### Application Details

MYTVOnline2 is an IPTV app that is only available with the z10/gtv series of Formuler android tv streaming boxes.

App info in live tv:
> adb_response: mSurface=Surface(name=tv.formuler.mytvonline.real/tv.formuler.mytvonline.live.LiveActivity)/@0x22c215e
>        mAnimationIsEntrance=true      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x943551d

App info in VOD:
> adb_response: mSurface=Surface(name=tv.formuler.mytvonline.real/tv.formuler.mytvonline.vod.VodListActivity)/@0x40dc148
>        mAnimationIsEntrance=true      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x943551d

**Comment by PRProd** [comment]
Greetings @giantorth!

As you stated:
>MYTVOnline2 is an IPTV app that is only available with the z10/gtv series of Formuler android tv streaming boxes.

Unfortunately, the [Formuler device family](https://www.formuler.tv/) is **not** supported by Firemote at this time. The [list of officially supported devices](https://github.com/PRProd/HA-Firemote/wiki#devices-officially-supported-by-firemote) can be found [here](https://github.com/PRProd/HA-Firemote/wiki#devices-officially-supported-by-firemote) in the [Firemote Wiki](https://github.com/PRProd/HA-Firemote/wiki).

Luckily, there is a process for the Firemote community to [vote on which device family they would like to see added next](https://github.com/PRProd/HA-Firemote/discussions/41).  That poll can be found at [discussion #41](https://github.com/PRProd/HA-Firemote/discussions/41).  Simply vote for **Other** and write **Formuler** in the [proper thread](https://github.com/PRProd/HA-Firemote/discussions/41#discussioncomment-5293057).

At this time, I will have to decline this request.  Thank you for your understanding.

-Doug
