### ISSUE TITLE
[New App Shortcut]: TiviMate IP TV Player

### ISSUE THREAD

**Issue by sebzat86** [PRProd/HA-Firemote#32]
### App Name

TiviMate IP TV Player

### Can this app be freely downloaded through official means?

- [X] Yes

### Optional Comments

If by official means the Amazon download app is meant, through which one can download the APK, then yes, otherwise not currently.

**Comment by PRProd** [comment]
@sebzat86 - You bring up a great point.  I should probably elaborate on what is meant by "official means" to avoid confusion.  Thanks for the note.

The term "official means" is supposed to indicate an app that is downloadable through the native menus / app search feature that comes included with a fire TV device.  Sideloaded app shortcut requests (apps that need to be installed through other apps, or ADB commands) are not supported at this time.  

In regards to adding this specific app shortcut, using the official fire TV app search feature, an app with the name "TiviMate IP TV Player" is not found, so it does not meet the requirements to be added at this time.  Keep checking with the Fire TV search feature to see if it shows up.  Once it's there, then please re-open this request and it will be done!

Thanks for your understanding.

**Comment by PRProd** [comment]
@sebzat86 - I recommend following Issue #34.  When that is complete, it will provide a workaround solution for you to launch this app from your Firemote.

**Comment by PRProd** [comment]
@sebzat86  - [A new beta version](https://github.com/PRProd/HA-Firemote/releases/tag/v2.0.0-beta3) is available for testing, which also happens to include this previously closed request.  

If you'd like to test it out as a beta tester, feel free to join us over at discussion #47.  We'd love to have you!
