### ISSUE TITLE
[New App Shortcut]: spacedesk Display

### ISSUE THREAD

**Issue by YoshiFan501** [PRProd/HA-Firemote#320]
### App Name

spacedesk Display Screen Cast

### Device Platform

Chromecast, NVIDIA Shield

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=ph.spacedesk.beta

### Application Details

Spacedesk is an app that lets you control your desktop from your tv

adb_response: mSurface=Surface(name=ph.spacedesk.beta/ph.spacedesk.httpwww.spacedesk.SAActivityConnect)/@0xff77cba        mAnimationIsEntrance=true      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x2cba730   mInputMethodTarget in display# 0 Window{c722cc9 u0 ph.spacedesk.beta/ph.spacedesk.httpwww.spacedesk.SAActivityConnect}

**Comment by PRProd** [comment]
Greetings @YoshiFan501!

Your app launcher request has been added in the latest Firemote version [v3.2.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.3)

Enjoy!
