### ISSUE TITLE
[New App Shortcut]: Apple Music

### ISSUE THREAD

**Issue by farmer2k3** [PRProd/HA-Firemote#321]
### App Name

Apple Music

### Device Platform

Roku

### Application Details

<app id="637193" type="appl" version="14.1.66">Apple Music</app>
app_id: 637193
app_name: Apple Music
source: Apple Music

**Comment by PRProd** [comment]
Greetings @farmer2k3!

Your app launcher request has been added in the latest Firemote version [v3.2.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.3)

Enjoy!
