### ISSUE TITLE
[App Shortcut]: Kayo

### ISSUE THREAD

**Issue by zjrawlings** [PRProd/HA-Firemote#322]
### App Name

Kayo

### Device Platform

Chromecast

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=au.com.kayosports&hl=en&gl=US&pli=1

### Application Details

adb_response: mSurface=Surface(name=au.com.kayosports.tv/au.com.foxsports.martian.tv.main.MainActivity)/@0x99372b8
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xaac31c5

### Optional Comments

This is a sport streaming service in Australia.

**Comment by PRProd** [comment]
Greetings @zjrawlings!

Firemote version [v3.2.4](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.4) has just been published, and it includes a chromecast launcher for the Kayo app.  Enjoy!

-Doug
