### ISSUE TITLE
[App Shortcut]: Channels DVR for Xiaomi

### ISSUE THREAD

**Issue by nate5532** [PRProd/HA-Firemote#324]
### App Name

Channels DVR

### Device Platform

Xiaomi

### App Store Link and/or URL to .apk file if sideloaded

https://getchannels.com/android/

### Application Details

adb_response: >-
  mSurface=Surface(name=com.getchannels.dvr.app/com.getchannels.android.MainActivity)/@0xcef4c32
        mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x23f33e9
    mCurrentFocus=Window{c46d5f u0 com.getchannels.dvr.app/com.getchannels.android.MainActivity}
    mFocusedApp=AppWindowToken{dd15264 token=Token{8f2f3f7 ActivityRecord{9c4a3f6 u0 com.getchannels.dvr.app/com.getchannels.android.MainActivity t574}}}

### Optional Comments

Thanks for looking at this!  The channels app shows up on the list, but it doesn't work when hitting the button.

**Comment by PRProd** [comment]
Greetings @nate5532!

I just re-downloaded the [Channels DVR app from the Google Play Store](https://play.google.com/store/apps/details?id=com.getchannels.dvr.app) to my Xiaomi Mi device, selected the Channels DVR app shortcut on my Xiaomi Mi Firemote, and when I clicked the button, the app opened without an issue.

Looking at the information you provided in the **Application Details** section (thank you!) your results are identical to what I see with my systems as well:
```
adb_response: mSurface=Surface(name=com.getchannels.dvr.app/com.getchannels.android.MainActivity)/@0xc8307e4
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x1ce92d0
  mCurrentFocus=Window{17fc9b4 u0 com.getchannels.dvr.app/com.getchannels.android.MainActivity}
  mFocusedApp=AppWindowToken{b2eabbf token=Token{c90bdde ActivityRecord{94b5919 u0 com.getchannels.dvr.app/com.getchannels.android.MainActivity t487}}}
```
(The most relevant section of this is com.getchannels.dvr.app/com.getchannels.android.MainActivity, which we both have)

So... I'm at a bit of a loss as to why you are having a different result when you push the button on your end.  Let's try a few troubleshooting steps to see if we can narrow it down.
<br>
<br>
## Is your Xiaomi Mi box running the latest OS version?
Gear Menu (Settings) -> Device Preferences -> About -> System Update -> Check for update
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/0bebc897-b957-4bbb-88ee-f362af4b5975)
(my Xiaomi mi box shows this)
<br><br>

## Are your Firemote config settings correct?
Double check to be sure that if you are using both the ADB and the Remote integrations, that they are both pointed to your Xiaomi mi device
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/4c4c2791-5fda-45d5-aaf5-6ad9a8ca496e)
<br><br>

## Are you running the latest version of Firemote?
The latest version as of now is version [v3.2.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.3)
<br><br>

## Have you tried forcing a cache refresh?
Home Assistant has a very persistent cache which is great for speed, but can sometimes cause unusual issues at random times.  I wrote a [Firemote wiki](https://github.com/PRProd/HA-Firemote/wiki) article titled [Force a Refresh](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) that will walk you through the steps
<br><br>

## Do you see any error messages?
Using steps 7 and 8 in the [Providing Details for App Launcher Requests](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-fire-tv-chromecast-nvidia-shield-xiaomi-mi-and-other-android-based-devices) article, after pressing the Channels DVR button on your Firemote, check to see if any error messages appear in the **adb_response** field.
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/9dece202-d0b2-4793-825a-1c3d70fb5a9b)
<br><br>

## Have you restarted?
Did you restart your Xiaomi Mi box?  Try that first, and then restart your Home Assistant host.
<br><br>

Somewhere in there, I hope we can find a solution for you.  Please let me know!

**Comment by PRProd** [comment]
@nate5532 ~

Did you have a chance to take a look at this yet?
