### ISSUE TITLE
[New App Shortcut]: iMPlayer

### ISSUE THREAD

**Issue by droeloe1818** [PRProd/HA-Firemote#325]
### App Name

iMPlayer

### Device Platform

NVIDIA Shield

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.myiptvonline.implayer&hl=nl&gl=US

### Application Details

adb_response: mSurface=Surface(name=)/@0xf042437
      mSurface=Surface(name=com.myiptvonline.implayer/com.myiptvonline.implayer.a)/@0x422b565
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x8771a4e
  mInputMethodTarget in display# 0 Window{758510f u0 com.myiptvonline.implayer/com.myiptvonline.implayer.a}

**Comment by PRProd** [comment]
Greetings @droeloe1818!

Firemote version [v3.2.4](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.4) has just been released, and it includes your requested iMPlayer app launcher button.  Enjoy!

-Doug
