### ISSUE TITLE
Visible corners of DR icon

### ISSUE THREAD

**Issue by MathiasReker** [PRProd/HA-Firemote#326]
![Screenshot_20240212-172337.png](https://github.com/PRProd/HA-Firemote/assets/26626066/bf367263-a082-4f08-b2db-1779cbb665bd)

Hello.

Awesome project.

The DR logo has visible corners. Is it possible to either change the image to stay inside the circle, or move the border to the top? 😊

**Comment by PRProd** [comment]
Greetings @MathiasReker!

Thanks for pointing that out!  I try to pay attention to details, but I can't see everything.  :smile:  That fix will be in the next push, and/or the next official release.

**Comment by MathiasReker** [comment]
Thanks a lot ❤️❤️

**Comment by PRProd** [comment]
Good news @MathiasReker!

Firemote version [v3.2.4](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.4) has just been published, and those corners should be gone now!  Enjoy!

-Doug
