### ISSUE TITLE
[New App Shortcut]: Watch IT

### ISSUE THREAD

**Issue by ckahmed** [PRProd/HA-Firemote#328]
### App Name

WATCH IT

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://www.amazon.com/WATCHiT/dp/B084C57FBL/

### Application Details

adb_response: mSurface=Surface(name=com.watchit.vod/com.watchit.vod.ui.tv.main.TvMainActivity)
  mCurrentFocus=Window{4ed34c8 u0 com.watchit.vod/com.watchit.vod.ui.tv.main.TvMainActivity}

### Optional Comments

Thank you for your understanding and dedication

**Comment by PRProd** [comment]
Hell @ckahmed!

Firemote version [v3.2.5](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.5) has just been released, and it contains the app shortcut that you requested.  Enjoy!

-Doug
