### ISSUE TITLE
[App Shortcut]: myCanal

### ISSUE THREAD

**Issue by airy10** [PRProd/HA-Firemote#329]
### App Name

myCanal

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/fr/app/mycanal/id694580816?platform=iphone

### Application Details

source_list:
...
- ARTE
- france•tv
- myCANAL
- OQEE by Free
...

**Comment by PRProd** [comment]
Greetings @airy10!

Firemote version [v3.2.5](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.5) has just been released, and it contains the myCanal shortcut for Apple TV devices.  Enjoy!

-Doug

**Comment by airy10** [comment]
Thanks! That was fast
