### ISSUE TITLE
[New App Shortcut]: towis X pro

### ISSUE THREAD

**Issue by smithr99** [PRProd/HA-Firemote#331]
### App Name

towis X pro

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://towisx.yourapk.uk/towisstore/

### Application Details

mSurface=Surface(name=com.boxbr.xc725T5ban/com.nathnetwork.orplayer.CategoriesActivity)/@0x590a722
  mInputMethodTarget in display# 0 Window{f73e6aa u0 com.boxbr.xc725T5ban/com.nathnetwork.orplayer.CategoriesActivity}

**Comment by PRProd** [comment]
Greetings @smithr99!

Firemote version [v3.2.6](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.6) has just been published, and it contains the app shortcut that you requested.  Enjoy!

-Doug

**Comment by smithr99** [comment]
Hi, sorry but can't seem to see the app shortcut under the App Launch Button dropdown? I'm assuming im doing something wrong?!!
![image](https://github.com/PRProd/HA-Firemote/assets/2308300/074a09df-eb33-4d43-93b2-367346b7a86d)

**Comment by PRProd** [comment]
This sort of thing tends to happen.  It's likely a result of a sticky Home Assistant cache.

Have a look at [this article](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for some tips on how to fix the issue.

**Comment by PRProd** [comment]
@smithr99 ~ Are you able to see it now?

**Comment by smithr99** [comment]
That solved it, thanks
