### ISSUE TITLE
[New App Shortcut]: Telia TV 

### ISSUE THREAD

**Issue by reinuke** [PRProd/HA-Firemote#334]
### App Name

Telia TV Estonia

### Device Platform

Xiaomi

### App Store Link and/or URL to .apk file if sideloaded

(https://play.google.com/store/apps/details?id=ee.telia.teliatv)

### Application Details

Android TV - Xiaomi Mi Box S - Google Play Store app

adb_response: mSurface=Surface(name=ee.telia.teliatv/ee.telia.teliatv.activity.MainActivity)/@0xc8273f0
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x2331faa
  mCurrentFocus=Window{d02aef u0 ee.telia.teliatv/ee.telia.teliatv.activity.MainActivity}
  mFocusedApp=AppWindowToken{4ebdb1 token=Token{692f858 ActivityRecord{604693b u0 ee.telia.teliatv/.activity.MainActivity t594}}}

**Comment by reinuke** [comment]
Edit: This applies to Estonian version of Telia TV. There are several.

**Comment by PRProd** [comment]
@reinuke ~

I have just published Firemote version [v3.2.7](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.7) which contains the app shortcut that you requested.  Enjoy!

-Doug

**Comment by reinuke** [comment]
Can confirm button works.
