### ISSUE TITLE
[New App Shortcut]: ERR Jupiter

### ISSUE THREAD

**Issue by reinuke** [PRProd/HA-Firemote#336]
### App Name

Jupiter

### Device Platform

Xiaomi

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=ee.err.jupiter

### Application Details

Android TV - Xiaomi Mi Box S - Google Play Store app

adb_response: mSurface=Surface(name=ee.err.jupiter/com.example.jupiter.MainActivity)/@0x93ea78e
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x2331faa
  mCurrentFocus=Window{f707618 u0 ee.err.jupiter/com.example.jupiter.MainActivity}
  mFocusedApp=AppWindowToken{be8440b token=Token{b8397da ActivityRecord{c51ad85 u0 ee.err.jupiter/com.example.jupiter.MainActivity t596}}}

**Comment by PRProd** [comment]
Greetings @reinuke!

Thanks for your requests!  While I'm helping you with them, could you help me with something?  

Judging by your requests, am I correct that perhaps you speak the Estonian language?  Would you be willing to help out the Firemote project by offering some translation help?

If so, [click here to help](https://github.com/PRProd/HA-Firemote/issues/new?assignees=PRProd&labels=Region+Issue%2Cenhancement&projects=&template=New_Language_Support.yaml&title=%5BNew+Language+Support%5D%3A%20Estonian&langcode=et).  The Firemote project will be very grateful, as well as all other users who speak Estonian.

Thank you in advance!

-Doug

**Comment by PRProd** [comment]
Hello again @reinuke!

I have just published Firemote version [v3.2.7](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.7) which contains the app shortcut that you requested.  Even though I'm closing this issue, it would still be awesome if you would choose to help with the [language translation](https://github.com/PRProd/HA-Firemote/issues/new?assignees=PRProd&labels=Region+Issue%2Cenhancement&projects=&template=New_Language_Support.yaml&title=%5BNew+Language+Support%5D%3A%20Estonian&langcode=et) too.  Enjoy!

-Doug

**Comment by reinuke** [comment]
Can confirm button works.
