### ISSUE TITLE
[New App Shortcut]: Now

### ISSUE THREAD

**Issue by jpcamps86** [PRProd/HA-Firemote#343]
### App Name

Now

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/gb/app/now/id512266300?ppid=57fb9119-d3a3-4d6e-adb3-ea84267ce51f

### Application Details

source_list:
  - Absolute Radio
  - Al Jazeera English
  - "App\_Store"
  - Arcade
  - BBC iPlayer
  - Channel 4
  - CNN
  - Computers
  - discovery+
  - Disney+
  - DS photo
  - DS video
  - FaceTime
  - FE File Explorer
  - Fitness
  - Flow VPN
  - Freevee
  - Global Player
  - ITVX
  - Movies
  - Music
  - My5
  - myTuner Radio Free
  - Netflix
  - NOW
  - Owlfiles
  - Paramount+
  - Photos
  - Podcasts
  - Prime Video
  - PureVPN
  - Qello Concerts
  - Search
  - Settings
  - Sky News
  - SpeedTesTV
  - Synology Photos
  - TalkTV
  - TNT Sports
  - TV
  - TV Shows
  - UKTV Play
  - WATCH FREE UK
  - YouTube
friendly_name: Living Room
supported_features: 450487
app_id: ""

### Optional Comments

I would like the ‘Now’ app added please. Not necessarily right… now(!), just when you get the chance to 😁 Cheers, Joel

**Comment by PRProd** [comment]
Greetings @jpcamps86!

In my first release for [onn. testing](https://github.com/PRProd/HA-Firemote/discussions/344), I just published a beta version of Firemote version [v3.3.0b1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.0b1).  This beta version includes your app request for the NOW shortcut for Apple TV devices.

You are welcome to download the beta version, or wait until this is pushed into production.

Enjoy!

-Doug
(your comments made me laugh)

**Comment by jpcamps86** [comment]
That’s great, thanks Doug. I’ll wait until it’s pushed into prod to add it. Cheers Joel
