### ISSUE TITLE
[New App Shortcut]: Elisa TV (Estonia)

### ISSUE THREAD

**Issue by reinuke** [PRProd/HA-Firemote#347]
### App Name

Elisa Elamus

### Device Platform

Chromecast, Xiaomi

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=ee.elisa.smarttvclient

### Application Details

app_id: ee.elisa.smarttvclient
app_name: ee.elisa.smarttvclient
source: ee.elisa.smarttvclient
adb_response: mSurface=Surface(name=ee.elisa.smarttvclient/tv.threess.threeready.ui.generic.activity.MainActivity)/@0x2d87d1b
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xb8dbefa
  mCurrentFocus=Window{94356c2 u0 ee.elisa.smarttvclient/tv.threess.threeready.ui.generic.activity.MainActivity}
  mFocusedApp=AppWindowToken{5b0e881 token=Token{3eacc68 ActivityRecord{8e5c38b u0 ee.elisa.smarttvclient/tv.threess.threeready.ui.generic.activity.MainActivity t649}}}
entity_picture: /api/media_player_proxy/media_player.android_tv_192_168_50_148?token=215884543cc45614ac3995f35e41e41de4d1e4730ec1accde6cc6e1746bca516&cache=5d676607da77d269

### Optional Comments

Another Estonian application. 
Don't use it myself but a friend suggested it ... I'm like a local ambassador 😂

**Comment by PRProd** [comment]
Ambassador @reinuke ~

(Do you like that name? :laughing:)  This launcher was added to the latest beta version [v3.3.0b2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.0b2) for your friend / you to try out.  Let me know if there are any issues.  Enjoy!

-Doug

**Comment by reinuke** [comment]
I indeed do like being called Ambassador Rein.
But that would make you a king or some other sort of a leader..
Anyway.. tries it last night.
Worked as it's supposed to.

**Comment by PRProd** [comment]
Ambassador Rein,

This is in the production version [v3.3.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.0) now!  Enjoy!

Servant Doug
