### ISSUE TITLE
[Feature Request]: Please add support for Homatics devices

### ISSUE THREAD

**Issue by Pro100x3mal** [PRProd/HA-Firemote#349]
### Feature Request

Please consider adding support for Homatics devices! They are becoming very popular and have all the licenses of popular streaming platforms! For example the Homatics Bix R 4k Plus is a great device that would love to be controlled with your fantastic integration!

https://homatics.eu/

**Comment by PRProd** [comment]
Greetings @Pro100x3mal!  

Thanks for your message!  It's good to have you here!  

I'm always looking for ways to move the Firemote [card](https://github.com/PRProd/HA-Firemote/wiki#how-does-firemote-send-commands-to-my-devices) project forward, and one of the ways I do that is by being receptive to feedback and requests from users like you, so **Thank You**!

I frequently receive requests like yours to add a new [device family](https://github.com/PRProd/HA-Firemote/wiki#devices-officially-supported-by-firemote) to Firemote, so I've actually been using a [poll](https://github.com/PRProd/HA-Firemote/discussions/41) to gauge the community's desire.  When I choose to add a device type, I announce it in [that discussion thread](https://github.com/PRProd/HA-Firemote/discussions/41).  After I publish the new Firemote version, I reset the poll results back to zero, and add any additional options (like yours) to the poll.  Recently, [onn. was declared as the winner](https://github.com/PRProd/HA-Firemote/discussions/41#discussioncomment-8730872) so I've been working on getting that published soon.  [(view the progress here)](https://github.com/PRProd/HA-Firemote/discussions/344)

Please add your **Homatics** request to the [proper thread](https://github.com/PRProd/HA-Firemote/discussions/41#discussioncomment-5293057) in the poll's discussion, and I will be sure to add it to the options when the poll is reset to zero.  When the poll is reset, cast your vote!  Simple as that!

In the meantime, you might experience some luck controlling your **Homatics** device by choosing Shield, Xiaomi, or onn. as your device type in Firemote.  If one of those options works, you can choose any sort of remote style you want.  The [Amazon Fire JVC TV](https://github.com/PRProd/HA-Firemote/issues/303#issuecomment-1913407802) has many buttons on it, similar to the remote for the device you have.

Best of luck!  Thanks for being here!
