### ISSUE TITLE
[New App Shortcut]: Sportsnet+

### ISSUE THREAD

**Issue by ustane23** [PRProd/HA-Firemote#352]
### App Name

Sportsnet+

### Device Platform

Amazon Fire, Chromecast

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.rogers.sportsnet.sportsnet&hl=en

### Application Details

adb_response: mSurface=Surface(name=)
      mSurface=Surface(name=com.rogers.sportsnet.sportsnet/com.rogers.sportsnet.tv.ui.AppActivity)
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)
  mCurrentFocus=Window{858740b u0 com.rogers.sportsnet.sportsnet/com.rogers.sportsnet.tv.ui.AppActivity}
  mFocusedApp=AppWindowToken{2f794ae token=Token{a212ffe ActivityRecord{52bbfb9 u0 com.rogers.sportsnet.sportsnet/com.rogers.sportsnet.tv.ui.AppActivity t5135}}}

**Comment by PRProd** [comment]
Greetings @ustane23!

I have just published Firemote version [v3.3.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.1) which contains your requested app shortcut.  Enjoy!

-Doug

**Comment by ustane23** [comment]
Great Thanks!
