### ISSUE TITLE
Change logo for Amazon Fire Switch Apps Function Button

### ISSUE THREAD

**Issue by chemelli74** [PRProd/HA-Firemote#354]
### Device Name

FireTV Stick 4K (2nd Gen)

### Which compatibility mode event number works BEST with your device?

event4

### Device ADB Input Interrogation Response

db_response: INPUT MANAGER (dumpsys input)

Input Manager State:
  Interactive: true
  System UI Visibility: 0x8008
  Pointer Speed: 0
  Pointer Gestures Enabled: true
  Show Touches: false
  Pointer Capture Enabled: false

Event Hub State:
  BuiltInKeyboardId: -2
  Devices:
    -1: Virtual
      Classes: 0x40000023
      Path: <virtual>
      Enabled: true
      Descriptor: a718a782d34bc767f4689c232d64d527998ea7fd:00000000
      Location: 
      ControllerNumber: 0
      UniqueId: <virtual>
      Identifier: bus=0x0000, vendor=0x0000, product=0x0000, version=0x0000
      KeyLayoutFile: /system/usr/keylayout/Generic.kl
      KeyCharacterMapFile: /system/usr/keychars/Virtual.kcm
      ConfigurationFile: 
      HaveKeyboardLayoutOverlay: false
      VideoDevice: <none>
    1: WOBLE_INPUT_DEVICE
      Classes: 0x00000001
      Path: /dev/input/event1
      Enabled: true
      Descriptor: 76d09a7d1f3b8d113bb56ed2568268f86d137837:00020002
      Location: 
      ControllerNumber: 0
      UniqueId: 
      Identifier: bus=0x0019, vendor=0x0002, product=0x0002, version=0x0002
      KeyLayoutFile: /system/usr/keylayout/Generic.kl
      KeyCharacterMapFile: /system/usr/keychars/Generic.kcm
      ConfigurationFile: 
      HaveKeyboardLayoutOverlay: false
      VideoDevice: <none>
    2: hdmipower
      Classes: 0x00000001
      Path: /dev/input/event0
      Enabled: true
      Descriptor: a917cc44911b6f32b9481384b0da35fb5f3d84d3:00000000
      Location: 
      ControllerNumber: 0
      UniqueId: 
      Identifier: bus=0x0000, vendor=0x0000, product=0x0000, version=0x0000
      KeyLayoutFile: /system/usr/keylayout/Generic.kl
      KeyCharacterMapFile: /system/usr/keychars/Generic.kcm
      ConfigurationFile: 
      HaveKeyboardLayoutOverlay: false
      VideoDevice: <none>
    3: amazon_touch
      Classes: 0x00000014
      Path: /dev/input/event2
      Enabled: true
      Descriptor: 185733e0df071e21edd860dd6224a1f9f378c689:00000000
      Location: 
      ControllerNumber: 0
      UniqueId: 
      Identifier: bus=0x0005, vendor=0x0000, product=0x0000, version=0x0008
      KeyLayoutFile: 
      KeyCharacterMapFile: 
      ConfigurationFile: /system/usr/idc/amazon_touch.idc
      HaveKeyboardLayoutOverlay: false
      VideoDevice: <none>
    4: WOW_INPUT_DEVICE
      Classes: 0x00000001
      Path: /dev/input/event3
      Enabled: true
      Descriptor: 485d69228e24f5e46da1598745890b214130dbc4:00010001
      Location: 
      ControllerNumber: 0
      UniqueId: 
      Identifier: bus=0x0019, vendor=0x0001, product=0x0001, version=0x0001
      KeyLayoutFile: /system/usr/keylayout/Generic.kl
      KeyCharacterMapFile: /system/usr/keychars/Generic.kcm
      ConfigurationFile: 
      HaveKeyboardLayoutOverlay: false
      VideoDevice: <none>
    5: kcmouse
      Classes: 0x80000008
      Path: /dev/input/event4
      Enabled: true
      Descriptor: 3b975ed12e4cb4357a995906d1f9c74d8457fd71:00000000
      Location: 
      ControllerNumber: 0
      UniqueId: 
      Identifier: bus=0x0005, vendor=0x0000, product=0x0000, version=0x0008
      KeyLayoutFile: 
      KeyCharacterMapFile: 
      ConfigurationFile: 
      HaveKeyboardLayoutOverlay: false
      VideoDevice: <none>
    7: amzkeyboard
      Classes: 0x80000023
      Path: /dev/input/event6
      Enabled: true
      Descriptor: ea16b8e37822378b09336d67566ac23418d207f4:00000000
      Location: 
      ControllerNumber: 0
      UniqueId: 
      Identifier: bus=0x0005, vendor=0x0000, product=0x0000, version=0x0008
      KeyLayoutFile: /system/usr/keylayout/Generic.kl
      KeyCharacterMapFile: /system/usr/keychars/Generic.kcm
      ConfigurationFile: 
      HaveKeyboardLayoutOverlay: false
      VideoDevice: <none>
    17: Amazon Fire TV Remote
      Classes: 0x80000021
      Path: /dev/input/event5
      Enabled: true
      Descriptor: 53d144a31549efa87006febafb586d5e45b52caa:01710421
      Location: 
      ControllerNumber: 0
      UniqueId: E8:4C:4A:09:70:5D
      Identifier: bus=0x0005, vendor=0x0171, product=0x0421, version=0x003a
      KeyLayoutFile: /system/usr/keylayout/Vendor_0171_Product_0421.kl
      KeyCharacterMapFile: /system/usr/keychars/Generic.kcm
      ConfigurationFile: 
      HaveKeyboardLayoutOverlay: false
      VideoDevice: <none>
  Unattached video devices:
    <none>

Input Reader State (Nums of device: 8):
  Device 18: Amazon Fire TV Remote
    EventHub Devices: [ 17 ] 
    Generation: 157
    IsExternal: true
    AssociatedDisplayPort: <none>
    HasMic:     false
    Sources: 0x00000301
    KeyboardType: 1
    ControllerNum: 0
    Keyboard Input Mapper:
      Parameters:
        OrientationAware: false
        HandlesKeyRepeat: false
      KeyboardType: 1
      Orientation: 0
      KeyDowns: 0 keys currently down
      MetaState: 0x0
      DownTime: 2772779194292000
  Device 8: amzkeyboard
    EventHub Devices: [ 7 ] 
    Generation: 31
    IsExternal: true
    AssociatedDisplayPort: <none>
    HasMic:     false
    Sources: 0x00000301
    KeyboardType: 2
    ControllerNum: 0
    Keyboard Input Mapper:
      Parameters:
        OrientationAware: false
        HandlesKeyRepeat: false
      KeyboardType: 2
      Orientation: 0
      KeyDowns: 0 keys currently down
      MetaState: 0x0
      DownTime: 179906343047000
  Device 6: kcmouse
    EventHub Devices: [ 5 ] 
    Generation: 159
    IsExternal: true
    AssociatedDisplayPort: <none>
    HasMic:     false
    Sources: 0x00002002
    KeyboardType: 0
    ControllerNum: 0
    Motion Ranges:
      X: source=0x00002002, min=0.000, max=1919.000, flat=0.000, fuzz=0.000, resolution=0.000
      Y: source=0x00002002, min=0.000, max=1079.000, flat=0.000, fuzz=0.000, resolution=0.000
      PRESSURE: source=0x00002002, min=0.000, max=1.000, flat=0.000, fuzz=0.000, resolution=0.000
      VSCROLL: source=0x00002002, min=-1.000, max=1.000, flat=0.000, fuzz=0.000, resolution=0.000
    Cursor Input Mapper:
      Parameters:
        HasAssociatedDisplay: true
        Mode: pointer
        OrientationAware: false
      XScale: 1.000
      YScale: 1.000
      XPrecision: 1.000
      YPrecision: 1.000
      HaveVWheel: true
      HaveHWheel: false
      VWheelScale: 1.000
      HWheelScale: 1.000
      Orientation: 0
      ButtonState: 0x00000000
      Down: false
      DownTime: 0
  Device -1: Virtual
    EventHub Devices: [ -1 ] 
    Generation: 3
    IsExternal: false
    AssociatedDisplayPort: <none>
    HasMic:     false
    Sources: 0x00000301
    KeyboardType: 2
    ControllerNum: 0
    Keyboard Input Mapper:
      Parameters:
        OrientationAware: false
        HandlesKeyRepeat: false
      KeyboardType: 2
      Orientation: 0
      KeyDowns: 0 keys currently down
      MetaState: 0x0
      DownTime: 0
  Device 3: WOBLE_INPUT_DEVICE
    EventHub Devices: [ 1 ] 
    Generation: 9
    IsExternal: false
    AssociatedDisplayPort: <none>
    HasMic:     false
    Sources: 0x00000101
    KeyboardType: 1
    ControllerNum: 0
    Keyboard Input Mapper:
      Parameters:
        OrientationAware: false
        HandlesKeyRepeat: false
      KeyboardType: 1
      Orientation: 0
      KeyDowns: 0 keys currently down
      MetaState: 0x0
      DownTime: 0
  Device 5: WOW_INPUT_DEVICE
    EventHub Devices: [ 4 ] 
    Generation: 16
    IsExternal: false
    AssociatedDisplayPort: <none>
    HasMic:     false
    Sources: 0x00000101
    KeyboardType: 1
    ControllerNum: 0
    Keyboard Input Mapper:
      Parameters:
        OrientationAware: false
        HandlesKeyRepeat: false
      KeyboardType: 1
      Orientation: 0
      KeyDowns: 0 keys currently down
      MetaState: 0x0
      DownTime: 0
  Device 2: hdmipower
    EventHub Devices: [ 2 ] 
    Generation: 6
    IsExternal: false
    AssociatedDisplayPort: <none>
    HasMic:     false
    Sources: 0x00000101
    KeyboardType: 1
    ControllerNum: 0
    Keyboard Input Mapper:
      Parameters:
        OrientationAware: false
        HandlesKeyRepeat: false
      KeyboardType: 1
      Orientation: 0
      KeyDowns: 0 keys currently down
      MetaState: 0x0
      DownTime: 0
  Device 4: amazon_touch
    EventHub Devices: [ 3 ] 
    Generation: 160
    IsExternal: false
    AssociatedDisplayPort: <none>
    HasMic:     false
    Sources: 0x00001002
    KeyboardType: 0
    ControllerNum: 0
    Motion Ranges:
      X: source=0x00001002, min=0.000, max=1919.000, flat=0.000, fuzz=0.000, resolution=0.000
      Y: source=0x00001002, min=0.000, max=1079.000, flat=0.000, fuzz=0.000, resolution=0.000
      PRESSURE: source=0x00001002, min=0.000, max=1.000, flat=0.000, fuzz=0.000, resolution=0.000
    Touch Input Mapper (mode - direct):
      Parameters:
        GestureMode: multi-touch
        DeviceType: touchScreen
        AssociatedDisplay: hasAssociatedDisplay=true, isExternal=false, displayId=''
        OrientationAware: true
      Raw Touch Axes:
        X: min=0, max=1919, flat=0, fuzz=0, resolution=0
        Y: min=0, max=1079, flat=0, fuzz=0, resolution=0
        Pressure: unknown range
        TouchMajor: unknown range
        TouchMinor: unknown range
        ToolMajor: unknown range
        ToolMinor: unknown range
        Orientation: unknown range
        Distance: unknown range
        TiltX: unknown range
        TiltY: unknown range
        TrackingId: unknown range
        Slot: unknown range
      Calibration:
        touch.size.calibration: none
        touch.size.scale: 40.000
        touch.size.bias: 0.000
        touch.size.isSummed: false
        touch.pressure.calibration: none
        touch.pressure.scale: 0.013
        touch.orientation.calibration: none
        touch.distance.calibration: none
        touch.coverage.calibration: none
      Affine Transformation:
        X scale: 1.000
        X ymix: 0.000
        X offset: 0.000
        Y xmix: 0.000
        Y scale: 1.000
        Y offset: 0.000
      Viewport INTERNAL: displayId=0, uniqueId=local:0, port=0, orientation=0, logicalFrame=[0, 0, 1920, 1080], physicalFrame=[0, 0, 3840, 2160], deviceSize=[3840, 2160], isActive=[1]
      RawSurfaceWidth: 1920px
      RawSurfaceHeight: 1080px
      SurfaceLeft: 0
      SurfaceTop: 0
      SurfaceRight: 1920
      SurfaceBottom: 1080
      PhysicalWidth: 3840px
      PhysicalHeight: 2160px
      PhysicalLeft: 0
      PhysicalTop: 0
      SurfaceOrientation: 0
      Translation and Scaling Factors:
        XTranslate: 0.000
        YTranslate: 0.000
        XScale: 1.000
        YScale: 1.000
        XPrecision: 1.000
        YPrecision: 1.000
        GeometricScale: 1.000
        PressureScale: 0.000
        SizeScale: 0.000
        OrientationScale: 0.000
        DistanceScale: 0.000
        HaveTilt: false
        TiltXCenter: 0.000
        TiltXScale: 0.000
        TiltYCenter: 0.000
        TiltYScale: 0.000
      Last Raw Button State: 0x00000000
      Last Raw Touch: pointerCount=0
      Last Cooked Button State: 0x00000000
      Last Cooked Touch: pointerCount=0
      Stylus Fusion:
        ExternalStylusConnected: false
        External Stylus ID: -1
        External Stylus Data Timeout: 9223372036854775807
      External Stylus State:
        When: 9223372036854775807
        Pressure: 0.000000
        Button State: 0x00000000
        Tool Type: 0
  Configuration:
    ExcludedDeviceNames: []
    VirtualKeyQuietTime: 0.0ms
    PointerVelocityControlParameters: scale=1.000, lowThreshold=500.000, highThreshold=3000.000, acceleration=3.000
    WheelVelocityControlParameters: scale=1.000, lowThreshold=15.000, highThreshold=50.000, acceleration=4.000
    PointerGesture:
      Enabled: true
      QuietInterval: 100.0ms
      DragMinSwitchSpeed: 50.0px/s
      TapInterval: 150.0ms
      TapDragInterval: 300.0ms
      TapSlop: 20.0px
      MultitouchSettleInterval: 100.0ms
      MultitouchMinDistance: 15.0px
      SwipeTransitionAngleCosine: 0.3
      SwipeMaxWidthRatio: 0.2
      MovementSpeedRatio: 0.8
      ZoomSpeedRatio: 0.3
      Viewports:
        Viewport INTERNAL: displayId=0, uniqueId=local:0, port=0, orientation=0, logicalFrame=[0, 0, 1920, 1080], physicalFrame=[0, 0, 3840, 2160], deviceSize=[3840, 2160], isActive=[1]

Input Classifier State:
  Motion Classifier:
    <nullptr>

Input Dispatcher State:
  DispatchEnabled: true
  DispatchFrozen: false
  InputFilterEnabled: false
  FocusedDisplayId: 0
  FocusedApplications:
    displayId=0, name='ActivityRecord{344eb40 u0 com.amazon.tv.settings.v2/.tv.device.DeviceActivity t228}', dispatchingTimeout=5000ms
  FocusedWindows:
    displayId=0, name='Window{c4bfea u0 com.amazon.tv.settings.v2/com.amazon.tv.settings.v2.tv.device.DeviceActivity}'
  TouchStates: <no displays touched>
  Display: 0
    Windows:
      0: name='Window{c4bfea u0 com.amazon.tv.settings.v2/com.amazon.tv.settings.v2.tv.device.DeviceActivity}', displayId=0, portalToDisplayId=-1, paused=false, hasFocus=true, hasWallpaper=false, visible=true, canReceiveKeys=true, flags=0x81810120, type=0x00000001, frame=[0,0][1920,1080], globalScale=1.000000, windowScale=(1.000000,1.000000), touchableRegion=[0,0][1920,1080], inputFeatures=0x00000000, ownerPid=27930, ownerUid=10194, dispatchingTimeout=5000ms
      1: name='bdc36c3 ActivityRecordInputSink com.amazon.tv.settings.v2/.tv.device.DeviceActivity', displayId=0, portalToDisplayId=-1, paused=false, hasFocus=false, hasWallpaper=false, visible=true, canReceiveKeys=false, flags=0x00000008, type=0x000007e6, frame=[-1,-1][0,0], globalScale=0.000000, windowScale=(1.000000,1.000000), touchableRegion=[0,0][1920,1080], inputFeatures=0x00000002, ownerPid=708, ownerUid=1000, dispatchingTimeout=0ms
      2: name='230eb6f ActivityRecordInputSink com.amazon.ftv.profilepicker/.ui.PickerActivity', displayId=0, portalToDisplayId=-1, paused=false, hasFocus=false, hasWallpaper=false, visible=false, canReceiveKeys=false, flags=0x00000018, type=0x000007e6, frame=[-1,-1][0,0], globalScale=0.000000, windowScale=(1.000000,1.000000), touchableRegion=[0,0][1920,1080], inputFeatures=0x00000002, ownerPid=708, ownerUid=1000, dispatchingTimeout=0ms
      3: name='ce6296 ActivityRecordInputSink com.amazon.firebat/.landing.LandingActivity', displayId=0, portalToDisplayId=-1, paused=false, hasFocus=false, hasWallpaper=false, visible=false, canReceiveKeys=false, flags=0x00000018, type=0x000007e6, frame=[-1,-1][0,0], globalScale=0.000000, windowScale=(1.000000,1.000000), touchableRegion=[0,0][1920,1080], inputFeatures=0x00000002, ownerPid=708, ownerUid=1000, dispatchingTimeout=0ms
      4: name='b44d6c5 ActivityRecordInputSink com.leed.sportsfire/.ui.HomeActivity', displayId=0, portalToDisplayId=-1, paused=false, hasFocus=false, hasWallpaper=false, visible=false, canReceiveKeys=false, flags=0x00000008, type=0x000007e6, frame=[-1,-1][0,0], globalScale=0.000000, windowScale=(1.000000,1.000000), touchableRegion=[0,0][1920,1080], inputFeatures=0x00000002, ownerPid=708, ownerUid=1000, dispatchingTimeout=0ms
      5: name='ad5abc5 ActivityRecordInputSink com.amazon.tv.launcher/.ui.HomeActivity_vNext', displayId=0, portalToDisplayId=-1, paused=false, hasFocus=false, hasWallpaper=false, visible=false, canReceiveKeys=false, flags=0x00000018, type=0x000007e6, frame=[-1,-1][0,0], globalScale=0.000000, windowScale=(1.000000,1.000000), touchableRegion=[0,0][1920,1080], inputFeatures=0x00000002, ownerPid=708, ownerUid=1000, dispatchingTimeout=0ms
  Global monitors in display 0:
    0: 'PointerEventDispatcher0 (server)', 
  RecentQueue: length=10
    KeyEvent, age=141560ms
    KeyEvent, age=141441ms
    KeyEvent, age=141100ms
    KeyEvent, age=141021ms
    KeyEvent, age=140540ms
    KeyEvent, age=140361ms
    KeyEvent, age=139600ms
    KeyEvent, age=139400ms
    KeyEvent, age=138901ms
    KeyEvent, age=138761ms
  PendingEvent: <none>
  InboundQueue: <empty>
  ReplacedKeys: <empty>
  Connections:
    674: channelName='c4bfea com.amazon.tv.settings.v2/com.amazon.tv.settings.v2.tv.device.DeviceActivity (server)', windowName='c4bfea com.amazon.tv.settings.v2/com.amazon.tv.settings.v2.tv.device.DeviceActivity (server)', status=NORMAL, monitor=false, responsive=true
      OutboundQueue: <empty>
      WaitQueue: <empty>
    668: channelName='d8e8659 com.amazon.ftv.profilepicker/com.amazon.ftv.profilepicker.ui.PickerActivity (server)', windowName='d8e8659 com.amazon.ftv.profilepicker/com.amazon.ftv.profilepicker.ui.PickerActivity (server)', status=NORMAL, monitor=false, responsive=true
      OutboundQueue: <empty>
      WaitQueue: <empty>
    664: channelName='f4e8a22 com.leed.sportsfire/com.leed.sportsfire.ui.HomeActivity (server)', windowName='f4e8a22 com.leed.sportsfire/com.leed.sportsfire.ui.HomeActivity (server)', status=NORMAL, monitor=false, responsive=true
      OutboundQueue: <empty>
      WaitQueue: <empty>
    460: channelName='4f714da com.amazon.vizzini (server)', windowName='4f714da com.amazon.vizzini (server)', status=NORMAL, monitor=false, responsive=true
      OutboundQueue: <empty>
      WaitQueue: <empty>
    441: channelName='9f74e91 com.amazon.vizzini (server)', windowName='9f74e91 com.amazon.vizzini (server)', status=NORMAL, monitor=false, responsive=true
      OutboundQueue: <empty>
      WaitQueue: <empty>
    481: channelName='b115cf6 com.amazon.tv.launcher/com.amazon.tv.launcher.ui.HomeActivity_vNext (server)', windowName='b115cf6 com.amazon.tv.launcher/com.amazon.tv.launcher.ui.HomeActivity_vNext (server)', status=NORMAL, monitor=false, responsive=true
      OutboundQueue: <empty>
      WaitQueue: <empty>
    426: channelName='62b3dee InputMethod (server)', windowName='62b3dee InputMethod (server)', status=NORMAL, monitor=false, responsive=true
      OutboundQueue: <empty>
      WaitQueue: <empty>
    134: channelName='PointerEventDispatcher0 (server)', windowName='PointerEventDispatcher0 (server)', status=NORMAL, monitor=true, responsive=true
      OutboundQueue: <empty>
      WaitQueue: <empty>
  AppSwitch: not pending
  Configuration:
    KeyRepeatDelay: 50ms
    KeyRepeatTimeout: 400ms
hdmi_input: null
device_class: tv
entity_picture: /api/media_player_proxy/media_player.fire_tv_192_168_1_84?token=8e71fe8b54efe06540df2a5912ba935b914c50a9d864e3a48e3685cb1a83212d&cache=9177c63a419a57a8
friendly_name: Fire TV 192.168.1.84
supported_features: 22961

### Additional Comments (optional)

![IMG_8984](https://github.com/PRProd/HA-Firemote/assets/57354320/05703d8b-f006-4c9a-b166-207492c707a0)

**Comment by PRProd** [comment]
Greetings @chemelli74!

Since the [Fire TV Stick 4K 2nd Gen (2023)](https://github.com/PRProd/HA-Firemote/wiki/Fire-TV-Stick-4K-2nd-Gen-(2023)) is already supported by Firemote, am I correct to assume that the *new remote layout* you are referencing is the different app launch buttons on your physical remote?

If so, this config should get you most of the way there:

Visual Editor:
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/0bf2d0be-7184-4080-b14c-cc75dcaccb74)

YAML config
```yaml
type: custom:firemote-card
entity: {{ YOUR MEDIA PLAYER ENTITY GOES HERE }}
device_family: amazon-fire
device_type: fire_tv_stick_4k_second_gen
compatibility_mode: default
app_launch_3: function-app-switch
```
The only part that is missing is the "Amazon Music" app launcher button.

If you wish to have the Amazon Music app added as a launcher button that can be selected, please submit a [new app shortcut request](https://github.com/PRProd/HA-Firemote/issues/new?assignees=PRProd&labels=New+App+Shortcut%2Cenhancement&projects=&template=App_Shortcut_Request.yaml&title=%5BNew+App+Shortcut%5D%3A+amazon+music) so I can get started on it.

Thanks!

-Doug

**Comment by chemelli74** [comment]
> Greetings @chemelli74!

Greetings @PRProd
 
> Since the [Fire TV Stick 4K 2nd Gen (2023)](https://github.com/PRProd/HA-Firemote/wiki/Fire-TV-Stick-4K-2nd-Gen-(2023)) is already supported by Firemote, am I correct to assume that the _new remote layout_ you are referencing is the different app launch buttons on your physical remote?

Yup is the layout as I tried to state in the subject ;-)

> The only part that is missing is the "Amazon Music" app launcher button.

That and the 2 new icons: APPS and Alexa

**Comment by PRProd** [comment]
> > The only part that is missing is the "Amazon Music" app launcher button.
>
>That and the 2 new icons: APPS and Alexa

## Alexa
Firemote is unable to emulate the Alexa interactions.  Because of this limitation, and even since the very first Firemote release, the Alexa button has been replaced with a keyboard button.  Using the keyboard button allows you to send text directly to your device by typing instead of navigating through the on-screen keyboard.  This will remain as it is.

## Apps
Can you confirm for me that **Function: Switch Apps / function-app-switch** completes the same task as when you press the APPS button on your physical remote?  Is your request to simply change the logo for that option?
| current | Requested|
| --------  | -------------- |
| ![image](https://github.com/PRProd/HA-Firemote/assets/25486599/4a3cb43f-4934-471d-a25e-9198cffb6905) | ![image](https://github.com/PRProd/HA-Firemote/assets/25486599/4dbd9762-7905-4af2-ac9c-26cd0e312e8e) |

## Amazon Music
I see that you've opened [[New App Shortcut]: Amazon Music #357](https://github.com/PRProd/HA-Firemote/issues/357).  Thank you.  I will complete that task for you.

**Comment by chemelli74** [comment]
> ## Alexa
> Firemote is unable to emulate the Alexa interactions. Because of this limitation, and even since the very first Firemote release, the Alexa button has been replaced with a keyboard button. Using the keyboard button allows you to send text directly to your device by typing instead of navigating through the on-screen keyboard. This will remain as it is.

Gotha, thx for the details.

> ## Apps
> Can you confirm for me that **Function: Switch Apps / function-app-switch** completes the same task as when you press the APPS button on your physical remote? Is your request to simply change the logo for that option?

Confirmed to be the same function, only a logo change.

> ## Amazon Music
> I see that you've opened [[New App Shortcut]: Amazon Music #357](https://github.com/PRProd/HA-Firemote/issues/357). Thank you. I will complete that task for you.

Thank you

**Comment by PRProd** [comment]
@chemelli74 ~

I've just published Firemote version [v3.3.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.1) which contains the new artwork for the apps button.  Enjoy!

-Doug

**Comment by chemelli74** [comment]
Hi,

thx!
Updated but seems a bit too large:

![image](https://github.com/PRProd/HA-Firemote/assets/57354320/09661c84-41eb-4b03-8a7c-4fc627397bba)

**Comment by PRProd** [comment]
@chemelli74 ~

What you are seeing is actually a sticky cache issue.  This happens a lot - It's nobody's fault, just a quirk of Home Assistant. I wrote a wiki article explaining what to do in this situation that you can find here: [Force a Refresh](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh).

This is what you should be seeing:
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/3566b7bd-b4ed-4eef-8053-0c0253d3c6a4)


After going through the steps in the  [Force a Refresh](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) article, if you are still having issues, please let me know.

**Comment by chemelli74** [comment]
I solved the issue with a browser ->F12->hard reset cache.

Strange issue as usually when I install a fresh version of a card there is a request of reload from HA that is enough.
