### ISSUE TITLE
[New App Shortcut]: Telus tv+

### ISSUE THREAD

**Issue by philou669** [PRProd/HA-Firemote#355]
### App Name

Telus tv+

### Device Platform

Chromecast

### App Store Link and/or URL to .apk file if sideloaded

mSurface=Surface(name=com.telus.mediaroom.tvx.byod/tv.threess.threeready.ui.generic.activity.MainActivity)/@0xbc39b2c
      mSurface=Surface(name=com.telus.mediaroom.tvx.byod/tv.threess.threeready.ui.generic.activity.MainActivity)/@0xc47338a
        mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x2cacf63

### Application Details

Watching tv in canada

thanks

**Comment by philou669** [comment]
yes and yes, great

thank you very much

**Comment by PRProd** [comment]
@philou669 

I have just published Firemote version [v3.3.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.1) which contains your requested app shortcut. Since I was not able to confirm that it works as expected because of a regional issue, I'll have to ask you to reply back here if it doesn't seem to work as expected.  Thanks!  Enjoy!

-Doug

**Comment by philou669** [comment]
I do the update and I reboot and it is not there. Same fot amazon music.

have a good day

![Sans titre](https://github.com/PRProd/HA-Firemote/assets/49702687/dae6354e-b50c-4c4d-9f3b-5751d48ee4da)

**Comment by PRProd** [comment]
@philou669 ~

This happens a lot - It's nobody's fault, just a quirk of Home Assistant.  I wrote a wiki article explaining what to do in this situation that you can find here: [Force a Refresh](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh).

The latest Firemote version [v3.3.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.1) does include **Telus tv+** and **Amazon Music**

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/515cdb38-d1cd-4916-ab20-5622156c66dd)

The Pluto TV logo was updated in release version [v3.3.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.0)

Let me know if this helps, or if something still isn't quite right.

**Comment by philou669** [comment]
works great

 thanks you
