### ISSUE TITLE
[New App Shortcut]: Amazon Music

### ISSUE THREAD

**Issue by chemelli74** [PRProd/HA-Firemote#357]
### App Name

Amazon Music

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.amazon.mp3

### Application Details

adb_response: >-
  mSurface=Surface(name=com.amazon.bueller.music/com.amazon.music.activity.TemplateActivity)/@0x8449957
        mSurface=Surface(name=com.amazon.bueller.music/com.amazon.music.activity.TemplateActivity)/@0x4ee7cb2
    mInputMethodTarget in display# 0 Window{f825d5f u0 com.amazon.bueller.music/com.amazon.music.activity.TemplateActivity}

**Comment by philou669** [comment]
For Chromcast/android tv (mibox) too please

thank you

**Comment by PRProd** [comment]
@chemelli74 & @philou669 ~

I have just published Firemote version [v3.3.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.1) which contains the app shortcut for Amazon Music.  As it turns out, Amazon Music is available on every device family that Firemote supports. [(click here to view the support chart for over 200+ apps)](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers)  Enjoy!

-Doug

**Comment by chemelli74** [comment]
Hi, just updated and cannot find the new link :-(

**Comment by philou669** [comment]
> Hi, just updated and cannot find the new link :-(

me too

**Comment by PRProd** [comment]
@chemelli74 & @philou669  ~

This happens a lot - It's nobody's fault, just a quirk of Home Assistant. I wrote a wiki article explaining what to do in this situation that you can find here: [Force a Refresh](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh).

The latest Firemote version [v3.3.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.1) does include the Amazon Music button:

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/c6484afe-c4ca-4f09-9bcc-0e30bc685526)

Let me know if this helps, or if something still isn't quite right.

**Comment by chemelli74** [comment]
I solved the issue with a browser ->F12->hard reset cache.

Strange issue as usually when I install a fresh version of a card there is a request of reload from HA that is enough.

**Comment by PRProd** [comment]
@chemelli74 ~ I struggle with the sticky cache issue a lot.  I have to "hard refresh" constantly while doing development.  Like I mentioned in the article, I know why it's like that.  Good caching is for our benefit!  We get a great speed increase!  ...but sometimes this happens too.  Ultimately, I'm still glad that it's like this though.
