### ISSUE TITLE
[New App Shortcut]: Redbull TV

### ISSUE THREAD

**Issue by millallo** [PRProd/HA-Firemote#358]
### App Name

Redbull TV

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.nousguide.android.rbtv

### Application Details

adb_response: mSurface=Surface(name=)/@0x711fc03
      mSurface=Surface(name=com.redbull.rbtv/com.redbull.MainActivity)/@0xb573f97
  mCurrentFocus=Window{8ae12b u0 com.redbull.rbtv/com.redbull.MainActivity}
  mFocusedApp=AppWindowToken{834144a token=Token{d1d95b5 ActivityRecord{75dddec u0 com.redbull.rbtv/com.redbull.MainActivity t2844}}}
hdmi_input: null
device_class: tv
friendly_name: Fire TV
supported_features: 22961
source_list: com.redbull.rbtv
app_id: com.redbull.rbtv
source: com.redbull.rbtv
entity_picture: /api/media_player_proxy/media_player.fire_tv?token=dc7634b14e97546268e4fe3e97b0ed7849d8e2be54a82dfa1469511537cb8ba9&cache=2b8226821646c1dc

**Comment by PRProd** [comment]
Greetings @millallo!

I have just published Firemote version [v3.2.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.2) which contains your app shortcut request.  After updating to the newest version, if you are unable to see the new updates, please visit this link for help: https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh

Enjoy!

-Doug
