### ISSUE TITLE
[New App Shortcut]: DirecTV Stream

### ISSUE THREAD

**Issue by bigmack48** [PRProd/HA-Firemote#36]
### App Name

Direct Tv Stream

### Can this app be freely downloaded through official means?

- [X] Yes

### Optional Comments

I want to select Direct Tv stream from your remote

**Comment by PRProd** [comment]
[Version 1.11.3](https://github.com/PRProd/HA-Firemote/releases/tag/v1.11.3) has been released which includes your completed request.  

Enjoy!
