### ISSUE TITLE
[New App Shortcut]: PIA VPN

### ISSUE THREAD

**Issue by GoldbergAF** [PRProd/HA-Firemote#363]
### App Name

PIA VPN

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/vpn-by-private-internet-access/id955626407

### Application Details

source_list:
  - PIA VPN

### Optional Comments

Want to hear a short joke and a long joke?

Joke Joooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooke.

**Comment by PRProd** [comment]
@GoldbergAF - Thank you for giving my my 250th star!  That's a milestone!

**Comment by PRProd** [comment]
Good News @GoldbergAF!

I've just published Firemote version [v3.2.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.2) which contains the Apple TV shortcut for PIA VPN.  After updating to the newest version, if you are unable to see the new updates, please visit this link for help: https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh

Enjoy!

-Doug
