### ISSUE TITLE
[Feature Request]: TCL Android TV Remotes

### ISSUE THREAD

**Issue by birwin88** [PRProd/HA-Firemote#364]
### Feature Request

UI option to select a remote for TCL Android TV's.

My specific remote is a RC902N FMR1 

Additionally there is an RC802V FNR1 that is very popular on Amazon as well.  

I feel like covering those two options would cover a large majority of TCL Android TV users.

**Comment by PRProd** [comment]
Greetings @birwin88!

Thanks for your interest in expanding Firemote to more and more device types!

As you might expect, I get similar requests like yours quite often.  As these requests come in, I like to have Firemote users like you vote on the next direction of the project.  

To make your voice heard, please make this request in the discussion [Poll: Vote for what gets added next! #41](https://github.com/PRProd/HA-Firemote/discussions/41).  Most of the recent devices added were the winners of this poll!

See you over there!

-Doug
