### ISSUE TITLE
[New App Shortcut]: Telia Play Norge

### ISSUE THREAD

**Issue by waato65** [PRProd/HA-Firemote#366]
### App Name

Telia Play Norge

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=no.get.play

### Application Details

source_list: App Store, Arcade, Bilder, Datamaskiner, Filmer, Innstillinger, Musikk, NRK TV, Podkaster, SVT Play, Søk, Telia Play, The Weather Channel, TV, TV 2 Play, Viafree, Viaplay, YouTube
friendly_name: Apple TV
supported_features: 450487

**Comment by PRProd** [comment]
@waato65 ~

Is this the correct logo for this app?

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/56e6db41-1d5d-4d98-8c63-1b53829a7494)

If not, could you provide me with a logo for this app, and/or a link to the Apple TV store?  The link you posted is for an app in the Google Play store.  I just want to be sure that I get the artwork correct.

Thanks.

-Doug

**Comment by waato65** [comment]
Yes, it's the correct logo for the app.

Here is the link for Apple store:
https://apps.apple.com/no/app/telia-play/id1213922701

tor. 11. apr. 2024, 22:05 skrev Doug Nelson ***@***.***>:

**Comment by PRProd** [comment]
Excellent!  Thank you for the information!  

While I'm working on that, do you happen to speak any languages other than English that are not [listed here](https://github.com/PRProd/HA-Firemote/wiki/#which-languages-are-currently-supported)?  If so, would you be willing to take a few minutes to help with a translation for Firemote users?

[Click here to start a new language support request](https://github.com/PRProd/HA-Firemote/issues/new?assignees=PRProd&labels=Region+Issue%2Cenhancement&projects=&template=New_Language_Support.yaml&title=%5BNew+Language+Support%5D%3A+)

It's OK if you choose not to do this, but if you choose to help out, I would be very grateful!

**Comment by PRProd** [comment]
@waato65,

I've just published Firemote version [v3.2.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.2) which contains your requested app shortcut.  After updating to the newest version, if you are unable to see the new updates, please visit this link for help: https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh

Enjoy!

-Doug

**Comment by waato65** [comment]
I had it for a day :)

I now have version 3.3.2 and i can't see it anymore?


Regards
Johnny A. Waagan



fre. 12. apr. 2024 kl. 00:00 skrev Doug Nelson ***@***.***>:

**Comment by PRProd** [comment]
@waato65 Johnny ~

The latest official version of Firemote (as of this second) is still v3.3.2 - There is also a beta version of Firemote v3.3.3b1 that was published.  Both of these versions contain the Telia Play launcher button code.
 - v3.3.2 [Telia Play code link](https://github.com/PRProd/HA-Firemote/blob/v3.3.2/dist/launcher-buttons.js#L4911-L4919)
 - v3.3.3b1 [Telia Play launcher code link](https://github.com/PRProd/HA-Firemote/blob/v3.3.3b1/dist/launcher-buttons.js#L4979-L4987)

This is a textbook case of being bitten by the Home Assistant Cache.  Please read this help article I've written especially for this type of issue:  https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh

**Comment by waato65** [comment]
I will do, thanks,

man. 15. apr. 2024, 20:41 skrev Doug Nelson ***@***.***>:
