### ISSUE TITLE
[New App Shortcut]: TV2 Play Norge

### ISSUE THREAD

**Issue by waato65** [PRProd/HA-Firemote#367]
### App Name

TV2 Play Norge

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/search?q=tv+2+play+app&c=apps

### Application Details

source_list: App Store, Arcade, Bilder, Datamaskiner, Filmer, Innstillinger, Musikk, NRK TV, Podkaster, SVT Play, Søk, Telia Play, The Weather Channel, TV, TV 2 Play, Viafree, Viaplay, YouTube
friendly_name: Apple TV
supported_features: 450487

**Comment by PRProd** [comment]
Greetings @waato65!

The **TV 2 Play** app launcher already exists for Apple TV.  It was requested in issue #226 and published on Nov 3, 2023 in Firemote version [v3.0.4](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.4)

Please update to the latest version of Firemote and try it out

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/11b20ee9-23a9-4987-9883-4dcee4d42535)

Based on the **source_list** data you posted in this request, the existing button should work for you.

Please let me know if I'm confused about your request in any way.  Thanks.

-Doug

**Comment by waato65** [comment]
Hi there Dough, thanks for the reply!

The one which is already there is the danish TV2 Play. I'm looking for the
norwegian TV2 Play.

Regards Johnny





tor. 11. apr. 2024, 20:29 skrev Doug Nelson ***@***.***>:

**Comment by PRProd** [comment]
Which one of these is the name of the TV2 Play norwegian app?
 - App Store
 - Arcade
 - Bilder
 - Datamaskiner
 - Filmer
 - Innstillinger
 - Musikk
 - NRK TV
 - Podkaster
 - SVT Play
 - Søk
 - Telia Play
 - The Weather Channel
 - TV
 - TV 2 Play (this is the one that gets opened using the button I posted above)
 - Viafree
 - Viaplay
 - YouTube

If the button I posted above actually does open the correct app, and you are just disagreeing with the logo attached to it, I would need to see what the actual logo looks like and/or a link to the proper Apple app store location where this can be downloaded.  The link you posted is for the Google Play store, which does not contain apps for Apple TV.

-Doug

**Comment by waato65** [comment]
Ok, i have not tried the one that's already there because i saw the logo
was for the danish TV2 Play. I'll give it a try!

tor. 11. apr. 2024, 22:01 skrev Doug Nelson ***@***.***>:

**Comment by PRProd** [comment]
@waato65 ~

Did this work as expected?  Can you send me a sample of the correct logo?

-Doug

**Comment by waato65** [comment]
Hello, yes it worked even if it's the danish version.

I have attached the norwegian logo for TV2 Play.

Regards
Johnny A. Waagan



man. 15. apr. 2024 kl. 17:00 skrev Doug Nelson ***@***.***>:

**Comment by PRProd** [comment]
@waato65 ~

Your attachment did not post to github, so I did not receive it.  You may need to actually log into this issue in the github app or on github.com and post it directly.

**Comment by waato65** [comment]
![TV_2_Play_Logo](https://github.com/PRProd/HA-Firemote/assets/63490451/82702f5c-2bb8-4f55-bb27-b0791fe64991)

**Comment by waato65** [comment]
![TV2 Play](https://github.com/PRProd/HA-Firemote/assets/63490451/e0eff510-7f8a-40bc-ba97-fe3c4139cc45)

**Comment by waato65** [comment]
Ok, no i have sent it from github👍

man. 15. apr. 2024, 20:31 skrev Doug Nelson ***@***.***>:

**Comment by PRProd** [comment]
@waato65,

Thanks for the  logo!  I've just published Firemote version [v3.3.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.3) which contains the appropriate logo under the new name of **TV 2 Play (Norway)**

Enjoy!

-Doug


After updating to the newest version, if you are unable to see the new updates on your Firemote card, please visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
