### ISSUE TITLE
[New App Shortcut]: KEXP TV Stream

### ISSUE THREAD

**Issue by lia-tc** [PRProd/HA-Firemote#368]
### App Name

KEXP TV Stream

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/kexp/id342254135

### Application Details

source_list: ``K E X P``

### Optional Comments

KEXP Seattle/San Francisco Radio Station

**Comment by PRProd** [comment]
Greetings @lia-tc!

I've just published Firemote version [v3.3.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.2) which contains your app shortcut request.  After updating to the newest version, if you are unable to see the new updates on your Firemote card, please visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
