### ISSUE TITLE
[New App Shortcut]: MSG+

### ISSUE THREAD

**Issue by Dragon1473** [PRProd/HA-Firemote#369]
### App Name

MSG+

### Device Platform

Roku

### Application Details

app_id: 691286
app_name: MSG+
source: MSG+

**Comment by PRProd** [comment]
Greetings @Dragon1473!

I just published Firemote Beta version [v3.3.3b1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.3b1) which contains an app shortcut for MSG+.  You can download and use this beta if you'd like, or you can wait for it to become  a part of the official version, which will likely happen very soon.

I'll leave this issue open until it is in the official version.

-Doug

**Comment by Dragon1473** [comment]
Works perfect!  Thank you so much, Doug!

**Comment by PRProd** [comment]
@Dragon1473,

This is in production version Firemote version [v3.3.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.3) now.

Enjoy!

-Doug
