### ISSUE TITLE
[New App Shortcut]: Disney+ Hotstar

### ISSUE THREAD

**Issue by clintferns2911** [PRProd/HA-Firemote#371]
### App Name

Disney+ Hotstar

### Device Platform

Amazon Fire

### Application Details

source_list: Disney+ Hotstar
app_id: in.startv.hotstar
source: Disney+ Hotstar
adb_response: mSurface=Surface(name=com.onemainstream.sonyliv.android/com.sonyliv.ui.home.HomeActivity)/@0xfb0df7c
  mCurrentFocus=Window{eab07f6 u0 com.onemainstream.sonyliv.android/com.sonyliv.ui.home.HomeActivity}
  mFocusedApp=AppWindowToken{9ba7622 token=Token{80b77ed ActivityRecord{598604 u0 com.onemainstream.sonyliv.android/com.sonyliv.ui.home.HomeActivity t1293}}}
hdmi_input: null
device_class: tv
entity_picture: /api/media_player_proxy/media_player.fire_tv_192_168_0_197?token=19c63e74fe82ca93b00250f0feeb7dfc817f42b993f43b7ad9ee0806f7b4ccbf&cache=5197c704e7000d1a
friendly_name: Fire TV 192.168.0.197
supported_features: 22961

**Comment by PRProd** [comment]
@clintferns2911 ~

Close, but not quite right.

This is the order you did the steps in:
 1. You ran the ADB command
 2. You opened the Disney+ Hotstar app on your Fire TV stick
 3. You copied the data from the **Developer Tools -> States** tab
<br>

This is the order they need to be run:
 1. Open the Disney+ Hotstar app **FIRST**
 2. After the app is open on your device, *then* run the ADB command
 3. Copy the data from the **Developer Tools -> States** tab
<br>

I cannot proceed without this procedure being done in the correct order.  Thank you for your understanding.

-Doug

**Comment by PRProd** [comment]
Good news @clintferns2911!

I searched hard for this app also, and was finally able to find the version that you are using.  I was able to answer my remaining questions and publish this in the latest release version Firemote version [v3.3.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.3).  It should be working as expected now.

Enjoy!

-Doug

After updating to the newest version, if you are unable to see the new updates on your Firemote card, please visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
