### ISSUE TITLE
[New App Shortcut]: Ziggo (NL)

### ISSUE THREAD

**Issue by Jorcoo** [PRProd/HA-Firemote#372]
### App Name

Ziggo Go TV

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/nl/app/ziggo-go-tv/id1268584236

### Application Details

Ziggo GO TV

**Comment by PRProd** [comment]
Greetings @Jorcoo!

Thanks for your request!  I just published Firemote version [v3.3.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.3) which contains the Apple TV launcher button for Ziggo Go.

Enjoy!

-Doug
<br>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
