### ISSUE TITLE
[New App Shortcut]: SomaFM

### ISSUE THREAD

**Issue by ivanrajkovic** [PRProd/HA-Firemote#373]
### App Name

SomaFM

### Device Platform

Roku

### Application Details

app_id: 2941
app_name: SomaFM
source: SomaFM

**Comment by PRProd** [comment]
Greetings @ivanrajkovic!

I've just published Firemote version [v3.3.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.3) which contains your app shortcut request for SomaFM.

Enjoy!

-Doug
<br>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
