### ISSUE TITLE
[New App Shortcut]: Antenna TV Channels on Fire TV

### ISSUE THREAD

**Issue by justinbramble** [PRProd/HA-Firemote#379]
### App Name

Antenna Channels

### Device Platform

Amazon Fire

### Application Details

adb_response: mSurface=Surface(name=com.amazon.tv.livetv/com.amazon.tv.livetv.TvChannelsPlayerActivity)/@0x4d5d626
  mCurrentFocus=Window{b3905f7 u0 com.amazon.tv.livetv/com.amazon.tv.livetv.TvChannelsPlayerActivity}
  mFocusedApp=AppWindowToken{3ba94a0 token=Token{32329a3 ActivityRecord{15ab4d2 u0 com.amazon.tv.livetv/.TvChannelsPlayerActivity t4897}}}

### Optional Comments

Just looking to be able to also control local digital channels that are available on my Fire TV as well as installed apps.

Thank you for your work in developing this, it is amazing!!!!

**Comment by PRProd** [comment]
Greetings @justinbramble!

I remember looking into this about a year ago and I was unable to figure out just how in the world to make it work.  Amazon Fire TVs aren't always the most agreeable things to work with.  :smile:  Happily, I'm older now and a little bit wiser, and I was able to find a way to make this work!  

I've just published Firemote version [v3.4.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.0) which contains an **Antenna** option after the HDMI inputs in the source dropdown.

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/958da08d-3c8a-4c82-93db-3f027dd4803e)

Enjoy!

-Doug
