### ISSUE TITLE
[New App Shortcut]: Greek TV Live & Radio Player

### ISSUE THREAD

**Issue by merc4derp** [PRProd/HA-Firemote#381]
### App Name

Greek TV Live & Radio Player

### Device Platform

Xiaomi

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.nickstamp.tvradio_gr

### Application Details

adb_response: mSurface=Surface(name=com.nickstamp.tvradio_gr/com.nickstamp.activity.TvActivity)/@0xf9d1290
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x696d3a9

**Comment by PRProd** [comment]
Greetings @merc4derp!

I have just published Firemote version [v3.4.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.1) which contains your app shortcut request.

Enjoy!

-Doug
