### ISSUE TITLE
[New App Shortcut]: Cheers - Danmu Player

### ISSUE THREAD

**Issue by JasonLoveCode** [PRProd/HA-Firemote#382]
### App Name

cheers

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/cheers-danmu-player/id1643375332

### Application Details

danmu player

**Comment by PRProd** [comment]
Greetings @JasonLoveCode!

I need to ensure that the information you provided is correct.  Typically I can do that by downloading the app for myself, but this app is not free so I need to confirm some information with you so it can be completed (to prevent the fate of issue #211)

When you completed this portion of the [Issue: App Shortcut Request](https://github.com/PRProd/HA-Firemote/issues/new?assignees=PRProd&labels=New+App+Shortcut%2Cenhancement&projects=&template=App_Shortcut_Request.yaml&title=%5BNew+App+Shortcut%5D%3A+) form, did you follow the [Instructions for Apple TV Devices](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-apple-tv-devices) before completing **Application Details** portion of the form?

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/c9dd844d-adf7-460a-8321-8681ae0f7d8d)

The value you entered into the box did not match the requested/expected format, so I need to be sure.

Thanks.

-Doug

**Comment by PRProd** [comment]
@JasonLoveCode ~

Have you had a chance to take a look at this yet?

**Comment by JasonLoveCode** [comment]
Later. I'm on vacation.


Doug Nelson ***@***.***>于2024年5月1日 周三01:58写道：

**Comment by PRProd** [comment]
@JasonLoveCode ~

I hope that you had a great vacation!  If you are back, have you had the opportunity to look at this?

**Comment by PRProd** [comment]
Thanks for getting back to me, @JasonLoveCode!

I have just published Firemote version [v3.4.4](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.4) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
