### ISSUE TITLE
[New App Shortcut]: APTV

### ISSUE THREAD

**Issue by JasonLoveCode** [PRProd/HA-Firemote#383]
### App Name

APTV

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/aptv/id1630403500

### Application Details

~iptv player~
APTV

### Optional Comments

iptv player

**Comment by PRProd** [comment]
Greetings @JasonLoveCode!

I have just published Firemote version [v3.4.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.1) which contains your app shortcut request.

Enjoy!

-Doug
