### ISSUE TITLE
[New App Shortcut]: Fox Local

### ISSUE THREAD

**Issue by justinbramble** [PRProd/HA-Firemote#385]
### App Name

Fox Local

### Device Platform

Amazon Fire

### Application Details

adb_response: mSurface=Surface(name=com.fox.fts.android/com.fox.fts.android.ui.NavHostActivity)/@0x6dfc001
  mCurrentFocus=Window{2c0aa18 u0 com.fox.fts.android/com.fox.fts.android.ui.NavHostActivity}
  mFocusedApp=AppWindowToken{e234f64 token=Token{18ac4f7 ActivityRecord{38518f6 u0 com.fox.fts.android/.ui.NavHostActivity t5083}}}
hdmi_input: null
device_class: tv
friendly_name: Family Room Fire TV ADB
supported_features: 22961
source_list: com.fox.fts.android
app_id: com.fox.fts.android
source: com.fox.fts.android
entity_picture: /api/media_player_proxy/media_player.family_room_fire_tv_adb?token=90b520631b70d2c96268179a74375760422a3fc380ff2fec8ac58e009e1a97fd&cache=e14492430ece0920

**Comment by PRProd** [comment]
Greetings @justinbramble!

I have just published Firemote version [v3.4.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.1) which contains your app shortcut request.

Enjoy!

-Doug
