### ISSUE TITLE
[Feature Request]: Support for Now TV on Nvidia Shield

### ISSUE THREAD

**Issue by wifispray** [PRProd/HA-Firemote#386]
### Feature Request

Support for Now TV on Nvidia Shield. Its possible via Andriod TV

**Comment by PRProd** [comment]
Greetings @wifispray!

Are you referring to an app called **NOW**?  If so, [it is supported for Apple and Amazon Fire TV currently](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers):

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/19df2e8e-6e12-419c-b329-a8038c8abdb6)
| Value for YAML File | App Name / Physical Input | Apple Support | Fire Support | Chromecast Support | Nvidia Shield Support | onn. Support | Roku Support | Xiaomi Support |
| ---------------------- | ------------------------------- | :---: | :-----: | :-----: | :-----: | :-----: | :-----: | :-----: |
| now-tv                 | Now                            | ✓ | ✓ |   |   |   |   |   |
<br>

If you simply want this app shortcut to exist for Shield devices as well, please open a new [App Shortcut Request](https://github.com/PRProd/HA-Firemote/issues/new?assignees=PRProd&labels=New+App+Shortcut%2Cenhancement&projects=&template=App_Shortcut_Request.yaml&title=%5BNew+App+Shortcut%5D%3A+) and provide the required details to get started.

**Comment by wifispray** [comment]
Yes. I need this for the shield?

**Comment by PRProd** [comment]
As stated above:
> open a new [App Shortcut Request](https://github.com/PRProd/HA-Firemote/issues/new?assignees=PRProd&labels=New+App+Shortcut%2Cenhancement&projects=&template=App_Shortcut_Request.yaml&title=%5BNew+App+Shortcut%5D%3A+) and provide the required details to get started.
