### ISSUE TITLE
[New App Shortcut]: Spectrum TV

### ISSUE THREAD

**Issue by cafe21** [PRProd/HA-Firemote#388]
### App Name

Spectrum TV

### Device Platform

Apple TV

### Application Details

source_list:  App Store, Arcade, CBC News, CNN, Computers, DAZN, Democracy Now!, discovery+, Disney+, DW,  Euronews, FaceTime, Fitness, FRANCE 24, FSTV, Hulu,  Max, Means TV, Movies, MSNBC, Music, NASA, Netflix, NHK WORLD, Paramount+, PBS, PBS KIDS, Peacock, Photos, Podcasts, Prime Video, Search, Settings, Showtime Anytime, Spectrum TV, STARZ, Tubi, TV, TV Shows,  YouTube, YouTube TV

**Comment by PRProd** [comment]
Greetings @cafe21!

I have just published Firemote version [v3.4.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.1) which contains your app shortcut request.

Enjoy!

-Doug
