### ISSUE TITLE
[New App Shortcut]: Sky Q

### ISSUE THREAD

**Issue by twagenpl** [PRProd/HA-Firemote#390]
### App Name

Sky Q

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/de/app/sky-q/id1350865868

### Application Details

source_list:
  - "App\_Store"
  - Arcade
  - ARD Mediathek
  - Computer
  - Disney+
  - Einstellungen
  - Prime Video
  - Sky Q
  - Suchen

**Comment by PRProd** [comment]
Greetings @twagenpl!

I have just published Firemote version [v3.4.1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.1) which contains your app shortcut request.

Enjoy!

-Doug

**Comment by twagenpl** [comment]
Thank you @PRProd
