### ISSUE TITLE
[New App Shortcut]: Freecast

### ISSUE THREAD

**Issue by jlt24** [PRProd/HA-Firemote#393]
### App Name

Freecast

### Device Platform

Chromecast

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.freecast.watch&hl=en_US&gl=US

### Application Details

adb_response: mSurface=Surface(name=com.freecast.watch/com.freecast.features.MainActivity)/@0x4088dd7
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xccfdb30

**Comment by PRProd** [comment]
Greetings @jlt24 !

I have just published Firemote version [v3.4.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.2) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
