### ISSUE TITLE
[New App Shortcut]: TV Vlaanderen (BE)

### ISSUE THREAD

**Issue by GylRon1** [PRProd/HA-Firemote#394]
### App Name

TV VLAANDEREN

### Device Platform

Chromecast

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=nl.streamgroup.vlaanderen&hl=nl&gl=US

### Application Details

mSurface=Surface(name=nl.streamgroup.vlaanderen/tv.solocoo.htmlapp.FullscreenActivity)/@0xd18f2ec
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x94938bb

### Optional Comments

https://tvapi.solocoo.tv/    used to work but isn't now...
I use this url for the logo:
https://image.winudf.com/v2/image1/bmwuc3RyZWFtZ3JvdXAudmxhYW5kZXJlbl9pY29uXzE1OTU0MTE1OTdfMDcw/icon.webp?w=140&fakeurl=1&type=.webp

**Comment by PRProd** [comment]
Greetings @GylRon1!

I have just published Firemote version [v3.4.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.2) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by GylRon1** [comment]
Thank you for the enhancement Doug. Really appreciated! I will buy you at
least a coffee for this brilliant piece of software you wrote.
Best regards,
Ronny.

Op wo 8 mei 2024 20:26 schreef Doug Nelson ***@***.***>:

**Comment by PRProd** [comment]
You're too kind!  Thank you!  Please let me know if this does not work properly, or if there is anything else I can help you with.

**Comment by GylRon1** [comment]
I will test when I get home. I am not a software guy, more experience with
the hardware side of things. Glad that people like you share their
expertise.

Op wo 8 mei 2024 20:59 schreef Doug Nelson ***@***.***>:

**Comment by GylRon1** [comment]
Do you have a Paypal account? I can't support you with one of the options
you propose... .

Op wo 8 mei 2024 om 20:59 schreef Doug Nelson ***@***.***>:

**Comment by PRProd** [comment]
@GylRon1 ~

If the [Buy Me A Coffee](https://buymeacoffee.com/prprod) thing doesn't work, I've also had people use my [Amazon Wish List](https://www.amazon.com/hz/wishlist/ls/2UDS10RPJ6F5K?ref_=wl_share) to select and send Amazon gift cards.  Even though the cards are on the wish list at $50, you can change the denomination to whatever you want it to be.

**Comment by GylRon1** [comment]
I don't get it. Where can I select a gift card in your whish list?

Op do 9 mei 2024 om 00:12 schreef Doug Nelson ***@***.***>:

**Comment by PRProd** [comment]
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/08d0b6f7-a02c-4d45-9b78-9fb72aae67eb)

**Comment by GylRon1** [comment]
I see no gift card in the list?
[image: image.png]

Op do 9 mei 2024 om 00:45 schreef Doug Nelson ***@***.***>:

**Comment by PRProd** [comment]
Unfortunately, images attached to emails don't actually post to GitHub conversations, so I can't see what you wanted to show me.

Try this ~ My PayPal
![pp_p2p_my_qrcode_1715214244347.jpg](https://github.com/PRProd/HA-Firemote/assets/25486599/cf6a16f2-6c44-4cf8-afca-58480b13fc8c)

**Comment by GylRon1** [comment]
I donated €20 Douglas, have fun with it. 😉

Op do 9 mei 2024 om 02:26 schreef Doug Nelson ***@***.***>:

**Comment by PRProd** [comment]
THANK YOU SO MUCH @GylRon1!  I sincerely appreciate it!!
