### ISSUE TITLE
[New App Shortcut]:  fioptics+

### ISSUE THREAD

**Issue by tommyjames43** [PRProd/HA-Firemote#395]
### App Name

Fioptics+

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/fioptics/id1510975504

### Application Details

source_list:
  - "App\_Store"
  - Arcade
  - Computers
  - ESPN
  - FaceTime
  - Fioptics Plus
  - Fitness
  - Movies
  - Music
  - Photos
  - Plex
  - Podcasts
  - Prime Video
  - Protect
  - Search
  - Settings
  - TV
  - TV Shows

**Comment by PRProd** [comment]
Greetings @tommyjames43!

I have just published Firemote version [v3.4.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.2) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
