### ISSUE TITLE
[New App Shortcut]: TV4 Play Sweden

### ISSUE THREAD

**Issue by AlexanderGson** [PRProd/HA-Firemote#397]
### App Name

TV4 Play - Sweden

### Device Platform

NVIDIA Shield

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=se.tv4.tv4playtab

### Application Details

adb_response: mSurface=Surface(name=se.tv4.tv4playtab/se.tv4.tv4play.ui.tv.navigation.TvHubActivity)/@0xf3e076f
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x5ab3389
  mInputMethodTarget in display# 0 Window{ea9b51a u0 se.tv4.tv4playtab/se.tv4.tv4play.ui.tv.navigation.TvHubActivity}

### Optional Comments

The current TV4 Play option available does not seem to open the TV4 Play app (for me). Not sure if it can be updated with new info. Or if a separate one for TV4 Play Sweden needs to be created.

**Comment by PRProd** [comment]
@AlexanderGson ~

Thanks for letting me know!  It looks like the publisher of that app has made some recent updates that broke this shortcut.  I'll patch the shortcut on the Firemote side to make it work again.

-Doug

**Comment by PRProd** [comment]
@AlexanderGson 

I have just published Firemote version [v3.4.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.2) which contains the updated app launcher code.  The TV4 Play launcher should work again.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
