### ISSUE TITLE
[New App Shortcut]: Telia Play - Sweden

### ISSUE THREAD

**Issue by AlexanderGson** [PRProd/HA-Firemote#398]
### App Name

Telia Play - Sweden

### Device Platform

NVIDIA Shield

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.teliasonera.telia.playplus

### Application Details

adb_response: mSurface=Surface(name=com.teliasonera.telia.playplus/se.telia.teliaplay.androidtv.TeliaTvNavigationActivity)/@0xa1cb041
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x5ab3389
  mInputMethodTarget in display# 0 Window{cf82057 u0 com.teliasonera.telia.playplus/se.telia.teliaplay.androidtv.TeliaTvNavigationActivity}

### Optional Comments

The Telia TV Estonia option does not work for this app. So it needs to be created another one for Telia Play (Probably works in all nordic countries but I named it Sweden just to be safe)

**Comment by AlexanderGson** [comment]
I can see in the list from https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers

That there is an entry for Telia-Play with only Apple TV Support. Maybe the information from my post can provide the information needed to enable Nvidia Shield support, and maybe more.

**Comment by PRProd** [comment]
Greetings @AlexanderGson!

I have just published Firemote version [v3.4.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.2) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
