### ISSUE TITLE
[New App Shortcut]: StingTV

### ISSUE THREAD

**Issue by eleibzon** [PRProd/HA-Firemote#400]
### App Name

STINGTV

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/il/app/stingtv/id1258059490

### Application Details

source_list: 12+, AnyDesk, App Store, Arcade, Cloud Stream TV, Computers, Endel, Facebook Watch, HOT, IKEA Catalogue, Kartina.TV, Movies, Music, Netflix, Photos, Plex, Podcasts, Prime Video, Search, Settings, Speedtest, Spotify, STINGTV, TIDAL, TV, VLC, YouTube, כאן BOX, רשת 13
media_duration: 2
media_position: 0
media_title: Ambient Display
media_artist: YouTube
media_album_name: Ambient Display
app_id: com.google.ios.youtube
friendly_name: Bedroom
supported_features: 450487

**Comment by PRProd** [comment]
Greetings @eleibzon!

I have just published Firemote version [v3.4.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.2) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
