### ISSUE TITLE
[New App Shortcut]: Norlys Play

### ISSUE THREAD

**Issue by larsalthof** [PRProd/HA-Firemote#402]
### App Name

Norlys Play

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/dk/app/norlys-play/id882490098?l=da

### Application Details

source_list: All Classic Movies, App Store, Arcade, Blockbuster, Computere, Disney+, DRTV, FaceTime, Film, Filmstriben, Fotos, HBO Max, Indstillinger, LEGO® TV, Musik, NASA, Netflix, Norlys Play, Pluto TV, Podcasts, Prime Video, Speedtest, Steam Link, Søg, TED, TV, TV SYD PLAY

**Comment by PRProd** [comment]
Greetings @larsalthof!

I have just published Firemote version [v3.4.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.2) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by larsalthof** [comment]
You are the man!
