### ISSUE TITLE
[New App Shortcut]: HBO Max - Denmark

### ISSUE THREAD

**Issue by larsalthof** [PRProd/HA-Firemote#403]
### App Name

HBO Max

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/dk/app/hbo-max-tv-film-og-serier/id971265422?l=da

### Application Details

source_list: All Classic Movies, App Store, Arcade, Blockbuster, Computere, Disney+, DRTV, FaceTime, Film, Filmstriben, Fotos, HBO Max, Indstillinger, LEGO® TV, Musik, NASA, Netflix, Norlys Play, Pluto TV, Podcasts, Prime Video, Speedtest, Steam Link, Søg, TED, TV, TV SYD PLAY

**Comment by PRProd** [comment]
@larsalthof ~

This looks like a continuation of #274.  Thanks!

**Comment by larsalthof** [comment]
> @larsalthof ~
> 
> 
> 
> This looks like a continuation of #274.  Thanks!

I think so, but it is also still called HBO Max in Denmark

**Comment by PRProd** [comment]
@larsalthof,

I have just published Firemote version [v3.4.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.2) which contains the change for the Apple TV launcher shortcut for HBO Max.  I've also re-named the selection in the menu to **HBO Max Denmark/Netherlands**.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
