### ISSUE TITLE
[New App Shortcut]: NOVA Video Player

### ISSUE THREAD

**Issue by bossdu15000** [PRProd/HA-Firemote#406]
### App Name

NOVA Video Player

### Device Platform

Amazon Fire

### Application Details

~adb_response: >-
  mSurface=Surface(name=com.amazon.tv.ftvambient/com.amazon.tv.ftvambient.MainActivity)/@0x9fcac67
    mInputMethodTarget in display# 0 Window{bb8d0f7 u0 com.amazon.tv.ftvambient/com.amazon.tv.ftvambient.MainActivity}~
    
adb_response: mSurface=Surface(name=)/@0x96389f9
mSurface=Surface(name=org.courville.nova/com.archos.mediacenter.video.leanback.MainActivityLeanback)/@0xd403de2
  mCurrentFocus=Window{c20fd81 u0 org.courville.nova/com.archos.mediacenter.video.leanback.MainActivityLeanback}
  mFocusedApp=AppWindowToken{cac57f2 token=Token{b137efd ActivityRecord{b8fff54 u0 org.courville.nova/com.archos.mediacenter.video.leanback.MainActivityLeanback t151}}}

**Comment by PRProd** [comment]
Greetings @bossdu15000!

I have just published Firemote version [v3.4.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.3) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
