### ISSUE TITLE
[New App Shortcut]: Cheers - Danmu Player

### ISSUE THREAD

**Issue by JasonLoveCode** [PRProd/HA-Firemote#411]
### App Name

Cheers - Danmu Player

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/cheers-danmu-player/id1643375332

### Application Details

<html>
<body>

source_list: App Store, APTV, Arcade, Capybara Reader, Cheers, Conflux, Emby, FaceTime通话, Fileball, HamHub, HamiVideo, HomeHub, Hulu, Infuse, iPerf, iPlayTV, Jellyfin, Just Dance Now, Loon, Magic Fireplace, Musify, Netflix, Plex, Prime Video, PuffGlide, Quantumult X, RetroArch, Shadowrocket, Simple Live, Speedtest, Stash, Steam Link, Surge, Syncnext, TestFlight, TOP, Turnip Player, TV, Twitch, UnPlay, VidHub, VidPlay, Vimeo, WHomeKit-tvOS, XPTV, YouTube, Yunbox, zFuse TV, 健身, 弹幕播放器, 影片, 搜索, 播客, 极空间, 照片, 狂野飙车 8, 电脑, 电视节目, 设置, 起飞了, 音乐
--

</body>
</html>

**Comment by PRProd** [comment]
Copied relevant missing info from this issue back into #382

Closing as duplicate of #382
