### ISSUE TITLE
[New App Shortcut]: Radioplayer (UK)

### ISSUE THREAD

**Issue by EHTiger66** [PRProd/HA-Firemote#412]
### App Name

Radioplayer

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/search?q=Radioplayer&c=apps

### Application Details

  mSurface=Surface(name=uk.co.radioplayer/uk.co.radioplayer.base.tv.activity.RPTVHomeActivity)/@0x9f7c03c
    mCurrentFocus=Window{a5248d1 u0 uk.co.radioplayer/uk.co.radioplayer.base.tv.activity.RPTVHomeActivity}
    mFocusedApp=AppWindowToken{6db3857 token=Token{68bbdd6 ActivityRecord{c6b1198 u0 uk.co.radioplayer/.base.tv.activity.RPTVHomeActivity t1601}}}

**Comment by PRProd** [comment]
Greetings @EHTiger66!

I have just published Firemote version [v3.4.4](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.4) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by EHTiger66** [comment]
Wow that was fast, Great work👍

On 25 May 2024 01:52:55 BST, Doug Nelson ***@***.***> wrote:
>Greetings @EHTiger66!
>
>I have just published Firemote version [v3.4.4](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.4) which contains your app shortcut request.  Enjoy!
>
>-Doug
><hr>
>
>After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/PRProd/HA-Firemote/issues/412#issuecomment-2130619538
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
