### ISSUE TITLE
[New App Shortcut]: VidHub

### ISSUE THREAD

**Issue by doctorkb** [PRProd/HA-Firemote#415]
### App Name

VidHub

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/ca/app/vidhub-video-library-player/id1659622164

### Application Details

source_list: App Store, Arcade, CBC Gem, CBC Listen , CBC News, Computers, Crave, CTV, Disney+, FaceTime, Fitness, Global TV, Hungry Shark, Movies, Music, Netflix, OctoPod TV, Paramount+, Photos, Pocket Penguins, Podcasts, Prime Video, Protect, Search, Settings, SiriusXM, Sportsnet, Spotify, Stingrays Live, TELUS TV+, TestFlight, TV, TV Shows, VidHub

**Comment by PRProd** [comment]
Greetings @doctorkb!

I have just published Firemote version [v3.4.5](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.5) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by doctorkb** [comment]
Thank you, works great! 😁
