### ISSUE TITLE
[New App Shortcut]: Acorn TV

### ISSUE THREAD

**Issue by Manfell** [PRProd/HA-Firemote#416]
### App Name

Acorntv

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/ca/app/acorn-tv/id896014310?platform=appleTV

### Application Details
```
source_list: Acorn TV,
```

### Optional Comments
Acorn TV is a premier streaming service offering a collection of world-class mysteries, dramas and thrillers from Britain, Australia, Ireland, France, and beyond – extraordinary originals, exclusive premieres, and thought-provoking hit series from around the globe, all in one place. From charmingly cosy to daringly dark, escape to whatever destinations you like, no matter your cup of tea. Acorn TV…nothing less than Brilliant.

-- Edit 
@PRProd edited this issue request to include the proper required information

**Comment by PRProd** [comment]
Greetings @Manfell!

I have just published Firemote version [v3.4.5](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.5) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by Manfell** [comment]
Thank youCheers HowardCell    604-614-6450Email: ***@***.*** May 29, 2024, at 3:00 PM, Doug Nelson ***@***.***> wrote:﻿
Greetings @Manfell!
I have just published Firemote version v3.4.5 which contains your app shortcut request.  Enjoy!
-Doug

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit this link for help.
