### ISSUE TITLE
[New App Shortcut]: Britbox

### ISSUE THREAD

**Issue by Manfell** [PRProd/HA-Firemote#417]
### App Name

britbox

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/ca/app/britbox-the-best-british-tv/id1206838907

### Application Details

```
source_list: Britbox,
```

### Optional Comments

"Excellent TV from the UK that you can't see anywhere else." - Vogue

Created by BBC and ITV, BritBox allows you to stream the biggest collection of British TV — all in one place.

<br>
-- Edit

@PRProd edited this issue to include the proper required information

**Comment by PRProd** [comment]
Greetings @Manfell!

I have just published Firemote version [v3.4.5](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.5) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
