### ISSUE TITLE
[New App Shortcut]: UHF

### ISSUE THREAD

**Issue by Paradox8** [PRProd/HA-Firemote#424]
### App Name

UHF

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/uhf-love-your-iptv/id6443751726

### Required Information

source_list:
  - "App\_Store"
  - Arcade
  - Computers
  - FaceTime
  - Fitness
  - Infuse
  - Jellyfin
  - Movies
  - Music
  - Photos
  - Plex
  - Podcasts
  - Prime Video
  - Red Bull TV
  - RetroArch
  - Search
  - Settings
  - Spotify
  - Steam Link
  - Tailscale
  - TV
  - TV Shows
  - UHF
  - YouTube

**Comment by PRProd** [comment]
Good to see you again @Paradox8!

I have just published Firemote version [v3.4.6](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.6) which contains your app shortcut request for UHF.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
