### ISSUE TITLE
[New App Shortcut]: National Theatre at Home

### ISSUE THREAD

**Issue by alexhk90** [PRProd/HA-Firemote#430]
### App Name

National Theatre at Home

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.ntathome

### Required Information

adb_response: mSurface=Surface(name=Sys2023:dream)
      mSurface=Surface(name=com.ntathome/tv.vhx.tv.home.TvHomeActivity)
  mCurrentFocus=Window{b2d1966 u0 Sys2023:dream}
  mFocusedApp=AppWindowToken{e365f62 token=Token{3247d44 ActivityRecord{6fe7e57 u0 com.ntathome/tv.vhx.tv.home.TvHomeActivity t722}}}
  mInputMethodTarget=Window{598846a u0 com.ntathome/tv.vhx.tv.home.TvHomeActivity}

### Optional Comments

Seems to work reliably for me by switching the Fire TV media source to "com.ntathome".

**Comment by PRProd** [comment]
Greetings @alexhk90!

I have just published Firemote version [v3.4.7](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.7) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
