### ISSUE TITLE
[New App Shortcut]: Molotov.tv

### ISSUE THREAD

**Issue by bastgau** [PRProd/HA-Firemote#431]
### App Name

Molotov

### Device Platform

Xiaomi

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=tv.molotov.app

### Required Information

adb_response: mSurface=Surface(name=)/@0x7af3d9
      mSurface=Surface(name=tv.molotov.app/tv.molotov.android.main.MainActivity)/@0xebb728c
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x2ccc676
  mCurrentFocus=Window{a300523 u0 tv.molotov.app/tv.molotov.android.main.MainActivity}
  mFocusedApp=AppWindowToken{6d3acd8 token=Token{5bd1fbb ActivityRecord{458d44a u0 tv.molotov.app/tv.molotov.android.main.MainActivity t4770}}}

**Comment by PRProd** [comment]
Greetings @bastgau!

I have just published Firemote version [v3.4.7](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.7) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
