### ISSUE TITLE
[New App Shortcut]: TF1+

### ISSUE THREAD

**Issue by bastgau** [PRProd/HA-Firemote#432]
### App Name

TF1+

### Device Platform

Xiaomi

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=fr.tf1.mytf1

### Required Information

adb_response: mSurface=Surface(name=)/@0x7af3d9
      mSurface=Surface(name=fr.tf1.mytf1/fr.tf1.mytf1.MainActivity)/@0xf4852ee
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x2ccc676
  mCurrentFocus=Window{ea5837e u0 fr.tf1.mytf1/fr.tf1.mytf1.MainActivity}
  mFocusedApp=AppWindowToken{b82827a token=Token{ae51ea5 ActivityRecord{73b349c u0 fr.tf1.mytf1/.MainActivity t4795}}}

**Comment by PRProd** [comment]
Greetings @bastgau!

I have just published Firemote version [v3.4.7](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.7) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
