### ISSUE TITLE
[New App Shortcut]: Deezer

### ISSUE THREAD

**Issue by bastgau** [PRProd/HA-Firemote#433]
### App Name

Deezer

### Device Platform

Xiaomi

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=deezer.android.app

### Required Information

adb_response: mSurface=Surface(name=)/@0x7af3d9
      mSurface=Surface(name=deezer.android.tv/com.deezer.android.tv.ui.feature.authentication.AuthenticationActivity)/@0x3279e6c
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x2ccc676
  mCurrentFocus=Window{71a1937 u0 deezer.android.tv/com.deezer.android.tv.ui.feature.authentication.AuthenticationActivity}
  mFocusedApp=AppWindowToken{6762a0c token=Token{c5b413f ActivityRecord{9e4395e u0 deezer.android.tv/com.deezer.android.tv.ui.feature.authentication.AuthenticationActivity t4796}}}

**Comment by PRProd** [comment]
Greetings @bastgau!

I have just published Firemote version [v3.4.7](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.7) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
