### ISSUE TITLE
[New App Shortcut]: ZDFheute

### ISSUE THREAD

**Issue by hindseb** [PRProd/HA-Firemote#434]
### App Name

ZDFheute

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=de.heute.mobile&hl=de&pli=1

### Required Information

adb_response: >-
  mSurface=Surface(name=de.heute.mobile/de.heute.mobile.ui.web.WebActivity)/@0x335b239
    mCurrentFocus=Window{358ab8d u0 de.heute.mobile/de.heute.mobile.ui.web.WebActivity}
    mFocusedApp=AppWindowToken{50530a0 token=Token{ec6b5a3 ActivityRecord{664f0d2 u0 de.heute.mobile/.ui.web.WebActivity t2528}}}

**Comment by PRProd** [comment]
Greetings @hindseb!

I have just published Firemote version [v3.4.7](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.7) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by hindseb** [comment]
Thank you, Doug!
