### ISSUE TITLE
[Feature Request]: Additional app launch icons

### ISSUE THREAD

**Issue by jwagner0789** [PRProd/HA-Firemote#436]
### Feature Request

Allow for a larger amount of app launch icons for Chromecast remote. 

### Additional Comments (optional)

Seems that the Chromecast remote only allows for 6 app launch icons. Looking to see if it would be possible to add more without creating a custom look.

**Comment by PRProd** [comment]
Greetings @jwagner0789!

Yes, it can be done.  The limits I set were to maintain the original "realistic" look as much as possible, so I won't be removing the limit, but I can increase it.  Is 8 enough?

**Comment by jwagner0789** [comment]
That makes sense. But 8 would work for me. Once someone reads this though, I wouldn't be surprised if you get another request for 10 haha. 

As I was waiting for your response, I started thinking of other possibilities. Perhaps after clicking the app, having browser_mod display a list of shows for that specific app. Too much... maybe? Probably...

Thanks again for the quick response.

**Comment by PRProd** [comment]
> Once someone reads this though, I wouldn't be surprised if you get another request for 10 haha.

YES!  This is _exactly_ what happens!  It's happened before.  Maybe I shouldn't be so rigid?  Maybe I should?  I suppose it all depends on catching me at the right time.  :smile: - I changed it from 6 to 8, which will appear in the next release.
<br>

>As I was waiting for your response, I started thinking of other possibilities. Perhaps after clicking the app, having browser_mod display a list of shows for that specific app. Too much... maybe? Probably...

Another user brought up an idea similar to that in #418.  For the same reasons I said "not me" for that idea, I have to say the same here.

**Comment by PRProd** [comment]
@jwagner0789 ~

Look what you started: https://github.com/PRProd/HA-Firemote/issues/438#issuecomment-2156349425  LOL!

**Comment by jwagner0789** [comment]
Wow! Well that didn't take long hahaha. O and by the way... I'm gonna need a couple more hahaha jk

**Comment by PRProd** [comment]
Good news @jwagner0789!

Greetings !

I have just published Firemote version [v3.4.8](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.8) which changes the max number of app launcher buttons on the Chromecast remote from 6 to 8.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
