### ISSUE TITLE
Magenta TV

### ISSUE THREAD

**Issue by mueller-dd** [PRProd/HA-Firemote#437]
### App Name

MagentaTV

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/de/app/magentatv-tv-streaming/id1625657880

### Required Information

source_list:
  - AccuWeather
  - "App\_Store"
  - Arcade
  - ARD Mediathek
  - ARTE
  - Computer
  - Disney+
  - DVB>IP TV
  - Einstellungen
  - FaceTime
  - FE File Explorer Pro
  - Filme
  - Fitness
  - Fotos
  - Infuse
  - iPlayTV
  - MagentaTV
  - Musik
  - Netflix
  - Podcasts
  - Qmedia by QNAP
  - Spotify
  - Suchen
  - Tagesschau
  - TV
  - TV-Sendungen
  - VLC
  - waipu.tv
  - YouTube
  - ZDFmediathek
volume_level: 0.5
friendly_name: Apple TV
supported_features: 155573

### Optional Comments

Magenta TV is currently no longer accessible. Nothing happens when you select. Thanks

**Comment by PRProd** [comment]
Thanks for letting me know @mueller-dd!

It looks like the app name has changed from "Magenta TV" to "MagentaTV" (space was removed).  I'll adjust for the next release.

**Comment by PRProd** [comment]
Good news @mueller-dd!

I have just published Firemote version [v3.4.8](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.8) which contains the launcher button fix for the new version of Apple TV's MagentaTV app.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by mueller-dd** [comment]
Hello Doug,

 

Thank you for the great remote control on Home Assistant and the short-term changes. Sorry for my bad english.

 

Juergen

 

Von: Doug Nelson ***@***.***> 
Gesendet: Montag, 10. Juni 2024 23:57
An: PRProd/HA-Firemote ***@***.***>
Cc: mueller-dd ***@***.***>; Mention ***@***.***>
Betreff: Re: [PRProd/HA-Firemote] Magenta TV (Issue #437)

 

Good news @mueller-dd <https://github.com/mueller-dd> !

I have just published Firemote version v3.4.8 <https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.8>  which contains the launcher button fix for the new version of Apple TV's MagentaTV app. Enjoy!

-Doug

  _____  

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit this link <https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh>  for help.
