### ISSUE TITLE
[New App Shortcut]: Fandango at Home

### ISSUE THREAD

**Issue by Nash738850** [PRProd/HA-Firemote#438]
### App Name

vudu/Fandango at home

### Device Platform

Roku

### Required Information

app_id: 13842
app_name: Fandango at Home
source: Fandango at Home

**Comment by Nash738850** [comment]
Also are we able to add a few more buttons to the roku remote? I had to make extra buttons for apps we use and it does not look as nice

**Comment by PRProd** [comment]
Greetings @Nash738850!

> are we able to add a few more buttons to the roku remote?

This is interesting timing.  :smile: I had a similar request in #436 for more buttons on the Chromecast remote.  To quote what I stated there:
>Yes, it can be done. The limits I set were to maintain the original "realistic" look as much as possible, so I won't be removing the limit, but I can increase it.

Which one of these 6 options are you using on your Firemote?
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/77558c59-4c7e-4a4f-b2e1-d6293930af6e)

**Comment by Nash738850** [comment]
The voice pro and the TCL REMKTESent from my iPhoneOn Jun 10, 2024, at 11:02 AM, Doug Nelson ***@***.***> wrote:﻿
Greetings @Nash738850!

are we able to add a few more buttons to the roku remote?

This is interesting timing.  😄 I had a similar request in #436 for more buttons on the Chromecast remote.  To quote what I stated there:

Yes, it can be done. The limits I set were to maintain the original "realistic" look as much as possible, so I won't be removing the limit, but I can increase it.

Which one of these 6 options are you using on your Firemote?
image.png (view on web)

**Comment by Nash738850** [comment]
I don’t hate it but that’s up to you. Is vudu something you are able to add?Sent from my iPhoneOn Jun 10, 2024, at 12:43 PM, Doug Nelson ***@***.***> wrote:﻿
@Nash738850 ~
The voice pro, I have no problem moving it from 8 to 10.  However, the TCL... that's not going to move up to 10.  Moving from 6 to 8 makes it start to look strange I think.  Am I wrong??
image.png (view on web)
image.png (view on web)

**Comment by PRProd** [comment]
Yes.  It will be in the next release.

**Comment by Nash738850** [comment]
Thanks so much! I also noticed that the app turns on my tv at weird moments. Sent from my iPhoneOn Jun 10, 2024, at 3:15 PM, Doug Nelson ***@***.***> wrote:﻿
Yes.  Fandango at Home will be in the next release.

**Comment by PRProd** [comment]
@Nash738850 ~

I have just published Firemote version [v3.4.8](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.8) which contains your app shortcut request for Fandango at Home.  This release also increases the number of app launcher buttons for the Roku Voice remote pro from 8 to 10, and the number of launchers for the TCL Roku TV remote from 6 to 8.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
