### ISSUE TITLE
New app: NBA

### ISSUE THREAD

**Issue by Kaiserjoss555** [PRProd/HA-Firemote#439]
### App Name

NBA TV

### Device Platform

Apple TV

### Required Information

[www.nba.com](https://apps.apple.com/us/developer/nba-media-ventures-llc/id1536087365)

### Optional Comments

I would like to have NBA.com as launch button app with your great card ffor Apple TV.

Thanks a lot for sharing!

Best regards.

**Comment by PRProd** [comment]
Greetings @Kaiserjoss555!

I have just published Firemote version [v3.4.8](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.8) which contains your NBA app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
