### ISSUE TITLE
[New App Shortcut]: Swisscom blue TV

### ISSUE THREAD

**Issue by nicolasmai** [PRProd/HA-Firemote#443]
### App Name

blue TV

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/ch/app/swisscom-blue-tv/id798597407

### Required Information

source_list: App Store, Arcade, blue TV, Computer, Einstellungen, Emby, FaceTime, Filme, Fitness, Fotos, Infuse, IPTV Expert, Musik, Netflix, Play SRF, PlaySuisse, Plex, Podcasts, Sky, Spotify, Suchen, TV, Web Video Caster Receiver, YouTube

**Comment by PRProd** [comment]
Greetings !

I have just published Firemote version [v3.4.9](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.9) which contains your Swisscom blue TV app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
