### ISSUE TITLE
[New App Shortcut]: ScreenCloud

### ISSUE THREAD

**Issue by morrisam74** [PRProd/HA-Firemote#445]
### App Name

ScreenCloud

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://www.amazon.com/ScreenCloud-Player/dp/B0168O5PVA/

### Required Information

adb_response: mSurface=Surface(name=io.screencloud.player/io.screencloud.player.MainActivity)
      mSurface=Surface(name=SurfaceView - io.screencloud.player/io.screencloud.player.MainActivity)
  mCurrentFocus=Window{44b8476 u0 io.screencloud.player/io.screencloud.player.MainActivity}
  mFocusedApp=AppWindowToken{c5c689a token=Token{85fe5bc ActivityRecord{f0cddaf u0 io.screencloud.player/.MainActivity t4554}}}
  mInputMethodTarget=Window{7352f91 u0 com.amazon.tv.parentalcontrols/com.amazon.tv.parentalcontrols.PINManagementActivity}

### Optional Comments

ScreenCloud player for Amazon Fire TVs and Fire TV Stick 4k

**Comment by PRProd** [comment]
Greetings @morrisam74!

I have just published Firemote version [v3.4.9](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.9) which contains your ScreenCloud app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by morrisam74** [comment]
Awesome! Thank you so much.
