### ISSUE TITLE
[New App Shortcut]: Cinema HD V2

### ISSUE THREAD

**Issue by devinalonzo** [PRProd/HA-Firemote#446]
### App Name

Cinema HD V2

### Device Platform

Amazon Fire

### Required Information

mSurface=Surface(name=com.yoku.marumovie/com.movie.ui.activity.MainActivity)/@0x2e53657
  mInputMethodTarget in display# 0 Window{974cccb u0 com.yoku.marumovie/com.movie.ui.activity.MainActivity}

**Comment by PRProd** [comment]
Greetings @devinalonzo!

My apologies for the delay.  I've just returned from a vacation, and I'm trying to catch up on all of my messages.

Can you provide a URL where there is a safe version of this .apk file to download?  I can't find it in any app store, or in any of the trustworthy apk sites I typically find things.  I'm also seeing a lot of "modded" versions out there too which raises some concerns ~ it looks very suspicious to me.

Can you clear up any of my concerns and provide a good link?

-Doug

**Comment by PRProd** [comment]
@devinalonzo ~

Have you had an opportunity to look into answering my questions yet?  I'm just wondering how best to proceed.  Thanks.

-Doug

**Comment by PRProd** [comment]
@devinalonzo ~

If I don't hear back from you in a few days, I'll be closing this issue.  Please get back to me when you can.  Thanks.

-Doug

**Comment by devinalonzo** [comment]
I am so sorry I didn't notice your emails!

This is a media streaming app

Here is their direct download link:

https://download2293.mediafire.com/zyc9jnoctndgKDT9zQIZgpNbTaI9v5CDZ_NQO7ChUOOv2lQmEe3cV9_N4bmhxgLIvx_8F2sOxRCrEyoLEGcyet9_TrOtTxx5_UP-6x9560iqlrYD8BLCalxygF2ECpsj5ld7aIdoA_4fJqbVcTYx7D0cOg4sgLSPc4Om2CsS4ByJ8x_gAg/p2o2ibkjoewfb98/chd+3.0.3.apk

And the website:

https://www.firesticktricks.com/cinema-apk-firestick.html

Thank you for looking into it!

-------- Original message --------
From: Doug Nelson ***@***.***>
Date: 7/17/24 2:54 PM (GMT-07:00)
To: PRProd/HA-Firemote ***@***.***>
Cc: devinalonzo ***@***.***>, Mention ***@***.***>
Subject: Re: [PRProd/HA-Firemote] [New App Shortcut]: Cinema HD V2 (Issue #446)


@devinalonzo<https://github.com/devinalonzo> ~

If I don't hear back from you in a few days, I'll be closing this issue. Please get back to me when you can. Thanks.

-Doug

**Comment by PRProd** [comment]
@devinalonzo ~

Thanks for the reply!  After looking into the information you've just sent, I have another question.

The links you sent both point towards **Cinema HD V3** but your request was specifically for **Cinema HD V2**.  I can confirm that you are running V2 based off of the information you provided in your original request submission:
> mSurface=Surface(name=com.yoku.marumovie/com.movie.ui.activity.MainActivity)/@0x2e53657
mInputMethodTarget in display# 0 Window{974cccb u0 com.yoku.marumovie/com.movie.ui.activity.MainActivity}

V3 appears to be different, so the same commands to launch V2 will not work for V3

>    mSurface=Surface(name=com.yoku.cinemahd.v3/com.movie.ui.activity.MainActivity)/@0x79a213a
>  mCurrentFocus=Window{ac9d0a4 u0 com.yoku.cinemahd.v3/com.movie.ui.activity.MainActivity}
>  mFocusedApp=AppWindowToken{58509e token=Token{77e7ed9 ActivityRecord{8a1e520 u0 com.yoku.cinemahd.v3/com.movie.ui.activity.MainActivity t595}}}

After discovering that, I searched again for the V2 version, and ran across [this page](https://archive.org/details/cinema-hd-v-2-com.yoku.marumovie_202009) from the Internet Archive that contains [a link](https://archive.org/download/cinema-hd-v-2-com.yoku.marumovie_202009/Cinema%20HD%20V2_com.yoku.marumovie.apk) to download the V2 version.

To be cautious, I ran V2 through a [virustotal scan](https://www.virustotal.com/gui/file/66eb6c0a221f9bee22c4ee067f41454b50ddb6e8ea9aac161749d45302b2d62e/behavior) and it looked fairly clean with the exception of one alarm:
![image](https://github.com/user-attachments/assets/c9dd14bb-114a-42bb-baa2-6d946b4d2839)
![image](https://github.com/user-attachments/assets/394b5110-6a0b-47ff-b679-5185507ea50a)

For context, a [virustotal scan](https://www.virustotal.com/gui/file/ff462010947315e330b2c80421dcc066c8f54e717da03c3f4420cc0dbb0b9a43/behavior) of V3 is also showing that same "clean" with one alarm state.

My question for you now is, are you aware that there is a new version?  If so, do you still want a new app launch button to launch V2 (the old version), or should it launch the new V3 version?  If you have a compelling reason why the old version is needed, would it be best for me to just make shortcuts for both V2 and V3?

Please let me know.  Thanks.

-Doug

**Comment by PRProd** [comment]
Good news @devinalonzo!

I have just published Firemote version [v3.4.11](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.11) which contains your app shortcut request for V2.  I also included a shortcut for V3 just in case.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
