### ISSUE TITLE
[New App Shortcut]: B tv

### ISSUE THREAD

**Issue by dicapriokim** [PRProd/HA-Firemote#448]
### App Name

B tv

### Device Platform

Apple TV

### Required Information

SK Broadband's "B tv" IPTV hopes to be added

**Comment by PRProd** [comment]
Greetings @dicapriokim!

Please excuse me, I'm just returning from a vacation so it might take me a while to complete this request.

In the meantime, did you post this request in reference to a topic thread from [cafe.naver.com](https://cafe.naver.com/koreassistant?iframe_url=%2FArticleRead.nhn%3Fclubid%3D29860180%26articleid%3D17298%26art%3DaW50ZXJuYWwtY2FmZS13ZWItc2VjdGlvbi1zZWFyY2gtbGlzdA.eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjYWZlVHlwZSI6IkNBRkVfVVJMIiwiYXJ0aWNsZUlkIjoxNzI5OCwiY2FmZVVybCI6ImtvcmVhc3Npc3RhbnQiLCJpc3N1ZWRBdCI6MTcxOTMzMTk2ODgyOX0.ig2_Wk-TKbxGTu5-VtJof5-Zh7-55BAWG2e79YGeEx8%26query%3Dfiremote)?  If so, are you willing and able to help with an English to Korean translation for the Firemote project?

If you'd like to help, [click this link](https://github.com/PRProd/HA-Firemote/issues/new?assignees=PRProd&labels=Region+Issue%2Cenhancement&projects=&template=New_Language_Support.yaml&title=%5BNew+Language+Support%5D%3A+Korean&langcode=ko) to get started.  If not, that's OK too.  I will continue to provide updates to this app shortcut request as they are available.

Thanks!

-Doug

**Comment by PRProd** [comment]
@dicapriokim ~

I am unable to move forward with this app shortcut request without some additional information.

For this part of the request form:

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/ecafe8df-6ca1-45c5-a2b1-b855ae0b76e8)

You instead chose to write 
> SK Broadband's "B tv" IPTV hopes to be added

As instructed, I really do need you to follow this link and provide the information you receive after completing those steps: [Instructions for Apple TV Devices](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-apple-tv-devices).  Please reply in this thread with that information.

As I was looking around for the appropriate logo, I also ran into another issue.  Can you tell me which of these logos is the correct one for your request, or let me know if none of them are correct?  Or better yet, can you provide a link to the Apple App store where this app can be found?

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/9dfa8474-fd23-4d92-94d3-40df53cf93aa) ![image](https://github.com/PRProd/HA-Firemote/assets/25486599/3a660ba9-b677-4321-9146-fefef9fd6560) ![image](https://github.com/PRProd/HA-Firemote/assets/25486599/ebf2f163-0db3-43c9-b4f2-357a8a0f4d98) ![image](https://github.com/PRProd/HA-Firemote/assets/25486599/a9eb2902-056d-4b2d-8756-0042b97d7a8c) ![image](https://github.com/PRProd/HA-Firemote/assets/25486599/c465b168-90d5-4437-b225-f7b77577c1b6) ![image](https://github.com/PRProd/HA-Firemote/assets/25486599/2c65a9ba-8c35-45b2-b27a-5bc45c320f4d) ![image](https://github.com/PRProd/HA-Firemote/assets/25486599/2e8d9179-6637-4f49-9e43-6a0597d6ec78) ![image](https://github.com/PRProd/HA-Firemote/assets/25486599/a1c8b5a8-fcd7-4999-ac44-7a1e9b847912) ![image](https://github.com/PRProd/HA-Firemote/assets/25486599/3d8dc49c-8cd8-49eb-9237-ebecab20c86b) ![image](https://github.com/PRProd/HA-Firemote/assets/25486599/62779a06-6855-4b27-b4b8-6a9d4a8abfbe)

Thanks.

-Doug

**Comment by dicapriokim** [comment]
friendly_name: Apple_tv_4K
supported_features: 450487
source_list: App Store, Arcade, B tv, Disney+, FaceTime, Infuse, Netflix, Speedtest, TV, YouTube, zFuse TV Pro, Search, Settings, Picture, Music, Computer, Podcast
app_id: com.skbroadband.BtvOnA
app_name: B tv
media_position_updated_at: 2024-06-28T02:16:15.583713+00:00

==========================================================
What I asked for is "B tv" in the list.

In addition, I hope Infuse and zFuse TV Pro can be added together.

(Infuse, zFuse TV Pro is a video player installed on the app TV store.) 


![스크린샷 2024-06-28 113655](https://github.com/PRProd/HA-Firemote/assets/140711196/126d4d98-998c-47e9-a34c-1f09092c3f83)

**Comment by PRProd** [comment]
@dicapriokim ~

I have just published Firemote version [v3.4.10](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.10) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
