### ISSUE TITLE
[New App Shortcut]: Cloudstream

### ISSUE THREAD

**Issue by 1333481** [PRProd/HA-Firemote#450]
### App Name

CloudStream

### Device Platform

Amazon Fire, Chromecast, onn., Xiaomi

### App Store Link and/or URL to .apk file if sideloaded

https://cloudstream-on-fleek-co.ipns.dweb.link/install/

### Required Information

mSurface=Surface(name=com.lagradost.cloudstream3.prerelease/com.lagradost.cloudstream3.MainActivity)/@0x606b59
    mInputMethodTarget in display# 0 Window{ba641f7 u0 com.lagradost.cloudstream3.prerelease/com.lagradost.cloudstream3.MainActivity}

### Optional Comments

There is a stable version with the ID com.lagradost.cloudstream3, which has a blue cloud logo instead of a red one. It is recommended to use the pre-release of this app anyway.

**Comment by PRProd** [comment]
Greetings @1333481!

It's recommended to use the pre-release version?  That sounds strange to me... where can I read about that?

-Doug

**Comment by 1333481** [comment]
> Greetings @1333481!
> 
> It's recommended to use the pre-release version?  That sounds strange to me... where can I read about that?
> 
> -Doug

https://cloudstream.miraheze.org/wiki/Release_versions_of_CloudStream

at the bottom, it says that.

**Comment by PRProd** [comment]
@1333481 ~

Thanks for that link!  It was very helpful.

What I decided to do is to make an app shortcut for **both** the stable release version and the pre-release (beta) version to avoid any sort of ambiguity or confusion for other Firemote users in the future.

As a note for future me (if I might need it), it appears as though the link you posted did work at the time, but yesterday when https://github.com/recloudstream/cloudstream/commit/b776642775b8683912d9241aeb03902289fae002 was posted, it was dethroned.  

https://cloudstream-on-fleek-co.ipns.dweb.link/install/ -> https://github.com/recloudstream/cloudstream/releases/download/pre-release/app-prerelease.apk = 404

As of yesterday, new valid Beta release apk: https://github.com/recloudstream/cloudstream/releases/download/pre-release/app-prerelease-release.apk

Current stable release version: https://github.com/recloudstream/cloudstream/releases/download/v4.3.0/4.3.0.apk


I hope to have something ready soon.  😄 

-Doug

**Comment by 1333481** [comment]
> @1333481 ~
> 
> Thanks for that link!  It was very helpful.
> 
> What I decided to do is to make an app shortcut for **both** the stable release version and the pre-release (beta) version to avoid any sort of ambiguity or confusion for other Firemote users in the future.
> 
> As a note for future me (if I might need it), it appears as though the link you posted did work at the time, but yesterday when https://github.com/recloudstream/cloudstream/commit/b776642775b8683912d9241aeb03902289fae002 was posted, it was dethroned.  
> 
> https://cloudstream-on-fleek-co.ipns.dweb.link/install/ -> https://github.com/recloudstream/cloudstream/releases/download/pre-release/app-prerelease.apk = 404
> 
> As of yesterday, new valid Beta release apk: https://github.com/recloudstream/cloudstream/releases/download/pre-release/app-prerelease-release.apk
> 
> Current stable release version: https://github.com/recloudstream/cloudstream/releases/download/v4.3.0/4.3.0.apk
> 
> 
> I hope to have something ready soon.  😄 
> 
> -Doug

Thank you!

**Comment by PRProd** [comment]
Good news @1333481 ~

I have just published Firemote version [v3.4.9](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.9) which contains both of the app sortcuts we discussed.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
