### ISSUE TITLE
[New App Shortcut]: Hayu

### ISSUE THREAD

**Issue by joedowling23** [PRProd/HA-Firemote#456]
### App Name

Hayu

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/gb/app/hayu-watch-reality-tv/id1052817340

### Required Information

source_list:
  - "App\_Store"
  - Arcade
  - BBC iPlayer
  - Channel 4
  - Computers
  - discovery+
  - Disney+
  - FaceTime
  - Fitness
  - Hayu
  - ITVX
  - Movies
  - Music
  - My5
  - Netflix
  - NOW
  - Photos
  - Podcasts
  - Prime Video
  - Search
  - Settings
  - TV
  - TV Shows
  - YouTube

**Comment by PRProd** [comment]
Greeetings @joedowling23!

I have just published Firemote version [v3.4.10](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.10) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
