### ISSUE TITLE
[New App Shortcut]: ArchiTV for Archillect

### ISSUE THREAD

**Issue by JammoJu** [PRProd/HA-Firemote#457]
### App Name

ArchiTV for Archillect

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=space.linuxct.architv&hl=en

### Required Information

 mSurface=Surface(name=space.linuxct.architv/space.linuxct.architv.MainActivity)/@0x50b2049
    mCurrentFocus=Window{de5e378 u0 space.linuxct.architv/space.linuxct.architv.MainActivity}
    mFocusedApp=AppWindowToken{37a5b2a token=Token{ac72c15 ActivityRecord{3b051cc u0 space.linuxct.architv/.MainActivity t2182}}}

### Optional Comments

Flames dance on the screen,
Creativity's fire sparked,
Desire brought to life.

In the code they write,
Passion swirls, ideas ignite,
Creating magic.

Through digital realms,
Imagination takes flight,
Excitement abounds.

Thank you :)

**Comment by PRProd** [comment]
@JammoJu ~

Greetings !

I have just published Firemote version [v3.4.10](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.10) which contains your app shortcut request ArchiTV for Archillect.  Your request indicated that this was for FireTV, but I was not able to download it for FireTV in my region, so I could not confirm 100% that it will work.  Please let me know if this does not work properly.  If it's good to go, Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by JammoJu** [comment]
Hi Doug, 

Thank you for your hard work. This is excellent. A real triumph. One of the best looking cards on HA.

You are correct as well, I think originally I had the app on my Nvidia Shiled and Side-loaded it on the FireTV.

But neverless it is all working wonderfully.

I'm glad you enjoyed the Haiku :)

If I think of any more additions I will contact you, Thanks again.

**Comment by PRProd** [comment]
Thanks for your kind words @JammoJu!
