### ISSUE TITLE
App launcher 2 for Roku

### ISSUE THREAD

**Issue by siesta5787** [PRProd/HA-Firemote#459]
### Describe the bug

I am using app launcher 2 for my roku and love it. Only thing that doesn't work is the hamburger button doesn't work.  I think because that is specific to firetv? I was hoping that it might be an easy fix to have a roju specific version that replaces that button with the * button on the roku remote. Its the only thing missing and this layout is way better than standard roku remote since that doesn't have volume buttons and its tougher to use.  Also it would be cool if you could see the current playing channel / media control built in one which adds some duplication and isn't layer out as nice.  Thanks for your work on this. Super helpful!!

### To Reproduce

Click the hamburger button when using app launcher 2 on roku. 

### Expected Behavior

Error message. 

### Which Type of Device Do You Own?

TCL and ONN with built in roku.

**Comment by PRProd** [comment]
Greetings @siesta5787!

You are correct.  The hamburger button is _not_ a button that the Roku family has on its remote controls.  If you get a chance to read through closed issue #435, you will see that this was also discussed and then patched about a month ago in the Firemote version [v3.4.7](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.7) released on June 6, 2024.  

If you are seeing an error message that looks like this when you press the hamburger button, then you should update to the latest Firemote version.
> ``Service androidtv.adb_command not found``

If instead (and/or after you update), this informational dialog message was displayed:

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/e2a9d9c3-470c-45c2-8f37-967e511bb0dd)

Following the link shown in this box https://github.com/PRProd/HA-Firemote#button-overrides provides instructions about how to make that button (or any other button) do something else.  

For example, adding something like this to your Firemote card's YAML should override the Hamburger Buttons non-functionality in AL2 with the Roku device family's options/info/* function:
```yaml
button_overrides:
  hamburger-button:
    service: remote.send_command
    target:
      entity_id: {{ REPLACE THIS LINE WITH THE ID OF YOUR ROKU REMOTE ENTITY }}
    data:
      command: info
```
Obviously, you'll want to edit this to properly fit your situation.  A full list of valid Roku commands (like the Roku "info" command) can be found [here](https://www.home-assistant.io/integrations/roku/#remote).

Another example similar to this was provided and accepted [here in #435](https://github.com/PRProd/HA-Firemote/issues/435#issuecomment-2146294169) as well.
<br>

In regards to this:
>  Its the only thing missing and this layout is way better than standard roku remote since that doesn't have volume buttons and its tougher to use

If you change your mind someday about your "tougher to use" experience, you actually CAN have volume control with the native looking Roku Firemote:

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/027f7d6d-d519-490f-8348-652f4ed53ceb)

At the bottom of the App Launch Button dropdown menus, you will see a selection of device specific Functions.  In that list, I've included volume controls, as well as some other features that might interest you:
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/dfe48af2-4a11-4d14-8283-aae54be884e0)
<br>

In regards to this:
> Also it would be cool if you could see the current playing channel / media control built in one which adds some duplication and isn't layer out as nice

I've considered doing something like this as an add-on to the AL1 or AL2 Firemotes, or possibly making a new layout.  If this is something that interests you, please sketch some ideas for me, and include them when you open a new [Feature Request](https://github.com/PRProd/HA-Firemote/issues/new?assignees=PRProd&labels=enhancement&projects=&template=feature_request.yaml&title=%5BFeature+Request%5D%3A+).  It could end up being a popular feature if we can create something that everyone likes.
<br>

In regards to this:
>I am using app launcher 2 for my roku and love it. ...Thanks for your work on this. Super helpful!!

Thank you for your kind words!  This is a passion project of mine, and I'm always happy to hear from folks who get some enjoyment or benefit from using it!

I hope this helps!

-Doug

**Comment by siesta5787** [comment]
Yes thank you very much for the helpful rely.  I will put a thought together on the layout.  Sorry I missed the closed issue.

**Comment by PRProd** [comment]
That's great news, @siesta5787!  I'm glad I could help!
