### ISSUE TITLE
[New App Shortcut]: Vtm go & npo & Videoland (Nvidia shield)

### ISSUE THREAD

**Issue by jrspowers** [PRProd/HA-Firemote#46]
### App Name

Vtm go & Npo & Videoland

### Can this app be freely downloaded through official means?

- [X] Yes

### Optional Comments

hello i am using nvidia via your fire remote now my question was there is still new support for app the following apps i would like vtm go & npo & videoland? thanks in advance!

**Comment by PRProd** [comment]
@jrspowers - You have sent this request at the absolute PERFECT time!  I'm currently in the process on refactoring the codebase to support the NVIDIA shield family of devices.  While I likely won't be able to publish your requests immediately, I will definitely target having them included in the first Shield ready release!

**Comment by jrspowers** [comment]
that is very nice to hear that you are working on it, look forward to it when this comes out, then it is very nice to operate the shield TV 😊

**Comment by MRobi1** [comment]
> first Shield ready release!
I was about to make a FR for shield support, but I figure I'll just chime in and ask here instead.
Any rough ETA on a shield release?

**Comment by PRProd** [comment]
@MRobi1 - Soon.  At least a pre-release.  Would you like to be a beta tester?

**Comment by jrspowers** [comment]
@PRProd I would like to become a beta test very much looking forward to helping you !

**Comment by PRProd** [comment]
@jrspowers - I knew you would.  :-)  I'm working on getting a pre-release out to you in the next few hours.

**Comment by jrspowers** [comment]
@PRProd that's nice to hear looking forward to it 😌😊

**Comment by PRProd** [comment]
@MRobi1 & @jrspowers - I created discussion #47 to track progress on the NVIDIA Shield release.  Feel free to use that thread to continue our conversation!

**Comment by PRProd** [comment]
@jrspowers - I'm having some difficulties finding/downloading the VTM Go app.  Could you provide some more detail for me by following the steps [listed here](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests) under "Details for App Requests"?

**Comment by PRProd** [comment]
Two of these requests were added in the current beta release which @jrspowers is actively testing.  The third (VTM Go) @jrspowers moved to #50, so I'm content with closing this one as completed at this time.
