### ISSUE TITLE
[New App Shortcut]: Tablo TV

### ISSUE THREAD

**Issue by Othy07** [PRProd/HA-Firemote#460]
### App Name

Tablo TV 

### Device Platform

Roku

### Required Information

app_id: "734366"
app_name: Tablo TV
source: Tablo TV

### Optional Comments

Two blondes walk into a bar.  You'd think one of them would have seen it.

**Comment by PRProd** [comment]
Greetings @Othy07!

You're the first to make a joke!  Yay!!  I had a similar one that said "Two guys walked into a bar, and the third one ducked" but I think I like yours better.  😄

**Comment by PRProd** [comment]
Good news, @Othy07!

I have just published Firemote version [v3.4.11](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.11) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by Othy07** [comment]
Hey Doug,

Thanks for the update.

Have great day.

-Tim

PS - If I get another good short joke I have a one or two more.
