### ISSUE TITLE
[New App Shortcut]: Ibo Player Pro

### ISSUE THREAD

**Issue by PadyLoki** [PRProd/HA-Firemote#463]
### App Name

~~IBOPro Player~~

-- Edit @PRProd --
Ibo Player Pro

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

~~https://play.google.com/store/apps/details?id=com.ibopro.player~~

-- Edit @PRProd --
https://cdn.iboproapp.com/download/app

### Required Information

adb_response: mSurface=Surface(name=com.flextv.livestore/com.flextv.livestore.activities.HomeActivity)/@0xe1c0214
  mCurrentFocus=Window{8d99781 u0 com.flextv.livestore/com.flextv.livestore.activities.HomeActivity}
  mFocusedApp=AppWindowToken{644866f token=Token{51f954e ActivityRecord{95a2849 u0 com.flextv.livestore/.activities.HomeActivity t3176}}}

**Comment by PRProd** [comment]
Greetings @PadyLoki!

I'm having a little difficulty with this request, and I'm hoping that you can help with my confusion.

You requested an app launcher for the **Amazon Fire** device platform, but provided a link to the Google app store.  The google app store does not work for Amazon Fire devices.  The built-in way to download apps to Fire TV devices is through the Amazon App Store, or by using the downloader app to sideload .apk files.

Additionally, the data you posted in the **Required Information** section shows that you had an app with the android name of ``com.flextv.livestore`` open when running [the command procedure listed in the instructions](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-fire-tv-chromecast-nvidia-shield-xiaomi-mi-and-other-android-based-devices), which didn't seem to be right at first glance.  (more about that later)

This is what I was able to find in my region when searching for an app with the name "IBOPro Player" in the Amazon app store:

## [Amazon App Store Search Results](https://www.amazon.com/s?k=ibo+pro+player&i=mobile-apps&crid=13AOVH2GAW4EU&sprefix=ibo+pro+playe%2Cmobile-apps%2C99&ref=nb_sb_noss_2)
| Logo | App Name | Store Link | Android Name |
| ---- | -------- | ---------- | ------------ |
| ![image](https://github.com/user-attachments/assets/1cad18f3-b413-4ab4-a9c3-5ba631727dce) | ibo pro tv | https://www.amazon.com/ibo-Ltd-LLC-pro-tv/dp/B0CT96GL6F | com.bibostore.zaandk |
| ![image](https://github.com/user-attachments/assets/895ea1a0-fd9a-47d3-8241-65fb65c69b82) | Ib Player | https://www.amazon.com/Ibo-Pro-LLC-Ib-Player/dp/B0D3R3KQT2 | com.ib.pro |
| ![image](https://github.com/user-attachments/assets/1d3a6410-9580-42e7-b1c6-dad1d3549047) | IBO PLAYER PRO | https://www.amazon.com/BT-SOLUCOES-IBO-PLAYER-PRO/dp/B0D2DSQRQ4/ | (unavailable on my device) |

After finding these results in the Amazon app store, and realizing that they don't seem to match your request, I tried instead searching for an app with the ``com.flextv.livestore`` name you provided, and I came across this site: https://apkgk.com/com.flextv.livestore/download - After downloading the .apk from this site, unfortunately I was unable to launch the app on my Fire TV device.

Can you help me out with any additional information?  I'd appreciate it.

Thanks.

-Doug

**Comment by PadyLoki** [comment]
Hi Doug,

Sorry I linked to the Play store variant out of habit. The official site for the app is https://iboplayer.pro/ which lists the firetv downloader for the apk as 834339 or https://shorturl.at/hsMW1

Hope this helps 😁

**Comment by PRProd** [comment]
@PadyLoki ~

Perfect!  Thank you!

**Comment by PRProd** [comment]
Good news @PadyLoki!

I have just published Firemote version [v3.4.11](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.11) which contains your app shortcut request for Ibo Player Pro.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
