### ISSUE TITLE
[New App Shortcut]: Fox Business

### ISSUE THREAD

**Issue by highincolorado** [PRProd/HA-Firemote#473]
### App Name

~~Fox News~~
Fox Business

### Device Platform

Amazon Fire

### Required Information

adb_response: mSurface=Surface(name=com.twoergo.foxbusiness/com.foxnews.androidtv.ui.landing.LandingActivity)
      mSurface=Surface(name=SurfaceView - com.twoergo.foxbusiness/com.foxnews.androidtv.ui.landing.LandingActivity)
      mSurface=Surface(name=SurfaceView - com.twoergo.foxbusiness/com.foxnews.androidtv.ui.landing.LandingActivity)
  mCurrentFocus=Window{ab178a7 u0 com.twoergo.foxbusiness/com.foxnews.androidtv.ui.landing.LandingActivity}
  mFocusedApp=AppWindowToken{8fd2a5c token=Token{2b7d0cf ActivityRecord{3420d2e u0 com.twoergo.foxbusiness/com.foxnews.androidtv.ui.landing.LandingActivity t2208}}}

### Optional Comments

Thanks for the work on this.

**Comment by PRProd** [comment]
You wrote **Fox News**, but since Fox News already exists, and since the app signature you posted is different from Fox News, I'm going to assume you actually meant to say **Fox Business**

Please let me know if I'm wrong about this assumption.

**Comment by highincolorado** [comment]
You’re right Fox Business is what I meant🤦‍♂️

**Comment by PRProd** [comment]
Greetings @highincolorado!

I have just published a beta Firemote version [v4.0.0b1](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.0b1) which contains your app shortcut request.  Feel free to download the beta version to try it out, or choose to wait until the next official Firemote release. I will leave this issue open until these changes are pushed to an official release. Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by highincolorado** [comment]
Many thanks the Fox Business works as expected. Took more time to figure out how to install the beta version than it should have I’m sure. And then it was also “sticky” in my FireFox browser but I found that whatever HACs does to clear the browser after a front end update solved this for me, other updates were pending. Might be nice to have this clear/reload available all the time since it does not wipe all the other things in the cache.

**Comment by PRProd** [comment]
Sticky cache is a blessing and a curse, eh?  That's why I include [that link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) in all of my update responses. Glad to hear that everything is now updated and working as expected!

If you'd like to contribute some more, and since you're already using the beta... if you have some extra time on your hands feel free to join us in discussion #477 😄 We'd love to have your input!

Also, [THANKS FOR THE COFFEE!!](https://buymeacoffee.com/prprod/c/10556964)

-Doug

**Comment by PRProd** [comment]
An update for you @highincolorado ~

I have just published Firemote version [v4.0.0](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.0) which moves your app shortcut request from beta to official.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
