### ISSUE TITLE
[New App Shortcut]: SKY +

### ISSUE THREAD

**Issue by viniciusfischer** [PRProd/HA-Firemote#474]
### App Name

SKY +

### Device Platform

Chromecast

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=br.com.skymais&hl=pt_BR

### Required Information

adb_response: mSurface=Surface(name=br.com.skymais/com.directvgo.feature.tv.profile.ProfileActivity)/@0x6af9fa2
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x891be88

**Comment by PRProd** [comment]
Greetings @viniciusfischer!

I have just published a beta Firemote version [v4.0.0b1](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.0b1) which contains your app shortcut request.  Feel free to download the beta version to try it out, or choose to wait until the next official Firemote release.  I will leave this issue open until these changes are pushed to an official release. Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by PRProd** [comment]
An update for you @viniciusfischer ~

I have just published Firemote version [v4.0.0](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.0) which moves your app shortcut request from beta to official.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
