### ISSUE TITLE
Applauncher buttons for RTL+ and Magenta TV not working on Fire TV

### ISSUE THREAD

**Issue by FranknStone** [PRProd/HA-Firemote#475]
### Describe the bug

Ich have applauncher buttons for RTL+ and Magenta TV configured on my firemote for Fire TV Stick 4k Max 2023 but they don‘t work. Other applauncher buttons like Netflix are ok.

### To Reproduce

Create an applauncher button on firemote for Fire TV for RTL+ or Magenta TV and press it.
There will be no action on the device.

### Expected Behavior

Pressing applauncher butto for RTL+ should launch the RTL+ app on Fire TV.
Same for Magenta TV.

### Which Type of Device Do You Own?

Fire TV Stick 4k Max (2023)

**Comment by PRProd** [comment]
Greetings @FranknStone!

Thank you for reporting this!  With [over 280 launcher buttons](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers) already available, many of which are not available from the app store in my region, it's not easy to keep track of when things stop working.  I sincerely appreciate your report!  Thank you.

## RTL+
This app is not available in my region, so I'm going to need your help.  First, did you notice that there are actually two different RTL+ options for Amazon Fire?  RTL+ and RTL+ Hungary

![image](https://github.com/user-attachments/assets/c94667ab-5689-4880-ada1-a1b85bd16818)

These two app variations were noticed when issue #330 was first opened to add RTL+ to Firemote, so both of them were included in the release.  Have you tried both of these options?  If you did and neither of them worked, let's continue.

Please follow the instructions [listed here](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-fire-tv-chromecast-nvidia-shield-xiaomi-mi-and-other-android-based-devices) or the same instructions [in this video](https://youtu.be/XMBs51zkD7k) (captions with auto translations are available if English isn't your primary language), and reply with the results for RTL+.
<br>

## Magenta TV
The same as the previous app, this app is not available in my region so I'm going to need your help.  This shortcut was last updated in Firemote version [v2.1.9](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.9) released on Apr 28, 2023 for issue #81.  I assume you have a newer version installed, but if you don't, then please update.

The next thing to check is your settings.  Looking at the [current launcher commands](https://github.com/PRProd/HA-Firemote/blob/v3.4.12/dist/launcher-buttons.js#L3100-L3123) for this app, I see that there is a different command being used for Amazon Fire devices than with other Android based devices.  Your request states that you are using a **Fire TV Stick 4k Max (2023)**, is that how you have Firemote configured as well?

![image](https://github.com/user-attachments/assets/6d25c1e9-99d2-4319-89cb-524a34961ea3)

If you are up to date and you've confirmed that your settings are correct, then I will need you to do the same procedure mentioned above.  Please follow the instructions [listed here](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-fire-tv-chromecast-nvidia-shield-xiaomi-mi-and-other-android-based-devices) or the same instructions [in this video](https://youtu.be/XMBs51zkD7k) (captions with auto translations are available if English isn't your primary language), and reply with the results for Magenta TV.
<br>

I look forward to hearing from you soon.  Thanks!

-Doug

**Comment by FranknStone** [comment]
Hello Doug,

rhank you for your response.
I tried both RTL+ entries without success.
My setting in firemote config are the same as in your screenshot.

Here are my results for these two apps from adb command:

Magenta TV:

adb_response: mSurface=Surface(name=de.telekom.magentatv.firetv/de.telekom.magentatv.androidtv.ApplicationMainActivity)/@0x656732d
  mInputMethodTarget in display# 0 Window{89e765a u0 de.telekom.magentatv.firetv/de.telekom.magentatv.androidtv.ApplicationMainActivity}

RTL+:

adb_response: mSurface=Surface(name=de.cbc.tvnow.firetv/de.rtli.everest.activity.MainActivity)/@0x1811200
  mInputMethodTarget in display# 0 Window{3888b88 u0 de.cbc.tvnow.firetv/de.rtli.everest.activity.MainActivity}

**Comment by PRProd** [comment]
@FranknStone ~

I have just published a beta Firemote version [v4.0.0b1](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.0b1) which contains the updates for each of these app launchers.  Feel free to download the beta version to try it out, or choose to wait until the next official Firemote release. I will leave this issue open until these changes are pushed to an official release. Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by FranknStone** [comment]
Hello Doug,

very good, just tried the Beta and all app launchers are working as expected.
Good work!

Frank

**Comment by PRProd** [comment]
An update for you @FranknStone ~ 

I have just published Firemote version [v4.0.0](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.0) which moves your app shortcut update requests from beta to official.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
