### ISSUE TITLE
[New App Shortcut]: Pathe Thuis

### ISSUE THREAD

**Issue by nickderks** [PRProd/HA-Firemote#476]
### App Name

Pathe Thuis

### Device Platform

Apple TV

### Required Information

source_list: 500px, App Store, Arcade, Computers, Disney+, FaceTime, Films, Foto's, GSE IPTV PRO, HBO Max, Instellingen, iPlayTV, IPTVX, Muziek, Netflix, Odido TV, Pathé Thuis, Plex, Podcasts, Prime Video, Speedtest, TV, Vevo, Vimeo, Zoek
app_id: com.hbo.hbonow

### Optional Comments

https://www.pathe-thuis.nl/over-pathe-thuis

**Comment by PRProd** [comment]
Greetings @nickderks!

I have just published a beta Firemote version [v4.0.0b2](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.0b2) which contains your app shortcut request.  Feel free to download the beta version to try it out, or you may also choose to wait until the next official Firemote release. I will leave this issue open until these changes are pushed to an official release. Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by PRProd** [comment]
An update for you @nickderks ~

Greetings !

I have just published Firemote version [v4.0.0](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.0) which moves your app shortcut request from beta to official.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
