### ISSUE TITLE
[Feature Request]: Custom Scale and lock ratio

### ISSUE THREAD

**Issue by qwerty13547** [PRProd/HA-Firemote#479]
### Feature Request

Feature: Custom ratio for the remote and then lock the ratio, so scaling remote still fit the device's ratio. 
I think App launcher 1 & 2 would be most suitable for this feature. The reason for this feature is to make it easier to make clean cards that eliminate scrolling. 

Now it is trial and error to make it fit well. As I use both Mobile, Ipad and computer and make separate dashboards for each device it take some time to fix after doing some changes.

Maybe it is something I have misses but I have looked around.

**Comment by PRProd** [comment]
@qwerty13547 ~

I don't have any immediate ideas for this yet.  I know that arranging dashboards with cards of varying sizes can get tricky, and I admit that the Firemote card can make things somewhat difficult too.

Have you had a chance to look at the latest Home Assistant versions, especially the latest release [2024.9](https://www.home-assistant.io/blog/2024/09/04/release-20249/)?  They have been making some great changes to the dashboards with the new experimental [sections](https://www.home-assistant.io/dashboards/sections/) layout option.  You should give that a try once, and see if it helps.

Let me know, I'm interested to hear if it works well for you or not.

-Doug

**Comment by PRProd** [comment]
@qwerty13547 ~

Does the "sections" view solve your layout challenges?  If so, I'd like to close this issue if that's OK.  Please let me know.
