### ISSUE TITLE
[New App Shortcut]: TiVimate and SmartTubeNext

### ISSUE THREAD

**Issue by MRobi1** [PRProd/HA-Firemote#48]
### App Name

TiviMate and SmartTubeNext

### Can this app be freely downloaded through official means?

- [X] Yes

### Optional Comments

TiViMate: ar.tvplayer.tv
SmartTube Stable: com.teamsmart.videomanager.tv
SmartTube Beta: com.liskovsoft.smarttubetv.beta

TiViMate is readily available through Playstore

SmartTube is sideloaded so may be rejected, but is also a massive open-sourced project so I figured I'd ask
https://github.com/yuliskov/SmartTubeNext

EDIT:
Thinking out loud here since there seems to be a few requests for sideloaded apps....
What about a "User Defined" field which would allow a user to manually enter the displayed app name, the android app name (ie: com.liskovsoft.smarttubetv.beta) and also the ADB command to launch it?
This would put the responsibility onto the user instead of having a user potentially load a malicious app due to seeing it in this package? It would also give users the ability to add an app while they wait for official compatibility.

**Comment by PRProd** [comment]
These are available for testing in the latest beta: [beta 3](https://github.com/PRProd/HA-Firemote/releases/tag/v2.0.0-beta3)

**Comment by MRobi1** [comment]
Confirmed both working. Thank you!

**Comment by PRProd** [comment]
These app shortcuts now exist in the  [newest official release: v2.0.0](https://github.com/PRProd/HA-Firemote/releases/tag/v2.0.0)  

Enjoy!

Join the discussion #52

**Comment by PRProd** [comment]
New release [v2.1.1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.1) is now available for download which includes the missing Smart Tube Next Beta button from the original request.  Enjoy!
