### ISSUE TITLE
[Feature Request]: Add remote control color options for Chromecast remotes

### ISSUE THREAD

**Issue by Valdorama** [PRProd/HA-Firemote#480]
### Feature Request

Request is to allow the colour of the Chromecast remotes (and perhaps others) to be specified (rather than having the single white colour).

When you have multiple Chromecast remotes displayed on a page (for multiple devices) it would be great to be able to easily differentiate them. I know that we can specify a display name at the top or bottom, but being able to change the colour of the whole remote itself would be visually more immediate. 

The options could be restricted to the existing set of actual Chromecast colours i.e. white (or off-white), light grey, light pink, light blue.

**Comment by PRProd** [comment]
Greetings @Valdorama!

Thank you for letting me know about these options!  I wasn't aware that they existed!  I did a quick image search, but I was only able to find three colors:

**Sky** (light blue), **Sunrise** (light pink), and **Snow** (white/off-white).

![image](https://github.com/user-attachments/assets/a17c577e-377b-4dd0-afe9-1327bb8e4271)

Do you have any sort of reference image I can look at for a light grey style next to a white one?

**Comment by Valdorama** [comment]
@PRProd Wow, yeah that looks fantastic!

**Comment by PRProd** [comment]
Excellent!  It will be included in the next version!  😄

**Comment by PRProd** [comment]
Good news @Valdorama!

I have just published Firemote beta version [v4.0.4b1](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.4b1).  This beta version has the new Chromecast remote colors included.  Please try them out, and let me know if you find any problems.

![image](https://github.com/user-attachments/assets/d1305637-782d-4b69-af22-8591d69ad258)

Thanks!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by Valdorama** [comment]
@PRProd Yeah, that's perfect. Thanks again....

![image](https://github.com/user-attachments/assets/7fd8a291-8edd-4e3b-8856-c80e64fb3939)

**Comment by PRProd** [comment]
Excellent!  I'm glad to hear it @Valdorama!

I'll keep this issue open until these changes are pushed into the official (non beta) version of Firemote.  I'm waiting on some testing for issue #293 before I push the changes.  Feel free to keep using the beta!  Enjoy!

-Doug

**Comment by PRProd** [comment]
Good news @Valdorama!

I have just published Firemote version [v4.0.4](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.4) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
