### ISSUE TITLE
[New App Shortcut]: Claro Tv Mais

### ISSUE THREAD

**Issue by leoguerran** [PRProd/HA-Firemote#481]
### App Name

Claro TV Mais

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

~~https://play.google.com/store/apps/details?id=br.com.netcombo.now&hl=pt_BR&pli=1~~
EDIT @PRProd: https://www.apkmirror.com/apk/claro-brasil/claro-tv-android-tv/claro-tv-android-tv-1-41-0-0-release/claro-tv-android-tv-1-41-0-0-android-apk-download/

### Required Information

adb_response: mSurface=Surface(name=br.com.claro.now.smarttvclient/tv.threess.threeready.ui.generic.activity.MainActivity)/@0xa7c8a7e
      mSurface=Surface(name=)/@0xe985d79
  mCurrentFocus=Window{936352c u0 br.com.claro.now.smarttvclient/tv.threess.threeready.ui.generic.activity.MainActivity}
  mFocusedApp=AppWindowToken{d45b922 token=Token{f7de6ed ActivityRecord{3645104 u0 br.com.claro.now.smarttvclient/tv.threess.threeready.ui.generic.activity.MainActivity t637}}}

**Comment by PRProd** [comment]
Greetings @leoguerran!

I have just published a beta Firemote version [v4.0.0b4](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.0b4) which contains your app shortcut request.  Feel free to download the beta version to try it out, or choose to wait until the next official Firemote release.  I will leave this issue open until these changes are pushed to an official release.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by leoguerran** [comment]
Greetings @PRProd !

Thank you very much!

**Comment by PRProd** [comment]
You're very welcome, @leoguerran!

I have just published Firemote version [v4.0.0](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.0) which moves your app shortcut request from beta to official.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
