### ISSUE TITLE
[New App Shortcut]: BabyTV

### ISSUE THREAD

**Issue by adamlc** [PRProd/HA-Firemote#482]
### App Name

BabyTV

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://www.amazon.co.uk/The-Walt-Disney-Company-Limited/dp/B0CR4DMRZ3

### Required Information

mSurface=Surface(name=)/@0xa895162
      mSurface=Surface(name=com.appbabytvvideo/com.applicaster.ui.activities.MainActivity)/@0xd88d6a7
  mCurrentFocus=Window{44f5e7d u0 com.appbabytvvideo/com.applicaster.ui.activities.MainActivity}
  mFocusedApp=AppWindowToken{e2b6ebb token=Token{162ff4a ActivityRecord{1594cb5 u0 com.appbabytvvideo/com.applicaster.ui.activities.MainActivity t112}}}

**Comment by PRProd** [comment]
Greetings @adamlc!

I have just published a beta Firemote version [v4.0.0b4](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.0b4) which contains your app shortcut request.  Feel free to download the beta version to try it out, or choose to wait until the next official Firemote release.  I will leave this issue open until these changes are pushed to an official release.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by PRProd** [comment]
An update for you @adamlc 

Greetings !

I have just published Firemote version [v4.0.0](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.0) which moves your app shortcut request from beta to official.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by adamlc** [comment]
Working perfectly, thank you!
