### ISSUE TITLE
[New App Shortcut]: Sky News, IpVanish, Now TV 

### ISSUE THREAD

**Issue by 80081** [PRProd/HA-Firemote#49]
### App Name

Sky News, IpVanish, Now TV

### Can this app be freely downloaded through official means?

- [X] Yes

**Comment by PRProd** [comment]
@80081 - Thanks for your requests!  Sky News and IPVanish will be good to go, but I'm having some troubles downloading Now TV in my country (US).  In order to keep this request moving for you, could you do me a favor and provide some additional information for the New TV app?

Simply [follow the instructions listed here](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests) and reply appropriately to this issue: https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests  

Thanks!

**Comment by PRProd** [comment]
@80081 -  [A new beta version](https://github.com/PRProd/HA-Firemote/releases/tag/v2.0.0-beta3) is available for testing, which includes 2 of the 3 app shortcuts that you requested.

If you'd like to test it out as a beta tester, feel free to join us over at discussion #47.  We'd love to have you!  Looking forward to hearing back about the "Now TV" question.

**Comment by PRProd** [comment]
Two of the three apps exist now in the  [newest release: v2.0.0](https://github.com/PRProd/HA-Firemote/releases/tag/v2.0.0)  I'll keep this issue open until I hear back from you about the "Now TV" questions I had.

Enjoy!

Join the discussion #52

**Comment by PRProd** [comment]
@80081 - Are you still with me?

**Comment by 80081** [comment]
Sorry buddy, I had a notification a few days ago but I clearly didn't read past the first few lines, I thought it was just letting me know there was a new version.

Output for Now TV

```
mSurface=Surface(name=com.bskyb.nowtv.beta/sky.wrapper.tv.AmazonMainActivity)
      mSurface=Surface(name=SurfaceView)
  mCurrentFocus=Window{28d2dcf5 u0 com.bskyb.nowtv.beta/sky.wrapper.tv.AmazonMainActivity}
  mFocusedApp=AppWindowToken{1f3c576b token=Token{19d85cba ActivityRecord{3a5cf9e5 u0 com.bskyb.nowtv.beta/sky.wrapper.tv.AmazonMainActivity t4602}}}
```

**Comment by 80081** [comment]
Is there a way to pass additional parameters to, i.e in the case of IPVanish to open the app and connect to a VPN as well.

**Comment by PRProd** [comment]
Preforming additional tasks like that inside of an app is sometimes possible.  It mostly depends on how the app was built.  I'll do some digging to see if I can extract a working command for opening and connecting.

**Comment by PRProd** [comment]
@80081 - Re: Now TV 
### **_Are you using an Amazon Fire device by any chance_**?  

Two things stand out with the data that you sent me.  One is the presence of the word "Amazon" and the other is the presence of the word "beta".

It's fine if you are just using this on a Fire device, BUT if you ALSO have other android tv devices such as the NVIDIA Shield, or the Xiaomi Mi Box, I'd love to see a data dump from those as well.

As far as the word "beta" is concerned, it would just mean that we most likely will have to re-visit this topic later when Now TV's app is out of beta.

**Comment by PRProd** [comment]
@80081 - My apologies, I neglected to mention that the "Now TV" launch button is available in the latest release.  Please test it out and let me know if it does what you expect it to do.  Thanks.

**Comment by PRProd** [comment]
@80081 - I looked into your request for automatically connecting when launching the IP Vanish app, but I was unable to make anything work.  I will keep this in the back of my mind just in case something comes up later.  My apologies.
