### ISSUE TITLE
[New App Shortcut]: Apollo Group TV

### ISSUE THREAD

**Issue by yjamal01** [PRProd/HA-Firemote#491]
### App Name

Apollo Group TV

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

downloader code: 299336

### Required Information

adb_response: mSurface=Surface(name=tv.apollogroup.androidtv/io.nitrix.tvprofiles.ui.activity.ProfileActivity)/@0xa3e24be
  mCurrentFocus=Window{9cf1ed4 u0 tv.apollogroup.androidtv/io.nitrix.tvprofiles.ui.activity.ProfileActivity}
  mFocusedApp=AppWindowToken{d24843c token=Token{89ee62f ActivityRecord{a6c9c0e u0 tv.apollogroup.androidtv/io.nitrix.tvprofiles.ui.activity.ProfileActivity t399}}}

**Comment by PRProd** [comment]
Good news @yjamal01!

I have just published Firemote version [v4.0.0](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.0) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
