### ISSUE TITLE
[New App Shortcut]: Odeon

### ISSUE THREAD

**Issue by enazevedo** [PRProd/HA-Firemote#492]
### App Name

Odeon

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://odeon.app/

### Required Information

adb_response: mSurface=Surface(name=com.tv.odeon/com.tv.odeon.ui.profile.ProfileSelectionActivity)/@0xbecae78
  mInputMethodTarget in display# 0 Window{6512a4 u0 com.tv.odeon/com.tv.odeon.ui.profile.ProfileSelectionActivity}

### Optional Comments

Odeon app is a third party app for streaming

PS: Thanks for this amazing card and work!

**Comment by PRProd** [comment]
Good news @enazevedo!

I have just published Firemote version [v4.0.1](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.1) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
