### ISSUE TITLE
[New App Shortcut]: WNBA

### ISSUE THREAD

**Issue by pdanders11** [PRProd/HA-Firemote#496]
### App Name

WNBA

### Device Platform

Roku

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.wnba.centercourt

### Required Information

app_id: 669757
app_name: WNBA - Live Games & Scores
source: WNBA - Live Games & Scores

### Optional Comments

Caitlin Clark from deep!!!

**Comment by pdanders11** [comment]
https://channelstore.roku.com/details/5f9a7b940fae28acf735ebbb86cb057d/wnba-live-games-and-scores

**Comment by PRProd** [comment]
Greetings @pdanders11!

I have just published Firemote version [v4.0.3](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.3) which contains your app shortcut request.  Enjoy!

-Doug
***
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
