### ISSUE TITLE
[New App Shortcut]: Bally Sports

### ISSUE THREAD

**Issue by pdanders11** [PRProd/HA-Firemote#498]
### App Name

Bally Sports

### Device Platform

Roku

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.foxsports.videogo

### Required Information

app_id: 285486
app_name: Bally Sports
source: Bally Sports

### Optional Comments

Thank you!  I hope I did this right!

**Comment by pdanders11** [comment]
Didn't realize there was a Roku store

https://channelstore.roku.com/details/28f9ccfd17ecb42e9815fc15826f5762/bally-sports

**Comment by PRProd** [comment]
Greetings @pdanders11!

Go MN Wild! 🏒 

I have just published Firemote version [v4.0.3](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.3) which contains your app shortcut request.  Enjoy!

-Doug
***
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
