### ISSUE TITLE
[New App Shortcut]: VTM GO (BE) &  Streamz (BE) & VRT MAX (BE)  (Nvidia Shield)

### ISSUE THREAD

**Issue by jrspowers** [PRProd/HA-Firemote#50]
### App Name

VTM GO (BE) &  Streamz (BE) & VRT MAX (BE) 

### Can this app be freely downloaded through official means?

- [X] Yes

### Optional Comments

VTM GO (BE): be.vmma.vtm.zenderapp

Streamz (BE): be.dpgmedia.streamz

VRT MAX (BE): be.vrt.vrtnu

~Youtube: YouTube~

**Comment by PRProd** [comment]
These are available for testing in the latest beta: [beta 3](https://github.com/PRProd/HA-Firemote/releases/tag/v2.0.0-beta3)

**Comment by jrspowers** [comment]
i don't see these apps i beta 3 ?

**Comment by jrspowers** [comment]
after downloading again the beta 3 works now test !

**Comment by PRProd** [comment]
These new apps are now in the  [newest official release: v2.0.0](https://github.com/PRProd/HA-Firemote/releases/tag/v2.0.0)  

Enjoy!

Join the discussion #52
