### ISSUE TITLE
[Feature Request]: Play Pause Toggle

### ISSUE THREAD

**Issue by ChristopherJacob** [PRProd/HA-Firemote#502]
### Feature Request

Would it be possible (and perhaps it already is with some helpers) to have the playpause_button switch back and forth? So the first time it's pressed is pauses, and the second time it plays?

**Comment by PRProd** [comment]
@ChristopherJacob ~

It should do that already by default.  Are you trying this with button overrides?  If so, you'll need to write a script.  If not, can you tell me what device you are trying to control, and send me a copy of your Firemote YAML?

-Doug

**Comment by ChristopherJacob** [comment]
lol - you are too fast for me. Came back to say "Duh, test before you past." All good, and works amazingly. Thanks!
