### ISSUE TITLE
[Feature Request]: entity_picture as Background

### ISSUE THREAD

**Issue by duczz** [PRProd/HA-Firemote#503]
### Is your feature request related to a problem?

nope

### Feature Request

It would be great when you can add a function to add the "entity_picture" live Picture from the integration as the Background from the card, so when i make the card bigger i see directly next the Remote the actual live picture

**Comment by PRProd** [comment]
Greetings @duczz!

That functionality has been introduced in [a different repo](https://github.com/berkansezer77/home-assistant?tab=readme-ov-file#-home-assistant-tv-card) by @berkansezer77 called [Home Assistant TV Card](https://github.com/berkansezer77/home-assistant/tree/main/custom-cards/tv-card)

Take a look at [this post in the Home Assistant Community Forum](https://community.home-assistant.io/t/home-assistant-tv-card/695732) for an excellent description of how it all works, as well as [this YouTube Short](https://www.youtube.com/shorts/t7Np3HeVlt0) that demonstrates some of its abilities.

At this time, I don't have any plans to add that type of functionality to Firemote directly, unless there is something different or better that someone would request of me.  I could be convinced to change my mind, but @berkansezer77's work looks awesome, and I think it's exactly what you are asking for.

-Doug

**Comment by duczz** [comment]
Thanks for reply, thanks for this info, that looks good, i will test it :)

**Comment by PRProd** [comment]
You're welcome, @duczz!  I'm happy to help! 😄
