### ISSUE TITLE
[New App Shortcut]: DirecTV (not DirecTV Stream)

### ISSUE THREAD

**Issue by thchewningcofc** [PRProd/HA-Firemote#504]
### App Name

DirecTV

### Device Platform

Amazon Fire

### Required Information

[IDIRECTV APP](https://www.amazon.com/AT-T-Services-Inc-DIRECTV/dp/B01J62Q632/ref=sr_1_1?dib=eyJ2IjoiMSJ9.53W1qrc7WfGpO9lSCBBXIg.yjskXU8KFb0Mq9G4LaXFRgZl3X5fxRIGTfrdBwL04L8&dib_tag=se&qid=1725755248&refinements=p_4%3ADIRECTV&s=mobile-apps&search-type=ss&sr=1-1)

**Comment by thchewningcofc** [comment]
Nevermind. Its working using the DirecTV Stream now.  This is freaking awesome.  Thanks!

**Comment by thchewningcofc** [comment]
Nevermind. Its working using the DirecTV Stream now. This is freaking awesome. Thanks!

**Comment by PRProd** [comment]
Glad you like it!!
