### ISSUE TITLE
[New App Shortcut]: KPN iTV for Android TV

### ISSUE THREAD

**Issue by jfeltges** [PRProd/HA-Firemote#506]
### App Name

KPN iTV

### Device Platform

Chromecast

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details/KPN_iTV_voor_Android_TV?id=com.kpn.kpnandroidtv&hl=nl&pli=1

### Required Information

adb_response: mSurface=Surface(name=com.kpn.kpnandroidtv/com.twentyfouri.tvbridge.webview.view.WebViewActivity)/@0x744f23f
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x5a0735b

**Comment by PRProd** [comment]
Greetings @jfeltges!

Congratulations on opening your first issue! 🎉 

I have just published Firemote version [v4.0.5](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.5) which contains your app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
