### ISSUE TITLE
Device selection assumes remote version

### ISSUE THREAD

**Issue by AeliusSaionji** [PRProd/HA-Firemote#51]
### Describe the bug

Hello-

I have a Fire TV Stick 3rd Gen with 3rd Gen remote.
The visual config selector only gives me the option to use a 2nd gen remote, without any shortcuts.

Product page for the "supported" 3rd gen stick using 2nd gen remote https://www.amazon.com/dp/B07ZZVX1F2
![image](https://user-images.githubusercontent.com/4342746/226255471-fe78382e-fa21-4491-8437-28220d430fcc.png)

The same stick but newer 3rd gen remote:
https://www.amazon.com/dp/B08C1W5N87
![image](https://user-images.githubusercontent.com/4342746/226255578-922093f1-15c7-4173-9d06-a156569e750f.png)

And, as the specs table indicates, the remote generations are compatible with a variety of models.

There should be more flexibility in allowing the users to choose whichever remote style is supported for their device - particularly when extra buttons are on the line :)

Thanks!

### To Reproduce

N/A

### Expected Behavior

N/A

### Which Fire TV Device do you own?

3rd Gen 2020 Fire TV Stick
3rd Gen Alexa Voice Remote

**Comment by AeliusSaionji** [comment]
As the table of support indicates, the 3rd gen remote supports the 4K max and 3rd gen 1080p stick.

I selected 4k max as my device, then played around with the compatibility mode and found `event4` worked on my 3rd gen stick- extra buttons and all.

I wonder if the event types correspond to remote+device pairings.

**Comment by PRProd** [comment]
This functionality exists now in the  [newest release: v2.0.0](https://github.com/PRProd/HA-Firemote/releases/tag/v2.0.0)  

Enjoy!

Join the discussion #52
