### ISSUE TITLE
[New App Shortcut]: ICI TOU.TV

### ISSUE THREAD

**Issue by Emilef22** [PRProd/HA-Firemote#512]
### App Name

ICI TOU.TV

### Device Platform

Apple TV

### Required Information

App Store, Arcade, Balados, CBC Gem, CBC News, Crave, Disney+, En forme, FaceTime, Films, ICI TOU.TV, Musique, Netflix, Noovo, Ordinateurs, Photos, Prime Video, Recherche, Réglages, TV, Télé-Québec, YouTube, Émissions

### Optional Comments

thanks!

**Comment by PRProd** [comment]
Greetings @Emilef22!

I have just published Firemote beta version [v4.1.0b2](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.0b2) which contains your app shortcut request.  Feel free to download and test this beta version, or you may also wait until it's officially released.  I will leave this issue open until this app has been pushed into the official version.

Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by PRProd** [comment]
@Emilef22 ~

An update for you: I have just published Firemote version [v4.1.0](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.0) which contains your app shortcut request.

-Doug
