### ISSUE TITLE
[Feature Request]: Add support for Roku volume

### ISSUE THREAD

**Issue by NightHawkATL** [PRProd/HA-Firemote#516]
### Is your feature request related to a problem?

Not a problem, just missing since the buttons are on the side of the remote.

### Feature Request

I would like to have the option to also control the volume for Roku TVs as it is on the TCL remotes and other Roku devices that support ARC over HDMI. Even if it was a side view of the remote that is added as an option would be a nice feature.
![image](https://github.com/user-attachments/assets/a54d39ae-8dac-4512-8492-01c4c0d43adf)

**Comment by PRProd** [comment]
Greetings @NightHawkATL!

Good news!  That feature already exists!  Volume buttons are included in the list of functions at the bottom of the App Launch Button drop-down menus.

![Roku Function Options](https://github.com/user-attachments/assets/784084b6-6807-4848-8ed7-6329cb97961a)
<br>

Simply select the volume buttons from the menu like this 

![UI Setup Example](https://github.com/user-attachments/assets/c56106dc-f3cb-4bd7-9e93-3cec6835b913)

or like this

```yaml
app_launch_5: function-volume-down
app_launch_6: function-volume-up
```

And they will appear on your remote like this!

![image](https://github.com/user-attachments/assets/f3d7bbb6-e975-4271-863b-3e1b704e7a49)

Enjoy!!  

-Doug

**Comment by PRProd** [comment]
No apologies needed at all @NightHawkATL!  I'm happy to help!  Plus, if others have the same question, they might run across this post and find it helpful too!  😄
