### ISSUE TITLE
[New App Shortcut]: Sky Go

### ISSUE THREAD

**Issue by schweppy** [PRProd/HA-Firemote#518]
### App Name

Sky Go

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/gb/app/sky-go/id446086440

### Required Information

source_list:
  - "App\_Store"
  - Arcade
  - BBC iPlayer
  - Channel 4
  - Computers
  - Disney+
  - Fitness
  - ITVX
  - Movies
  - Music
  - My5
  - Netflix
  - Photos
  - Plex
  - Podcasts
  - Prime Video
  - Search
  - SecuritySpy
  - Settings
  - Sky Go
  - Speedtest
  - Spotify
  - Trailers
  - TV
  - TV Shows
  - YouTube

### Optional Comments

Thanks

**Comment by PRProd** [comment]
Greetings @schweppy!

I have just published Firemote beta version [v4.1.0b2](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.0b2) which contains your app shortcut request.  Feel free to download and test this beta version, or you may also wait until it's officially released.  I will leave this issue open until this app has been pushed into the official version.

Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by PRProd** [comment]
@schweppy

An update for you: I have just published Firemote version [v4.1.0](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.0) which contains your app shortcut request.

-Doug
