### ISSUE TITLE
[New App Shortcut]: Waipu.tv 

### ISSUE THREAD

**Issue by marchein** [PRProd/HA-Firemote#522]
### App Name

Waiput.tv

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/de/app/waipu-tv-live-tv-streaming/id1119988075

### Required Information

source_list: App Store, Arcade, ARD Mediathek, Asphalt 8, Computer, Das Erste, Developer, Dyn Sport Live & auf Abruf, Einstellungen, FaceTime, Filme, Fitness, Fotos, Joyn, kabel eins, kabel eins Doku, Mensaplan, Musik, Netflix, Podcasts, Prime Video, ProSieben, ProSieben MAXX, Real Racing 3, RetroArch, Riptide GP: Renegade, Rocket Beans TV, RTL+, SAT.1, SAT.1 Gold, sixx, Speedtest, Spotify, SR Mediathek, Steam Link, Suchen, Tagesschau, TestFlight, Tiny Wings, TV, TV Pro, TV-Sendungen, Twitch, waipu.tv, WELT Nachrichtensender, YouTube, ZDFmediathek, Zwift
app_id: de.exaring.waipu
app_name: waipu.tv

**Comment by PRProd** [comment]
Greetings @marchein!

I have just published Firemote beta version [v4.1.0b3](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.0b3) which contains your app shortcut request.  Feel free to download and test this beta version, or you may also wait until it's officially released.  I will leave this issue open until this app has been pushed into the official version.

Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by marchein** [comment]
Just loaded the latest beta, works like a charm.

Thank you very much!

**Comment by PRProd** [comment]
@marchein

An update for you: I have just published Firemote version [v4.1.0](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.0) which contains your app shortcut request.

-Doug
