### ISSUE TITLE
Fire TV Stick prime-video button not working

### ISSUE THREAD

**Issue by Privatacc** [PRProd/HA-Firemote#523]
### Describe the bug

Hello, i have a bug, my prime-video button is not working. Every other buttons like Netflix, Youtube are working. Is there a fix?
Thank you

### To Reproduce

On_press

### Expected Behavior

App starting

### Which Type of Device Do You Own?

Raspberry Pi
Homeassistant
Firemote

**Comment by PRProd** [comment]
Hello!

Which [Amazon Fire Stick model](https://github.com/PRProd/HA-Firemote/wiki/Existing-Amazon-Devices---Support-Chart#fire-tv-streaming-media-player) do you own?  I want to try to reproduce the issue in my lab.

-Doug

**Comment by Privatacc** [comment]
Hey, thanks for the quick reply!

I have the Amazon Fire TV Stick Lite (2021)

**Comment by PRProd** [comment]
No problem, @Privatacc!  I'll get mine connected and have a look.

**Comment by PRProd** [comment]
Good news @Privatacc!

I have just published Firemote beta version [v4.1.0b4](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.0b4) which contains the update to the Prime Video launcher button command.  Feel free to download and test this beta version, or you may also wait until it's officially released.  I will leave this issue open until this app has been pushed into the official version.

Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by Privatacc** [comment]
It works! Thank you so much!

Have a nice day.

**Comment by PRProd** [comment]
I'm always happy to help!  Thank you for reporting it @Privatacc!

It can get tricky to maintain [nearly 300 app launcher buttons](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers) across 8 different device platforms, especially when app developers are constantly improving and changing their stuff.  Things change, and we must adapt.  😄

**Comment by PRProd** [comment]
@Jonny-T-cyber ~

This issue is solved in the latest beta release as mentioned above.  Please download and install [v4.1.0b4](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.0b4), and the issue will go away.

Thanks for your patience.

-Doug

**Comment by PRProd** [comment]
@Privatacc & @Jonny-T-cyber 

An update for you: I have just published Firemote version [v4.1.0](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.0) which puts this fix into the offical release.

-Doug
