### ISSUE TITLE
[New App Shortcut]: Clipious

### ISSUE THREAD

**Issue by Handrail9** [PRProd/HA-Firemote#526]
### App Name

Clipious

### Device Platform

Amazon Fire, Chromecast, NVIDIA Shield, onn., Xiaomi

### App Store Link and/or URL to .apk file if sideloaded

https://github.com/lamarios/clipious
https://f-droid.org/en/packages/com.github.lamarios.clipious/

### Required Information

```
adb_response: mSurface=Surface(name=)/@0x15cd014
      mSurface=Surface(name=com.github.lamarios.clipious/com.github.lamarios.clipious.MainActivity)/@0xd97e8a
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xe1d2a0a
```

### Optional Comments

Clipious good app
It uses Invidious
Which proxies YouTube

Haiku by Handrail9

**Comment by PRProd** [comment]
Greetings @Handrail9!

Thanks for the ⭐!  I have just published Firemote version [v4.1.0](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.0) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
