### ISSUE TITLE
[New App Shortcut]: SmartTube (onn. box)

### ISSUE THREAD

**Issue by Handrail9** [PRProd/HA-Firemote#527]
### App Name

SmartTube

### Device Platform

onn.

### App Store Link and/or URL to .apk file if sideloaded

https://github.com/yuliskov/SmartTube

### Required Information

adb_response: mSurface=Surface(name=)/@0x15cd014
      mSurface=Surface(name=com.teamsmart.videomanager.tv/com.liskovsoft.smartyoutubetv2.tv.ui.browse.BrowseActivity)/@0x29d7894
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xe1d2a0a

### Optional Comments

I seem to have another small issue,
This one requires no tissues.
SmartTube shows up under FireTV
but I have an Onn, so it shows not for me!
![Screenshot_20241014_043608](https://github.com/user-attachments/assets/b2cc85b8-94df-4e7e-8289-efd5d331742d)
![Screenshot_20241014_043640](https://github.com/user-attachments/assets/16af8df1-796f-4016-b5a4-c80df6c5a60a)

Poem by Handrail9

**Comment by PRProd** [comment]
Greetings @Handrail9!

I really enjoyed your poems!  I have just published Firemote version [v4.1.0](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.0) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by Handrail9** [comment]
This is awesome! Thank you Doug, I appreciate your hard work :)

**Comment by PRProd** [comment]
You're very welcome, @Handrail9!  I'm happy to help!
