### ISSUE TITLE
[New App Shortcut]: B.TV

### ISSUE THREAD

**Issue by Kaiserjoss555** [PRProd/HA-Firemote#528]
### App Name

B.TV

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/fr/app/b-tv-par-bouygues-telecom/id739824309

### Required Information

Hi,
it will be great if you can create B.TV button for apple TV to launch the TV app in France:

https://apps.apple.com/fr/app/b-tv-par-bouygues-telecom/id739824309

Thanks a lot,

Kind regards,

José

**Comment by PRProd** [comment]
Greetings @Kaiserjoss555!

Since that App is not available for download on Apple TV in my region, I need you to follow [the procedure listed here](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-apple-tv-devices) and reply with the results.  I won't be able to complete this request without that information.

Thanks for your understanding.

-Doug

**Comment by Kaiserjoss555** [comment]
Hi Doug,

The attribute for B.tv is :

source_list:
  - 6play 360
  - AeroTV
  - Air Video HD
  - "App\_Store"
  - Arcade
  - ARTE
  - Asphalt 8
  - B.tv
  - dailymotionTV
  - Disney+
  - DS video
  - Films
  - Forme
  - france•tv
  - Infuse
  - IPTV Streamer HD
  - L'Équipe
  - Molotov
  - MrMC
  - Musique
  - myCANAL
  - NBA
  - Netflix
  - Okoo
  - OQEE by Free
  - Ordinateurs
  - Photos
  - Plex
  - Pluto TV
  - Podcasts
  - Prime Video
  - Rayman Adventures
  - Real Racing 3
  - Rechercher
  - Remote Drive for Mac
  - RMC Sport
  - RTP Play
  - Réglages
  - SPORT TV
  - "Séries\_TV"
  - TV
  - TV Streams
  - Viki
  - Vimeo
  - VLC
  - YouTube
  - YouTube Kids
app_id: com.apple.TVMusic
app_name: Musique
friendly_name: salon (2)
supported_features: 450487


Thanks

José Fernandes
________________________________
De : Doug Nelson ***@***.***>
Envoyé : lundi 14 octobre 2024 23:57
À : PRProd/HA-Firemote ***@***.***>
Cc : Kaiserjoss555 ***@***.***>; Mention ***@***.***>
Objet : Re: [PRProd/HA-Firemote] [New App Shortcut]: B.TV (Issue #528)


Greetings @Kaiserjoss555<https://github.com/Kaiserjoss555>!

Since that App is not available for download on Apple TV in my region, I need you to follow the procedure listed here<https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-apple-tv-devices> and reply with the results. I won't be able to complete this request without that information.

Thanks for your understanding.

-Doug

**Comment by PRProd** [comment]
Good news @Kaiserjoss555!

I have just published Firemote version [v4.1.1](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.1) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
