### ISSUE TITLE
[New App Shortcut]: tinyCam PRO

### ISSUE THREAD

**Issue by Strider11** [PRProd/HA-Firemote#529]
### App Name

tinyCam PRO

### Device Platform

NVIDIA Shield, onn.

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.alexvas.dvr.pro

### Required Information

adb_response: mSurface=Surface(name=com.alexvas.dvr.pro/com.alexvas.dvr.activity.LiveViewActivity)/@0x62d0354
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xbc2a429
  mInputMethodTarget in display# 0 Window{4de8f7d u0 com.alexvas.dvr.pro/com.alexvas.dvr.activity.LiveViewActivity}

**Comment by PRProd** [comment]
Greetings @Strider11!

Sorry about the delay here.  The icons I provide for Firemote need to be in SVG format, and quite often that involves some work on my end to find them and/or draw them from scratch.  The icon for this is probably the most advanced one that I've ever made, and it took quite a while.

Anyway, I have just published Firemote version [v4.1.1](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.1) which contains your app shortcut request.

Enjoy!

-Doug

![tinycam-monitor-pro (2)](https://github.com/user-attachments/assets/bab369b7-f5e2-42ad-af90-1f0112516c65)

<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by Strider11** [comment]
Thank you so much, Doug!  I'm sorry that the icon was a pain, but it looks great!

**Comment by PRProd** [comment]
You're welcome @Strider11, I'm happy to help!  It was actually kind of fun when it started to come together.
