### ISSUE TITLE
[New App Shortcut]: Surfshark VPN

### ISSUE THREAD

**Issue by augster** [PRProd/HA-Firemote#53]
### App Name

Surfshark VPN

### Device Platform

Amazon Fire(stick 4k max)

### Is this app downloadable through you device's "store" app?

- [X] Yes

**Comment by PRProd** [comment]
This app shortcut has been added to the latest release version: [v2.0.1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.0.1)

Enjoy!
