### ISSUE TITLE
[New App Shortcut]: IP Camera Viewer - IPCams

### ISSUE THREAD

**Issue by nhaun24** [PRProd/HA-Firemote#530]
### App Name

IP Camera Viewer - IPCams

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/ip-camera-viewer-ipcams/id1045600272

### Required Information

source_list: App Store, Arcade, CCTV Viewer, Computers, Disney+, ESPN, Fitness, HBO Max, Hulu, IPCams, Max, Mini Motorways, Movies, Music, Netflix, Peacock, Photos, Podcasts, Prime Video, Search, Settings, Slideshow, Spotify, TJPP3, TV, TV Shows, YouTube, YouTube TV
friendly_name: Home Theater
supported_features: 450487

**Comment by PRProd** [comment]
Greetings @nhaun24!

I have just published Firemote version [v4.1.1](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.1) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
