### ISSUE TITLE
[New App Shortcut]: PlanetaPL TV

### ISSUE THREAD

**Issue by alwa2** [PRProd/HA-Firemote#532]
### App Name

PlanetaPL TV

### Device Platform

Amazon Fire

### Required Information

mSurface=Surface(name=com.planetapl.tv.PlayerCW/com.planetapl.tv.basePlayer.MainActivity)/@0xc50ed34
    mCurrentFocus=Window{ab108ed u0 com.planetapl.tv.PlayerCW/com.planetapl.tv.basePlayer.MainActivity}
    mFocusedApp=AppWindowToken{e403e23 token=Token{6254b52 ActivityRecord{f94a3dd u0 com.planetapl.tv.PlayerCW/com.planetapl.tv.basePlayer.MainActivity t2775}}}

**Comment by PRProd** [comment]
Greetings @alwa2!

I have just published Firemote version [v4.1.1](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.1) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
