### ISSUE TITLE
[New App Shortcut]: Viki

### ISSUE THREAD

**Issue by sushimonstr** [PRProd/HA-Firemote#535]
### App Name

Viki

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/viki-asian-drama-movies-tv/id445553058

### Required Information

source_list: App Store, Arcade, CBC Gem, Citytv Video, Computers, CTV, Fitness, Global TV, Movies, Music, Photos, Plex, Podcasts, Popcorn Trailers, Prime Video, Search, Settings, Spotify, TSN, TV, TV Shows, Viki, YouTube

**Comment by PRProd** [comment]
Greetings @sushimonstr!

Congratulations on opening your first GitHub issue!  It's great to have you here!  I have just published Firemote version [v4.1.2](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.2) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

To see a complete list of all Firemote launchers visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers)
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
