### ISSUE TITLE
[New App Shortcut]: Flow app (Argentina Cable provider)

### ISSUE THREAD

**Issue by Drtatom** [PRProd/HA-Firemote#536]
### App Name

Flow

### Device Platform

onn.

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=ar.com.flow.androidtv

### Required Information

~adb_response: mSurface=Surface(name=com.google.android.apps.tv.launcherx/com.google.android.apps.tv.launcherx.home.HomeActivity)/@0x54baf2e
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x578021d~

ar.com.flow.androidtv/.base.view.BaseActivity

### Optional Comments

This is an app from an Argenine Internet and Cable provider

**Comment by PRProd** [comment]
Greetings @Drtatom!

It's great to have you here!  I have just published Firemote version [v4.1.2](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.2) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

To see a complete list of all Firemote launchers visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers)
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by Drtatom** [comment]
Thank you for including this app in the last release!!

**Comment by PRProd** [comment]
You're welcome @Drtatom!  I'm happy to help!
