### ISSUE TITLE
[New App Shortcut]: MiTele

### ISSUE THREAD

**Issue by Nebur692** [PRProd/HA-Firemote#537]
### App Name

MiTele

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.mitelelite&hl=es

### Required Information

https://www.amazon.es/Mitele-TV-online-y-carta/dp/B07YY7T5HS

### Optional Comments

This is an app from an Spain TV provider

**Comment by Nebur692** [comment]
adb_response: >-
  mSurface=Surface(name=tv.accedo.mitele_xdk/es.mediaset.apptv.ui.screenHost.ScreenHostActivity)/@0xdf33d69
    mInputMethodTarget in display# 0 Window{9f86655 u0 tv.accedo.mitele_xdk/es.mediaset.apptv.ui.screenHost.ScreenHostActivity}

**Comment by Nebur692** [comment]
Do you need more information or is what I have posted worth it?

**Comment by PRProd** [comment]
@Nebur692 ~

Sorry about the delay, I've been a busy guy.  Thank you for sending that info to me!  It was enough to get me pointed in the right direction.  I should have an update for you shortly.

-Doug

**Comment by PRProd** [comment]
@Nebur692 ~

I have just published Firemote version [v4.1.2](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.2) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

To see a complete list of all Firemote launchers visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers)
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
