### ISSUE TITLE
[New App Shortcut]: NOW TV for Roku

### ISSUE THREAD

**Issue by kenh748** [PRProd/HA-Firemote#539]
### App Name

NOW TV

### Device Platform

Roku

### Required Information

app_id: "20242"
app_name: NOW
source: NOW

**Comment by PRProd** [comment]
Greetings @kenh748!

Congratulations on opening your first GitHub issue!  I have just published Firemote version [v4.1.2](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.2) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

To see a complete list of all Firemote launchers visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers)
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
