### ISSUE TITLE
[New App Shortcut]: Sky Sport Now

### ISSUE THREAD

**Issue by nzadrian** [PRProd/HA-Firemote#541]
### App Name

Sky Sport Now,

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/nz/app/sky-sport-now/id941399309?platform=appleTV

### Required Information

source_list: Amazing Aquarium, App Store, Arcade, AroVision, Beamafilm, Computers, Disney+, Doc Edge, DocPlay, FaceTime, Fantastic Fireplace, Fitness, Kanopy, Movies, Music, MĀORI+, Netflix, Photos, Plex, Podcasts, Prime Video, Search, Settings, Sky Sport Now, Spotify, ThreeNow, TV, TVNZ+, Vimeo, VLC, WaterBear, YouTube

**Comment by PRProd** [comment]
Greetings @nzadrian!

I have just published Firemote version [v4.1.2](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.2) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

To see a complete list of all Firemote launchers visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers)
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
