### ISSUE TITLE
[New App Shortcut]: 12+

### ISSUE THREAD

**Issue by alexboch321** [PRProd/HA-Firemote#542]
### App Name

12+

### Device Platform

NVIDIA Shield

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.keshet.mako.VOD&pcampaignid=web_share

### Required Information

mSurface=Surface(name=com.keshet.mako.VODAndroidTV/com.keshet.mako.VODAndroidTV.controller.activitiesAndFragments.Activities.MainActivity)/@0x6940031
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x4af02ec
  mInputMethodTarget in display# 0 Window{6c2f2a9 u0 com.keshet.mako.VODAndroidTV/com.keshet.mako.VODAndroidTV.controller.activitiesAndFragments.Activities.MainActivity}

**Comment by PRProd** [comment]
Greetings @alexboch321!

Welcome to GitHub and to Firemote!  It's great to have you here!  I have just published Firemote version [v4.1.2](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.2) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

To see a complete list of all Firemote launchers visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers)
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
