### ISSUE TITLE
[New App Shortcut]: Skylink SK

### ISSUE THREAD

**Issue by rirac** [PRProd/HA-Firemote#543]
### App Name

Skylink SK

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/sk/app/skylink-live-tv-sk/id1009300512?l=sk&platform=appleTV

### Required Information

source_list: App Store, Arcade, Computers, Disney+, FaceTime, JustWatchTV, Max, Moonlight, Movies, Music, Netflix, Photos, Plex, Podcasts, rtvs, Search, Settings, Skylink SK, Spotify, TV, YouTube

**Comment by PRProd** [comment]
Greetings @rirac!

It's nice to have you here!  I have just published Firemote version [v4.1.2](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.2) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

To see a complete list of all Firemote launchers visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers)
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by rirac** [comment]
Hello. I can confirm it is working. Thanks!

**Comment by PRProd** [comment]
That's great to hear, @rirac!
