### ISSUE TITLE
Add Volume Buttons for Roku TV

### ISSUE THREAD

**Issue by sedward5** [PRProd/HA-Firemote#544]
### Feature Request

Hello, love the card. I have TCL Roke TV whose volume_up volume_down and volume_mute buttons are available through the Roku HA integration. Would it be possible to add these buttons to Firemote?

Thank you so much.

**Comment by PRProd** [comment]
Greetings @sedward5!

You're in luck!  That feature already exists!  Take a look at [issue #516](https://github.com/PRProd/HA-Firemote/issues/516) for details.

If you need any help, please let me know.  I'm always happy to help.

-Doug

**Comment by sedward5** [comment]
Ugh sorry. I searched, but not thoroughly enough. Thank you for the support.

**Comment by PRProd** [comment]
No problem at all @sedward5!  I'm happy to help!
