### ISSUE TITLE
[New App Shortcut]: Smarters Pro for Apple TV

### ISSUE THREAD

**Issue by BZPJoe** [PRProd/HA-Firemote#548]
### App Name

Smarters Pro

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/smarters-pro/id6450746159

### Required Information

source_list: 10 Pin Shuffle Pro, Amazing Aquarium, Angry Birds Reloaded, App Store, Arcade, Asphalt 8+, Browser, Charrua Soccer, Cityscapes, Computers, Disney+, Doodle Jump Race, Drawful 2, EIG, ESPN, Fandango at Home, Fitness, FXNOW, hoopla, Hulu, iMovie Theater, Junkworld, KNXV, LEGO Star Wars Battles, Max, Movies, Movies Anywhere, Music, NASA, Netflix, NFL, Paramount+, Peacock, Photos, Plex, Pluto TV, Podcasts, Prime Video, Search, Settings, SG: Storm Raiders 2, ShowTix4U, SmartersPro, Speedtest, SpellStruck, Tablo, Tetris Beat, TJPP2, TJPP4, Trailers, Tubi, TV, TV Shows, TVParty, Web Video Player, Winding Worlds, YouTube, Zombie Rollerz: Pinball Heroes

### Optional Comments

Why did the Smarter Pro go to therapy?

Because it had too many "issues" to debug!

**Comment by PRProd** [comment]
Ha!

Thanks @BZPJoe!  I love it when someone puts something special in that field!

**Comment by PRProd** [comment]
Good news @BZPJoe!

I have just published Firemote version [v4.1.3](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.3) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

To see a complete list of all Firemote launchers visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers)
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by PRProd** [comment]
You're welcome!  And thank YOU for the coffee! ☕
