### ISSUE TITLE
[New App Shortcut]: BlazeTV

### ISSUE THREAD

**Issue by theharshl** [PRProd/HA-Firemote#551]
### App Name

BlazeTV

### Device Platform

Roku

### Required Information

app_id: 82559
app_name: BlazeTV
source: BlazeTV

### Optional Comments

Thank you so much for your work on this card. I think it is the best card in Home Assistant!

**Comment by PRProd** [comment]
Greetings @theharshl!

It's great to have you here!  I have just published Firemote version [v4.1.3](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.3) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

To see a complete list of all Firemote launchers visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers)
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
