### ISSUE TITLE
[New App Shortcut]: GeForce Now

### ISSUE THREAD

**Issue by Supermankal718** [PRProd/HA-Firemote#556]
### App Name

GForce Now

### Device Platform

NVIDIA Shield

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.nvidia.geforcenow&hl=en_US

### Required Information

adb_response: >-
  mSurface=Surface(name=com.nvidia.tegrazone3/com.nvidia.geforcenow.MallActivity)/@0x7e0ec76
        mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xd06127f
    mInputMethodTarget in display# 0 Window{d0ed9db u0 com.nvidia.tegrazone3/com.nvidia.geforcenow.MallActivity}

**Comment by PRProd** [comment]
Greetings @Supermankal718!

Thank you for joining us!  I have just published Firemote version [v4.1.3](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.3) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

To see a complete list of all Firemote launchers visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers)
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
