### ISSUE TITLE
[New App Shortcut]: Windscribe VPN

### ISSUE THREAD

**Issue by tejadab** [PRProd/HA-Firemote#557]
### App Name

Windscribe

### Device Platform

Amazon Fire, onn.

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.windscribe.vpn&hl=en_US

### Required Information

adb_response: mSurface=Surface(name=com.windscribe.vpn/com.windscribe.tv.windscribe.WindscribeActivity)/@0xc32474e
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x9f413fc

**Comment by PRProd** [comment]
Greetings @tejadab!

Congratulations on opening your first issue!  It's awesome to have you here!

I have just published Firemote version [v4.1.4](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.4) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

To see a complete list of all Firemote launchers visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers)
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
