### ISSUE TITLE
[New App Shortcut]: Foxtel (Australia)

### ISSUE THREAD

**Issue by karanmakhija88** [PRProd/HA-Firemote#558]
### App Name

Foxtel

### Device Platform

NVIDIA Shield

### App Store Link and/or URL to .apk file if sideloaded

~~https://play.google.com/store/apps/details?id=au.com.foxtel.Go~~
https://play.google.com/store/apps/details?id=au.com.foxtel.atv

Edit: @PRProd - correcting for Android TV version vs Mobile version

### Required Information

mSurface=Surface(name=au.com.foxtel.atv/foxtel.play.droid.atv.MainView)/@0x335671
     mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x28a9773

### Optional Comments

Would be great to have this shortcut and associated icon. Many thanks in advance

**Comment by PRProd** [comment]
Greetings @karanmakhija88!

Welcome to GitHub and the Firemote project!  Congratulations on opening your first issue as well!

I have just published Firemote version [v4.1.4](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.4) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

To see a complete list of all Firemote launchers visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers)
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by karanmakhija88** [comment]
Thank you so much for this and for providing such a great a service to the
community.

**Comment by PRProd** [comment]
I'm always happy to help!
