### ISSUE TITLE
Telenet tv app

### ISSUE THREAD

**Issue by jrspowers** [PRProd/HA-Firemote#56]
### App Name

Telenet tv

### Device Platform

NVIDIA Shield

### Is this app downloadable through you device's "store" app?

- [X] Yes

### Optional Comments

App_id: be.telenet.tv
[logo telenet tv](https://mega.nz/file/i4YnGRBT#swaZw3nvYGBQ7gDUN7mFFxL1dyP6SwbCXksPv5qPe-k)

**Comment by PRProd** [comment]
Thanks for the logo!  I beat you to it, I already found one.  :smile: You'll be able to test this shortcut in the next beta release.
![image](https://user-images.githubusercontent.com/25486599/228058430-439a8c1c-c777-482c-902f-1636f98e29f5.png)

**Comment by PRProd** [comment]
[Version 2.1.0-beta2](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.0-beta2) contains the new app shortcut, and is ready for you to test!

**Comment by jrspowers** [comment]
> [Version 2.1.0-beta2](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.0-beta2) contains the new app shortcut, and is ready for you to test!

I can proudly say that the telenet tv button works & vtm go logo looks nice now too thanks for it!

**Comment by PRProd** [comment]
Glad to hear it!
