### ISSUE TITLE
[New App Shortcut]: IP Camera Viewer - Pro

### ISSUE THREAD

**Issue by theharshl** [PRProd/HA-Firemote#560]
### App Name

IP Camera Viewer - Pro

### Device Platform

Roku

--EDIT-- added by @PRProd
https://channelstore.roku.com/details/4d75a841b5ca64054d0d577cd68aa043/ip-camera-viewer-pro

### Required Information

app_id: 143683
app_name: IP Camera Viewer - Pro
source: IP Camera Viewer - Pro

### Optional Comments

Thanks again for all your work on this card!

**Comment by PRProd** [comment]
Hello again @theharshl!

I have just published Firemote version [v4.1.4](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.4) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

To see a complete list of all Firemote launchers visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers)
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by theharshl** [comment]
Thank you so much!

**Comment by PRProd** [comment]
You're very welcome, as always @theharshl!
