### ISSUE TITLE
After months all od suddon custom element doeisnt exist

### ISSUE THREAD

**Issue by IIIdefconIII** [PRProd/HA-Firemote#562]
Hi, i used this card for months an configurared perfectly to my needs.

All of suddently i recieve an error
![image](https://github.com/user-attachments/assets/2701eea5-9dbd-49c3-b7c7-b9226c49ca36)

```
type: custom:firemote-card
entity: media_player.android_tv_10_3_10_13
device_family: nvidia-shield
device_type: shield-tv-pro-2019
compatibility_mode: default
android_tv_remote_entity: remote.shield_iiidefconiii
defaultRemoteStyle_override: ""
app_launch_1: plex
app_launch_2: youtube
app_launch_3: spotify
app_launch_4: ziggo-go
app_launch_5: kodi
visible_name_text: Shield
name_position: top
visible_name_text_color: "#ffffff"
scale: "59"
```

![image](https://github.com/user-attachments/assets/5fd1f876-252f-4858-bdc4-19c9554d7999)

Going to redownload it from hacs now brb

**Comment by IIIdefconIII** [comment]
HUH, any way i redownloaded from hacs and its working great again. sry for bothering

![image](https://github.com/user-attachments/assets/e0f11e2e-5b89-4d52-8657-33a06d75bd48)

**Comment by IIIdefconIII** [comment]
nice trick to make the card even look better:
![image](https://github.com/user-attachments/assets/2b4f2669-a5f6-4ffc-b74e-d7d244aa8b74)
```
type: custom:spotify-card-v2
card_mod:
  style: |
    ha-card {
    background: none !important;  
    border: none !important;
     }
```

**Comment by PRProd** [comment]
@IIIdefconIII ~

Greetings!  Yeah, this kind of thing happens often in many setups.  Typically it can be handled by [forcing a cache refresh](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) and is usually a result of Home Assistant somehow holding on to old data.  It's odd, but it does happen.

I'm glad you figured out a solution and got it working again!

-Doug
