### ISSUE TITLE
[New App Shortcut]: Okoo cartoons and videos

### ISSUE THREAD

**Issue by Ph4n70** [PRProd/HA-Firemote#564]
### App Name

Okoo 

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/fr/app/okoo-dessins-anim%C3%A9s-et-vid%C3%A9os/id504269555

### Required Information

source_list: Air France, App Store, Arcade, ARTE, Asphalt 8, BFMTV, Disney+, Dolby Summit, Dolby XP, FaceTime, Films, Forme, france•tv, Infuse, MUBI, Musique, myCANAL, Netflix, Okoo, OQEE by Free, Ordinateurs, Photos, Plex, Podcasts, Prime Video, Rechercher, Réglages, Speedtest, Spotify, Séries TV, TV, VLC, YouTube
friendly_name: Salon
supported_features: 150965

### Optional Comments

Just discovered your work and this is Awesome!!
Thank you so much for Firemote! Love it !

**Comment by PRProd** [comment]
Greetings @Ph4n70!

Can I ask you to correct the information you put in the **Required Information** field?  [click here](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-apple-tv-devices) to see the exact information that I'm looking for.

Thanks!

-Doug

**Comment by Ph4n70** [comment]
Hi Doug,

Thanks for your quick reply, highly appreciated ! 
I don't know how to edit the form I've fulfilled previously so I am pasting here the required information (hope this fine like this) : 
source_list: Air France, App Store, Arcade, ARTE, Asphalt 8, BFMTV, Disney+, Dolby Summit, Dolby XP, FaceTime, Films, Forme, france•tv, Infuse, MUBI, Musique, myCANAL, Netflix, Okoo, OQEE by Free, Ordinateurs, Photos, Plex, Podcasts, Prime Video, Rechercher, Réglages, Speedtest, Spotify, Séries TV, TV, VLC, YouTube
friendly_name: Salon
supported_features: 150965

**Comment by Ph4n70** [comment]
@PRProd : found how to edit !

**Comment by PRProd** [comment]
@Ph4n70,

Thanks for your help!  I have just published Firemote version [v4.1.4](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.4) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

To see a complete list of all Firemote launchers visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers)
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by Ph4n70** [comment]
Thank you so much Doug! 
You've made my day 🤩

**Comment by PRProd** [comment]
That's awesome @Ph4n70!  I'm glad to hear that!
