### ISSUE TITLE
[New App Shortcut]: IP Camera Viewer - Basic

### ISSUE THREAD

**Issue by gritting** [PRProd/HA-Firemote#567]
### App Name

IP Camera Viewer - Basic

### Device Platform

Roku

### App Store Link and/or URL to .apk file if sideloaded

https://channelstore.roku.com/en-ca/details/b0d7e5a97716f695a3c4af1abe3c33b1/ip-camera-viewer-basic

### Required Information

app_id: 143924
app_name: IP Camera Viewer - Basic
source: IP Camera Viewer - Basic

### Optional Comments

I saw the request for the pro version of this channel was included in the most recent update and figured I'd request the basic version as well for the other users like myself that only have one camera and haven't paid for the pro version. Thank you for this card, it has high family-approval factor. :)

**Comment by PRProd** [comment]
Greetings @gritting!

I have just published Firemote version [v4.1.5](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.5) which contains your app shortcut request.

Thanks for the positive note about the family approval factor!  😄

Enjoy!

-Doug
<hr>

To see a complete list of all Firemote launchers visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers)
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
