### ISSUE TITLE
[New App Shortcut]: Seasons4U

### ISSUE THREAD

**Issue by phil725** [PRProd/HA-Firemote#573]
### App Name

Seasons4U

### Device Platform

Chromecast

### App Store Link and/or URL to .apk file if sideloaded

seasons4u.com/apk09364981

### Required Information

  mSurface=Surface(name=com.android.s4u/com.android.s4u.ui.MainActivity)/@0x1bc2526
        mSurface=Surface(name=com.android.systemui.wallpapers.ImageWallpaper)/@0x5f1c971

**Comment by PRProd** [comment]
Greetings @phil725!

Congratulations on opening your first issue!  I have just published Firemote version [v4.1.5](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.5) which contains your app shortcut request.

Enjoy!

-Doug
<hr>

To see a complete list of all Firemote launchers visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers)
After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
