### ISSUE TITLE
[New App Shortcut]: Magenta TV

### ISSUE THREAD

**Issue by ChristophCaina** [PRProd/HA-Firemote#58]
### App Name

Magenta TV (German IP TV Streaming App)

### Device Platform

Android TV

### Is this app downloadable through you device's "store" app?

- [X] Yes

### Optional Comments

The Magenta TV App is an IP TV Streaming application provided by the "deutsche Telekom".
Magenta TV is part of the Internet Serivce provided by the telekom - and usually you will get a receiver from the telekom.
But it is also possible, to install the same app on any other android tv based device...
This would allow you to reduce the amount of devices, since you don't need to implement another device which is usually not possible to integrate into smarthome systems like HomeAssistant.

Link to the App: https://play.google.com/store/apps/details?id=de.telekom.magentatv.atv&gl=DE

**Comment by PRProd** [comment]
No matter what I do, I can't seem to be able to download this app for testing in my country.  (US)  I'm going to need your help.  Could you please [follow the instructions here](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests) and post the results?  The information there will help a lot.  Thanks.

**Comment by ChristophCaina** [comment]
here we go :)
but pls. remember the issue I currently have with the "emby" app ;)

```
source_list:
  - Android TV Launcher
  - Spotify
  - Prime Video
  - Google Cast
  - Magenta TV
  - Emby
  - Netflix
  - Jellyfin
  - Play Store
  - YouTube
volume_level: 1
is_volume_muted: false
adb_response: >-
  mSurface=Surface(name=de.telekom.magentatv.atv/tv.accedo.xdk.dtag.MainActivity)/@0x44539ae
        mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x242014e
hdmi_input: null
device_class: tv
entity_picture: >-
  /api/media_player_proxy/media_player.android_tv_192_168_52_73?token=a1a1dac6014c8cb9c0b5bf54651689dddfd1396ddd6d2843bad3b9d9d7e357f3&cache=1679938249.401256
friendly_name: Android TV
supported_features: 23997
```

**Comment by PRProd** [comment]
Yeah, I remember.  :smile:  We might end up having a few conversations about this, unless we get lucky and the integration just needs to be rebuilt as I suggested.

**Comment by PRProd** [comment]
[Version 2.1.0-beta2](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.0-beta2) contains the new app shortcut, and is ready for you to test!

**Comment by ChristophCaina** [comment]
no worries :)
I'll looking forward to contribute with testing :)
it's fine for me, since I can't contribute with code...

**Comment by ChristophCaina** [comment]
sorry - the same as for emby... still not working.
After removing the card completely and reinstalling it, I will try it again...

Never mind. I know that my hardware is still not supported and testing with an app that you don't get in the US might be tricky... ^^
If you want, you can provide me some further information what I could test with the adb command shell?

**Comment by PRProd** [comment]
Hmmm... this might get tricky.  Let's try a few things, and hopefully we can get somewhere like we did with emby. Let's try these launch commands to see if any of them will make Magenta TV start up:
### Developer Tools -> Services -> Android TV: ADB command
```
adb shell am start -n de.telekom.magentatv.atv/tv.accedo.xdk.dtag.MainActivity
```
```
adb shell am start -a android.intent.category.LAUNCHER -d -n de.telekom.magentatv.atv/tv.accedo.xdk.dtag.MainActivity
```
```
adb shell am start -a android.intent.category.LEANBACK_LAUNCHER -d -n de.telekom.magentatv.atv/tv.accedo.xdk.dtag.MainActivity
```
<br>

If those don't work, I'll want to see another data dump
```
adb shell dumpsys package de.telekom.magentatv.atv
```
post the response to this command which you will find under 'attributes' in the STATES tab

<br>

If the data you see there seems to contain an error or two that look like "Unable to find package: de.telekom.magentatv.atv", then I'll want you to run this command and post these results instead
```
adb shell pm list packages -f
```

**Comment by ChristophCaina** [comment]
no worries :)
I also have still several other topics on my "to integrate in HomeAssistant" list... so I can utilize the time on other projects ;)
