### ISSUE TITLE
Cannot create or change any remotes with error: Unknown entity: media_player.adb_living_room_tv

### ISSUE THREAD

**Issue by naeblis11** [PRProd/HA-Firemote#603]
### Describe the bug

Remote was working, and now just displays an error.  The entity is a good entity, media_player.adb_living_room_tv.  

The firemote UI does not even display, to be able to change this entity.  Even after deleting this remote, the error persists, and I am unable to create or change any remotes without this error coming up.

### To Reproduce

Unsure what caused the issue.  created the ADB integration for an android tv.  created a firemote pointing to this entity.  Opened  card on my phone and error appeared.  Now is on all devices.

### Expected Behavior

UI should come up

### Which Type of Device Do You Own?

Android phone, windows laptop, Sony Android TV setup for ADB

**Comment by PRProd** [comment]
Greetings @naeblis11!

>The firemote UI does not even display, to be able to change this entity. Even after deleting this remote, the error persists, and I am unable to create or change any remotes without this error coming up.

Can you help me understand this a little better?  Are you unable to access the graphical **Firemote Card configuration** menu?  If you can access that, are you able to click and view the **SHOW CODE EDITOR** button on the bottom of that screen?  If you're able to post a picture of what you see, that might help me out.

As far as troubleshooting goes, have you tried [refreshing your device cache?](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh).  This is the most likely cause of your issue if you had created the Firemote card using one device (a computer, a different phone, etc) and then tried loading your updated dashboard on your phone.  

If that didn't work, did you try uninstalling Firemote from HACS and then re-installing it?

Please let me know.  Thanks.

-Doug

**Comment by PRProd** [comment]
Greetings @naeblis11!

>The firemote UI does not even display, to be able to change this entity. Even after deleting this remote, the error persists, and I am unable to create or change any remotes without this error coming up.

Can you help me understand this a little better?  Are you unable to access the graphical **Firemote Card configuration** menu?  If you can access that, are you able to click and view the **SHOW CODE EDITOR** button on the bottom of that screen?  If you're able to post a picture of what you see, that might help me out.

As far as troubleshooting goes, have you tried [refreshing your device cache?](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh).  This is the most likely cause of your issue if you had created the Firemote card using one device (a computer, a different phone, etc) and then tried loading your updated dashboard on your phone.  

If that didn't work, did you try uninstalling Firemote from HACS and then re-installing it?

Please let me know.  Thanks.

-Doug

**Comment by naeblis11** [comment]
I was unable to get to the UI, at all.  The ADB device went 'unavailable' when this occurred, which is what I think caused it.  Once the ADB entity was available again, it started working.  I did not have to refresh cache or reinstall for it to start working again.  Restarting HA did not solve the issue.  It was only when the entity was no longer 'unavailable' that the Firemote configuration UI was able to be accessed.  I was not able to access any of the other remotes or cards I had setup when this occurred.

ADB and Firemote have been working since it became available again.

**Comment by PRProd** [comment]
Interesting... and odd.  I wonder why that happened.  I've never experienced that sort of thing when I have a device go offline.

Either way, I'm glad it's working again!
