### ISSUE TITLE
NVIDIA Shield: volume buttons don't work

### ISSUE THREAD

**Issue by alexdelprete** [PRProd/HA-Firemote#63]
### Describe the bug

The two volume buttons (+/-) don't work. I added the Mute button to test it and that one works.

Tried on NVIDIA SHIELD TV Pro 2019 and NVIDIA SHIELD TV 2019 with same results.

### To Reproduce

My configuration:

![image](https://user-images.githubusercontent.com/7027842/229224860-7474deea-4e0a-47ae-8889-c299ece30cac.png)

### Expected Behavior

Volume control when pressing the two buttons

### Which Fire TV Device do you own?

- NVIDIA Shield TV Pro 2019
- NVIDIA Shield TV 2019

**Comment by PRProd** [comment]
On your Shield device(s), under Settings -> Device Preferences -> Display & Sound -> Volume control, can you tell me what you have set up?  This specific setup works for me, (but the volume increments might need some fixing)

![image](https://user-images.githubusercontent.com/25486599/229234780-4b2965ae-b4b4-459a-a3d0-0a17ee0532a1.png)

If you used "Setup IR", then that might mean that control via Firemote through your shield might not be possible.  Do the buttons on your physical remote control the volume of a TV or a receiver?

**Comment by alexdelprete** [comment]
I have a Samsung Q90R tv with a HW-Q90R, using eARC (finally samsung decided to release a fw with earch for the Q90R panel some months ago, after years of waiting for it).

I confirm it works with Volume Control -> CEC. :)

I thought the adb commands used for volume didn't depend on whatever setting the device is in but worked at a lower level.

The reason I don't use CEC for volume on the shield is that when using CEC I don't see the volume level number on the TV because it addresses the soundbar directly. My wife wants to see the volume level when she lowers/raises it. Via IR, I see the usual volume UI on the tv, via CEC it doesn't. I think it's a bug in the shield fw because when I reset it some months ago, I saw the volume UI on the tv with CEC, but only for a few days. I read on the nvidia forums that other users experienced the same thing.

I'll leave it with CEC for now...untile wife protests again. 😄

**Comment by PRProd** [comment]
I might have a fix for that!  Try these commands with your CEC control on.  Let me know if you see the volume control display on the TV again:
```
adb shell cmd media_session volume --show --adj raise
```
```
adb shell cmd media_session volume --show --adj lower
```

**Comment by alexdelprete** [comment]
Nope. I see the usual + symbol on the soundbar...

Those 2 are the commands used by the 2 buttons on the remote UI right?

**Comment by PRProd** [comment]
No, not yet.  

Current commands:
 - VOLUME_UP
 - VOLUME_DOWN

Proposed Commands for Shield:
 - adb shell cmd media_session volume --show --adj raise
 - adb shell cmd media_session volume --show --adj lower

**Comment by alexdelprete** [comment]
The proposed commands seem a bit quicker...but it might be just perception...

**Comment by PRProd** [comment]
They are quicker for me too.  As an added bonus, they adjust the volume one notch at a time as they should.  The current commands move the volume 4 notches at a time, which I do not like.  These new commands will be a part of the next release.

**Comment by alexdelprete** [comment]
> The current commands move the volume 4 notches at a time, which I do not like. These new commands will be a part of the next release.

Maybe there's some advanced setting for the volume step definition, but VOLUME_UP/DOWN look like sort of functions/macros that are then processed and maybe that's why they seem slower.

I agree, those 2 commands are better, but it is subjective. Can the commands be changed if a user wants to?

**Comment by PRProd** [comment]
Every button can be overridden with a HA script or just a command written into your YAML config

[Instructions are in the Readme file](https://github.com/PRProd/HA-Firemote#button-overrides)

**Comment by alexdelprete** [comment]
> into your YAML config

Maybe I overlooked something: where's the location of the yaml file? the usual /config ?
