### ISSUE TITLE
Remote no longer working, HA no longer recognizing custom:firemote-card

### ISSUE THREAD

**Issue by dfernan5** [PRProd/HA-Firemote#65]
### Describe the bug

Remote no longer working, HA no longer recognizing custom:firemote-card. Have removed and redownloaded.

### To Reproduce

Remove fireremote
Redownload fireremote,
Refresh browser
Restart HA

### Expected Behavior

Ability to use fireremote by adding card

### Which Type of Device Do You Own?

firetv cube

**Comment by wired-dev** [comment]
Same issue here

**Comment by PRProd** [comment]
Acknowledged.  The issue is with an external dependency.  I will work on a solution.

**Comment by PRProd** [comment]
...and just as soon as I published the work-around, it looks like the issue with unpkg.com has resolved itself.  Oh well, this works too.

**Comment by wired-dev** [comment]
maybe just include it as part of the release so it's not external?
