### ISSUE TITLE
[New App Shortcut]: Ott Navigator

### ISSUE THREAD

**Issue by Litus23** [PRProd/HA-Firemote#66]
### App Name

Ott Navigator

### Device Platform

Fire Cube, Google TV, Xiaomi Mi box

### Is this app downloadable through you device's "store" app?

- [X] Yes

### Optional Comments

Ott navigator is not there in the Amazon store but its owner does allow installation on Fire devices.

**Comment by PRProd** [comment]
Hello @Litus23!

This request has been completed, and is now a part of the latest official release, [v2.1.3](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.3)

Enjoy!
