### ISSUE TITLE
[New App Shortcut]: DS Video

### ISSUE THREAD

**Issue by almighty059** [PRProd/HA-Firemote#68]
### App Name

DS Video

### Device Platform

Nvidia Shield (but it is available for both)

### Is this app downloadable through you device's "store" app?

- [X] Yes

### Optional Comments

Here is the link for the app on Google Play store: [https://play.google.com/store/apps/details?id=com.synology.dsvideo](https://play.google.com/store/apps/details?id=com.synology.dsvideo)

**Comment by PRProd** [comment]
Hello @almighty059!  Thanks for your request!

This has been added to the latest version [v2.1.4](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.4) which is ready for you to download and use right away.  Enjoy!

**Comment by almighty059** [comment]
@PRProd thank you...
