### ISSUE TITLE
[New App Shortcut]: SVT Play

### ISSUE THREAD

**Issue by sweup** [PRProd/HA-Firemote#72]
### App Name

SVT Play

### Device Platform

Nvidia shield 

### Is this app downloadable through you device's "store" app?

- [X] Yes

### Optional Comments

https://www.google.com/url?q=https://play.google.com/store/apps/details%3Fid%3Dse.svt.android.svtplay%26hl%3Dsv%26gl%3DUS&sa=U&ved=2ahUKEwiKisqk86P-AhWqRPEDHUJMCXgQFnoECAkQAg&usg=AOvVaw1n9nBCs-sFrj7uIX5K1phO

**Comment by PRProd** [comment]
Hello @Martof!  Your request has been added to the latest release [v2.1.6](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.6)

Enjoy!

**Comment by Martof** [comment]
Thanks a lot Doug.
Crunchy roll works perfectly.
It seems that Oqee doesn't work.
For information on my player the app name is oqee.launcher. I don't know if
the difference is important.

Best regards

Le ven. 14 avr. 2023 à 00:13, Doug Nelson ***@***.***> a
écrit :
