### ISSUE TITLE
(New Device Support) Waipu TV Stick 

### ISSUE THREAD

**Issue by tomg1970** [PRProd/HA-Firemote#73]
Hello, is it possible to include the waipu tv stick in the integration.

This is a very successful Android tv stick

That would be very great

**Comment by PRProd** [comment]
@tomg1970 - Thanks for your request!  I'm always looking ahead to see what I should add next.  Those discussions are happening at #41.  Please add your request over there, and it will be considered for the next update.

**Comment by PRProd** [comment]
@tomg1970 - I will re-open this issue if/when I begin official support work for the Waipu TV Stick
