### ISSUE TITLE
[New App Shortcut]: Sky Sport Now (NZ)

### ISSUE THREAD

**Issue by IceyyBoi** [PRProd/HA-Firemote#79]
### App Name

Sky Sport Now

### Device Platform

Amazon Fire

### Is this app downloadable through you device's "store" app?

- [X] Yes

**Comment by PRProd** [comment]
[Version 2.1.7](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.7) contains this new app launch shortcut, and is available for download.  Please let me know right away if it doesn't work as expected.  

Enjoy!

**Comment by IceyyBoi** [comment]
Works perfectly - thank you :)
