### ISSUE TITLE
[New App Shortcut]: ABC iview

### ISSUE THREAD

**Issue by phatrickk** [PRProd/HA-Firemote#83]
### App Name

ABC iview

### Device Platform

NVIDIA Shield

### Is this app downloadable through you device's "store" app?

- [X] Yes

### Optional Comments

Australian streaming service

**Comment by phatrickk** [comment]
https://play.google.com/store/apps/details?id=au.net.abc.iview

**Comment by PRProd** [comment]
@phatrickk - Please download the latest pre-release, [Version 2.1.10-beta1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.10-beta1) of HA-Firemote and verify that the "ABC iview" app launch button is functioning as expected.  Thanks!

**Comment by phatrickk** [comment]
Confirmed that this is working, thanks.
