### ISSUE TITLE
Remotes Delayed

### ISSUE THREAD

**Issue by fin05** [PRProd/HA-Firemote#89]
I have 3 Firestick 4k max and the only way I can get the Firemote to work is to set compatiblity mode to "stronger(slower)" which causes every button stroke to have a 1 second delay. What am I doing wrong and how do I fix this?

**Comment by fin05** [comment]
That did not solve the issue.  I think maybe the firestick I have isn't compatible yet? The UPC is 840080588964. It is the firestick 4K 3rd gen. I do not see that on the list. I tried a couple different ones and ran thru all the compatibility modes and only the strong (slower) works

**Comment by PRProd** [comment]
I'm puzzled about which device you own.  From the Amazon developer documentation that I've found, the "Firestick 4K 3rd Gen" doesn't exist.  These are the models that they have listed:

![image](https://user-images.githubusercontent.com/25486599/236959942-c3812598-aa68-4d08-9ebc-969dae01748e.png)

It's possible that [their documentation](https://developer.amazon.com/docs/fire-tv/device-specifications-fire-tv-streaming-media-player.html) is out of date and a newer device exists that I haven't seen before.

If possible, can you do two things for me?
1. Paste a link to the Amazon website where I can find the device that you have
2. Go [here](https://developer.amazon.com/docs/fire-tv/device-specifications.html) and find your device, and attach a screenshot or copy/paste the official product name so I can see it.

Another possibility here is that you own the [Fire TV Stick 4K Max 1st Gen (2021)](https://github.com/PRProd/HA-Firemote/wiki/Fire-TV-Stick-4K-Max---1st-Gen-(2021)) and your experiencing the annoying remote disconnect issue that all Fire TV devices seem to have.  The way to get around that one is described in the first step of the [Why don't any of the buttons on the Firemote work at all?](https://github.com/PRProd/HA-Firemote#why-dont-any-of-the-buttons-on-the-firemote-work-at-all) section of the [FAQ](https://github.com/PRProd/HA-Firemote#faq):
> If your Firemote used to work perfectly, and some or all of the buttons suddenly stopped working, it could be that all you need to do is press one button (any button) on your Fire TV device's physical remote control. After doing that step, try your Firemote again.

If this solves the issue, then you'll need to remember that any time you power off your Firestick, you may need to complete this step again after powering it back on, or periodically at random times.  Unfortunately, there doesn't seem to be a different way around this issue yet, other than what I've described.

Good luck!

**Comment by fin05** [comment]
Here is the link where I purchased 
https://www.bestbuy.com/site/amazon-fire-tv-stick-4k-with-alexa-voice-remote-dolby-vision-hd-streaming-media-player-includes-tv-controls-black/6480937.p?skuId=6480937

Based on the link you sent it is the Fire TV Stick 4K Max - 1st Gen (2021) My apology for that - In any case it still does not work even hitting a button on the regular remote first.  the only combination of settings I can get to work is the Strong(slower) and that on all 3 firesticks I have of this model

**Comment by PRProd** [comment]
Very strange...

I just dug out my 4K Max and tested it to be sure that something didn't change with the one that I own, and it still works with Firemote.

Can you do one more test for me?  Please follow the instructions under [Device Interrogation For New Device Support](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#device-interrogation-for-new-device-support) and post the results back here.

**Comment by fin05** [comment]
Yes I do have the latest update

device_class: tv
entity_picture: /api/media_player_proxy/media_player.fire_tv_192_168_1_128?token=8d52482fc902f8db6e58d919c3ff47d7e6a4a1032ca8b9be0cc046a5eab82d3f&cache=1683677122.57351
friendly_name: Fire TV 192.168.1.128
supported_features: 22961
source: com.amazon.tv.launcher
adb_response: INPUT MANAGER (dumpsys input)

Input Manager State:
  Interactive: true
  System UI Visibility: 0x0
  Pointer Speed: 0
  Pointer Gestures Enabled: true
  Show Touches: false

Event Hub State:
  BuiltInKeyboardId: -2
  Devices:
    -1: Virtual
      Classes: 0x40000023
      Path: <virtual>
      Descriptor: a718a782d34bc767f4689c232d64d527998ea7fd:00000000
      Location: 
      ControllerNumber: 0
      UniqueId: <virtual>
      Identifier: bus=0x0000, vendor=0x0000, product=0x0000, version=0x0000
      KeyLayoutFile: /system/usr/keylayout/Generic.kl
      KeyCharacterMapFile: /system/usr/keychars/Virtual.kcm
      ConfigurationFile: 
      HaveKeyboardLayoutOverlay: false
    1: WOBLE_INPUT_DEVICE
      Classes: 0x00000001
      Path: /dev/input/event1
      Descriptor: 76d09a7d1f3b8d113bb56ed2568268f86d137837:00020002
      Location: 
      ControllerNumber: 0
      UniqueId: 
      Identifier: bus=0x0019, vendor=0x0002, product=0x0002, version=0x0002
      KeyLayoutFile: /system/usr/keylayout/Generic.kl
      KeyCharacterMapFile: /system/usr/keychars/Generic.kcm
      ConfigurationFile: 
      HaveKeyboardLayoutOverlay: false
    2: hdmipower
      Classes: 0x00000001
      Path: /dev/input/event0
      Descriptor: a917cc44911b6f32b9481384b0da35fb5f3d84d3:00000000
      Location: 
      ControllerNumber: 0
      UniqueId: 
      Identifier: bus=0x0000, vendor=0x0000, product=0x0000, version=0x0000
      KeyLayoutFile: /system/usr/keylayout/Generic.kl
      KeyCharacterMapFile: /system/usr/keychars/Generic.kcm
      ConfigurationFile: 
      HaveKeyboardLayoutOverlay: false
    3: amazon_touch
      Classes: 0x00000014
      Path: /dev/input/event2
      Descriptor: 185733e0df071e21edd860dd6224a1f9f378c689:00000000
      Location: 
      ControllerNumber: 0
      UniqueId: 
      Identifier: bus=0x0005, vendor=0x0000, product=0x0000, version=0x0008
      KeyLayoutFile: 
      KeyCharacterMapFile: 
      ConfigurationFile: /system/usr/idc/amazon_touch.idc
      HaveKeyboardLayoutOverlay: false
    4: kcmouse
      Classes: 0x80000008
      Path: /dev/input/event3
      Descriptor: 3b975ed12e4cb4357a995906d1f9c74d8457fd71:00000000
      Location: 
      ControllerNumber: 0
      UniqueId: 
      Identifier: bus=0x0005, vendor=0x0000, product=0x0000, version=0x0008
      KeyLayoutFile: 
      KeyCharacterMapFile: 
      ConfigurationFile: 
      HaveKeyboardLayoutOverlay: false

Input Reader State:
  Device -1: Virtual
    Generation: 2
    IsExternal: false
    HasMic:     false
    Sources: 0x00000301
    KeyboardType: 2
    Keyboard Input Mapper:
      Parameters:
        HasAssociatedDisplay: false
        OrientationAware: false
        HandlesKeyRepeat: false
      KeyboardType: 2
      Orientation: 0
      KeyDowns: 0 keys currently down
      MetaState: 0x0
      DownTime: 0
  Device 1: WOBLE_INPUT_DEVICE
    Generation: 6
    IsExternal: false
    HasMic:     false
    Sources: 0x00000101
    KeyboardType: 1
    Keyboard Input Mapper:
      Parameters:
        HasAssociatedDisplay: false
        OrientationAware: false
        HandlesKeyRepeat: false
      KeyboardType: 1
      Orientation: 0
      KeyDowns: 0 keys currently down
      MetaState: 0x0
      DownTime: 0
  Device 2: hdmipower
    Generation: 4
    IsExternal: false
    HasMic:     false
    Sources: 0x00000101
    KeyboardType: 1
    Keyboard Input Mapper:
      Parameters:
        HasAssociatedDisplay: false
        OrientationAware: false
        HandlesKeyRepeat: false
      KeyboardType: 1
      Orientation: 0
      KeyDowns: 0 keys currently down
      MetaState: 0x0
      DownTime: 0
  Device 3: amazon_touch
    Generation: 14
    IsExternal: false
    HasMic:     false
    Sources: 0x00001002
    KeyboardType: 0
    Motion Ranges:
      X: source=0x00001002, min=0.000, max=1919.000, flat=0.000, fuzz=0.000, resolution=0.000
      Y: source=0x00001002, min=0.000, max=1079.000, flat=0.000, fuzz=0.000, resolution=0.000
      PRESSURE: source=0x00001002, min=0.000, max=1.000, flat=0.000, fuzz=0.000, resolution=0.000
    Touch Input Mapper:
      Parameters:
        GestureMode: multi-touch
        DeviceType: touchScreen
        AssociatedDisplay: hasAssociatedDisplay=true, isExternal=false
        OrientationAware: true
      Raw Touch Axes:
        X: min=0, max=1919, flat=0, fuzz=0, resolution=0
        Y: min=0, max=1079, flat=0, fuzz=0, resolution=0
        Pressure: unknown range
        TouchMajor: unknown range
        TouchMinor: unknown range
        ToolMajor: unknown range
        ToolMinor: unknown range
        Orientation: unknown range
        Distance: unknown range
        TiltX: unknown range
        TiltY: unknown range
        TrackingId: unknown range
        Slot: unknown range
      Calibration:
        touch.size.calibration: none
        touch.size.scale: 40.000
        touch.size.bias: 0.000
        touch.size.isSummed: false
        touch.pressure.calibration: none
        touch.pressure.scale: 0.013
        touch.orientation.calibration: none
        touch.distance.calibration: none
        touch.coverage.calibration: none
      Affine Transformation:
        X scale: 1.000
        X ymix: 0.000
        X offset: 0.000
        Y xmix: 0.000
        Y scale: 1.000
        Y offset: 0.000
      Viewport: displayId=0, orientation=0, logicalFrame=[0, 0, 1920, 1080], physicalFrame=[0, 0, 3840, 2160], deviceSize=[3840, 2160]
      SurfaceWidth: 1920px
      SurfaceHeight: 1080px
      SurfaceLeft: 0
      SurfaceTop: 0
      SurfaceOrientation: 0
      Translation and Scaling Factors:
        XTranslate: 0.000
        YTranslate: 0.000
        XScale: 1.000
        YScale: 1.000
        XPrecision: 1.000
        YPrecision: 1.000
        GeometricScale: 1.000
        PressureScale: 0.000
        SizeScale: 0.000
        OrientationScale: 0.000
        DistanceScale: 0.000
        HaveTilt: false
        TiltXCenter: 0.000
        TiltXScale: 0.000
        TiltYCenter: 0.000
        TiltYScale: 0.000
      Last Raw Button State: 0x00000000
      Last Raw Touch: pointerCount=0
      Last Cooked Button State: 0x00000000
      Last Cooked Touch: pointerCount=0
      Stylus Fusion:
        ExternalStylusConnected: false
        External Stylus ID: -1
        External Stylus Data Timeout: 9223372036854775807
      External Stylus State:
        When: 9223372036854775807
        Pressure: 0.000000
        Button State: 0x00000000
        Tool Type: 0
  Device 4: kcmouse
    Generation: 15
    IsExternal: true
    HasMic:     false
    Sources: 0x00002002
    KeyboardType: 0
    Motion Ranges:
      X: source=0x00002002, min=0.000, max=1919.000, flat=0.000, fuzz=0.000, resolution=0.000
      Y: source=0x00002002, min=0.000, max=1079.000, flat=0.000, fuzz=0.000, resolution=0.000
      PRESSURE: source=0x00002002, min=0.000, max=1.000, flat=0.000, fuzz=0.000, resolution=0.000
      VSCROLL: source=0x00002002, min=-1.000, max=1.000, flat=0.000, fuzz=0.000, resolution=0.000
    Cursor Input Mapper:
      Parameters:
        HasAssociatedDisplay: true
        Mode: pointer
        OrientationAware: false
      XScale: 1.000
      YScale: 1.000
      XPrecision: 1.000
      YPrecision: 1.000
      HaveVWheel: true
      HaveHWheel: false
      VWheelScale: 1.000
      HWheelScale: 1.000
      Orientation: 0
      ButtonState: 0x00000000
      Down: false
      DownTime: 0
  Configuration:
    ExcludedDeviceNames: []
    VirtualKeyQuietTime: 0.0ms
    PointerVelocityControlParameters: scale=1.000, lowThreshold=500.000, highThreshold=3000.000, acceleration=3.000
    WheelVelocityControlParameters: scale=1.000, lowThreshold=15.000, highThreshold=50.000, acceleration=4.000
    PointerGesture:
      Enabled: true
      QuietInterval: 100.0ms
      DragMinSwitchSpeed: 50.0px/s
      TapInterval: 150.0ms
      TapDragInterval: 300.0ms
      TapSlop: 20.0px
      MultitouchSettleInterval: 100.0ms
      MultitouchMinDistance: 15.0px
      SwipeTransitionAngleCosine: 0.3
      SwipeMaxWidthRatio: 0.2
      MovementSpeedRatio: 0.8
      ZoomSpeedRatio: 0.3

Input Dispatcher State:
  DispatchEnabled: 1
  DispatchFrozen: 0
  FocusedApplication: name='AppWindowToken{fd47774 token=Token{5c15e86 ActivityRecord{65cf361 u0 com.amazon.tv.launcher/.ui.HomeActivity_vNext t106}}}', dispatchingTimeout=5000.000ms
  FocusedWindow: name='Window{c9b62a u0 Sys2023:dream}'
  TouchStates: <no displays touched>
  Windows:
    0: name='Window{f55f0b4 u0 com.amazon.vizzini}', displayId=0, paused=false, hasFocus=false, hasWallpaper=false, visible=false, canReceiveKeys=false, flags=0x01000108, type=0x000007da, layer=241005, frame=[0,0][1920,1080], scale=1.000000, touchableRegion=[0,0][1920,1080], inputFeatures=0x00000000, ownerPid=8491, ownerUid=10153, dispatchingTimeout=5000.000ms
    1: name='Window{d1365c6 u0 com.amazon.vizzini}', displayId=0, paused=false, hasFocus=false, hasWallpaper=false, visible=false, canReceiveKeys=false, flags=0x01000100, type=0x000007da, layer=241000, frame=[0,0][1920,1080], scale=1.000000, touchableRegion=[0,0][1920,1080], inputFeatures=0x00000000, ownerPid=8491, ownerUid=10153, dispatchingTimeout=5000.000ms
    2: name='Window{a7a6cad u0 KeyguardScrim}', displayId=0, paused=false, hasFocus=false, hasWallpaper=false, visible=false, canReceiveKeys=false, flags=0x01110900, type=0x000007ed, layer=141000, frame=[0,0][1920,1080], scale=1.000000, touchableRegion=[0,0][1920,1080], inputFeatures=0x00000000, ownerPid=619, ownerUid=1000, dispatchingTimeout=5000.000ms
    3: name='Window{c9b62a u0 Sys2023:dream}', displayId=0, paused=false, hasFocus=true, hasWallpaper=false, visible=true, canReceiveKeys=true, flags=0x01810581, type=0x000007e7, layer=101000, frame=[0,0][1920,1080], scale=1.000000, touchableRegion=[0,0][1920,1080], inputFeatures=0x00000000, ownerPid=14638, ownerUid=10097, dispatchingTimeout=5000.000ms
    4: name='Window{92899ad u0 com.amazon.tv.launcher/com.amazon.tv.launcher.ui.HomeActivity_vNext}', displayId=0, paused=false, hasFocus=false, hasWallpaper=false, visible=true, canReceiveKeys=true, flags=0x83810120, type=0x00000001, layer=21025, frame=[0,0][1920,1080], scale=1.000000, touchableRegion=[0,0][1920,1080], inputFeatures=0x00000000, ownerPid=9209, ownerUid=10138, dispatchingTimeout=5000.000ms
    5: name='Window{66404e u0 com.plexapp.android/com.plexapp.plex.home.tv.HomeActivityTV}', displayId=0, paused=false, hasFocus=false, hasWallpaper=false, visible=false, canReceiveKeys=false, flags=0x81810120, type=0x00000001, layer=21020, frame=[0,0][1920,1080], scale=1.000000, touchableRegion=[0,0][1920,1080], inputFeatures=0x00000000, ownerPid=14966, ownerUid=10095, dispatchingTimeout=5000.000ms
    6: name='Window{e2a3894 u0 com.teamsmart.videomanager.tv/com.liskovsoft.smartyoutubetv2.tv.ui.playback.PlaybackActivity}', displayId=0, paused=false, hasFocus=false, hasWallpaper=false, visible=false, canReceiveKeys=false, flags=0x8b8105a0, type=0x00000001, layer=21015, frame=[0,0][1920,1080], scale=1.000000, touchableRegion=[0,0][1920,1080], inputFeatures=0x00000000, ownerPid=22253, ownerUid=10196, dispatchingTimeout=5000.000ms
    7: name='Window{ede5332 u0 SurfaceView - com.teamsmart.videomanager.tv/com.liskovsoft.smartyoutubetv2.tv.ui.playback.PlaybackActivity}', displayId=0, paused=false, hasFocus=false, hasWallpaper=false, visible=false, canReceiveKeys=false, flags=0x00004218, type=0x000003e9, layer=21010, frame=[0,0][1920,1080], scale=1.000000, touchableRegion=[0,0][1920,1080], inputFeatures=0x00000000, ownerPid=22253, ownerUid=10196, dispatchingTimeout=5000.000ms
    8: name='Window{f5fd0b7 u0 com.teamsmart.videomanager.tv/com.liskovsoft.smartyoutubetv2.tv.ui.channeluploads.ChannelUploadsActivity}', displayId=0, paused=false, hasFocus=false, hasWallpaper=false, visible=false, canReceiveKeys=false, flags=0x8b8105a0, type=0x00000001, layer=21005, frame=[0,0][1920,1080], scale=1.000000, touchableRegion=[0,0][1920,1080], inputFeatures=0x00000000, ownerPid=22253, ownerUid=10196, dispatchingTimeout=5000.000ms
    9: name='Window{ca07554 u0 com.teamsmart.videomanager.tv/com.liskovsoft.smartyoutubetv2.tv.ui.browse.BrowseActivity}', displayId=0, paused=false, hasFocus=false, hasWallpaper=false, visible=false, canReceiveKeys=false, flags=0x8b8105a0, type=0x00000001, layer=21000, frame=[0,0][1920,1080], scale=1.000000, touchableRegion=[0,0][1920,1080], inputFeatures=0x00000000, ownerPid=22253, ownerUid=10196, dispatchingTimeout=5000.000ms
  MonitoringChannels:
    0: 'WindowManager (server)'
  RecentQueue: length=10
    KeyEvent, age=103591608.0ms
    KeyEvent, age=103591328.0ms
    DeviceResetEvent(deviceId=10), policyFlags=0x00000000, age=103585992.0ms
    , age=103585992.0ms
    KeyEvent, age=97612944.0ms
    KeyEvent, age=97612944.0ms
    KeyEvent, age=97609048.0ms
    KeyEvent, age=97609048.0ms
    KeyEvent, age=97607344.0ms
    KeyEvent, age=97607344.0ms
  PendingEvent: <none>
  InboundQueue: <empty>
  ReplacedKeys: <empty>
  Connections:
    0: channelName='WindowManager (server)', windowName='monitor', status=NORMAL, monitor=true, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
    1: channelName='a7a6cad KeyguardScrim (server)', windowName='Window{a7a6cad u0 KeyguardScrim}', status=NORMAL, monitor=false, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
    2: channelName='c9b62a Sys2023:dream (server)', windowName='Window{c9b62a u0 Sys2023:dream}', status=NORMAL, monitor=false, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
    3: channelName='e2a3894 com.teamsmart.videomanager.tv/com.liskovsoft.smartyoutubetv2.tv.ui.playback.PlaybackActivity (server)', windowName='Window{e2a3894 u0 com.teamsmart.videomanager.tv/com.liskovsoft.smartyoutubetv2.tv.ui.playback.PlaybackActivity}', status=NORMAL, monitor=false, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
    4: channelName='f5fd0b7 com.teamsmart.videomanager.tv/com.liskovsoft.smartyoutubetv2.tv.ui.channeluploads.ChannelUploadsActivity (server)', windowName='Window{f5fd0b7 u0 com.teamsmart.videomanager.tv/com.liskovsoft.smartyoutubetv2.tv.ui.channeluploads.ChannelUploadsActivity}', status=NORMAL, monitor=false, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
    5: channelName='ede5332 SurfaceView - com.teamsmart.videomanager.tv/com.liskovsoft.smartyoutubetv2.tv.ui.playback.PlaybackActivity (server)', windowName='Window{ede5332 u0 SurfaceView - com.teamsmart.videomanager.tv/com.liskovsoft.smartyoutubetv2.tv.ui.playback.PlaybackActivity}', status=NORMAL, monitor=false, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
    6: channelName='ca07554 com.teamsmart.videomanager.tv/com.liskovsoft.smartyoutubetv2.tv.ui.browse.BrowseActivity (server)', windowName='Window{ca07554 u0 com.teamsmart.videomanager.tv/com.liskovsoft.smartyoutubetv2.tv.ui.browse.BrowseActivity}', status=NORMAL, monitor=false, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
    7: channelName='d1365c6 com.amazon.vizzini (server)', windowName='Window{d1365c6 u0 com.amazon.vizzini}', status=NORMAL, monitor=false, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
    8: channelName='f55f0b4 com.amazon.vizzini (server)', windowName='Window{f55f0b4 u0 com.amazon.vizzini}', status=NORMAL, monitor=false, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
    9: channelName='66404e com.plexapp.android/com.plexapp.plex.home.tv.HomeActivityTV (server)', windowName='Window{66404e u0 com.plexapp.android/com.plexapp.plex.home.tv.HomeActivityTV}', status=NORMAL, monitor=false, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
    10: channelName='92899ad com.amazon.tv.launcher/com.amazon.tv.launcher.ui.HomeActivity_vNext (server)', windowName='Window{92899ad u0 com.amazon.tv.launcher/com.amazon.tv.launcher.ui.HomeActivity_vNext}', status=NORMAL, monitor=false, inputPublisherBlocked=false
      OutboundQueue: <empty>
      WaitQueue: <empty>
  AppSwitch: not pending
  Configuration:
    KeyRepeatDelay: 50.0ms
    KeyRepeatTimeout: 500.0ms


  Keyboard Layouts:
    "English (UK) - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_en_GB
    "French - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_fr_FR
    "Italian - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_it_IT
    "English (US) - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_en_US
    "Spanish (Latin) - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_es_ES
    "German - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_de_DE
    "Turkish - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_tr_TR
    "Danish - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_da_DK
    "Finnish - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_fi_FI
    "Swiss French - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_fr_CH
    "Slovak - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_sk_SK
    "Russian - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_ru_RU
    "Slovenian - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_sv_SE
    "Croatian - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_hr_HR
    "Norwegian - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_nb_NO
    "Swiss German - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_de_CH
    "Czech - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_cs_CZ
    "French (Canada) - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_fr_CA
    "Ukrainian - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_uk_UA
    "Bulgarian - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_bg_BG
    "Portuguese - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_pt_PT
    "Hungarian - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/locale_hu_HU
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_05ac_pt_PT
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_04f2_fr_FR
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_05ac_fr_FR
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_045e_fr_FR
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_046d_fr_FR
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_04f2_de_DE
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_05ac_de_DE
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_045e_de_DE
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_046d_de_DE
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_05ac_it_IT
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_045e_it_IT
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_046d_it_IT
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_04f2_es_ES
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_05ac_es_ES
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_045e_es_ES
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_046d_es_ES
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_04f2_en_GB
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_05ac_en_GB
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_045e_en_GB
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_046d_en_GB
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_04f2_en_US
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_045e_ja_JP
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_05ac_ja_JP
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_1949_en_GB
    " - Fire keyboard layout": com.amazon.fireinputdevices/com.amazon.fireinputdevices.FireInputDeviceReceiver/vendor_0171_en_GB

  PersistentDataStore
    mLoaded=true
    mDirty=false
    InputDeviceStates:

**Comment by PRProd** [comment]
@fin05 - Thank you.  I see the problem.

You have not successfully pressed a button your 4K max device's physical remote control that was actually received by the stick.  This is evident by the absence of an **Amazon Fire TV Remote** in your data dump.  Mixed in with the data you sent me, here are the important parts:
```
1: WOBLE_INPUT_DEVICE
Classes: 0x00000001
Path: /dev/input/event1
...
2: hdmipower
Classes: 0x00000001
Path: /dev/input/event0
Descriptor: a917cc44911b6f32b9481384b0da35fb5f3d84d3:00000000
...
3: amazon_touch
Classes: 0x00000014
Path: /dev/input/event2
...
4: kcmouse
Classes: 0x80000008
Path: /dev/input/event3
```
If you re-connect your physical remote control to your 4K Max stick, you will see an entry in that list showing the connected remote.

For instance, here is an edited version of what happens when I run that command against my Fire Stick 4K Max:
```
1: WOBLE_INPUT_DEVICE
Classes: 0x00000001
Path: /dev/input/event1
...
2: hdmipower
Classes: 0x00000001
Path: /dev/input/event0
...
3: amazon_touch
Classes: 0x00000014
Path: /dev/input/event2
...
4: WOW_INPUT_DEVICE
Classes: 0x00000001
Path: /dev/input/event3
...
5: kcmouse
Classes: 0x80000008
Path: /dev/input/event4
...
7: Amazon Fire TV Remote
Classes: 0x80000021
Path: /dev/input/event5
```

The Firemote Card pretends to be your connected remote control, so if there isn't a connected remote control, your Firestick refuses to listen to any commands sent.

What you need to do is connect a physical remote control to your Firestick 4K max device, and ensure that it is actually working by pressing some navigation buttons and witnessing movement on the screen.  Then, Firemote will work by pretending to be your already connected remote control.  IF it still doesn't work, then you might want to try a different event number.  event5 is the default for the Firestick 4K Max, but based on the data dump you sent, your physical remote might connect on event4.  (that's just a guess)  But, now you know exactly how to see if a remote is connected, and what "event" number it is connected to.

I hope this helps.

**Comment by fin05** [comment]
Thank you setting it to the event 4 did work but I do have to hit a button on the remote first before the firemote card will work. Do you know if the issue is with the remote or the fire stick itself? Could I pair and older remote to the fire stick max and avoid having to hit a button on the regular remote to activate it?

**Comment by fin05** [comment]
Sorry for the late response I was on out of town last week

**Comment by PRProd** [comment]
How often do you need to re-establish the connection with your physical remote?

**Comment by fin05** [comment]
Every rebootOn May 20, 2023 7:20 PM, Doug Nelson ***@***.***> wrote:
How often do you need to re-establish the connection with your physical remote?
