### ISSUE TITLE
[New App Shortcut]: Movistar Plus+

### ISSUE THREAD

**Issue by Guerrero884** [PRProd/HA-Firemote#91]
### App Name

Movistar

### Device Platform

Amazon Fire

### Is this app downloadable through you device's "store" app?

- [X] Yes

**Comment by PRProd** [comment]
@Guerrero884 - Thank you for your request!  

When I search for "Movistar" through the Fire TV Appstore, I find two apps
 - Movistar Plus+
 - Movistar TV App Peru

I'm not exactly sure which one you are asking about.

The BEST way to answer my question would be to follow the instructions here:[ Details for App Requests](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests) and reply to this post with the results.  Thank you for your help!

**Comment by Guerrero884** [comment]
Sorry for not specifying the application correctly, the application I'm referring to is 

Movistar Plus+.

Thank you very much in advance

**Comment by PRProd** [comment]
Thanks for the clarification!  

[Version 2.1.10](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.10) is now available which officially supports your app shortcut request.  Thanks for contributing!
