### ISSUE TITLE
[New App Shortcut]: Live Channels

### ISSUE THREAD

**Issue by mattmckernan** [PRProd/HA-Firemote#92]
### App Name

Live Channels

### Device Platform

NVIDIA Shield

### Is this app downloadable through you device's "store" app?

- [X] Yes

### Optional Comments

Is it possible to map the Live Channels app on Android/Shield so that it works on the remote?

**Comment by PRProd** [comment]
[Version 2.1.10](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.10) is now available which officially supports your app shortcut request.  Thanks for contributing!

**Comment by PRProd** [comment]
@mattmckernan - I just witnessed a message pop up on my NVIDIA Shield that stated
```
Live Channels is deprecated on July 31st 2022
```
If this note actually means 2023, then that could indicate that this app will no longer function after July 31st 2023.  We will want to keep an eye on what happens.

**Comment by mattmckernan** [comment]
Yeah there's a lot of discussion around this, apparently a replacement app is coming but Google haven't pushed it out so Live Channels continues to run.  Thanks for the button add!

**Comment by PRProd** [comment]
Good to know!  Thank you.  Since I'm not a frequent user of that app, feel free to send me updates here if/when anything changes.  I want to keep your shortcut button working as expected.
