### ISSUE TITLE
[New App Shortcut]: COSMOTE TV

### ISSUE THREAD

**Issue by grego1981** [PRProd/HA-Firemote#97]
### App Name

COSMOTE TV

### Device Platform

NVIDIA Shield

### Is this app downloadable through you device's "store" app?

- [X] Yes

### Optional Comments

https://play.google.com/store/apps/details?id=gr.cosmote.cosmotetv.android&hl=el&gl=US

**Comment by PRProd** [comment]
@grego1981 - I've published a new pre-release version [v2.2.0-b3](https://github.com/PRProd/HA-Firemote/releases/tag/v2.2.0-b3) which includes your app shortcut request.  Feel free to download it and test it out to make sure that it works as expected.

This will become a part of the next official release once unrelated changes are out of testing.

**Comment by grego1981** [comment]
> @grego1981 - I've published a new pre-release version [v2.2.0-b3](https://github.com/PRProd/HA-Firemote/releases/tag/v2.2.0-b3) which includes your app shortcut request. Feel free to download it and test it out to make sure that it works as expected.
> 
> This will become a part of the next official release once unrelated changes are out of testing.

It works as expected, tested in 3 different android tv devices
