### ISSUE TITLE
[New App Shortcut]: EON TV

### ISSUE THREAD

**Issue by acmeGR** [PRProd/HA-Firemote#98]
### App Name

Cosmote TV & EON TV

### Device Platform

Nvidia shield

### Is this app downloadable through you device's "store" app?

- [X] Yes

### Optional Comments

Used in Greece

**Comment by PRProd** [comment]
Cosmote TV is a duplicate from #97, so this issue will only track EON TV

**Comment by PRProd** [comment]
@acmeGR - I've published a new pre-release version [v2.2.0-b3](https://github.com/PRProd/HA-Firemote/releases/tag/v2.2.0-b3) which includes your app shortcut request.  Feel free to download it and test it out to make sure that it works as expected.

This will become a part of the next official release once unrelated changes are out of testing.

**Comment by acmeGR** [comment]
Tested EON TV and it works great. Thx!
