### ISSUE TITLE
[New App Shortcut]: Israel Station

### ISSUE THREAD

**Issue by xelamod** [PRProd/HA-Firemote#99]
### App Name

Israel Stations

### Device Platform

NVIDIA Shield

### Is this app downloadable through you device's "store" app?

- [X] Yes

**Comment by PRProd** [comment]
@xelamod - The link you provided is for the mobile version.  I believe this is the one you wanted?
https://play.google.com/store/apps/details?id=israelstation.androidtv

**Comment by PRProd** [comment]
@xelamod - I've published a new pre-release version [v2.2.0-b3](https://github.com/PRProd/HA-Firemote/releases/tag/v2.2.0-b3) which includes your app shortcut request.  Feel free to download it and test it out to make sure that it works as expected.

This will become a part of the next official release once unrelated changes are out of testing.

**Comment by PRProd** [comment]
Great! Thanks for letting me know. Closing as completed.
